### ISSUE TITLE
[Dynamic Page]: Scrollbar is not in intended design

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents#10013]
### Describe the bug

The scrollbar is the normal browser scrollbar.

### Isolated Example

https://stackblitz.com/edit/github-seaow7?file=src%2FApp.tsx

### Screenshots or Videos

<img width="670" alt="Bildschirmfoto 2024-10-12 um 18 27 43" src="https://github.com/user-attachments/assets/bdf40688-2ba8-4b3d-93e1-f51aca0be213">

### UI5 Web Components for React Version

2.2.0

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @skowrons,
you need to set up some flex layout for DynamicPage and ShellBar, because DP is designed to be the main page layout and for it to take up all the available space you also need to set html, body {width: 100%; height: 100%} style to make it work.
In your case you need to not set height 100vh to Dynamic Page root element, since it will always trigger scrollbar when there are other components taking up extra height on the page.
Best regards,
Petya Markova.
(UI5 Dispatcher)
