### ISSUE TITLE
[ui5-input]: suggestions max-width has increased

### ISSUE THREAD

**Issue by jarrettwchan** [SAP/ui5-webcomponents#10139]
### Bug Description

In 1.20, the suggestions width was the input width.
But, now the suggestions max-width is a minimum of 40rem (or up to 62rem based on the input width).

This has changed the behavior of a couple of our searches where the suggestions were lined up with the input.
We are relying on the width of the suggestions to cause wrapping in our suggestion items. 

### Affected Component

ui5-input

### Expected Behaviour

Please confirm if this change to the minimum max-width is intended.

### Log Output, Stack Trace or Screenshots

|1.24.8|1.20.0|
|-|-|
| ![image](https://github.com/user-attachments/assets/41037534-0f1a-499f-8a96-8beebeb6a71b) | ![image](https://github.com/user-attachments/assets/1975f099-309b-46eb-a637-d01ba3ef8ea3) |

### Priority

Medium

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Operating System

macOS 14.6.1

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hello!

I can confirm that the minimum `max-width` is set to `40rem` based on our latest specs for the drop down for all input fields.

In order to get a easier maintenance I would suggest you to update to 2.x version of webcomponents.
The input suggestion items in 2.x are physical, real elements on which you can set your own width.

Best Regards!
Martin

**Comment by jarrettwchan** [comment]
Setting the width for input suggestion items sounds like it does not account for the width of the scrollbar.
It seems that I will have to read the input width and write the popover width, regardless of 1.x or 2.x
