### ISSUE TITLE
ui5-title: Default size has changed with 2.X Upgrade?

### ISSUE THREAD

**Issue by MFel0123** [SAP/ui5-webcomponents#10225]
### Bug Description

Hello colleagues,
when checking the changes to introduce Web Components 2.x (in this case: 2.4 to be exact) I have the impression that the standard size of the ui5-title (the default) has been changed: in 1.x it appeared bigger (I guess it would be size=H2). Now the new default is "size=H5". So this is much smaller.
I did not find this change documented here in the migration guide:
https://sap.github.io/ui5-webcomponents/docs/migration-guides/to-version-2/#ui5-title
Please correct me if I am wrong or take it as an issue.
Kind Regards

### Affected Component

ui5-title

### Steps to Reproduce

1. Just check the default title appearance in different UI5 Webcomponent versions.
2.
3.
...

### Priority

None

### UI5 Web Components Version

2.4

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The default value of the `level` property of the `ui5-title` component has been changed with version 2, but was not mentioned in the [migration guide](https://sap.github.io/ui5-webcomponents/docs/migration-guides/to-version-2/#ui5-title). 

Could you please confirm that this was intentional change?
