### ISSUE TITLE
IllustratedMessage: Title of type "Scene" is smaller

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents#10240]
### Bug Description

When using the Illustrated Message Component in the largest size (type: Scene), the heading is smaller than for other types e.g. Dialog. Is this design intended? In version 1 of the components, the heading is quite large.

Comparison:

v2 scene
<img width="365" alt="image" src="https://github.com/user-attachments/assets/1794e03d-2367-4abe-ba07-de022e74515c">

v1 scene
<img width="405" alt="image" src="https://github.com/user-attachments/assets/90850629-4c50-44ba-867a-0962009d1004">

v2 dialog
<img width="288" alt="image" src="https://github.com/user-attachments/assets/f6574d06-f02f-4969-b7ea-96b4ad39e282">

### Affected Component

ui5-illustrated-message

### Priority

None

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello @tkeiner,

Thank you for your observation. However, I would like to clarify that this section is not intended for consultation or discussion on design-related queries. If there is a confirmed issue or a deviation from the design specifications, please provide concrete evidence when raising it.

In the future, kindly ensure that concerns are supported with specific details rather than general questions to help us maintain focus and efficiency.

Best regards,
Ivaylo
