### ISSUE TITLE
MultiComboBox - support custom styling on selected items/tokens

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1115]
**Is your feature request related to a problem? Please describe.**

Selected values can have different styling such as background color. This component is very useful for tagging use-case.

https://codesandbox.io/s/ui5-webcomponents-v6846
https://codesandbox.io/s/ui5-webcomponents-j9m9w

**Describe the solution you'd like**

Provide a slot to define custom templates for selected token/items.

**Describe alternatives you've considered**

**Additional context**

**Comment by fifoosid** [comment]
Hi @sunnyyadav100,

Thanks for the feature request! We are going to discuss it internally and come back to you with a statement.

In the meantime you can use a workaround in order to style the selected items in the multicombobox. Here is an example how you can achieve this using addCustomCSS method: https://codesandbox.io/s/ui5-webcomponents-9or2i

Best regards,
Filip

**Comment by fifoosid** [comment]
This is the target design: https://codesandbox.io/s/ui5-webcomponents-j9m9w

Every token should have different color(while when in the popover, they should behave like regular list items).

**Comment by fifoosid** [comment]
We are evaluating this feature request, and currently we don't imagine adding a slot for this use case. We are thinking about approach using css parts: #843

Best regards,
Filip

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 should you support IE11, because css parts are not supported in IE11 currently.

**Comment by sunnyyadav100** [comment]
Yes , we support IE11 but we encourage our users to use modern browsers for better experience. I can try this and get back with feedback.

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 I see.

Note that the tokens html elements currently don`t have the part="token-{some_unique_key}" attribute. It was just a quick POC on my machine to show you and ask if this approach would be fine for you. You can't test it right now. 

I think that we can provide that "part" attribute soon, because it gives a standard (in most of the browsers) way to customize the tokens from outside.

Best,
ilhan
