### ISSUE TITLE
How to setup internationalisation files

### ISSUE THREAD

**Issue by mehdijouan** [SAP/ui5-webcomponents#1128]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

**Description of the issue**
I found a documentation on how to import your i18n module but, I didn't found where to put my properties files and what is the expected format.

Could you help me on that ?

**Comment by ilhan007** [comment]
Hello @mehdijouan 

Do you have "slack" to discuss your issue? 

We have a slack channel, called "webcomponents" and there is a link to slack at the bottom of the project readme([link](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/)).

**Comment by ilhan007** [comment]
Hello @mehdijouan

You can find out text entries (for example for package "main") here:
https://github.com/SAP/ui5-webcomponents/tree/master/packages/main/src/i18n

All the text entries, that need translations, are listed in the `messagebundle.properties` file. 
We need this format, because the translation setup we use rely on this file and based on it generates messagebundle_{languagecode}.properties for each language we support with all the texts translated
(these files you can find in the same folder).

I assume you are developing you own web component(s) extending the base UI5Element class (or some of the rest)? Are you using our build tooling?

Best,
ilhan

**Comment by ilhan007** [comment]
Hello @mehdijouan I am closing the issue due to inactivity,
if you are still interested in the i18n, reopen the issue any time and please answer the questions above
in order to help you.
