### ISSUE TITLE
CodeSandBox broken with 1.0.0-rc5

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1189]
The link for creating a reproducible example in code sand box is not working:
https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html

![image](https://user-images.githubusercontent.com/8775211/73968543-b0821780-48ce-11ea-92d0-81cc639df8ca.png)

**Comment by ilhan007** [comment]
Hello @MarcusNotheis thanks for letting us know,
probably the issue exists with rc.4 as well?

First I left just a ui5-button on the page and the error is gone. 
When I opened the console and looked for the component JS files, I saw that the Button.js file is ES6,
but for example the MessageStrip.js/Switch.js are transpiled to ES5 and probably this is the reason for the error.
But, why the Button.js is ES6, the others- ES5 I don`t know yet.

Best,
ilhan

**Comment by MarcusNotheis** [comment]
Hi @ilhan007 , 
Yes, happens to rc.3, rc.4 and rc.5.

Best regards,
Marcus

**Comment by pskelin** [comment]
It should work now. The problem was that the project was transpiled and extending native classes needs a different "extends" implementation.

Solved by adding a new .babelrc file and removing the `preset-env` which seems to be the default at the moment and causing this wrong transpiling behaviour.

Anyway, checkout the official link from the landing page for a working solution.
