### ISSUE TITLE
Tab container: support tab label with count

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1195]
**Is your feature request related to a problem? Please describe.**

Support of tab label with counter -

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/9139037/74084213-f2f45180-4a92-11ea-841b-c053948bd32f.png">

e.g.
https://sapui5.hana.ondemand.com/#/entity/sap.m.TabContainer/sample/sap.m.sample.TabContainerIcons (without tab image)

https://sap.github.io/fundamental-styles/components/tabs.html#tabs-with-counters 

We have a requirement to show count on tab label as highlighted in above screenshot.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fifoosid** [comment]
Hi @sunnyyadav100,

Have you tried using the additionalText property?

**Comment by sunnyyadav100** [comment]
Yes, in that label appear as `Tab label (23)`. 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/9139037/74136455-1266b800-4c14-11ea-9973-ad9a486c624e.png">

As per fiori guideline (I think), count shows above the label

**Comment by ilhan007** [comment]
@sunnyyadav100 It turns out that "Standard" (the counter above the main text) and "Inline" (the counter next to the main text) modes exist:
https://experience.sap.com/fiori-design-web/icontabbar/

Although, the component is called TabContainer we tried to also implement it to fullfill the sap.m.IconTabBar from openui5.

We will think of something, so you can be able to display it both ways.
