### ISSUE TITLE
Title attribute support for <ui5-option>

### ISSUE THREAD

**Issue by tnurmi82** [SAP/ui5-webcomponents#1198]
Please consider adding title attribute support for ui5-option.

In my case I'm building a configuration UI where I have multiple dropdowns for parameter selection.
Each selection has a "name" but also a longer "description".
My plan was to use the title attribute to show the "description" in a tooltip, when hovering cursor over the selection. However, this is currently not supported.

Generically speaking almost all elements should support the title attribute, while the alt attribute should be supported by especially img and input:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

**Comment by elenastoyanovaa** [comment]
Hello @tnurmi82 ,

Thanks for reporting!

Due to an inconsistent browser support and many accessibility issues it is not a best practise to use a tooltip. You can read more about this here in the accessibility section [MDN titile attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)
The tooltip will be available only for mouse users on a limited set of browsers and only on a desktop device. What is more, there are screen readers which will not read the title attribute and therefore the tooltip description will not be available for blind users. 

Additional information can also be found here: https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute

As this information would be available only for a limited set of users it would not be a good idea to implement it on ui5-option level. What is more tooltips are used mainly to provide text alternatives to non textual elements.

Kind Regards,
Elena
