### ISSUE TITLE
MultiComboBox: Scroll bar visible when more items selected than space available

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#1304]
**Summary:**
For the MultiComboBox, according to Fiori, when there are more items selected than space available, scrolling behavior exists, but a scroll bar is not visible. Currently, when more items are selected, a scroll bar pops up, blocking the view of the Tokens selected.

**Current Behavior:**
1. MultiComboBox (with either less width or enough elements to take up at least the width of the MultiComboBox.
2. Multi-select items to fill the space.
3. See that a scroll bar appears, which in the Fiori images, does not become visible.

**Expected Behavior:**
1. MultiComboBox (with either less width or enough elements to take up at least the width of the MultiComboBox.
2. Multi-select items to fill the space.
3. As more items are selected, items are pushed to the left out of view, but no scroll bar is visible.

**Screenshots:**
Current behavior:
![Screen Shot 2020-03-16 at 9 44 58 AM](https://user-images.githubusercontent.com/61565124/76782982-5185ad00-676e-11ea-8f62-25a21a28b8a2.png)

Fiori expected behavior:
![Screen Shot 2020-03-16 at 9 52 21 AM](https://user-images.githubusercontent.com/61565124/76783019-5f3b3280-676e-11ea-9f22-416885c17dab.png)

**Affected Components**
MultiComboBox

Original Issue: https://github.com/SAP/ui5-webcomponents-react/issues/353

**Comment by ilhan007** [comment]
Hello @MarcusNotheis I remember someone else also reported the same issue to us, but I could not reproduce it, I tried now and I still don`t see that horizontal  scrollbar. Do you have it somewhere I can access and reproduce it.

no scrollbar on my side:

<img width="375" alt="Screenshot 2020-03-18 at 1 36 10 PM" src="https://user-images.githubusercontent.com/15702139/76957108-f1356d80-691d-11ea-9f20-663781fe77dd.png">

**Comment by ilhan007** [comment]
I managed to reproduce it, we will take a look fo it : )

**Comment by MarcusNotheis** [comment]
Hi @ilhan007, great :) In case you need further information, @n-devlin reported that issue on our side.

**Comment by n-devlin** [comment]
Hello, 
Thank you for working so quickly to fix this issue. I am now having the problem that rather than allowing a user to see that there are more elements selected, ("1 more" as above), the MultiComboBox just gets wider to fit as many elements as are selected:

![Screen Shot 2020-03-23 at 1 50 06 PM](https://user-images.githubusercontent.com/61565124/77361884-4d790280-6d0d-11ea-82e6-9ba68229eba7.png)
![Screen Shot 2020-03-23 at 1 50 19 PM](https://user-images.githubusercontent.com/61565124/77361893-5073f300-6d0d-11ea-827e-b1faca7bc362.png)
![Screen Shot 2020-03-23 at 1 50 28 PM](https://user-images.githubusercontent.com/61565124/77361902-54a01080-6d0d-11ea-9f9f-17398e1a6410.png)

This seems to either be a new bug, or possibly a result of the earlier scroll bar issue fix? Thank you so much!

**Comment by ilhan007** [comment]
Hello @n-devlin
The fix, regarding the horizontal scrollbar is not released in npm yet, the only way to have the fix is to clone our repository, fetch the latest master and "npm | yarn link" the library and use it in your app. 

But, I guess it's something else. Which version are you using - rc.5?
You can try setting max-width to the ui5-multi-cbx, I guess it has width: auto and it grows with each token.

Best,
ilhan
