### ISSUE TITLE
Switch Control style mess up in Compact RTL

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#1309]
**Describe the bug**
Switch Control style mess up in Compact RTL.

https://sap.github.io/ui5-webcomponents/playground/components/Switch/?sap-ui-theme=sap_fiori_3&sap-ui-compactSize=true&sap-ui-rtl=true

**To reproduce**
1. Choose Compact & RTL

![image](https://user-images.githubusercontent.com/6975707/76921776-dbb64880-6909-11ea-8e29-70474fb9ff68.png)

2. The font and icon position is not right
![image](https://user-images.githubusercontent.com/6975707/76921799-ea046480-6909-11ea-8e00-a19476385316.png)

**Context**
- OS/Platform: Mac 
- Browser *(if relevant)*: Chrome

**Comment by ilhan007** [comment]
Hello @TinaC 
this is already fixed in the master

The following link with "master" in the url shows the current state:
https://sap.github.io/ui5-webcomponents/master/playground/components/Switch/

We will soon release a new "rc" version, but if you want to use the latest development, you can install
the latest development version we have by typing:

```js
npm install  @ui5/webcomponents@next
```

Best Regards,
ilhan
