### ISSUE TITLE
MenuButton component

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#1436]
Feature request for UI5 MenuButton as webcomponent - https://openui5.hana.ondemand.com/entity/sap.m.MenuButton 

**Describe alternatives you've considered**

**Additional context**

**Comment by deathctalker** [comment]
Hi,
When to expect implementation? How to increase priority?

**Comment by sunnyyadav100** [comment]
Hi, is it possible to get this component in rc10 or rc11?

**Comment by scameron** [comment]
Hello,

This control is the last missing piece for us to use UI5 web components in our project.  I see on your roadmap that this one is currently planned for Q2.

How firm is that plan?  Is it a sure enough thing that we can plan against this on our side as a dependency?  It would be awesome if we could use this in Q2.

**Comment by petyabegovska** [comment]
Hi @scameron,

The implementation of this requirement will be done in 3 steps:

- Implementation of Split Button component - already in progress, should be finished in Q1.
- Implementation of Menu component - not started yet, but planned to start in Q1.
- Implementation of MenuButton component- not started yet (Split and Menu are prerequisite), planned for Q2.

This is our plan, but always there is a risk from unpredictable obstacles.

Best Regards,
Petya

**Comment by scameron** [comment]
Thanks for the reply, @petyabegovska.  That sounds good.  We'll keep a watch on this item for any updates.

One maybe naïve question... when you introduce a new web component, does the React version come along at the same time?  Or is there additional work required there?

**Comment by MarcusNotheis** [comment]
> One maybe naïve question... when you introduce a new web component, does the React version come along at the same time? Or is there additional work required there?
Let me jump in here 🙂 We have to update our React Wrapper to support the new component, but most of these steps are already automated. Usually you can expect that the React Wrapper releases a new version on the same day (or latest the next day) as the UI5 Web Components.

**Comment by petyabegovska** [comment]
Hi @scameron! We are still on tract. Soon we will be ready with the ui5-menu component (see #4742). We should start MenuButton in April (Q2).

**Comment by petyabegovska** [comment]
Hi @scameron! ui5-menu component is already in master: https://sap.github.io/ui5-webcomponents/master/playground/components/Menu/.

**Comment by scameron** [comment]
Thank you for letting me know.  I'll inform the team so we can give it a try!

**Comment by ddrana** [comment]
Hi @petyabegovska , 

Thanks for sharing this information. It is good to know that Menu component is available now.

From consumption perspective:
* When do you think that the Menu control will be released?
* Since we use UI5 Web Components for React, do you have any idea about availability of this component in WC4R library?

**Comment by MarcusNotheis** [comment]
> Since we use UI5 Web Components for React, do you have any idea about availability of this component in WC4R library?

Hey, I'm one of the maintainers of the UI5 Web Components for React library. Usually, we release our updated React wrapper on the same or the next day of the UI5 Web Components release, so the component availability of both libraries is pretty much in sync.
As far as I know, we're planning the release for this or next week.

**Comment by ilhan007** [comment]
Hello @ddrana due to the Easter vacations we had to delay the release a bit (otherwise planned for April's first week),
but as Marcus said -> this or next week.

**Comment by ddrana** [comment]
Thanks a lot @MarcusNotheis and @ilhan007 for the update. 

We shall try the Menu component once it is available in WC4R library.

**Comment by ilhan007** [comment]
Welcome @ddrana we will let you know once we release 1.3.0 -> this will be the version to include the Menu component.

**Comment by ilhan007** [comment]
Hello @ddrana the component is available with 1.3.0 
https://sap.github.io/ui5-webcomponents/playground/components/Menu/

**Comment by ddrana** [comment]
Thanks for the update, @ilhan007

**Comment by DMihaylova** [comment]
Hello @ddrana, @MarcusNotheis, @scameron & @sunnyyadav100,

We'll work on providing a sample how a Split Button could open a Menu and since there's already [a sample how a Button opens a Menu](https://sap.github.io/ui5-webcomponents/playground/components/Menu/) we're wondering whether you have a scenario for dynamically changing regular and split button mode or the existing functionality suits your needs already.

Thanks & Regards,
Diana

**Comment by DMihaylova** [comment]
Hello @ddrana, @MarcusNotheis, @scameron & @sunnyyadav100,

Since currently there is no scenario for a dynamic change between regular and split button mode and since the existing Split Button already fulfils the functionality of opening a menu, we'd prefer to eliminate the need for introducing another component (Menu Button).
Here you could see a sample how a Split Button opens a Menu:
https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-splitbutton--split-button-with-menu 

Thanks & Regards,
Diana

**Comment by ddrana** [comment]
Thanks @DMihaylova for adding the MenuButton Component to the library. We do not have further requirements as of now.

CC: @scameron
