### ISSUE TITLE
ui5-tabcontainer: add custom tab support

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1453]
hi,  

we need to add a custom tab(not the ui5-wc standard) for business requirement. 

so, is there any possibility to open the slot for business customization？

-----

![image](https://user-images.githubusercontent.com/4457451/78911645-28301680-7ab9-11ea-8356-118c798b0e85.png)

**Comment by vladitasev** [comment]
Hi Alex,

Currently it's not possible, due to the fact that the tab strip is built based on the metadata of the tabs (text/additional text, etc...) automatically, and the tabs themselves are only slotted underneath the strip.

There are several reasons: 
 - The tabs have different presentation, based on the TabContainer's properties (TabLayout)
 - There is an overflow menu to the right when the space is too little, and in this menu the tab has a yet different representation.

Is this a hard requirement for you?

**Comment by alex-zhang** [comment]
hi @vladitasev  

thanks for your reply.   

so, The Tab is driven by the TabContainer's data right? In my opinion, the TabContainer's data should be extendible and The Tab View should be polymorphism. We define the BaseData Structure which can support current logic，and can also can extend the Base Data Structure in TabContainer that can support the customization right?

**Comment by vladitasev** [comment]
Please track the progress on this here:
https://github.com/SAP/ui5-webcomponents/issues/1490
