### ISSUE TITLE
DatePicker/TimePicker/DateTimePicker - consider changing how "value" works

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1503]
The problem is that the format of the value that needs to be provided by the app varies by locale and cannot be known in advance. 

Therefore, when the app tries to initialize f.e. the DatePicker with the correct value, it needs to check the locale, format the value according to the locale, and then set it.

Consider having a `displayValue` property, which will be the value, formatted according to the selected `formatPattern`, and a `value` property, which will be the value in a universal format, that can be safely set, regardless of locale.

Or, the other way round, keep the current `value` as it is for compatibility (although it is technically displayValue) and add a new property - something like `UTCValue`.

Needs discussion

**Comment by MWFIAE** [comment]
I very much support this proposal, was very difficult to implement a proper handling for that in my app. And that's not even considering the various calendar-types there are.
So having a simple universal format would be best.
Considering most are using the web-components in conjunction with js I would even prefer the output of `new Date().getTime()` so basically the milliseconds since 1970. That would be the most universal, transportable and easiest way to represent a Date/Time/DateTime.

**Comment by vladitasev** [comment]
After a discussion we've been told by the experts on this topic that having several value properties that need to be synchronized leads to problems in the long run. They believe having a single value is the best implementation and advised us to provide a static method or another kind of external util that does this job before setting the `value` property.

Scope of the task:
 - Create dynamic/static methods / external utility functions that can be easily imported, for `ui5-datepicker`, `ui5-timepicker`, `ui5-datetime-picker` that allow to format a universal value to the currently set-up calendar type and locale. 
 - Document and create examples so that stakeholders can assess the usability of the feature
