### ISSUE TITLE
Reactive Forms Angular

### ISSUE THREAD

**Issue by camilo2312** [SAP/ui5-webcomponents#1513]
Hello everyone

1. I implement the use of reactive forms with the ui5-input control but it still doesn't work

![image](https://user-images.githubusercontent.com/42982644/80000203-757d9200-8482-11ea-973f-572e13eb53fe.png)

Visit Issue # 697 but it doesn't work

Still have no support for this?

Do I need to implement any module?

Thanks for the help

**Comment by fifoosid** [comment]
Hi @camilo2312 

In order to use UI5 Web Components with Angular two way data binding you have to provide ControlValueAccessor for the used components. In our [Angular tutorial](https://sap.github.io/ui5-webcomponents/playground/tutorials/angular/) you can check out ```Two-way data binding``` section.

In order to make it work:
1. Install Origami:
```bash
npm install @codebakery/origami
```

2. Import the OrigamiFormsModule from Origami
```js
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { OrigamiFormsModule } from '@codebakery/origami/forms';
import { AppComponent } from './app.component';

@NgModule({
  imports: [BrowserModule, OrigamiFormsModule],
  declarations: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

3. Use it in your template
```html
<ui5-input [(ngModel)]="value" origami></ui5-input>
```
