### ISSUE TITLE
ui5-select: cannot select an item with space/enter

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1537]
When you open the select and navigate with keyboard, the currently selected item has the focus, although pressing the arrows moves the background up and down. Therefore, when you press enter/space, you activate the old selection, and not where you navigated with the arrows. This way you can't change the selection by pressing space

**Comment by vladitasev** [comment]
Can only be reproduced when all other components but ui5-select and ui5-option are bundled.

**Comment by fifoosid** [comment]
When all components but selects are removed from the test page, the problem is that too many invalidations are happening in one tact. In this case there is visual latency for applying focus. Check the video:


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16850339/80360408-f922ee80-8887-11ea-931a-b8682bb4967a.gif)

**Comment by vladitasev** [comment]
@fifoosid thanks, i'll look into it now

**Comment by vladitasev** [comment]
Will largely be fixed by: https://github.com/SAP/ui5-webcomponents/pull/1552

Additionally, we should tackle the invalidation synchronization in another pull request for the select, as it is not related to the framework as the big delay.
