### ISSUE TITLE
ui5-shellbar/ui5-input support loading indicator

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1589]
**Is your feature request related to a problem? Please describe.**
The current input in the shellbar does not support any good loading indicator to show that the search is ongoing. The current UI5 version on successfactors does.

**Describe the solution you'd like**
It would be nice if there was a good way to show that the search is currently waiting for search results. 

**Describe alternatives you've considered**
Extending the ui5-input to have a loading - or adding a search result item with a custom list item with a busy indicator instead.

**Additional context**
![image](https://user-images.githubusercontent.com/730310/81463817-64ff3400-9171-11ea-93e0-8b5ed82fced8.png)

**Comment by fifoosid** [comment]
Hi @codefactor 

Currently the ```ui5-input``` has icon slot. This slot can be used for this exact purpose. I prepared a [sample](https://codesandbox.io/s/ui5-webcomponents-jecos?file=/index.html) for you in order to see it in action. You can pass anything to this slot, but I assume that you have the loading animation as gif.

*Note*: It would be your responsibility to show/hide the loading indicator when the search has started/finished.
