### ISSUE TITLE
No tooltip interface for <ui5-list>

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#1601]
**Is your feature request related to a problem? Please describe.**
When I using <ui5-list>, there is no tooltip for both title and description.
![image](https://user-images.githubusercontent.com/5724592/81782948-309ec580-952d-11ea-8b8f-b3a0b5035336.png)

**Describe the solution you'd like**
Could you consider to offer the  tooltip interface for both title and description ?

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ilhan007** [comment]
Hello @sleric1024 we usually don't have tooltips for texts, but I will let @elenastoyanovaa share her opinion on the topic.

**Comment by elenastoyanovaa** [comment]
Hello @sleric1024 ,

It is not a good practise to use a tooltip as a way of showing the full text. You can read more about it here https://experience.sap.com/fiori-design-web/using-tooltips/ 

Tooltips are not reliable, since their appearance is browser specific and what is more, there are browsers which do not show tooltips at all. One more thing - tooltips are present only on desktop, so there is no way for a mobile user to see the information inside a tooltip.
