### ISSUE TITLE
Set ValueState Text

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents#1635]
Hi,

After searching the documentation, I didn't find any way to modify the `ValueState` text (the text appearing when the `ValueState` is not `None`) for any controls.

First, is it possible to modify this text? And if so, how? If it's not possible, can a `ValueStateText` property be added to do so?

Thanks!
Mathieu

**Comment by ilhan007** [comment]
Hello @MatthiasSchmalz  

Currently, the built-in text are available and you can`t change them, we will take that as a feature request as it makes sense.

FEATURE REQUEST:
All the components that has valueState property, should also provide valueStateTex in order to override the built-in text.

Thanks,
ilhan

**Comment by ilhan007** [comment]
Hello @MatthiasSchmalz 

Actually, you can use the "valueStateMessage" slot. The default text would not appear if the slot is set.

```html
<ui5-input value-state="Error">
  <div slot="valueStateMessage">
     Information message. 
     This is a <a href="#">Link</a>. Extra long text used as an information message.
  </div>
</ui5-input>
```

What do you think?

**Comment by MatthiasSchmalz** [comment]
Hi @ilhan007, 
Why do you think that I can help here? 
I assume you mean somebody else.

**Comment by ilhan007** [comment]
Hello @MatthiasSchmalz  I suggested a solution to you, not somebody else.

Instead of introducing a new property called valueStateText, you can use the existing "slot", called "valueStateMessage". As you can see the slot can receive any element and text. When this "slot" is set, the default text will not appear.

```html
<ui5-input value-state="Error">
  <div slot="valueStateMessage">
     Information message. 
     This is a <a href="#">Link</a>. Extra long text used as an information message.
  </div>
</ui5-input>
```

**Comment by ilhan007** [comment]
> Hi @ilhan007,
> Why do you think that I can help here?
> I assume you mean somebody else.

Sorry, I wanted to tag somebody else
