### ISSUE TITLE
Input type="Number": typing decimal separator causes value to disappear  

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents#1637]
Hi,

There's an issue in the `Input` control when its type is `Number`. When trying to type a decimal number, only a comma (,) can be used as the decimal separator. When trying to use a dot (.), the input's text is emptied. This can be confusing to the user, as he/she doesn't know that only the comma separator is accepted. [Here](https://codesandbox.io/s/input-number-issue-ht50j) is a small sample where you can test the behaviour of the control.

To fix this problem, I think the dot separator should be accepted. Then, when the user focus out of the control (or anything else that could trigger the `change` event), the input's value could be formatted to use a comma separator instead of a dot separator. Or the dot separator could also be left in the input's value...

Furthermore, after typing a decimal number (for example, 3,14), if the user presses the up (or the down) arrow, the value is incremented (or decremented) to the next integer (for example, 3). I think that it should increment (or decrement) the value by 1. So, for example, if the user types 3,14 and then press the down arrow, the value should become 2,14 instead of 3. Or, even better, a property could be added to specify how much the value should be incremented (or decremented).

Do you think all of this would make sense?

Thanks!
Mathieu

**Comment by ilhan007** [comment]
Hello @mathlizee 

First, I see you are using "UI5 webcomponents for React", the wrappers of the pure UI5 webcomponents. Issues related to  "UI5 webcomponents for React" should be filed here: https://github.com/SAP/ui5-webcomponents-react

However,

About the "dot" and the "comma".
The "ui5-input" actually accepts "dot" and does not accept "comma" and this is how the native HTML input element behaves. In addition you can check the sap.m.Input control from openui5. It also accepts "dot", but not "comma". So the input, the ui5-input and sap.m.Input accepts "dot" and do not accept "comma". **So, "dot" is accepted.**

You can try the ui5-input type="Number" here (there are a lot of examples, just look for "Number"): https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/

About the increment/decrement feature. Indeed, I can see that from 3,14 , the value will change to  3 or 4, instead of 2,14 or 4,14. But, this is also how the native HTML input behaves, but for this one the sap.m.Input from openui5 behaves as you expect (2,14 and 4,14). **So, this request will be discussed.**

About the empty value when typing "dot". I checked that and I can type single "dot", but if I type a second one, the value disappears. The native HTML input does not behave like that. **This seems to be a bug.**


Best,
ilhan

**Comment by mathlizee** [comment]
Hi @ilhan007,

Thank you for your response! I will use the ui5-webcomponents-react repository for future issues. I went to the link you provided ([https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/](https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/)) and tried to use a "Number" input.

However, I still get the same behaviour as I described when using a dot as the decimal separator. The comma separator seems to work fine for me... [Here](https://www.loom.com/share/73d1590d50304b1dbfc7040b45136a63) is a video showing was I was describing. As you can see, when typing "3,14", everything work as expected, by when I try to use a dot, the input is emptied.

Is is possible that I get this behaviour because my browser uses a French locale?

Thanks again!
Mathieu

**Comment by ilhan007** [comment]
Hello @mathlizee

Yes I think so, after a quick research in the net, it seems like locale specific.

**Comment by ilhan007** [comment]
The empty value turns out to be a browser bug

Try with native input element, type 1, "1" is logged, type the separator you use "comma" / "dot", empty value will be logged.

```html

 <input id='myInput' type="number">

 myInput.addEventListener("input", (e) => {
     console.lof(e.target.value);
});
```

However, we have to handle that.

**Comment by ilhan007** [comment]
From the 3 issues, 1 left about the empty value and it will be tracked in a new issue
