### ISSUE TITLE
ui5-table: refactor component internal DOM

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#1641]
**Motivation** 
Currently the Table component is using "th", "tr" and "td" tags, which are a bit difficult to style and make certain features difficult to implement. For example: applying the selection state to a row with "popped in" columns.

**Task**
To rework the Table component with plain DIVs, that would give more flexibility to implement the aforementioned feature
and any new that might come.

**Important**
- The Table's a11y should work by the spec
- The Table and all its features should continue working on IE

**Comment by hristop** [comment]
Hi @vladitasev 

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.
 
The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.
 
While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.
 
However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.
 
We are excited about the opportunities this transition will bring and the positive impact it will have on our product.
 
Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.
 
Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component. 

Best Regards,
Hristo

**Comment by simlin** [comment]
Hi,

In the 2.0 version of the UI5 Web Components we introduced a new Table component:
https://sap.github.io/ui5-webcomponents/nightly/components/Table/

The table is still in an experimental phase and certain APIs might slightly change. Nevertheless we ask you to try out the new component already now. The earlier we get some feedback the better :)

The functionality you requested is already considered. The table internally uses a CSS grid.

Best Regards
Jens
