### ISSUE TITLE
ui5-table sticky-column-header overlay open ui5-dialogs

### ISSUE THREAD

**Issue by chisholmd** [SAP/ui5-webcomponents#1722]
If you set a ui5-table as having sticky-column-header = true and then open a ui5-dialog box, the column headers overlay and obscure portions of the dialog box

**Comment by ilhan007** [comment]
Hello @chisholmd 

It is already fixed with this PR: https://github.com/SAP/ui5-webcomponents/issues/1722

However, it is not part of rc.7, it will be part of rc.8. Meanwhile, it is available in our dev versions - 0.0.0-xyz in npm. To try it out you have to install the components package with "next" tag.

npm i @ui5/webcomponents@next
