### ISSUE TITLE
[Calendar] What's the exact type of selectedDates in the Calendar component

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#1730]
In the storybook, it says the type of selectedDates property is `unknown[]`, which is very unclear.
![image](https://user-images.githubusercontent.com/4338219/82639519-79e0ca80-9c3b-11ea-8b37-9463e866dd81.png)

On the other side, my editor tells me the type of the selectedDates is `number[]`.
![image](https://user-images.githubusercontent.com/4338219/82639601-a5fc4b80-9c3b-11ea-9d26-8d9d076bd5e2.png)

If I set the selectedDates to `[Date.now()/1000]`, I'll get an error:
![image](https://user-images.githubusercontent.com/4338219/82639689-d217cc80-9c3b-11ea-833b-0e8936f2c404.png)
![image](https://user-images.githubusercontent.com/4338219/82639728-de9c2500-9c3b-11ea-8267-f52df1d7b6cb.png)

What kind of data should I pass to the Calendar component if I want to specify an initial date?

**Comment by vladitasev** [comment]
Hi @SunnyWind @MarcusNotheis 

Yes, I think it makes sense to promote the Calendar as a real standalone component. We'll estimate what kind of effort will be required and we'll update you here.

Regards

**Comment by vladitasev** [comment]
The goal of the story is to make the calendar usable standalone. This would require all APIs to be re-evaluated and changed where necessary, it should have all necessary events, proper docs.

**Comment by ilhan007** [comment]
There is а private [ui5-calendar](https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Calendar/) web component that is internally used by the DatePicker, DateTimePicker and DateRangePicker. The task is to make it public, to ensure it is completely usable standalone. But also to review the current API
and make it more user friendly if possible.

**1. API to support**

-  Props
      minDate (already exists)
      maxDate (already exists)
      primaryCalendarType (already exists)
      selectedDates(already exists)
      hideWeekNumbers (already exists)
     selection: {
            type: CalendarSelection // enum of ["Single" (default), "Range"]
      } (does not exist)

- Events
      selected-dates-change (already exists)

**2. We would like to have single range selection.**

Currently if you set the following:

`calComponent.selectedDates = [1600041600, 1600128000, 1600214400, 1600300800, 1600387200, 1600473600, 1600560000, 1600646400, 1600732800, 1600819200, 1600905600]`

You will get:

<img width="313" alt="Screenshot 2020-09-03 at 4 17 22 PM" src="https://user-images.githubusercontent.com/15702139/92120067-44827600-ee01-11ea-852e-7d9ded0f7764.png">

But, it is not possible to get it via user interaction. We have DateRangePicker, so some of the logic should be extracted from the DateRangePicker and implemented on Calendar level and then DateRangePicker would rely on the Calendar for this. If both components should communicate in this regards, it should be done via events.


**3. Upon TAB the focus should move to the "selected day" or "today".**
Currently the button, that opens the Month Picker gets the focus. But as far as I researched,  the order should be: the "selected day/today", month picker button and year picker button.


**4. The components (DatePicker, DateTimePicker and DateRangePicker) using the Calendar should adopt the API changes (if any)**

**5. The component has a test page (Calendar.html) that need to be improved:** 
- Bind for the "selected-dates-change" event,
display the result in an <ui5-input> for example
- Showcase the minDate, maxDate and hideWeekNumbers properties.
- Showcase the Single and Range selection.

**6. The component has a test spec (Calendar.spec.js) that might need to be adjusted.**

**7. Properly document - add overview section, import info, etc (refer to the existing components and the openui5 equivalent for the text), remove all @ since tags and provide jus one for the entire class @ since 1.0.0-rc.10**

**8. Playground sample - create Calendar.sample.html with few examples that showcase the component**

**Comment by ilhan007** [comment]
Phase 2 - Declarative way of setting the selected days


**API Changes**

- selectedDates is a property, that works only with array of timestamps that can be set through the Calendar property
`calComponent.selectedDates = [1600041600]`.
This is not convenient when the  Calendar is used inside React view as the selectedDates can't be set in declarative way.
That is why we would like to try with different approach by having a small component, called ui5-calendar-timestamp,
that will have the data (the timestamp) and used as child (slot) of the Calendar. Having such a component will allow the following:

```html
<ui5-calendar>
   <!--This array of elements can be looped by any app JS framework, like React -->
   <ui5-calendar-timestamp value="1600041600"></ui5-calendar-timestamp>
   <ui5-calendar-timestamp value="1600128000"></ui5-calendar-timestamp>
</ui5-calendar>
``` 

As mentioned, selectedDates  is a property. To make the above possible we have to create a slot. As the Calendar does not have other slots, we can make this one the default. We can keep selectedDates property as private, to make the change smoother, less risky, as it is used widely by all the pickers and remove it later on .Note that you have to keep the property in sync with the slot and vice versa.


- When the selected-dates-change fires it provides event details object - event.details.dates, that is an array of timestamps.
Obviously after the previous change it should return an array of the ui5-calendar-timestamp components.

**Comment by ilhan007** [comment]
Hello @SunnyWind

we introduced the Calendar as standalone component (ui5-calendar). The component is merged into the master, not yet released. This was the first step to achieve the goal. Now, we created a separate issue "Calendar: Declarative way of setting the selected days" that we will full-fill your request completely. You can track the progress here: #2528

BR,
ilhan

**Comment by SunnyWind** [comment]
Hi @ilhan007 

Fantastic 👍 

I use ui5-webcomponent-react instead of the base lib. I'll try it if the new feature is applied in that library.

BRs,
Ryan
