### ISSUE TITLE
ui5-datepicker: button in calendar - "Today"

### ISSUE THREAD

**Issue by kamych1916** [SAP/ui5-webcomponents#1745]
**Is your feature request related to a problem? Please describe.**
Hello team of UI5 Web Components! Calendar on date-picker and date-time-picker needs to button for fast adding to input "date of today".

**Describe the solution you'd like**

- If it's dati-picker:
button "Today"
![](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmfMFbe9YHWbLcKnsVrMOarWwvJMHt87DOsHTxAz7mDQEYMTir&usqp=CAU)

- if it's date-time-picker:
button "Today" and "Now", or only "Now"
![](https://help.syncfusion.com/angularjs/datetimepicker/Behaviour_settings_images/datetime1.png)

**Thanks for your attention!**

**Comment by ilhan007** [comment]
Hello @kamych1916 

thanks for your feature request, but all the components are aligned strictly with the Fiori3 design guidelines and your request deviates a lot from the spec.

The guidelines:
https://experience.sap.com/fiori-design-web/date-picker/

We will discuss it and let you know.

**Comment by deathctalker** [comment]
Hello @ilhan007 ,
I am read guideline https://experience.sap.com/fiori-design-web/date-picker/

**Comment by deathctalker** [comment]
Hello @ilhan007 ,
I am read guideline https://experience.sap.com/fiori-design-web/date-picker/

**Comment by deathctalker** [comment]
Hello @ilhan007 ,
I am read guideline https://experience.sap.com/fiori-design-web/date-picker/
There is a footer in the guideline, why can't add a "Today" button to it"?
User history: failed to select a date and to quickly select the current date, quickly click on the "Today" button. Instead of deleting the value and selecting the date again
