### ISSUE TITLE
ui5-datetime-picker: It's not possible to set a language for the component

### ISSUE THREAD

**Issue by CristianDDias** [SAP/ui5-webcomponents#1749]
**Describe the bug**
My application is in English and my browser is in Portuguese. The `ui5-datetime-picker` component is in Portuguese but I would like to set its language to English. I've tried the HTML `lang` property, but it didn't work. I've tried the URL parameter `sap-ui-language=en-US`, which works fine, but we wouldn't like to use it. How can I set a language for the `ui5-datetime-picker` component?

**To reproduce**
- Set the browser language to Portuguese (or another language other than English)
- [Codesandbox](https://codesandbox.io/s/jolly-bassi-xlpc5?file=/src/App.js)
- Click to open any `ui5-datetime-picker` and notice that the language is not English, even though the HTML `lang` property defined on the `index.html` file and on the `div` elements is English (en).

**Expected behavior**
Define a language for the `ui5-datetime-picker` component.

**Screenshots**
![image](https://user-images.githubusercontent.com/30023600/84045628-69408c00-a97f-11ea-9a4b-9917422f5bae.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: Windows
- Browser: Chrome

**Comment by vladitasev** [comment]
Hello,

The only way to change language is to modify the configuration. You don't have to use a URL parameter (if that seems inconvenient), you can set this in the script tag as well.

```html
<script data-ui5-config type="application/json">
{
	"language": "en"
}
</script>
```

See: https://github.com/SAP/ui5-webcomponents/blob/master/docs/Configuration.md
for more about configuration.

In the near future we also plan to provide an API for dynamic language change (since currently it's only set statically - in the configuration script or URL).

Regards,
Vladi
