### ISSUE TITLE
ui5-link can't be tabbed in Firefox and Safari

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#1795]
**Describe the bug**
ui5-link can't be tabbed in Firefox and Safari.

**To reproduce**
1. Use Firefox/ Safari to open https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail
2. use tab key to access interactive elements on the page and you will find top breadcrumb link can't be tabbed.
![2020-06-15_15-34-06](https://user-images.githubusercontent.com/13098801/84629983-c6a78080-af1d-11ea-8ac0-690c97bdd618.jpg)

**Context**
- UI5 Web Components version 1.0.0-rc7
- OS/Platform: {macos}
- Browser *(if relevant)*: {Firefox and Safari}
- Other information: {...}

**Comment by fifoosid** [comment]
Hello @GongRichard 

Unfortunately this issue is OS related. As you can see [here](https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox), there is a way to resolve the issue for Firefox by changing your mac settings.

On the other hand, when it comes to Safari, the expected behaviour is just different. As you can read [here](https://stackoverflow.com/a/29141377), Option + Tab works perfectly fine in your scenario. However, if a user wants to use Tab/Shift + Tab for navigation, they should explicitly toggle the following option:

Safari -> Preferences -> Advanced -> Press Tab to highlight each item on a web page

I tested out with the following versions:

MACOS: 10.15.5
Safari:  13.1.1 (15609.2.9.1.2)
Firefox: 77.0.1

Best regards,
Filip
