### ISSUE TITLE
ui5-button can't be tabbed in Safari

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#1797]
**Describe the bug**
ui5-button can't be tabbed in Safari.

**To reproduce**
1. Use Safari to open https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail
2. use tab key to access interactive elements on the page and you will find action buttons can't be tabbed.
![2020-06-15_15-34-06](https://user-images.githubusercontent.com/13098801/84631030-5568cd00-af1f-11ea-8cb0-f61ad98328cd.jpg)

**Context**
- UI5 Web Components version 1.0.0-rc7
- OS/Platform: {macos}
- Browser *(if relevant)*: {Safari}
- Other information: {...}

**Comment by fifoosid** [comment]
Hello @GongRichard 

This issue is related to #1795.

The expected behaviour in Safari is different. As you can read [here](https://stackoverflow.com/a/29141377), Option + Tab works perfectly fine in your scenario. However, if a user wants to use Tab/Shift + Tab for navigation, they should explicitly toggle the following option:

Safari -> Preferences -> Advanced -> Press Tab to highlight each item on a web page

Best regads,
Filip
