### ISSUE TITLE
Can't tab any elements in IE

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#1813]
**Describe the bug**
Can't tab any elements in IE

**To reproduce**
1. Use IE to open https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock#/goal-detail
2. use tab key to access interactive elements on the page and you can't tab any elements.

**Context**
- UI5 Web Components version 1.0.0-rc7
- OS/Platform: {win10}
- Browser *(if relevant)*: {IE11}
- Other information: {...}

**Comment by ilhan007** [comment]
Hello @GongRichard I have the feeling that this is something not related to the web components.
Can you try to replace the ui5-buttons (the ones below) with the native ones (<button>) and check if they would be reached with the TAB key.
<img width="144" alt="Screenshot 2020-06-16 at 2 34 21 PM" src="https://user-images.githubusercontent.com/15702139/84769463-8b20bb00-afde-11ea-8889-1b934fa2975d.png">

**Comment by vladitasev** [comment]
Hello @GongRichard 

The problem is that you have put "disabled" on a "div":
![image](https://user-images.githubusercontent.com/15844574/86002476-0f306500-ba19-11ea-8517-42ad10cefa21.png)

This confuses IE enormously. Just try this in IE:
```html
<div disabled>
		<button>Cannot click</button>
	</div>
```
and you'll see that you cannot tab inside at all.

So not related to UI5 Web Components.

Regards,
Vladi
