### ISSUE TITLE
Memory leak with Dialog closing and Deleting from DOM at same time

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#1821]
**Describe the bug**
If a Dialog is closed and removed from the DOM at the same time, the static area item is deleted and then re-created due to a RenderScheduler call on the block layer at close time which is not ignored later when the shadow DOM is destroyed in the same tick.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-99gmi
2. click the open button and close button a few times
3. look into the DOM tree at the static area
4. notice that there are now a few static area items for each of the block layers of the dialogs that have been deleted already

**Isolated example**
https://codesandbox.io/s/ui5-webcomponents-99gmi

**Expected behavior**
The static area item should be destroyed along with the Dialog when onExitDOM is called.

**Screenshots**
![image](https://user-images.githubusercontent.com/730310/84791479-812f9580-afa7-11ea-950c-28344c5907af.png)

**Context**
- UI5 Web Components version: 0.21.3
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Affected components** *(if known)*
Popup/Dialog
```

**Comment by codefactor** [comment]
To explain a little more context here - we have a complex dialog which we open and then clean up any time the dialog is closed. There are several work arounds we found though, but it should be an easy fix as well.

Work-arounds:
1. Delay the DOM removal with a setTimeout so it occurs in the next tick
2. Do not remove the DOM after the dialog is closed, allowing for the same DOM to be reused in case the user opens the dialog again.

**Comment by vladitasev** [comment]
Hi @codefactor 

We are in the review process of the above change. As our codebase has evolved a bit since the time we created `release-0.21.0`, we'll not downport the fix directly, but rather just apply a part of it manually so that the memory leak disappears. We'll keep you posted on the progress.

In the meanwhile, we'd like to ask you whether you use `renderDeferred` and `renderImmediately` in your custom components, because one of the changes we're discussing is making these reject promises in certain scenarios, which would require changes in your code as well, if we were to merge this part of the code in particular.

Regards

**Comment by codefactor** [comment]
@vladitasev ,
Yes - we do use both of these functions. Rejecting a promise should not be too difficult to implement; however, most of the time we use the renderDeferred function and do not await on the promise - so in those places most likely a rejected promise would be logged as an error to the console. Maybe we can have a different function that doesn't care if it really gets rendered or not?

**Comment by vladitasev** [comment]
Thanks,

This was everything we needed to know. Indeed, having two sets of functions would be a good solution. We'll update you once we decide on the API.

Vladi
