### ISSUE TITLE
Tree description feature request

### ISSUE THREAD

**Issue by haojia321** [SAP/ui5-webcomponents#1845]
Hello Team,

Currently the tree item component only accepts text attribute. It would be good if it can also display additional field like description. Similar to the one we have in ListItem. Please see screenshot below for your reference.

<img width="830" alt="Screen Shot 2020-06-19 at 10 39 41 AM" src="https://user-images.githubusercontent.com/4699158/85144647-74b27380-b219-11ea-9488-32853d1b864f.png">

Thanks,
Hao

**Comment by mastanshaikk** [comment]
The ask is for a ui5-tree-item-custom similar to ui5-li-custom where the node content can be custom provided.

**Comment by vladitasev** [comment]
Hello @haojia321  @mastanshaikk 

If all you need is to add "description", we can propose the following solution:

https://github.com/vladitasev/custom-tree

This is a small project, demonstrating how to create your custom tree with miminal overhead.

It looks like this:

![image](https://user-images.githubusercontent.com/15844574/85402314-22988780-b564-11ea-98d7-73767993b716.png)

Let us know if it works for you.

Regards,
Vladi

**Comment by haojia321** [comment]
@vladitasev Thank you for your response. The description in our case is optional, so some of the item will have description some of them won't. Will this demo work for that case too?

For now we only need title and description but we might want to display more. So we are actually thinking if we could enhance the ui5-tree-item to support full customization, similar to what ui5-li-custom does. If we can do this it will be easier for us to enhance our UI in the future.

**Comment by vladitasev** [comment]
@haojia321 I will then enhance the sample to show how you can replace the "tree list item" in addition to the "tree item". Then you'll have even more control.

**Comment by mastanshaikk** [comment]
That sounds good @vladitasev

**Comment by mastanshaikk** [comment]
@vladitasev If a slot for tree item content was offered in place of ```{{this.treeItem.text}}```, it could let the target developer to simply add the tree item content into the slot instead of creating the custom tree where it will not limit to the use case that the developer was working. I guess the slot approach will help address this use case in a generic way.

**Comment by vladitasev** [comment]
@mastanshaikk Sounds like a great idea!
We'll try this out today

**Comment by vladitasev** [comment]
Hello, we tried the "slots" idea, but we couldn't get it to work mainly due to the fact that `ui5-tree-item` s are nested into each other and there's no way to proxy the slot back to the internal list of the tree.

So we made the initial solution easier by providing a partial that you can override without copying the whole tree `.hbs` file.

See:
https://github.com/vladitasev/custom-tree/blob/master/src/CustomTree.hbs

Regards,
Vladi
