### ISSUE TITLE
[FeatureRequest] MultiInput Component

### ISSUE THREAD

**Issue by alex-zhang** [SAP/ui5-webcomponents#1852]
hi, 

please support MultiInput Component in ui5 web component.

ui5 sample link http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/index.html#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp

fiori-design: https://experience.sap.com/fiori-design-web/multiinput/

project requirement ux:

![image](https://user-images.githubusercontent.com/4457451/85264525-65465b00-b4a3-11ea-9eea-7591b58067d8.png)

**Comment by vladitasev** [comment]
Hello @alex-zhang 

We deliberately don't have this component, because we have MultiComboBox. In OpenUI5, for the last several years there have been several attempts to merge these two controls, as they are very similar to the point where each requirement for one of them must be implemented in the other one and it's inefficient to support both. So with UI5 Web Components we decided to only support one (MultiComboBox) with the ability for user text as well, to achieve middle ground. If there is something specific that you need and is not found in MultiComboBox, we can discuss this separately as a feature request for this control.

From what I can see, you need to be able to provide your own dialog when the user clicks the button (rather than the standard one we have with MultiComboBox). Can you show me some more picture of how it looks like with values. Can the user type freely? Then we can discuss internally what we can suggest you to implement this.

Regards,
Vladi

**Comment by alex-zhang** [comment]
hi @vladitasev 

thanks for ur reply.

![image](https://user-images.githubusercontent.com/4457451/85399489-7ec1d280-b589-11ea-85ab-b469cd79f631.png)

yes, there is a custom dialog after use click the icon. yes, user also can type freely that when the  custom dialog is open  the user input's can also be the search value. 

just as this example show.
 
http://veui5infra.dhcp.wdf.sap.corp:8080/demokit/index.html#/entity/sap.m.MultiInput/sample/sap.m.sample.MultiInputValueHelp
