### ISSUE TITLE
Custom ui5 input webcomponent suggestions

### ISSUE THREAD

**Issue by kostadin-kar** [SAP/ui5-webcomponents#1878]
**Is your feature request related to a problem? Please describe.**
We have an interesting use case for the ui5 input webcomponent, specifically the provided suggestions. When we type text, there is a pattern recogniser for certain placeholders. When you enter the placeholder, the suggestions start appearing. The placeholder is segregated into a few different segments, denoting a path. We would like to have different suggestions to pop up when a new segment is reached in the entered path. It is very important that scrolling through or selecting a provided suggestion does not clear or replace the entire input, but only the part that follows  

**Describe the solution you'd like**
If there is a way to prevent the entire entered input from being replaced when selecting a suggestion would be great (e.g. insertion mechanism). 

**Describe alternatives you've considered**
We have considered applying monkey patches to the underlying component code, so as to achieve the desired behaviour. Here are some images

<img width="688" alt="Screenshot 2020-06-29 at 16 15 35" src="https://user-images.githubusercontent.com/32493838/86015810-b5d13180-ba2a-11ea-988b-fcab2fd97d7e.png">

<img width="803" alt="Screenshot 2020-06-29 at 16 15 05" src="https://user-images.githubusercontent.com/32493838/86015836-bec20300-ba2a-11ea-89de-a9adbda1ae45.png">

<img width="667" alt="Screenshot 2020-06-29 at 16 13 52" src="https://user-images.githubusercontent.com/32493838/86015856-c71a3e00-ba2a-11ea-9f07-caa53bec9481.png">

**Additional context**
Expected behaviour should follow these images:

<img width="476" alt="Screenshot 2020-06-29 at 17 52 24" src="https://user-images.githubusercontent.com/32493838/86021312-a1446780-ba31-11ea-8e9e-b8abf343cb5e.png">

<img width="468" alt="Screenshot 2020-06-29 at 17 52 35" src="https://user-images.githubusercontent.com/32493838/86021329-a5708500-ba31-11ea-9cfe-b3e82646a7de.png">

<img width="473" alt="Screenshot 2020-06-29 at 17 55 30" src="https://user-images.githubusercontent.com/32493838/86021444-c33dea00-ba31-11ea-83af-3065fda46035.png">

<img width="470" alt="Screenshot 2020-06-29 at 17 53 21" src="https://user-images.githubusercontent.com/32493838/86021475-c89b3480-ba31-11ea-97f0-ae4877233bb4.png">

**Comment by ilhan007** [comment]
Hello @kostadin-kar 

we have just merged a change within the Input, that allows third party components, extending ones, to control how the value should change upon suggestion preview. For the purpose, we added a new method "Input.prototype.updateValueOnPreview", that can be overwritten. Here is the method:


```js
/**
 * Updates the input value on item preview.
 * @param {itemValue} itemValue The value of the item that is on preview
*/
updateValueOnPreview(itemValue) {
  this.value = itemValue; // here the extending component may overwrite the behaviour
}
```

Basically, the method is called whenever the user navigates through the items with the arrow keys and replaces the entire text in the input field with the text of the suggestion on preview. For your use case, by overwriting this method, you can control how the value should change, instead of replacing the entire text, you can replace just part of it, to add on, etc.
You have the current value (this.value) and you have the value of the suggestion as a parameter (itemValue) and it is up to you how to update the value of the Input (this.value).


```js
import Input from "@ui5/webcomponents/dist/Input.js";

class MyInput extends Input {

  /**
   * Updates the input value on item preview.
   * @param {itemValue} itemValue The value of the item that is on preview
   * @overridden
  */
  updateValueOnPreview(itemValue) {
     // this.value = fn(this.value, itemValue); the new value is kind of function of the currentValue and the itemValue
  }
}
