### ISSUE TITLE
[ Feature Request ] [ TabContainer ] Add Slot to TabInStrip & TabInOverflow & TabSeparator to make them more conveniently be customized

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#1958]
**Hi UI5 WebComponents team,**
I am hubery shen from Successfactors. I are using tab container component. 
Thanks you for giving me the example about how to extend the tab container by writing web component code. 
**But If slots be added to TabInStrip & TabInOverflow & TabSeparator, it will be more conveniently for them be customized.**

### TabContainer Website
[TabContainer Website](https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/)

### Feature Request Description
Add Slot to TabInStrip & TabInOverflow & TabSeparator to make them more conveniently be customized

### Expected Code

**Customize TabInStrip by slot**

```
<ui5-tab>
    <div slot="custom-strip"> my codes ...</div>
</ui5-tab>
```
![tab container tabinstrip](https://user-images.githubusercontent.com/63704163/87621138-afdd8f00-c752-11ea-81fa-3e6c08476bb9.png)

**Customize TabSeparator by slot**

```
<ui5-tab-separator>
    <div slot="custom-separator"> my codes ...</div>
</ui5-tab-separator>
```

![tab container separator](https://user-images.githubusercontent.com/63704163/87623434-f4b7f480-c757-11ea-984f-d7000a8c8fd2.png)

**Customize TabInOverflow by slot**

```
<ui5-tab-overflow>
    <div slot="custom-overflow"> my codes ...</div>
</ui5-tab-overflow>
```

![tab container overflow](https://user-images.githubusercontent.com/63704163/87623550-347edc00-c758-11ea-8d24-4d7b30d51080.png)

**Comment by vladitasev** [comment]
Hi @Hubery-Shen ,

After thinking about the proposed solution, there are two fundamental problems that don't allow us to proceed with it:
 - If the tab container slots tabs, and tabs slot other items (`<div slot="strip">`), we can't display the other items in the tab container, only in the tab. Therefore a nested structure, in which a tab slots other items, representing it in the tab strip and overflow menu is not possible. The only possibility would be to have a flat structure, where the tab container gets as direct children tabs, tab strip items and overflow items. But then we get back to the same question - how do we link these to one another?
 - The second problem is that the tab container needs to change the CSS of the items when the user clicks on the tabs. The most common functionality is to set the "selected" state of a tab - currently background + bottom border. This is now possible since the tab container builds and knows the tab strip items so it modifies them at will. But if you pass from the outside arbitrary items, the tab container won't know how to change them to look selected for example. Other similar states are focused and disabled. There are also, although less important, the semantic variations - positive/negative/information/etc... The only reliable way to solve the problem would be to have specific web components for the strip items, imagine `<ui5-tab-strip-item` with predefined properties such as `selected`, `focused`, `disabled` and then the tab container would not change CSS, but would rather directly manipulate the items' public API: `stripItem.selected = true;`. This would work, but again, you would need to create custom items by extending the existing tab or something similar. So this won't be a "no-new-elements" solution either.

We still believe that the right approach would be to create a custom tab container, even if used for one app only, as it will implement the needed design and behavior. You could add more properties to make it more universal, so you don't need to create two custom elements for two different tab containers in the same app for example. Let's discuss further on the next meeting.

Regards,
Vladi

**Comment by Hubery-Shen** [comment]
Hi @vladitasev ,
Thanks vladitasev.
Let's discuss further on the meeting.

**Comment by ilhan007** [comment]
Hello @Hubery-Shen Vladi explained the obstacles with the proposal, do you have some input on the topic.
As there is no update since a month I am closing the issue, but feel free to reopen it in case you have an update.
