### ISSUE TITLE
Web Components do not render in IE-11 while in dev mode

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#1959]
**Describe the bug**
Web Components do not render in IE-11 while in dev mode and no errors in the console either. 

**To reproduce**
1. Clone "@xweb/common-webcomponents"
2. Install, start and open http://localhost:8081/test-resources/pages/headerMock.html in IE-11
3. Notice no errors in the console and ui5-shellbar does not render

- Side note: As a work around we were running build and using serve to serve the build file, but with the recent upgrade to 0.21.8 we ran into a build failure that was reported here: https://github.com/SAP/ui5-webcomponents/issues/1946 

**Expected behavior**
Web Components render in IE-11 in dev mode

**Screenshots**
![wc not rendering IE dev mode](https://user-images.githubusercontent.com/38701667/87700042-959fb300-c74a-11ea-8ccf-53d078b49ee8.PNG)

**Context**
- UI5 Web Components version: 0.21.8
- OS/Platform: Windows 10
- Browser *(if relevant)*: IE-11

**Comment by vladitasev** [comment]
Hi @allen138 

The reason you're not seeing anything on IE (not even an error) is that you have commented out the webcomponents polyfill from the html file:

```html
<!--<script src="../../webcomponentsjs/webcomponents-loader.js"></script>-->
```

This is the webcomponents polyfill. When I uncomment it however, I get "syntax error", because there is ES6 code. It seems the ES5 bundle did not undergo babel processing at all.

Upon further inspection, it turned out the rollup configuration file `config/rollup.config.js` has been modified, so probably something there broke.

Regards,
Vladi

**Comment by allen138** [comment]
Hi @vladitasev,

I un-commented the webcomponents-loader.js script, but I still do not get any errors in the console and the component does not load. However, when I check the network traffic, "bundle.es5.js" has thrown a 404. The rollup.config.js shows this file as an input and looks like it has a proper output. Please see the following: 
![rollup config log](https://user-images.githubusercontent.com/38701667/87996629-a8e2b380-caa7-11ea-8ee0-1ceb90bf17c6.png)

But the file format is "iife", so I'm thinking that the error mentioned in #1946 could be the reason why this file does not get successfully built?
![iife rollup error](https://user-images.githubusercontent.com/38701667/87996700-e5161400-caa7-11ea-81cd-ec3008eb5255.png)

**Comment by vladitasev** [comment]
Hi @allen138 ,

I checked out the master branch, upgraded to 0.21.8 and ran the test server:
 - The es5 file is there and gets served: 
![image](https://user-images.githubusercontent.com/15844574/88055894-5ddca500-cb68-11ea-996a-99206d21f735.png)
However, for IE unfortunately you have to clear cache every time in order to get the latest changes (through the Network tab).
The error is also there:
```
SCRIPT1002: Syntax error
```

However, in your custom rollup config there is:

```js
if (process.env.TARGET_VERSION === "es6") {
  rollup = rollup.filter((config) => !/es5\.js$/.test(config.input));
}
```
so if you have this variable, it will filter out the IE build altogether and will never generate it. Can you check where/if it is set for you?

On a separate note, you have the mock build (in addition to the esm.js build). You should have the same es5 mock build too (in addition to the es5 build) and then in the test page:

```html
<script src="../../webcomponentsjs/webcomponents-loader.js"></script>
<script src="../../resources/bundle.mock.js" type="module"></script>
<script nomodule src="../../resources/bundle.es5mock.js"></script>
```

for example. Otherwise, none of the mock code would ever be loaded for IE.

Regarding the `iife` thing - yes, the IE11 build is supposed to be like that, and I don't think this issue is related to the build issue, it's just that the same term comes up.

Regards,
Vladi

**Comment by allen138** [comment]
Hi @vladitasev,

Thanks for the details. I was working in my branch "feature/personInput" and it seems I am having different issues compared to the master branch. So I checked out the master branch and upgraded to 0.21.8 just as you described and now I do get the syntax error and the bundle.es5.js file is a 200. The component still does not seem to render though. The custom config you mentioned ```
if (process.env.TARGET_VERSION === "es6") {
  rollup = rollup.filter((config) => !/es5\.js$/.test(config.input));
}
```
so if the target is "es6" then we do not include any es5 bundles. So far when I console log `process.env.TARGET_VERSION` it is returning undefined, so it never goes inside this statement. 

Please try to pull my branch "feature/personInput", install and start and you should be able to reproduce the `iife` error and the es5 bundle will then be a 404. Here is the log for the rollup config before we export it:
![rollup config before exporting](https://user-images.githubusercontent.com/38701667/88082302-75029f00-cb36-11ea-8769-9d4acb0a90d3.PNG)

**Comment by vladitasev** [comment]
Hi @allen138 

I pulled the latest version of the `feature/personInput` branch and I had errors which I had to fix a bit - mainly queryPeopleSearch exports. Then I could run the build successfully.

This however is not related to the IE11 problem directly (why code does not get transpiled) so I'll update you once I have some findings there as well.

Regards,
Vladi

**Comment by allen138** [comment]
Hi @vladitasev,

There should not have been any errors, did you do a npm install? I know there was changes to the "@xweb/core-utils" which had changes to the queryPeopleSearch, but running an install should fix those issues. But anyways, yes we need to figure out why the code is not getting transpiled. Thanks for your help!

Regards,
Allen
