### ISSUE TITLE
[All] Dropping a file outside upload collection removes page scrollbar

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#2001]
http://localhost:8081/test-resources/pages/UploadCollection.html

Initially:
![image](https://user-images.githubusercontent.com/15844574/88537732-c7502e00-d016-11ea-9605-70f755ed16ba.png)

Drop some file between upload collections:

![image](https://user-images.githubusercontent.com/15844574/88537794-dd5dee80-d016-11ea-897e-d8560d78b6d1.png)

Scrollbar is gone

**Comment by gmkv** [comment]
Hi Vladi,

That's the expected behaviour. Initially the UploadCollection is empty, for which a min-height is applied to it:
```css
.ui5-uc-content.ui5-uc-content-no-data {
    min-height: 20rem;
}
```

Once there are elements in the default slot (files were uploaded), that `ui5-uc-content-no-data` class is removed and the element is as tall as its contained children, which in this case is shorter than the inital height of 20rem, causing the page to shrink in height, therefore removing its scrollbar.

**Comment by gmkv** [comment]
The component accepts dropping files in its header area which should be changed. It should only allow dropping in its 'drop-zone'.
