### ISSUE TITLE
ui5-label: be able to put the required star symbol at the start of the label

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents#2105]
Dear colleagues,

I am from Successfactors Web Experience Shanghai team. Here is just a simple and minor feature request.

In fiori design, the required star symbol is put at the start position of the user input.
Please check https://experience.sap.com/fiori-design-web/input-field/#required

Is it possible to provide a property in ui5-label for the caller to put the red star at the start of label, just like:
![image](https://user-images.githubusercontent.com/1867889/90528007-bc676400-e1a4-11ea-99fb-0653261b4061.png)

Thanks
Jacob

**Comment by ilhan007** [comment]
Perhaps this is the old design, that has not been updated: See the openui5 Label control example:
https://openui5nightly.hana.ondemand.com/entity/sap.m.Label/sample/sap.m.sample.Label
The "star" symbol is displayed after the text. However, we will consider the request to provide a option and display it before the text. I will update you soon.


Best,
ilhan

**Comment by ilhan007** [comment]
I have a question. Do you need to have the "star" in the beginning or you filed the issue, because you though this is how it should be by Fiori. Because it turns out that the "star" should be after the text. The designers did not update the public website that you refer.

So if you set it in the beginning it won't be by the latest Fiori guidelines. Do you still need it?

This is the spec sapui5/openui5 and we follow,  snapshots from internal Visual Design Wiki:

<img width="442" alt="Screenshot 2020-08-19 at 3 49 15 PM" src="https://user-images.githubusercontent.com/15702139/90636673-a359c400-e233-11ea-9453-b3076994b9fb.png">

<img width="527" alt="Screenshot 2020-08-19 at 3 49 44 PM" src="https://user-images.githubusercontent.com/15702139/90636683-a654b480-e233-11ea-8da5-076776dc55f2.png">

**Comment by zhangliangyi** [comment]
@ilhan007 
Actually this is our current UX requirement to put the star before the text. I also asked UX member what the standard is but it seems that there are some different views between UX and Engineer or even in the UX members internally.
So far I have a workaround to meet the requirement and if this design is confirmed that it is not fiori standard, I am OK to close this issue.

Thanks
Jacob

**Comment by ilhan007** [comment]
I see. Fiori suggests to have the "start" at the end, so this requirement in not FIori standard.

Thanks,
ilhan
