### ISSUE TITLE
Shellbar does not Resize according to screen zoom/ size

### ISSUE THREAD

**Issue by andressasilveira** [SAP/ui5-webcomponents#2128]
**Describe the bug**
When the content overflows the body (in screens less than 1440px or zooming the page) and enable the horizontal scrollbar, the shellbar does not follow the body, not resizing as expected

**To reproduce**
1. Go to https://assignments.ingress.dev.lp.shoot.live.k8s-hana.ondemand.com/ 
2. Zoom in until the enablement of horizontal scroll bar
2. Observe the shellbar does not follow the card that overflow the screen size

**Isolated example**
[CodeSandbox with Isolated Example](https://codesandbox.io/s/cool-currying-3nsbb?file=/src/App.js)

**Expected behavior**
Shellbar fill 100% the width, even with overflow

**Screenshots**
Screen 1920px wide
![image](https://user-images.githubusercontent.com/13407969/90684925-5c71cb80-e23f-11ea-97f7-eee47dfcb1d4.png)

Screen 1247px wide
![image](https://user-images.githubusercontent.com/13407969/90685701-91cae900-e240-11ea-889b-2cb54db19ff8.png)

**Comment by ilhan007** [comment]
Hello @andressasilveira 

When I try to open https://assignments.ingress.dev.lp.shoot.live.k8s-hana.ondemand.com/ and use my SAP email and pw, the app responds with "Looks like you have no permission to access this page" and I don't have these cards in the content and I can't reproduce the issue.

Then I opened the codesandox sample, but there the ShellBar is taking 100% of its parent "div".
The "div" element under the ShellBar with the red background has width: 150% and that is why it is wider.
There is nothing wrong with the ShellBar in the sample, the "body" has margins by default, that's why it is not 100% width, then the parent <div id="root" takes 100% of the body, and then the ShellBar takes 100% from the "root div". The Shellbar takes the full width of its parent. Sorry, but I can't see un issue so far?

BR,
ilhan
