### ISSUE TITLE
PopoverUtil report endless errors

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#2165]
**Describe the bug**
In my Karma test, If I create a Popover, and remove the DOM mounted with the Popover, I will get endless ERROR logs like the pic. Even though I use  `ReactDOM.unmountComponentAtNode();` to unmount ahead, I still get these errors.
![image](https://user-images.githubusercontent.com/4338219/91736032-b0859400-ebdf-11ea-9d78-20daf923db03.png)

![image](https://user-images.githubusercontent.com/4338219/91736094-c430fa80-ebdf-11ea-9f55-cd63a4d6a797.png)

**Expected behavior**
No error reported.

**Context**
- UI5 Web Components version: "@ui5/webcomponents": "1.0.0-rc.7"
- OS/Platform: MacOS
- Browser *(if relevant)*: Karma(Chrome)

**Affected components**
Popover

**Comment by fifoosid** [comment]
Hello @SunnyWind 

Have you tried reproducing the bug with version RC8? If the bug is still present, could you please create a [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html) example with the issue. Locally I am not able to reproduce the issue by removing the popup parent from the DOM

**Comment by SunnyWind** [comment]
Hi @fifoosid 

 I wrote a sample to reproduce this issue.
https://codesandbox.io/s/vigorous-sky-bwg5k?file=/src/App.js
