### ISSUE TITLE
[Feature Request][A11Y][Panel]  Need a parameter to custom the aria-labelledby attribute of ui5-panel-header dom for Panel component

### ISSUE THREAD

**Issue by Hubery-Shen** [SAP/ui5-webcomponents#2188]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Feature request**
1. Need a parameter to custom the aria-labelledby attribute of ui5-panel-header dom for Panel component
![FR  Panel](https://user-images.githubusercontent.com/63704163/92436256-da8a1800-f1d6-11ea-92aa-14d15c93f72b.png)

**Expected API Spec**

```
<ui5-panel labelledby="myLabelledbyid">
</ui5-panel>
```

**Comment by ilhan007** [comment]
Hello @Hubery-Shen 

there is a slot "header" in the Panel, that you can use your own element for div and set any attributes you need.
The slot is implemented exactly for such customization that might be needed.

Did you consider using the header slot? Of course, the UX differs a bit, with a built-in header the entire header can be clicked, while with custom - just the toggle arrow button.

BR,
ilhan

**Comment by Milo-Shen** [comment]
Hi @ilhan007 

Question 1:
I will try the header slot. And can the custom header behave the same as the built-in header ? ( for example:  the entire header can be clicked )

Question 2:
I think provide a parameter to custom the aria-labelledby attribute of ui5-panel-header DOM for Panel component is make sense. Because it means a huge effort for us to rewrite all the head panel just to add a aria-labelledby attribute.
