### ISSUE TITLE
Date Time Picker minimum width limit

### ISSUE THREAD

**Issue by m-ignatov** [SAP/ui5-webcomponents#2194]
Date Time Picker has a minimum width of 15 rem, unlike the other Date/Time components which have min. width of 10 rem.

**Isolated example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-uok8e?file=/index.html)

**Context**
- UI5 Web Components version: 1.0.0-rc.8

**Affected components** *(if known)*
Date Time Picker

**Comment by ilhan007** [comment]
Hello @m-ignatov 
thanks for reporting.

The DateTimePicker and after the latest development the DateRangePicker have min-width: 15 rem,
while all other pickers (DatePicker, TimePicker, DurationPicker) and all other input components such as Input, Select, ComboBox, MultiComboBox and MultiInput have min-width (not 10rem) of 13.25rem.

You can set to all of them width: 15rem; and they will become equal. But, if you want the components to be equal and smaller than 15rem, for example 10rem as in the samle - this is what is currently not possible.

**Solution:**
Instead of making all of them 15rem (because we have 2 components out of 10 with such a demand), we will make the min-width also customizable. So setting min-width: 10rem; width: 10rem will make them equal and smaller in width.

Would be fine for your case?

_Note: The DateTimePicker the DateRangePicker require more space to display the date and time, and date range.
So, if you were able to make the DateTimePicker the DateRangePicker just 10 rem wide, the value won't be read._


BR,
ilhan

**Comment by m-ignatov** [comment]
@ilhan007 Sounds great! Making the min-width customizable should do the job.
Thanks 👍
