### ISSUE TITLE
RTL: Panel expand / collapse button's icon faces incorrect direction

### ISSUE THREAD

**Issue by udi-nir** [SAP/ui5-webcomponents#2212]
**Describe the bug**
When I use a page with Right To Left direction, the button's arrow icon is not of the correct direction (left / top).

**To reproduce**
1. Go to documentation page: https://sap.github.io/ui5-webcomponents/playground/components/Panel/?sap-ui-rtl=true
2. Press the Panel expand / collapse button.
Actual result: the buttons arrow icon is not of the correct direction (left / top).

**Expected behavior**
the buttons arrow icon is of the correct direction (left / bottom).

**Screenshots**
![ui5_panel_rtl_button_arrow_direction](https://user-images.githubusercontent.com/17381639/93059942-1c550b80-f67a-11ea-9587-35d89aa8471d.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.7
- OS/Platform: Win10

Hope I didn't miss anything silly...
Thanks,
Udi

**Comment by ilhan007** [comment]
The issue was recently reported and fixed: https://github.com/SAP/ui5-webcomponents/issues/2191

The fix will be part of:
1.0.0-rc.9 - our public version (2-3 weeks timeframe)
0.23.2 - based on 1.0.0-rc.8 and including non-breaking fixes since 1.0.0-rc.8 (in 1 week timeframe)
0.0.0-commit_hash - available under the "next" tag in NPM, representing our current master (in 1-2 days timeframe)

**Comment by udi-nir** [comment]
Super, thx!
