### ISSUE TITLE
ComboBox doesn't update immediately after set value via useState

### ISSUE THREAD

**Issue by lenient** [SAP/ui5-webcomponents#2233]
**Describe the bug**
The value of ComboBox doesn't update immediately after set value via useState.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/story/ui5-web-components-combobox--generated-default-story
2. Click the down arrow to select one item from the dropdown list.
3. Typing some text like 'test' in the `value` property on the right panel, you will see the ComboBox still shows the previous value text.
4. Just click on the ComboBox, you will see the text updated.

**Expected behavior**
The text value should be updated immediately once changing it.

**Context**
- UI5 Web Components version: v0.10.5

**Affected components** *(if known)*
ComboBox

**Comment by fifoosid** [comment]
@MarcusNotheis I suppose that this is an issue related with the sample. Can you take a look?

**Comment by MarcusNotheis** [comment]
Hey @fifoosid,

looks like ComboBox is not reacting to the value update immediately. I've created this [codesandbox](https://codesandbox.io/s/nervous-gareth-yt7wu?file=/src/App.js) with "plain" UI5 Web Components and I can observe the same behavior.

Web Components Version: 1.0.0-rc.8

**Comment by ilhan007** [comment]
Hello @lenient 
at first we resolved the issue the the referenced PR, but after further testing we found 
side effects on the component behaviour, see the the issue: https://github.com/SAP/ui5-webcomponents/issues/2321

So we will revert the change and try to fix it in another way.
Sorry for the inconvenience.

BR,
ilhan

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rl 

**Describe the bug**
The value of ComboBox doesn't update immediately after set value via useState.

**Steps**
1. Go to [codesandbox](https://codesandbox.io/s/nervous-gareth-yt7wu?file=/src/App.js) 
2. Click the down arrow to select one item from the dropdown list.
3. Typing some text like 'test' in the value property on the right panel, you will see the ComboBox still shows the previous value text.

4. Just click on the ComboBox, you will see the text updated.

**Expected behavior**
The text value should be updated immediately once changing it.


Note: we tried to resolve the issue in the past with the referenced [PR](https://github.com/SAP/ui5-webcomponents/pull/2253), but after further testing we found side effects on the component behaviour, described by this issue #2321 and that's why we reverted the change.

**Comment by jaquelinebonoto** [comment]
Hi! Do we have any progress on this fix?? We are using this component and facing this situation too.
Best Regards

**Comment by Martotko** [comment]
It seems it will be handled with a backlog item.

**Comment by MarcusNotheis** [comment]
Hey colleagues,
any news on this issue? We are facing the same issue now in multiple apps and have to replace all `ComboBox` with `Select` components.
