### ISSUE TITLE
[ui5-multi-combobox / ui5-multi-input] tokens are cutted wrong

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#2262]
When there is not enough space for all tokens they are cutted from the wrong side. In some cases the last token can't be deselected through the token.

**Expected:**
Tokens to be cut from the left side and the last token **X**  to be visible.
![image](https://user-images.githubusercontent.com/31909318/94437807-f0bc4000-01a6-11eb-977d-003da67d9653.png)

**Comment by ilhan007** [comment]
@nnaydenow do you still reproduce that
 https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiComboBox/

**Comment by nnaydenow** [comment]
@ilhan007 Yes. It is still reproducible.

![image](https://user-images.githubusercontent.com/31909318/100877305-3d770c80-34b1-11eb-86ad-a1d300006ebf.png)

**Comment by nnaydenow** [comment]
@ilhan007 Focusing the input field the items should be cutted from the left side. Not from the right.

![image](https://user-images.githubusercontent.com/31909318/101162794-7511c000-363b-11eb-98e8-b4edba72d27e.png)

**Comment by ilhan007** [comment]
> @ilhan007 Focusing the input field the items should be cutted from the left side. Not from the right.
> 
> ![image](https://user-images.githubusercontent.com/31909318/101162794-7511c000-363b-11eb-98e8-b4edba72d27e.png)

This makes sense, I will forward to the responsible team @SAP/ui5-webcomponents-topic-rl

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl

**What is the issue:** Currently when the tokenizer expands either when the user clicks in the input field or the "nMore" text, the last token can be cut off, because the tokens are displayed, starting from the first. And the last tokens are cur off, when the space is not enough for all to fit in. And this is not how it is supposed to work. Just the oposite - the tokens should e displayed starting from the last and let the first ones be cut off.
For reference use the openui5 [mcb sample](https://openui5nightly.hana.ondemand.com/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox).

**Note:** the issue applies to the MultiInput as well, I suggest providing fix in the Tokenizer that will fix the behavior in both parent components. Ideally, the Tokenizer should align its tokens based on state (private property value).

**Comment by Martotko** [comment]
There is a backlog item for this ticket.
