### ISSUE TITLE
Wrong color for StandardListItem "Information" infoState

### ISSUE THREAD

**Issue by m1trix** [SAP/ui5-webcomponents#2296]
**Describe the bug**
When you set the `info-state` property of a `<ui5-li>`, it's not the right color.

**Expected behavior**
According to the [Fiori guidelines](https://experience.sap.com/fiori-design-web/list-overview/#highlight-items) the color should be [Semantic Color Information](https://experience.sap.com/fiori-design-web/colors/#semantic-colors).

**Screenshots**
![image](https://user-images.githubusercontent.com/3427023/94993884-b1259780-059c-11eb-8b6e-ce67e28d41af.png)

**Context**
N/a

**Affected components**
StandardListItem

**Comment by ilhan007** [comment]
Hello @m1trix 

we will have a discussion with the  main contact from VD side Gerrard Kean regarding the correct parameters that have to be used:

Either these ones, currently used (also used in openui5):

 --sapNegativeTextColor: #bb0000;
 --sapPositiveTextColor: #107e3e;
 --sapCriticalTextColor: #e9730c;
 --sapInformativeTextColor: #053b70;
 --sapNeutralTextColor: #6a6d70;

or
  --sapNegativeColor: #bb0000;
  --sapCriticalColor: #e9730c;
  --sapPositiveColor: #107e3e;
  --sapInformativeColor: #0a6ed1;
  --sapNeutralColor: #6a6d70;

BR,
ilhan

**Comment by ilhan007** [comment]
Hello @m1trix 

It turns out that the current implementation and colors are by the spec. 

The parameter that should be used for the Informative infoText is:
--sapInformativeTextColor: #053b70; (dark blue)

It is a darker color (derived from the main information color listed on Fiori guidelines page) because a light blue color is too similar to a link and would cause a usability issue if the user cannot click it. The main (lighter blue) color is used for borders or indicator icons but the text must be a darker color.

BR,
ilhan
