### ISSUE TITLE
Feature request for a Wizard component

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2368]
**Is your feature request related to a problem? Please describe.**
I am from SAP Successfactors team, we have a new feature that needs to use Wizard.

**Describe the solution you'd like**
UX totally uses the design of UI5 Wizard sap.m.Wizard
https://sapui5.hana.ondemand.com/#/entity/sap.m.Wizard/sample/sap.m.sample.Wizard
https://experience.sap.com/fiori-design-web/wizard

Would you please implement a WC version Wizard?

**Comment by ilhan007** [comment]
Hello @GongRichard we will consider your feature request, in the meantime we would like to know if there is particular feature that is a must for your use case?

**Comment by GongRichard** [comment]
Hi @ilhan007 ,
Below are our designs, the particular is we use Wizard in a dialog.
<img width="881" alt="Wizard_Step1" src="https://user-images.githubusercontent.com/13098801/96542650-23a0b200-12d5-11eb-9e0e-bedce751555c.png">
<img width="885" alt="Wizard_Step2" src="https://user-images.githubusercontent.com/13098801/96542657-269ba280-12d5-11eb-84be-81d700aef515.png">
<img width="883" alt="Wizard_Step3" src="https://user-images.githubusercontent.com/13098801/96542660-28fdfc80-12d5-11eb-9ecd-23afe7c29538.png">

**Comment by ilhan007** [comment]
Hi @hristop  we will provide a user story for that soon

**Comment by GongRichard** [comment]
Hi @ilhan007,
BTW, would you please put this feature request as high priority as we will start development on Nov 4th？We will appreciate it if you can deliver this component before Nov 4th.

**Comment by ilhan007** [comment]
Hello @GongRichard well, it is  a short notice. I would suggest filing requests upfront, so that we can react properly.
We are starting Architecture/API discussions and then we will continue with the development. Based on the architecture we would better know what time would the development take. 
But, realistically I would expect to take longer than 2 weeks.

What would be the impact if that happen?

Implementation detail:
Would it be reasonable if we provide the upper part of the sap.m.Wizard, the steps:
<img width="776" alt="Screenshot 2020-10-21 at 1 32 25 PM" src="https://user-images.githubusercontent.com/15702139/96708436-ea824380-13a1-11eb-9f45-aea6828c4cc2.png">
You will be able to control what is the active step, the disabled ones, so on. 
And the rest - hiding/showing the content, scrolling the content, validation of steps, etc. to be taken over by the one that uses the Wizard component.


Best Regards,
ilhan

**Comment by GongRichard** [comment]
Hi @ilhan007 ,
And this feature is p1 priority feature for our B2105 release. Without this component, it will block our development.
What we expect is the same function sap.m.Wizard. From my perspective, if only provide upper part, it's not a complete wizard component.
