### ISSUE TITLE
Accessibility issue with the <TextArea>

### ISSUE THREAD

**Issue by JWandrocke** [SAP/ui5-webcomponents#2370]
JAWS is not reading typed in text if tabbing out and back into TextArea

1.) Create a TextArea component with a placeholder.
2.) Type in some text then tab out of the TextArea.  Tab back into the TextArea.  JAWS reads the placeholder text and not the typed in text.

Using "@ui5/webcomponents": "1.0.0-rc.8",

**Comment by ilhan007** [comment]
Hello @JWandrocke

could you just confirm that it reproduces with 1.0.0-rc.9 before we start processing the issue?
Also, do you use the latest JAWS version and latest Chrome?

Best,
ilhan

**Comment by ilhan007** [comment]
Test @SAP/ui5-webcomponents-topic-rl

**Comment by JWandrocke** [comment]
Hi ilhan
I will try upgrading, was hoping to you could tell me if it was fixed before doing this. 
The error was actually reported by our QA team see BCP: https://support.wdf.sap.corp/sap/support/message/2080377418.  I did verify with JAWS 2018 version and I have tried on Chrome, Firefox, IE11, Edge and Safari  (All the latest versions)

**Comment by JWandrocke** [comment]
@ilhan007 Just tried 1.0.0-rc.9 and the problem still occurs.  The version of JAWS (2018 1811.30 ILM) is up to date per our https://wiki.wdf.sap.corp/wiki/display/Acc/How+to+Install+and+Use+Freedom+Scientific+Jaws page
And Chrome is the latest also (86.0.4240.111).

**Comment by jyguyomarch** [comment]
@ilhan007 any progress here?

**Comment by hristop** [comment]
Hi @jyguyomarch 

We haven't started working on this one yet. 
Once we have some progress we will let you know.

Best Regards,
Hristo

**Comment by elenastoyanovaa** [comment]
Hi @jyguyomarch ,

Actually it is expected to not read out out the text inside a text area. This is also present for a native texarea. You can read more about this here https://github.com/FreedomScientific/VFO-standards-support/issues/42 .Since the content of a text area could be quite large it will be very confusing for the user of assistive technology to wait for the whole value of the text area to be read out. What is more you have additional keystrokes in JAWS for reading each line or even the whole content of the page if this is really the desired case. 

Please recheck that JAWS behaves the same with a native textarea also. If you still think that this is actually an issue, please reopen the issue, providing more information regarding the use case and the deviation of the accessibility standard.

Kind Regards,
Elena
