### ISSUE TITLE
ui5-date-picker: can't set aria-describedby attribute

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2380]
**Describe the bug**

**To reproduce**
1. set aria-describedby attribute of ui5-date-picker

**Actual Results**
Only set aria-describedby attribute to the root ui5-date-picker tag, won't set the attribute value to the inside input aria-describedby attribute

**Expected behavior**
Should also set the attribute value to the inside input aria-describedby attribute

**Screenshots**
<img width="1791" alt="2020-10-21_15-24-53" src="https://user-images.githubusercontent.com/13098801/96686856-abf48500-13b1-11eb-9685-b35b3e24dc5b.png">

**Context**
- UI5 Web Components version: 0.23.2
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-b

**Comment by ilhan007** [comment]
Hello @GongRichard 

we have already support for ariaLabelledby and I can see you use it in you example, ins't it possible to use aria-labelledby with couple of IDs, instead of adding aria-describedby. Can you explain the need for aria-describedby

Best,
ilhan

**Comment by GongRichard** [comment]
Hi @ilhan007 ,
This is the A11Y issue raised by the SF a11y testing team, they advise using aria-describedby.


Steps:

Login to instance
Navigate to More actions buttona and select Create Activity
Under Create Activity modal, with JAWS ON navigate to Achived On input field with date picker.
Actual Results:

Visual label is 'Achieved On:' is available and placeholder text is 'MMM,d,yyy'.  Screen reader is reading the placeholder text as "MMM D,YYYY" which is creating ambiguity to the user,the screen reader use is unable to identify the calendar date format (i.e. Alpha-numeric ) 

Expected Result:

The placeholder should descriptive to the screen reader user.

Provide extra information about the format type as offscreen text.Provide aria-describedby="please edit the month in alphabetic manner" as off screen text for the input field.

![_thumb_2654454](https://user-images.githubusercontent.com/13098801/97662803-f6ad8580-1ab2-11eb-907c-7fc3a0ddbb5b.png)

**Comment by ilhan007** [comment]
Hello @GongRichard 

we will support aria-describedby on the datepicker tag:

```html
<ui5-date-picker aria-describedby="someId">
</ui5-date-picker
```

But at the end, we will add the text of the element with id="someId" as  value of the "aria-label" attribute in the inner "input" element. We do the same when aria-labelledby is used. The reason is that that the element on focus, the inner input is deep in the Shadow Dom, while the referenced element is in the Light DOM, and the screen readers would not find it. That's why we extract the text and set it internally as aria-label. So ,no matter you use aria-labelledby or aria-describedby, the referenced element's text would be set as aria-label in the inner "input" element.

This is just for letting you know the details. We will support aria-describedby for the ui5-datepicker, ui5-input, but internally it will end up as aria-label inside the Shadow Dom. Perhaps you can communicate this to the accessibility experts on your side.

Best,
ilhan

**Comment by ilhan007** [comment]
Hello @GongRichard can you discuss with your ACC team the possibility to use aria-labelledby for now. 

We have internal discussions on how to handle referencing of elements between the Light and Shadow DOM. 
Because of the current implementation, there will be no difference in terms of reading or screen reader interpretation if you use aria-labelledby as at the end, as I explained in my previous reply, we set aria-label with the text of the referenced element in the shadow DOM.

**Comment by GongRichard** [comment]
Hi @ilhan007,

I will try to use aria-labelledby later, will give you feedback later.

Thanks,
Richard

**Comment by GongRichard** [comment]
Close this issue as we can use aria-labelledby.
