### ISSUE TITLE
ui5-button does not allow overriding CSS letter-spacing and word-spacing

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#2390]
**Describe the bug**
Some people use custom spacing in their browser to make the page more readable. This is done using global CSS styles. The ui5-button is not affected by these styles.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Button/
2. Using devtools, add the following CSS rule to the page:
```
* {
    line-height:1.5 !important;
    letter-spacing:0.12em !important;
    word-spacing:0.16em !Important;
}
```
3. Notice the custom spacing is applied to all text on the page besides the ui5-button inner text.

**Expected behavior**
According to the SAP accessibility wiki, all text should adapt to custom spacing. (https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-283+Details)

**Screenshots**
![Screen Shot 2020-10-22 at 11 40 53 AM](https://user-images.githubusercontent.com/24360164/96915738-7c9a5280-145b-11eb-916d-6aa27d42759e.png)

**Affected components**
ui5-button

**Organization:** 
SuccessFactors

**Priority:**
Low

Thank you for looking into this.

**Comment by fifoosid** [comment]
Hi @ee92 

After applying the following styles to the following [url](https://sap.github.io/ui5-webcomponents/master/playground/components/Button/)(this is the current master branch).
```
line-height:1.5 !important;
    letter-spacing:0.12em !important;
    word-spacing:0.16em !Important;
```

This is the result:

![image](https://user-images.githubusercontent.com/16850339/96972698-808fa880-151f-11eb-9a8b-766099e62d89.png)
You can see the styles in the upper right corner

The problem is that the deployment of the playground has failed for some time and what you are looking at is not the playground version for rc9

**Comment by fifoosid** [comment]
The playground is deployed successfully and the issue is resolved
