### ISSUE TITLE
DatePicker: Cannot Recognize day when 'DD' is in the format pattern

### ISSUE THREAD

**Issue by eleminsoda** [SAP/ui5-webcomponents#2428]
**Describe the bug**
The 'formatPattern' can not recognize the 'day' if 'DD' is in the format pattern.

**Isolated Example**
https://codesandbox.io/s/muddy-breeze-zdl0x

**To Reproduce**
1. The first or the third date picker, pick one date.
2. The result can be shown correctly.
3. The second or the late date picker, pick one date.
4. The 'day' field is missing in the result

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/27283476/97691986-199f6000-1ada-11eb-9118-a51aaa721c55.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.3
Operating System: MacOS
Browser: Chrome

**Additional context**

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b 

do you know if the following format patterns 'YYYY-MM-DD' and "M/DD/YYYY" are supported, 
because with lower case "dd" (MM/dd/YYYY and YYYY-MM-dd ) everything works fine, but with capital "DD" - it does not.

It does not seem to be invalid according to https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns

**Comment by tsanislavgatev** [comment]
Hello,

The following formats are not supported.
As shown here: https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns 
The capital 'D' letter stands for 'Day in year' so used like this, it's not supported.

We advice the usage of lower case letter 'd' for days in date formats.

Best Regards,
Tsanislav
