### ISSUE TITLE
Sidebar is not very responsive

### ISSUE THREAD

**Issue by hrstoyanov** [SAP/ui5-webcomponents#2443]
**Is your feature request related to a problem? Please describe.**
Sidebar is not very mobile friendly. Ideally, on mobile phone, I would like it to disappear to just the hamburger button dropdown in teh shellbar. Right now it can be expanded or collapsed, but still taking up valuable real estate on the screen.

Additionally, i do not see events being fired when the side bar transitions from collapsed to expanded?

**Describe the solution you'd like**
Take a loook at [this off-canvas component](https://getuikit.com/docs/offcanvas) 

**Describe alternatives you've considered**
Implement some code that hides the SideBaar and populates the the products drop-down in the ShellBar or vice cersa - hid eteh products drop downw and show the sidebar

**Comment by hrstoyanov** [comment]
Also, the start button in the shell bar seems misaligned with the sidebar entries
![Screen Shot 2020-11-05 at 17 59 35](https://user-images.githubusercontent.com/5327044/98317300-17814980-1f91-11eb-8c0c-b7852a553787.png)

**Comment by ilhan007** [comment]
Hello @hrstoyanov thank you for the questions.

About the events, the only way to collapse/expand the sidebar is via the SideNavigation API (as a guideline it is recommended to happen happen on "menu" button press as you did). You already know when the side navigation collapses/expands it is on the "hamburger" press, because it is imperative. It does not happen on scroll, on resize or upon other uncontrolled user interaction.

About the hiding, the expanded and collapsed states are defined by Fiori 3 Design team and implemented by design. If you need to hide the component entirely, you can set the "hidden" attribute and remove it, when it needs to be displayed.

About populating the ShellBar. The hamburger button and the top ShellBar are not connected internally in any way with the SideNavigation (sidebar). It is up to the application to decide what to show in the ShellBar and what to do upon the hamburger press.


Best,
ilhan

**Comment by hrstoyanov** [comment]
Thanks, @ilhan007 , when is the next release coming out? I see some improvements planned around side bar in it.

**Comment by ilhan007** [comment]
The next release, RC.10, is coming at the end of the next week.
