### ISSUE TITLE
Styling a component like Card, Panel,... individually

### ISSUE THREAD

**Issue by ansujohn** [SAP/ui5-webcomponents#2525]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is missing

**Description of the issue**
How can I style components individually? A Card or Panel component for example.

For example, I tried this but it's not working.
        
```
<ui5-card heading="David Willams" subheading="Sales Manager" className="medium"
                     style={{ "background-color": "black"}}/>
```

Could you please provide pointers to the right documentation or github examples?

**Comment by ansujohn** [comment]
Also where can I find all the choices for className property?

**Comment by ilhan007** [comment]
Hello @ansujohn 

The whole idea behind the web components in general is the encapsulation that the Shadow Dom provides from the outer DOM. For the elements that are slots, the ones you put as children of the components, you have the full control to style them as you wish. But, **we can’t just style the web components internals and this is by design**.

However, there are few available ways to set custom styles:
- **Styles on tag level**: we designed more simple components such as Title, Label, Badge and few more in such way, that it is possible to set styles/classes on the custom elements like “ui5-badge { background-color: red}” that will take effect.
 You can try this yourself here: https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Badge/

- **Shadow Parts** : For more complex components, the styling on tag level is not possible, therefore we introduced shadow parts on specific elements in the components’ Shadow DOM, that the user can restyle, using standard CSS syntax for shadow parts
For example: you can change the appearance of the Card’s heading, subheading status:
```css
  #myCard::part(status) {
    color: red;
  }
```
- **Custom Theming:** The UI5 WebComponents use CSS variables, to change the entire color scheme, the users can create their own theme. More details on how to do that, you can find here:
https://sap.github.io/ui5-webcomponents/playground/docs/customtheming/

Best,
ilhan
