### ISSUE TITLE
ui5-popover: wrong position after open

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#2556]
**Description**

**ui5-popover** is not correctly positioned when the **.openBy** method is called twice with different opener. 

**Steps to reproduce:**
1. Open the isolated example: https://codesandbox.io/s/ui5-webcomponents-forked-q62mk
2. Click the first button (could be clicked with mouse)
3. Press tab to focus the second button
4. Press space/tab to open the popover

![4](https://user-images.githubusercontent.com/31909318/101621951-1b383e00-3a1f-11eb-8e56-7b4655991034.gif)

**Note:The issue is reproduced only with if you trigger action through the keyboard.**

**Comment by NHristov-sap** [comment]
Hi,

The issue is reproducible, please see example mentioned above. When the Button 1 is clicked, popover opens correctly; then, when button 2 is clicked, popover also opens correctly. The issue is reproducible only when the focus is moved with keyboard interaction (Tab, Shift+Tab), and then the popover is opened with Space/Enter - then the popover is not moved to the currently focussed button, but stays at the same.

Best Regards,
Nikolay Hristov
Github Dispatcher

**Comment by NHristov-sap** [comment]
FYI @SAP/ui5-webcomponents-topic-rd
