### ISSUE TITLE
ui5-table: growing on scroll

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#2570]
**Is your feature request related to a problem? Please describe.**
Our case has lots of data items and can't load all at one time. But the ui5-table doesn't support scrolling loading more items.

**Describe the solution you'd like**
Our requirement is to make ui5-table the same as ui5-list to scroll to load more items. And has a busy indicator when loading more items.

**Additional context**
 Would you possibly deliver this feature before the end of December?

**Comment by vladitasev** [comment]
Implementation note: in OpenUI5 the table itself doesn't have a scrollbar, but requires to be put in a container with a scrollbar. Consider the pros and cons of such a solution against the table having its own scrollbar type of solution.

Additionally: consider IntersectionObserver with an alternative implementation for IE11.

**Comment by vladitasev** [comment]
Hi @GongRichard 

We discussed the feature request and we would like to ask you if the following solution would be ok with you.

1) The `ui5-table` component will have a property to show a "Load more" button at the bottom of the table. Whenever the user presses the button, a `loadMore` event will be triggered.

Obviously, this will work for all browsers since it's pretty trivial.

2) Additionally, for modern browsers, it will be possible to have a "growing" feature that triggers the `loadMore` event upon the user scrolling the page to the bottom of the table. For IE11 it will always default to the button.

Some technical details about the proposal to go in this direction: the `table` tag that we use internally to render the `ui5-table` does not support a scrollbar and the only way to make a table scrollable would be to wrap the table in a div and set the scrollbar to it, but then the whole table will be scrolled, along with the header. Furthermore, and more importanly, the Fiori design requires the scrollbar to be not on the table, but rather on the whole page (application).

For all of these reasons, we want to go for a modern approach to the problem and use the `IntersectionObserver` browser API that is very straightforward and performant and ideal for such requirements. It is supported by all browsers but IE11. Hence our suggestion to have the "continuous growing" feature only on modern browsers and for IE11 to default to the "load more" button. This behavior will be completely managed internally in `ui5-table` and you, as an app developers, would not need to branch your code in any way.

Example implementation:

- New property `has-more` indicating that the table has more data that is not yet shown to the user and the `loadMore` event will be fired upon the user clicking teh "load more" button:

```html
<ui5-table has-more>...</ui5-table>
```

Shows a "Load more" button on all browsers.

- New property `growing`, indicating that the table will fire **automatically** the aforementioned `loadMore` event upon the user scrolling the page to the bottom (or in other words, the bottom of the table is visible in the viewport of the app)

```html
<ui5-table has-more growing>...</ui5-table>
```

On modern browsers - the auto-grow feature will work (no button shown), on IE11 there will be the "Load more" button, basically the `growing` property will be ignored and `ui5-table` will fall back to the button.

Would that solution suit you?

Regards,
Vladi

**Comment by GongRichard** [comment]
Hi @vladitasev,

I discussed with our PM, she agrees with this solution. Please go ahead.

Thanks,
Richard
