### ISSUE TITLE
ui5-date-picker: expose Month picker view

### ISSUE THREAD

**Issue by sunnyyadav100** [SAP/ui5-webcomponents#2575]
**Is your feature request related to a problem? Please describe.**
As per the business scenario, only month and year need to be selected. Expose ui5-monthpicker as part of ui5-date-picker to select the only month.

**Additional context**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9139037/101986396-99147780-3cb3-11eb-8201-84127c162bf5.png">

**Comment by kineticjs** [comment]
Hi @sunnyyadav100 ,

Thank you for raising this feature request!

To sum up again, your request is to expose ui5-monthpicker (possibly as part of ui5-date-picker), which allows to select entire months (as in the image you provided), since in your business scenario the data granularity is entire months (and not specific dates within the month).

Please correct me if something is missing, before I put this request to the pipeline.

Thanks!

**Comment by sunnyyadav100** [comment]
Hi @kineticjs, yes that is correct.

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 
we are in a process of evaluating your request, in that matter, could you  give us more details about your business scenario, 
do you work on a application, if yes what is its purpose?

BR,
ilhan

**Comment by sunnyyadav100** [comment]
The business scenario is - 
The users collect monthly prices for materials from suppliers. In 360 view, users want to see view monthly prices for a chosen period. To select months, we need a month picker.

**Comment by ilhan007** [comment]
Hello @sunnyyadav100 you can track the progress in a newly created issue
https://github.com/SAP/ui5-webcomponents/issues/2993

We plan to support a new DatePicker display type based on format, f.e if the format includes only month and year,
just the month and year pickers will be displayed, ss in the "DatePickers types based on display format" example here:
https://openui5nightly.hana.ondemand.com/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker

**Comment by sunnyyadav100** [comment]
Thanks
