### ISSUE TITLE
ui5-label: Unable to align colons

### ISSUE THREAD

**Issue by jurajbak** [SAP/ui5-webcomponents#2625]
**Describe the bug**
In form with labels aligned to right, colon position is different for labels with and without _required_ attribute.
It's caused by `span.ui5-label-required-colon` and it's  `::after` CSS definition which adds content and increases width.

**To reproduce**
1. Create two labels with right align.

**Isolated example**
```
<ui5-label required show-colon style="width: 300px; border: 1px solid black; text-align: right;">Required field</ui5-label><br>
<ui5-label show-colon style="width: 300px; border: 1px solid black; text-align: right;">Optional field</ui5-label>
```

**Expected behavior**
It should be possible to align right with colons in one vertical line.

**Screenshots**
![obrázok](https://user-images.githubusercontent.com/10481182/103456935-29663b00-4cfb-11eb-94ac-23aa0ada4c44.png)

**Context**
- UI5 Web Components version: 1.0.0-rc.11

**Affected components** *(if known)*
ui5-label

**Depends on**
#2624

**Comment by a-z-ivanov** [comment]
The wrapping element with class ui5-label-root has width of 100% only when the wrap property is set on the control. Without it, the control does not respect the provided width of 300px.
See here packages/main/src/themes/Label.css

**Comment by a-z-ivanov** [comment]
Hello @ui5-webcomponents-topic-rd, this is for you.

**Comment by a-z-ivanov** [comment]
Sorry, my comments are regarding the related issue https://github.com/SAP/ui5-webcomponents/issues/2624

**Comment by a-z-ivanov** [comment]
I think, this alignment is by design, right? @ui5-webcomponents-topic-rd, please, have a look.

**Comment by jurajbak** [comment]
Hello,

I didn't find ui5-webcomponents-topic-rd. It's not a part of ui5-webcomponents or is it?

**Comment by ilhan007** [comment]
> Hello,
> 
> I didn't find ui5-webcomponents-topic-rd. It's not a part of ui5-webcomponents or is it?
It is a github group, part of SAP github organization, I edited the mention above

**Comment by jurajbak** [comment]
@SAP/ui5-webcomponents-topic-rd looks private and I don't have access.

I don't think this alignment is intentional. It just need to set fixed space for asterix and keep this space regardles asterix is visible or not.

**Comment by alexandar-mitsev** [comment]
Hello @jurajbak ,

You can add a padding of 10px in right to align the labels. Here is a sample with the added padding: https://codesandbox.io/s/ui5-webcomponents-forked-vv8gz?file=/index.html

Since ui5-webcomponents does not provide a specific layout for a form and since the layout is built by you, the alignment also relies on your coding. Additionally since you can use any css styling required for this, there is no direct need for the ui5-label to have a property about it (or to always have padding).

Best Regards,
Alexandar Mitsev

**Comment by jurajbak** [comment]
Yes, it is possible to set styles according to label attributes from outside. This is currently my workaround.

I think this is bug and fix should be done inside of component, in it's shadow CSS.

**Comment by alexandar-mitsev** [comment]
Hello @jurajbak ,

For us, since the layout is done by you, it makes sense that this alignment is done also by you. Because it depends on the layout.
Since ui5-webcomponents are open for such styling - this is not a workaround but is the regular way to achieve the alignment.

Best Regards,
Alexandar Mitsev
