### ISSUE TITLE
SuccessFactors: ui5-tree-item Inactive type

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2634]
**Is your feature request related to a problem? Please describe.**
While the `ui5-list-item` supports types like `Inactive` to allow a list item to be disabled, `ui5-tree-item` does not.

**Describe the solution you'd like**
Please add support for types for `ui5-tree-item`.

**Describe alternatives you've considered**
Adding the "disabled" attribute does not do anything.

**Comment by ilhan007** [comment]
Hello @agauyeung, just one clarification

The ui5-li can be Active/Inactive.

The "Inactive" list item
- has standard opacity (it is not reduced)
- can be focused
- **does not** have the active/pressed state
- **does not**  have the hover state.

The "Active" list item
- has standard opacity (it is not reduced)
- can be focused
-  **has** the active/pressed state
-  **has** have the hover state.


Is that what you also expect for the tree item - to have both Active and Inactive states with the visual characteristics described above?

**Comment by agauyeung** [comment]
Hi @ilhan007, when `ui5-list` is in `MultiSelect` mode, the checkbox for an `Inactive` list item is disabled. Please also implement this behavior for `ui5-tree-item`.
![image](https://user-images.githubusercontent.com/8508119/104220182-f6573200-53f3-11eb-829d-28b94ff74d3d.png)

**Comment by ilhan007** [comment]
Hello @agauyeung 

I just checked the ui5-li web component. Indeed, the checkbox becomes blurred and the item can't be selected. And, I found that we implemented this behaviour for another SFSF request: https://github.com/SAP/ui5-webcomponents/issues/1171

But, in openui5 equivalent control (List with sap.m.StandardListItem) it is not like that. The item can be selected in both Inactive and Active states and the checkbox is not disabled.
You can check the openui5 control behaviour [here](https://openui5nightly.hana.ondemand.com/entity/sap.m.List/sample/sap.m.sample.ListSelection).

So, it turns out that the ui5-li component with type="Inactive" is not behaving as expected. Therefore we would avoid doing the same for TreeItem, but rather we should find another solution.

The most obvious one  is to introduce a new "disabled" property (for both ui5-li and ui5-tree-item) that makes them none-interactive. The thing is that such state is not specified and we will need to create a request to the Visual Design team to implement such Visual Design spec?

Usually new specs take time, how urgent is the requirement?

**Comment by nnaydenow** [comment]
Hi @agauyeung ,

We will process the issue in following GitHub issue: #2560 . Please follow its status there. 

Regards,
Nayden
