### ISSUE TITLE
Step Input

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents#2640]
**Is your feature request related to a problem? Please describe.**
We need a number incrementer/decrementer.

**Describe the solution you'd like**
Please implement Step Input as detailed in the [Fiori Documentation](https://sap.github.io/ui5-webcomponents/playground/components/Input/).

**Describe alternatives you've considered**
[`Input`](https://sap.github.io/ui5-webcomponents/playground/components/Input/) with `type` as `Number`. However, UX has told us that Step Input is easier to use on mobile screens.

**Additional context**
![image](https://user-images.githubusercontent.com/8508119/103937060-17aadc00-50dd-11eb-8e81-85ec01695c9c.png)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b please consider this request with a highest priority after #2528

This is the API we would like to support:

**Properties** 
- disabled
- readonly
- value,
- placeholder
- min
- max
- step (with the default stepMode for openui5)
- valueState

**Slots**
- valueStateMessage(slot for custom message - see Input for reference)

**Events**: 
- change (due to focus out or increment/decrement buttons are used)

**Comment by agauyeung** [comment]
Hi @NHristov-sap any updates on this?

**Comment by agauyeung** [comment]
hi @NHristov-sap what is the timeline for releasing this?

**Comment by ilhan007** [comment]
Hi @agauyeung 

The timeline is RC.13, but it would be merged in few days.

<img width="303" alt="Screenshot 2021-02-17 at 8 34 27 AM" src="https://user-images.githubusercontent.com/15702139/108165273-f5a07280-70fa-11eb-87ce-bd734bf7a4fe.png">

<img width="341" alt="Screenshot 2021-02-17 at 8 33 55 AM" src="https://user-images.githubusercontent.com/15702139/108165228-e1f50c00-70fa-11eb-8e16-366cae98a703.png">
