### ISSUE TITLE
Potential security risk in <ui5-link/> component

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#27]
**Describe the bug**
when generating an external link, the [ui5-link](https://github.com/SAP/ui5-webcomponents/blob/99f429ae74ee45cee9553028ad1d553ee2a4f166/packages/main/src/Link.js) component misses "noopener"/"noreferrer" relation attributes between linked documents. More info: https://developers.google.com/web/tools/lighthouse/audits/noopener

**Expected behavior**
automatically added `rel="noopener noreferrer"` to all cross-origin links. *Important:* Only to cross-origin links, otherwise inner-site statistic might be broken.

**Comment by a-z-ivanov** [comment]
There is a problem with cross-origin scripts, that have agreed to set their sites' domains to the same "superdomain", to pass cross-origin checks. We cannot really detect those. The undesired effect would be that we prevent their communication through window.opener API. That's why why decided to make the rel attribute an API of ui5-link.
