### ISSUE TITLE
Datepicker for primary-calendar-type is not displaying (video attached)

### ISSUE THREAD

**Issue by yogananda-muthaiah** [SAP/ui5-webcomponents#2792]
**Describe the documentation issue**

- [ X] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
A clear and concise description.
https://www.loom.com/share/922251dc29994df3a60dea67805164f8

**Comment by unazko** [comment]
Hello @yogananda-muthaiah,

Thank you for contacting us with this issue.
Are there any errors in the developer console, when you are trying to open the ui5-date-picker component popover?

Also could you please point out, which is the used ui5-webcomponents version.

I've made some tests within the following code snippet:
https://codesandbox.io/s/charming-engelbart-0dxrw

In order to use other types of calendars they should be loaded first
and when I switched between different ui5-webcomponents versions I had to clear the browser cache.

Best Regards,
Boyan

**Comment by yogananda-muthaiah** [comment]
@unazko @ilhan007 

Below lib is missing in the documentation for date picker...  please take care of the documentation

````
import "@ui5/webcomponents-localization/dist/features/calendar/Buddhist.js";
import "@ui5/webcomponents-localization/dist/features/calendar/Islamic.js";
import "@ui5/webcomponents-localization/dist/features/calendar/Japanese.js";
import "@ui5/webcomponents-localization/dist/features/calendar/Persian.js";
````

**Comment by ilhan007** [comment]
Hi @yogananda-muthaiah sure thanks for letting us know.

**Comment by yogananda-muthaiah** [comment]
Thanks, @ilhan007 
I have noticed a lot many are missing inside documentation like above..
