### ISSUE TITLE
ui5-li default font size is non standard.

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#2811]
**Describe the bug**
Default font size for the text in ui5-li is: --_ui5_list_item_title_size which is 16px.
Most for the other ui5 web components e.g. ui5-label, ui5-link etc has font-size: --sapFontSize
ui5-li text looks a little bigger next to these elements on the same page.
It should be changed to --sapFontSize or provide an option to set it as this is defined inside the shadowRoot. See screenshot.

**Screenshots**

<img width="1902" alt="listFontSize" src="https://user-images.githubusercontent.com/65705637/107711496-9c5cbd00-6c7c-11eb-86f9-7ac378b78dd8.png">

Version: @ui5/webcomponents 0.29.1

**Priority:** *(optional)* *(Low, Medium, High or Very High)*
Medium

**Comment by ilhan007** [comment]
The title size is implemented by design - by Fiori 3:
- In cozy content density , the font size of list item title should be 1rem.
- In compact content density , the font size of list item title should be 0.875rem (--sapFontSize).

You can use the global class "ui5-content-density-compact" to force compact content density on any level - page, section or single component. In this case you can set the class to the List component. But in this way the checkboxes would be a bit smaller and the items height a bit smaller as well. Is this fine or you need to only change the size of the title font and keep the rest of the item spacing and checkbox size the same?

```html
<ui5-list class="ui5-content-density-compact"
```

Also, there is existing part attribute (part="title") on the DOM element, displaying the list item title.

This will work in all browsers, besides ie11
```css
ui5-list::part(title) {
 font-size: 0.875rem;
}
```

Also, you can try to overwrite the `_ui5_list_item_title_size` css variable.

BR,
ilhan

**Comment by ilhan007** [comment]
Hi @gurkirpalgill any update or feedback about my previous comment.

**Comment by gurkirpalgill** [comment]
`<ui5-list class="ui5-content-density-compact" ..>` works fine but we want to keep the checkbox size same for consistency. 

`ui5-list::part(title) {
 font-size: 0.875rem;
}`
is exactly what we need but its' not working in IE11. can we add something for IE11 only?

we want to avoid overwriting `_ui5_list_item_title_size`

**Comment by ilhan007** [comment]
Hi @gurkirpalgill, I see.

for IE, as there is not ShadowDom, you can try adding styles for the title DOM element. It has the following class "ui5-li-title", so I would try:

```css
ui5-li .ui5-li-title {
   font-size: 0.875rem;
}
```

*This will not apply in the rest of the browsers, but there you have the ::part solution

**Comment by gurkirpalgill** [comment]
`ui5-li .ui5-li-title {
 font-size: 0.875rem;
}`
doesn't seem to be working in IE11. I tried both in App.css and .module.css files
<img width="1649" alt="Screen Shot 2021-02-18 at 1 24 33 PM" src="https://user-images.githubusercontent.com/65705637/108423821-34aef080-71ed-11eb-8a36-e82c131eedfd.png">

**Comment by gurkirpalgill** [comment]
this definition overrides my **font-size: 0.875rem**:
`ui5-li .ui5-li-title {
    color: #32363a;
    font-size: 1rem;
}`
how do i disable this?

**Comment by ilhan007** [comment]
The reason is that the selector you add and the one in the shadow DOM are exactly the same with the same weight, but the one in the ShadowDOM will be applied later and overwrite yours. So, you have to make your selector stronger

1. With !important
```html
<style>
	ui5-li .ui5-li-title { color: red !important; font-size: 4rem !important }
</style>
```

2. With more specific selector

```html
	<style>
			ui5-li span.ui5-li-title { color: red; font-size: 4rem; }
	</style>
```

<img width="1311" alt="Screenshot 2021-02-19 at 10 19 08 AM" src="https://user-images.githubusercontent.com/15702139/108477519-fcb2b680-729b-11eb-969a-0be578017ddb.png">

**Comment by gurkirpalgill** [comment]
Proposed solution works. Thanks.
