### ISSUE TITLE
Duration Picker numbers don't snap at the right place on mobil 

### ISSUE THREAD

**Issue by Fabioni** [SAP/ui5-webcomponents#2819]
The Duration Picker has a lot major issues on mobil phone. It's not really useable cauze the tiles jitter strangely while scrolling and don't snap in the right places. See the following screenshot.

![Screenshot_20210216-030242_Chrome](https://user-images.githubusercontent.com/45362676/108009854-d83cad00-7003-11eb-80b7-7bbf0ae83691.jpg)

**Comment by ilhan007** [comment]
Hi @SAP/ui5-webcomponents-topic-b the issue is reproducible with the Chrome Device Emulator. The DurationPicker (and possibly the TimePickerl) doesn't snap  to the correct square while scrolling  - it doesn't happen 100/100 cases but if you scroll couple of times, you will get the state the author is showing above.
