### ISSUE TITLE
 UI5 Web Components Enablement in OpenUI5: support all UI5 concepts that apply to UI5 Controls  

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2925]
As part of the Retrofit topic, we aim to reuse the UI5 Web Components inside the UI5 Controls. In order to do this, we have to check all UI5 concepts that apply to UI5 Controls to ensure the ones that will start to use internally UI5 Web Components would be able to support those concepts.

For example:
- Badge concept
- Enabled/Disabled in container
- Busy Indicators etc.
- Form labelling

**Comment by vladitasev** [comment]
A couple of things to test and consider:
 - Using retrofit controls instead of their counterparts in typical sap.m apps: f.e. ui5-button in a toolbar, ui5-input in a form. Check what happens? Do they have to implement sap.m interfaces? Do they look bad since they don't get overstyled?
 - Check for OpenUi5 concepts such as LabelEnablement and similar, which traverse controls and change their state. Do they work with retrofit controls?
 - Check how retrofit controls work in forms in OpenUI5 - do they have the necessary APIs to work there?

**Comment by ilhan007** [comment]
**Enabled/Disabled propagation**
The EnablePropagator (even used) don't work as with standard UI5 Controls. 

Example: Disabled Toolbar (enabled: false) with **sap.ui.webcomponents.Button** instances.
In this case, **the buttons remains enabled**, because of the aforementioned reason.
In case of **sap.m.Button** instances - **they automatically become disabled** because their parent container, the Toolbar, is disabled.

**Comment by fifoosid** [comment]
Findings about **Check how many controls get as public aggregations things such as sap.m.Button and similar building blocks. Would they be able to accept also retrofit buttons? Can we change them easily?**:

- Controls & components are interchangeable as slots tot both Contrls/Components wrappers aggregations.
- There are some size & positioning issues (I would assume that it is expected that ```sap.m.Button``` and ```ui5-button``` would will have consistent behaviour, which is not the case right now). For example, we have ```sap.m.Button```, ```ui5-button```, ```sap.m.Input``` and ```ui5-input``` all nested as aggregation in ```ui5-panel```. This is the result:

![image](https://user-images.githubusercontent.com/16850339/115533340-52f1a500-a29f-11eb-9b20-f2565fb7600e.png)


- For the icon, there is a deviation in the default colour in addition to the size & positioning differences:

![image](https://user-images.githubusercontent.com/16850339/115533597-8cc2ab80-a29f-11eb-829a-0ddb516e453e.png)
