### ISSUE TITLE
a11y + visuals: ui5-tree-item highlights background-color and border-bottom when pressing Space or Return

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#2974]
**Describe the bug**
Pressing Space or Return on keyboard selects Tree Item on level 1 highlights background color or adds border-bottom width or color.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Tree/
2. Scroll down to **Tree with multiple selection**
3. Use keyboard to navigate through Tree items
4. Press Space or Return on Tree Item's first level
5. Background color and bottom border changes color

**Expected behavior**
Pressing Space or Return on keyboard selects Tree Item on level 1 and should not highlight background color or add border-bottom width or color.

**Screenshots**
![Screen Shot 2021-03-19 at 12 34 41](https://user-images.githubusercontent.com/11576789/111833581-9c6d5f80-88af-11eb-9d19-7a19561f1b08.png)

**Organization:** *SAP SuccessFactors*

**Priority:** *Medium*

Setting priority would indicate the importance of the issue
and would help the process of dispatching and processing.

To set the appropriate priority, you need to consider the impact
and if the issue:
- Breaks entire application or system - Low
- Is accessibility one (Screan Reader, Keyboard Handling) - High
- Is functional one and makes a single component unusable - Low
- Is visual, styling one - Medium

Note: the priority would be re-evaluated by the issue processors, according to the project internal criterias

**Business impact:** *Medium*

**Comment by ilhan007** [comment]
The background-color and the border are exactly what should happen when you select a tree item. See the openui5 Tree control for reference https://openui5nightly.hana.ondemand.com/entity/sap.m.Tree/sample/sap.m.sample.TreeSelection

Actually, the issue is that this does not happen to the nested levels, but only for the 1st level:

So this how the item when selected should look like, and we will do that for the nested levels as well.
<img width="304" alt="Screenshot 2021-03-22 at 09 18 50" src="https://user-images.githubusercontent.com/15702139/111953677-a087c000-8aef-11eb-8c03-91da28db7ccd.png">
