### ISSUE TITLE
ui5-input with suggestions closes parent dialog on escape

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#3028]
**Describe the bug**
If a ui5-input using the suggestions dropdown is inside a dialog and the escape key is pressed when the dropdown is open with an item selected, the dialog gets closed along with the dropdown.

**To reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-g96uv 
2. Follow the instructions at the top in the sandbox

**Expected behavior**
When the escape key is pressed, the suggestion dropdown should close without closing the parent dialog.

**Context**
- UI5 Web Components version 0.29.9

**Affected components**
ui5-input

**Organization:**
SuccessFactors

**Priority:** *(optional)*
Medium

Thanks :)

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

I am forwarding this issue to you as it is in relation with the Input component.
The issue is reproducible with the described by the author steps.

Start typing in the input field and when suggestion popover is opened press arrow down keyboard key.
After that when pressing escape keyboard key both the popover and the dialog gets closed.

Best Regards,
Boyan

**Comment by ilhan007** [comment]
Hello @ee92   we released a fix with 0.29.13, the parent Dialog is no longer closed when you use ESC over Input Suggestions
