### ISSUE TITLE
ui5-input with suggestions accessibility issues

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#3051]
**Describe the bug**
There are several issues that our Accessibility QAs at SuccessFactors have brought up regarding the ui5-input suggestion dropdown.

1) "Suggestions available" is fine but "no results" is announced even before any search term is entered which is a misleading announcement
2) Each result/option is announced twice when selected. Like this:
"Foo"
"List item 1 of 10 Foo Is Selected"

**To reproduce**
1. Use a screen reader like JAWS or NVDA
2. Go to https://sap.github.io/ui5-webcomponents/playground/components/Input/
3. Type into the "Input With Suggestions"
4. Notice the screen reader has an output like this:
![image](https://user-images.githubusercontent.com/24360164/113021720-b6713280-9138-11eb-8f65-ef95ba7d8a49.png)

**Expected behavior**
- "No results" should not be read out unless there is no results for the search input
- The item should only be ready once (the first "Argentina" is unnecessary)

**Context**
- UI5 Web Components version 0.29.9

**Affected components** 
ui5-input

**Organization:** 
SuccessFactors

**Priority:**
Medium

Thank you

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The described announcements could be easily reproduced via the provided by the author steps.
Used tools - JAWS 2019 and chrome browser on windows machine.

The same redundant announcements aren't present in openUI5 project for comparison.

On my windows machine there were announcement in addition to what the author describes:
- "a"
- "Suggestions available 6 results are available"
- "6 results are available"

Could you take over.

Best Regards,
Boyan

**Comment by niyap** [comment]
Hello @ee92,

Thanks for sharing your findings!
For the first reported issue "'No results' should not be read out unless there is no results for the search input" we have prepared a fix.
For the second one, the speech output is expected, since firstly the input value is read out "Argentina", then the list item. 
If just the input value is read out, then you will not be able to hear additional information for that list item, such as the item's description.

Kind Regards,
Niya

**Comment by ilhan007** [comment]
Hello @ee92 
the fix will be included in the next 0.29.15 patch, you can expect it in a week 16-19 April

**Comment by ee92** [comment]
@ilhan007 the fix does not seem to be included in 0.29.15 or even 0.31.6 

We will not patch the fix, so its okay to include it in the next 0.31.x release and skip patching it to 0.29.x

Thanks

**Comment by ee92** [comment]
@ilhan007 issue 1 ("no results" announcement) seems to be fixed but issue 2 (options read twice) is still present.

Is there any plan to fix it? Please let me know, thanks!

**Comment by ilhan007** [comment]
Hello @ee92 

I think this is what @niyap explained above:

"For the second one, the speech output is expected, since firstly the input value is read out "Argentina", then the list item.
If just the input value is read out, then you will not be able to hear additional information for that list item, such as the item's description."
