### ISSUE TITLE
Calendar: The position of weekday title is wrong

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents#3059]
It can be re-produced in the storybook. When you set the primaryCalendarType to Japanese, the week numbers disappear but the column titles don't change.

![image](https://user-images.githubusercontent.com/4338219/113084978-9a8d8f80-9211-11eb-8781-b79050915264.png)

**Comment by unazko** [comment]
Hello @SunnyWind,

I couldn't recognize the issue in the provided screen shot.
Is the expected behavior to translate the day names from English to Japanese,
when the primary calendar type is set to "Japanese"?

As the "primary-calendar-type" attribute affects dates representation in the UI, but it doesn't translate the texts.
In order for the texts to be translated the "sap-ui-language" query parameter has to be set.

Best Regards,
Boyan

**Comment by Lukas742** [comment]
Hello @unazko 

@SunnyWind please correct me if I am wrong, but the problem here should be the first column that should represent the calendar weeks (week numbers). The documentation says that for calendars other than Gregorian the week numbers are not displayed, but as you can see in the screenshots the column is not displayed with the week numbers (or not at all), but with one day of the month.

Gregorian Calendar with calendar weeks:
![image](https://user-images.githubusercontent.com/9749730/113137011-4b9d2580-9224-11eb-9cd9-b660641ac2af.png)

Japanese Calendar with faulty calendar weeks column:
![image](https://user-images.githubusercontent.com/9749730/113137144-6cfe1180-9224-11eb-9f69-85e7f4b8b4d6.png)
Here a week basically has 8 days.

Both screenshots were taken from the [playground](https://sap.github.io/ui5-webcomponents/playground/components/Calendar/)

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Calendar day names are miss-aligned, when "primary-calendar-type" attribute is set to "Japanese" as in the playground sample.
The issue is clearly visible from the @Lukas742's message. As week numbers aren't visible, the week number element in
the Calendar component header section shouldn't be rendered.

Could you please forward with a solution.

Best Regards,
Boyan
