### ISSUE TITLE
Token: onClick on default CloseIcon

### ISSUE THREAD

**Issue by ArneBuetergerds** [SAP/ui5-webcomponents#3062]
I want to use the token component and its default CloseIcon. I need to know when this icon is clicked, but there is no property for it.

I like to set a onCloseIconClick prop as a function.
Or is there another way to get notified?

If this is not possible, you have always to set the closeIcon on your own.

![chrome_2Hf7U0VFUl](https://user-images.githubusercontent.com/40249316/113108297-21883b00-9205-11eb-8569-3de31ab8a16f.png)

**Comment by fifoosid** [comment]
Hi @ArneBuetergerds 

I have prepared this [sample](https://codesandbox.io/s/ui5-webcomponents-forked-1k84y?file=/index.html) in order to show you how you can use the token and its ```delete``` event.(BTW I noticed that it doesn't always load properly from the first time. If so, just refresh the inner page and it should work fine)

Usually tokens are used inside ```ui5-tokenizer``` but if you want to use them standalone, it is possible
