### ISSUE TITLE
A11Y: Placeholder in UI5 TextArea

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3110]
Hi colleagues,

This issue is not fixed, at lease, isn't contained in released version. 
Please go to below link to see details:
https://github.com/SAP/ui5-webcomponents/issues/2641

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 

In #2641, the original issue, the "Organisation" field has not been set to "SF" and that's why the change has not been transferred to 0.29 branch. We will merge the change in the 0.29 branch and make it available until the end of the week.

If you look at the test page:
https://sap.github.io/ui5-webcomponents/master/playground/main/pages/TextArea/


and apply 

```css
    line-height: 1.5 !important;
    letter-spacing: 0.12em !important;
    word-spacing: 0.16em !important;
```

you will get:

<img width="475" alt="Screenshot 2021-04-06 at 19 30 34" src="https://user-images.githubusercontent.com/15702139/113746054-9203f000-970e-11eb-996b-dd4ebeea92ec.png">
