### ISSUE TITLE
Support for "sap-theme" URL parameter

### ISSUE THREAD

**Issue by tjbutz** [SAP/ui5-webcomponents#3114]
**Is your feature request related to a problem? Please describe.**

Currently UI5 Web Components only support the URL parameter for theming:

"sap-ui-theme"

UI5 also [supports another URL parameter for theming](https://openui5.hana.ondemand.com/topic/e9fc648661d84ed89360bbec3ae02611), as many products use this URL parameter as default:

"sap-theme"

**Describe the solution you'd like**

Please add the "sap-theme" URL parameter as a possible option for theming to UI5 WC.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-team I am forwarding the issue to you.

**Comment by ilhan007** [comment]
Hello @tjbutz  thanks for the issue.

Do you have a particular app that is using UI5 and UI5 Web Components, where the theme does not apply to the UI5 Web Components, because it is set by the "?sap-theme" param? 

If your app uses both UI5 and UI5 Web Components, UI5 Web Components can benefit
from OpenUI5 configuration via the following module:

```js
import "@ui5/webcomponents-base/dist/features/OpenUI5Support.js";
```

When the app imports the above module, OpenUI5 configuration takes precedence over UI5 Web Components configuration for all common entities (theme, language, etc...). In addition, changing the theme.
So if the theme is set with "?sap-theme" param I expect that would be still applied to the UI5 Web Components, because of the aforementioned integration.

BR,
ilhan

**Comment by tjbutz** [comment]
Hi @ilhan007. Thanks for your fast answer. As far as I know the cFLP appends "sap-theme" to the URLs of the applications. The App is not build with UI5 (build with Angular / UI5 WC for React), so the provided solution is unfortunately no option for us.

**Comment by ilhan007** [comment]
Hello @tjbutz we prepared a fix: https://github.com/SAP/ui5-webcomponents/pull/3138

Nevertheless, is it possible to somehow see the issue, can we see the app in the cFLP?

BR,
ilhan
