### ISSUE TITLE
FileUploader: Component inline ‘Button’, The ’Button‘ border disappears when the mouse is hovering over it

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents#3119]
**Describe the bug**
As title.

**Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-react-template-29l34

```
import React from "react";
import { FileUploader, Button } from "@ui5/webcomponents-react";

export default function App() {
  return (
    <div>
      <FileUploader hideInput={true}>
        <Button className={""} design="Transparent">
          No2.No_Border
        </Button>
      </FileUploader>

      <Button design="Transparent">No2.Normal_Border</Button>

      <FileUploader hideInput={true}>
        <Button className={""} design="Emphasized">
          No3.Error_Color
        </Button>
      </FileUploader>
    </div>
  );
}

```

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

I am forwarding this issue to you as it is in relation with the FileUploader component and it`s inline button in particular. 
The button`s border disappears on hover (with design="Transparent") and also it has lighter background and unreadable text (with design="Emphasized").

The issue is reproducible here: https://codesandbox.io/s/ui5-webcomponents-forked-j9t27?file=/index.html

Best Regards,
Yana
