### ISSUE TITLE
ui5-date-picker: Focus is missing for next and previous button

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3122]
**Describe the bug**

**To reproduce**
Open page https://sap.github.io/ui5-webcomponents/playground/components/DatePicker/
Tab to date-picker input to open ui5-date-picker.
Try to navigate to the next and previous button. 

Actually Result:
The focus is missing for the next and previous button.

**Expected behavior**
The Visual focus should come to the next and previous button.
The focus should come to all the interactive elements.

**Context**
- UI5 Web Components version: 0.29 .13
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

Organization:
SF

Priority: (optional) (Low, Medium, High or Very High)
Medium

**Comment by ilhan007** [comment]
Hello @GongRichard as far as I know, this is by design. You can see the sap.m.DatePicker is working the same way.
https://openui5nightly.hana.ondemand.com/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker

@SAP/ui5-webcomponents-topic-b @ghristanov  I think the  DatePicker's PREV/NEXT button should not be focusable and should not be part of the tab chain by design. Could you confirm that?

**Comment by ghristanov** [comment]
Hello @GongRichard,

@ilhan007 is right, such tab chain is suggested by our Fiori keyboard interaction and this is the reason why both ui5-webcomponents and OpenUI5 are behaving the same. What I've been told by designers before is that those arrows are the mouse user's alternative to the arrow keys, which can be used to navigate between months via keyboard.

Best regards,
Georgi
