### ISSUE TITLE
SuccessFactors : RTL issue for icon in UploadCollection component

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#3167]
**Describe the bug**
When the language is RTL the empty data icon (document icon) is wrongly flipped diagonally. The icon should remain unchanged from the non-RTL mode.

**To reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/
2. Change operation system language to RTL language
3. Check the document icon

**Expected behavior**
The icon should remain unchanged from the non-RTL mode.

**Screenshots**
![image001](https://user-images.githubusercontent.com/10460331/115318378-7c40f280-a132-11eb-88d3-85c9d1ecc9b7.png)

**Context**
- UI5 Web Components version 1.29.13
- OS/Platform: MacOS
- Browser *(if relevant)*: Chrome

**Affected components** 
https://sap.github.io/ui5-webcomponents/playground/components/UploadCollection/

**Organization:** 
SuccessFactors

**Comment by alexandar-mitsev** [comment]
Hello @mydavidzhang ,

For me if I choose rtl language Hebrew I see that the icon has correctly switched direction. See this screenshot 
![image](https://user-images.githubusercontent.com/2347042/115415377-8846b600-a1ff-11eb-9ac5-2228e4c2ebbf.png)

Can you specify more details how to reproduce:
1. which language you use
2. do you reproduce it on the upload collection demo page (can't locate the exact screenshot which you share) or in your application
3. very likely this was fixed in v1.0.0-rc.7 which is the current version in the demo page

Regards,
Alexandar Mitsev

**Comment by mydavidzhang** [comment]
Hi @Alex,

We double checked 0.29.13 version the issue has been fixed which is same with v1.0.0-rc.7.

![Screen Shot 2021-04-20 at 9 34 20 AM](https://user-images.githubusercontent.com/10460331/115433117-084b2c80-a1bc-11eb-8e0b-aae2e204b4a6.png)
