### ISSUE TITLE
ui5-busyindicator delay and a11y announcement 

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#3186]
**Is your feature request related to a problem? Please describe.**
- According to our accessibility specialist: "whenever the loading spinner shows up, the text equivalent of it must be announced by screen readers" and "the spinner as such need not receive focus as its not going to be interactive".
So our requirement is to have the busy indicator be announced even if it not in focus. The ui5-busyindicator currently does not support this.

- By the Fiori guidelines, the busy indicator should not be used if the operation takes less than 1 second. (https://experience.sap.com/fiori-design-web/busy-indicator/#do-not-use-the-busy-indicator-if)
The ui5-busyindicator currently gets displayed immediately, and to implement a delay of 1 second, the user has to handle the timeout code which is unfortunate especially if the ui5-busyindicator is used in multiple places.

**Describe the solution you'd like**
It would be good if the ui5-busyindicator supported a screen reader announcement and a 1 second delay. We currently are considering to have a wrapper around the ui5-busyindicator to allow this functionality, but we would like to see it supported on the webcomponent level.

**Describe alternatives you've considered**
We can use a wrapper for the ui5-busyindicator, but we want to request the feature at the webcomponent level before going that approach.

**Comment by tsanislavgatev** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

Can you please check if this is by specification? And consult if it's working correct?

Regards,
Tsanislav Gatev

**Comment by alexandar-mitsev** [comment]
Hello @ee92 , 

1. About the busy indicator announcement:
a. it does not make sense to announce each and every busy indicator on the page. If the keyboard only user is focused in one region, he is not interested in the fact that a second region outside of his focus is currently busy, so there should be no announcement in that case
b. if the focus is inside a region which becomes busy, it makes sense to announce this to the user

2. About if the busy indicator should be focusable:
our best practice shows that it should be focusable so that the keyboard user can understand that the region he tries to access is currently busy. The fact that it is not interactive does not prevent it to be focusable

3. About the delay: we will plan to implement it

So what do you and your accessibility specialist think about point 1. and 2. If you agree with does and if it covers your use case we can look into providing a solution for 1.b.

Thanks and Regards,
Alexandar Mitsev

**Comment by gmkv** [comment]
Hi @ee92 
We have added the delay property to the (now renamed) ui5-busy-indicator with PR #3419 .

**Comment by gmkv** [comment]
Hi @ee92 
I reached out to you in Teams to check up on the status of the issue, but haven't heard back yet.
I will close this issue due to inactivity. Feel free to reopen it when you have an answer to my colleague Alex' questions.
