### ISSUE TITLE
ProgressIndicator: The progress bar is not smooth

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents#3193]
**Describe the bug**
The progress bar is not smooth from value x to value y.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/goofy-chebyshev-9mrhr?file=/src/App.js).*

**To Reproduce**
1. first set value as 30.
2. progress bar loading is done.
3. then set value as 60.
4. progress bar loading is done once again.

**Expected behavior**
set value as 30, the progress bar from 0 to 30.
then set value as 60, the progress bar from 0 to 60 (it is still started from 0, it turns back to 0, then rise to 60.it is supposed to start from 30, and rise to 60.)

**Comment by MarcusNotheis** [comment]
Additional Info from https://github.com/SAP/ui5-webcomponents-react/issues/1534:
```
import React, { useState } from "react";
import { FlexBox, Button, ProgressIndicator } from "@ui5/webcomponents-react";

export default function App() {
  const [progressIndicatorVal, setProgressIndicatorVal] = useState(0);

  const runtest = async () => {
    setProgressIndicatorVal(30);
    await sleep(1000);
    setProgressIndicatorVal(60);
    await sleep(1000);
  };

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  return (
    <FlexBox>
      <Button
        onClick={() => {
          runtest();
        }}
      />
      <ProgressIndicator
        style={{ height: "1rem", width: "25rem" }}
        valueState={"Information"}
        value={progressIndicatorVal}
      />
    </FlexBox>
  );
}
```

**Comment by tsanislavgatev** [comment]
Hello @ggfer,

In the given example i see the progress indicator working well. It goes 0 -> 30 -> 60.

Can you please check it and if it's still broken on your side provide video/gif, it will be easier for us to proceed with the issue.

Thanks and Best Regards,
Tsanislav

**Comment by ggfer** [comment]
> Hello @ggfer,
> 
> In the given example i see the progress indicator working well. It goes 0 -> 30 -> 60.
> 
> Can you please check it and if it's still broken on your side provide video/gif, it will be easier for us to proceed with the issue.
> 
> Thanks and Best Regards,
> Tsanislav

Thanks for your reply~
I got this issue. The percentage is at left at first. It turns to right when it is bigger than 50. It causes the bar is not smooth.

**Comment by tsanislavgatev** [comment]
Hello @ggfer ,

The component is created by the example given in openui5: https://ui5.sap.com/#/entity/sap.m.ProgressIndicator/sample/sap.m.sample.ProgressIndicator

And this is the default behavior of the component. The change of the side of the percentage is implemented because of the edge cases of 0% and 100% in which the text would be outside of the component.

Thanks for the reply and Best Regards,
Tsanislav

**Comment by gmkv** [comment]
Hello @SAP/ui5-webcomponents-topic-p 

Would you have a look at this?

**Comment by plamenivanov91** [comment]
Hello @ggfer ,

Everything works as expected with the ProgressIndicator UI5 Web Component.

You can see this sample for more information:
https://sap.github.io/ui5-webcomponents/playground/components/ProgressIndicator/

The visible value (number percentage) is supposed to be on the left side for 50% or less, and on the right side for 51% and more.

The transition is smooth.

The transition/animation duration might vary depending on the length which the indicator will travel before finishing its designated destination. This time might be more than 1000ms/1sec if the we set the indicator from 0 to 90% for example.

The jerkiness you are experiencing might be because you are not giving enough time for the animation to finish.

As I said above, everything is working as expected from our side. I am closing the issue now.

Regards,
Plamen Ivanov

**Comment by evangeline-fjy** [comment]
Hello,

I have a question regarding the progress bar animation. If the value is set from, let's say 0 to 60, the right edge of the is flat; but if the value is set from any percentage to 100, while the animation continues, the right edge is already become rounded.

![Peek 2022-10-24 18-35](https://user-images.githubusercontent.com/50171639/197578804-93cbc662-4488-42c0-957b-7152b478417c.gif)

Is there any elegant way to avoid this?
