### ISSUE TITLE
ui5-label: `wrap` is ignored when used inside FlexBox / Custom List Item

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#3324]
### **Bug Description**
The `ui5-label` ignores the `wrap` property when being used inside of a Flex Box / Custom List Item:
![image](https://user-images.githubusercontent.com/8775211/119818864-062d6980-bef0-11eb-86e3-3cca6c6d050d.png)

When the wrap attribute is removed, the label truncates correctly.

### **Expected Behavior**
I would expect that the Label wraps it's text content after reaching the max width.

### **Steps to Reproduce**
1. Open this CodeSandBox: https://codesandbox.io/s/gallant-black-nk2xe?file=/src/App.js
2. See the Error: The first label is truncated correctly, the second label is way too large.

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: macOS
- Browser: Chrome 90
- Affected component: ui5-label

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

cc @d3nergy

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please take a look of this issue, it's reproducible in the sample given above.

Best Regards,
Tsanislav

**Comment by ilhan007** [comment]
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by gmkv** [comment]
When the Label is used inside a List > CustomListItem > inside a flex container, the wrapping breaks due to a `white-space: nowrap`style set in `ui5-li-content` which later gets inherited by the Label.

The Label with `wrapping-type="Normal"` works fine in just a flex container.

https://codesandbox.io/s/ui5-webcomponents-forked-w9jq6
