### ISSUE TITLE
Combobox: Scroll handle not working

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents#3330]
**Describe the bug**
When clicking in the handle of the ComboBox, the dropdown is closed.

**Isolated Example**
*Code example: [this codesandbox](https://codesandbox.io/s/nostalgic-sky-tsgvg?file=/src/App.js).*

**To Reproduce**
1. Create and dropdown with a lot of options
2. Open it
3. Click in the scroll Handle

**Expected behavior**
Use the handle to scroll.

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/16123699/119872084-755b8b80-bef9-11eb-9f72-78e91efe195e.gif)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 16.0.1
Operating System: MacOS
Browser: Chrome

**Comment by lpohren** [comment]
Thanks @MarcusNotheis ,

I also noticed, it only happens on the last versions, when using webcomponents 1.0.0-rc11 it works fine and the performance on loading the options is way better.
See this example: [CodeSandbox with older version](https://codesandbox.io/s/ecstatic-sara-iyycw?file=/src/App.js)

**Comment by pskelin** [comment]
Hi @lpohren ,
thanks for providing both samples, makes the investigation so much easier!

Could you elaborate more on the performance being better in the older versions? I ran a performance timeline recording on Chrome and both versions are equal - both rendering the combobox, and rendering the items after a click are roughly the same.

Which part are you referring to?

**Comment by lpohren** [comment]
My bad, there was no performance difference.
One of the examples had already cached the list, that`s why it was quicker.

The only issue will be the handle.

**Comment by fifoosid** [comment]
Hello @SAP/ui5-webcomponents-topic-rl 

I am forwarding this issue to you as it occurs in the ComboBox.

Here is an [isolated example](https://codesandbox.io/s/ui5-webcomponents-forked-o6zjs?file=/index.html) with standalone popover(used to validate the issue is not reproducible outside of the ComboBox).

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

I analyse the issue and I found out the root cause is in the Popup. In order to correct focus when there is no focusable content, you have added tabindex="-1" to the root element of the Popup, which causes the issue.
When we have a ui5-combobox with many suggestions(scroll is presented), when trying to scroll down, the dropdown is closed. 
Unfortunately ,the ui5-combobox is not the only affected component. The other input components are affected as well. Imagine, you have the same scenario (suggestions with scroll) in ui5-input component, when trying to scroll down among the suggestions, the input field loses the focus. Try to scroll down and then to type any character - it is not possible, since the focus is not in the input field. The expected behaviour is to have the physical focus always in the input field and to be able to type in.
Is it possible to add tabindex = "-1" only when there is no focusable content in the popover?

Could you please check and investigate the issue from your side?
If any adjustments in the input components are necessary, do not hesitate to contact us or return the issue back to our team.

Thank you in advance!

Kind Regards,
Niya
