### ISSUE TITLE
Wrong arrow position in Popover component

### ISSUE THREAD

**Issue by pavelkornev** [SAP/ui5-webcomponents#3391]
### **Bug Description**
When using a reference example for ShellBar component (https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/) the Popover arrow is wrongly positioned:
![Screenshot 2021-06-04 at 08 58 55](https://user-images.githubusercontent.com/748043/120759487-5a010980-c513-11eb-9139-368f88b4baa8.png)

Sometimes it's positioned correctly, depends on the width of the content part of Popover...

### **Expected Behavior**
Popover arrow should point to the middle part of Avatar component and should not depend on content width.

### **Steps to Reproduce**
See example below.

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-92x4n?file=/index.html

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: macOS 11.2.3
- Browser: Chome 90.0.4430.212
- Affected component: Popover

### **Log Output / Stack Trace / Screenshots**
N/A

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP Graph
- Business impact: -

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

this issue is about misalignment of the arrow of the popover (the arrow is not displayed at the center of the opener).

![CPT2106041533-532x110](https://user-images.githubusercontent.com/22766569/120802253-e67aee80-c54a-11eb-9830-841d728c3f96.gif)

Here is a more isolated example: https://codesandbox.io/s/ui5-webcomponents-forked-8l197?file=/src/index.js
It is only reproducible if a long `ui5-title` is used in the popover. If just a text or div/h1/h2 etc. elements are used - the issue is no longer reproducible.

Kind Regards,
Dobrin
