### ISSUE TITLE
the relation about this project and Fundamental Library Styles

### ISSUE THREAD

**Issue by chenshuichao** [SAP/ui5-webcomponents#3448]
https://github.com/SAP/fundamental-styles

**Comment by pskelin** [comment]
@akudev has posted a great comparison as a comment to a blog post here:
https://blogs.sap.com/2019/02/11/ui5-web-components-the-beta-is-there/#comment-451391

I am posting it as a quote as well:

> I'm sure that Peter will give the official reply, but let me give my version:
>
> Fundamentals as it is offered right now is a set of stylesheets (SCSS compiling into CSS) along with a recommendation how the HTML has to look in order to be styled correctly by that CSS. It is your task to write that HTML, it is your task to update the HTML as the user interacts with it.
>
> UI5 Web Components, on the other hand, encapsulate not only the design, but also the structure and the functionality inside new HTML elements you can use like any other HTML elements without caring about how they work internally.
> 
>
>
> Taking the datepicker calendar popup as a drastic example: if you write an app which puts the correct html structure with all the tags for the single days etc. into a web page, then Fundamentals will make this HTML look according to the Fiori guidelines for displaying a calendar. But it's your task to provide the day/month names in the user's language and when the user clicks an arrow to skip to the next month, then it is your task to change the HTML, to fill in the new day numbers to the correct place, to only show 28 days when it is February (or sometimes 29, you have to check the year), and to know whether Sunday or Monday should be displayed in the first column according to the current user's locale. Once you have done all of this correctly, Fundamentals will make sure the result looks again like a real Fiori calendar, showing the next month. Oh, and opening this calendar in an overlay which appears at the correct location once the user clicks in the date input and to hide that overlay again once the user clicked on a day, is also your task. In case you want to enable users to use their keyboard, you might want to register event handlers on your HTML to react on cursor key presses and move the focus accordingly. In case you want this calendar to be usable by blind people, you have to make sure that screenreaders read helpful information, e.g. by changing aria attributes in the HTML, as the user interacts with the calendar. Etc.
>
>
>
>So all in all, UI5 Web Components are fully functional UI controls, usable like regular HTML tags, while Fundamentals is focusing on the design and leaving you all the freedom to implement the functionality to the degree needed.
>
>If you already have a fully working app which is functionally complete and can adapt its HTML according to the needs of Fundamentals' CSS, then Fundamentals may be a good choice to enable the official Fiori design for the app. If you prefer dropping in the new HTML tags instead of adapting the HTML or you need not only the design, but consistent behavior, or you create a new app (regardless of the framework you want to use), then UI5 Web Components may be a good choice.

**Comment by zhang928160849** [comment]
@pskelin But there is also [Fundamental-react](https://github.com/SAP/fundamental-react), it wrap functionality inside React component just like this project did, so what's the relation about these two projects.

**Comment by pskelin** [comment]
Fundamental styles - CSS styles for building Fiori components (visuals only, no behaviour)

On top of it, three independent component implementations were created
- fundamental react
- fundamental ngx
- fundamental vue

The problem with that approach is that the implementation and maintenance of each component (like button) is duplicated for each framework that needs to be supported. Also new frameworks are not supported (like Svelte - you're on your own as fundamental has no offering).

ui5-webcomponents offer directly the Fiori components in a framework independent way, because web components are a browser standard. This means a single implementation effort to build these components makes them available across all frameworks - even future ones.

One small issue at this time is that react has a long-standing gap of not supporting web components well enough (although this is about to change). You can still use them, albeit in a more inconvenient way for developers with writing more glue code.
To address this shortcoming of react/webcomponents, the ui5-webcomponents-react wrapper project was created, which uses ui5-webcomponents internally, but provides a nice wrapper.

In the end, both Fundamental React and UI5 web components (via the react wrapper) offer a Fiori components implementation for react developers. The major difference is how this implemented - single framework (fundamental) or multi framework support (ui5 web components).
