### ISSUE TITLE
<ui5-page>

### ISSUE THREAD

**Issue by octavonu** [SAP/ui5-webcomponents#3454]
Hello,

i have copy/paste the example for ui5-page (https://sap.github.io/ui5-webcomponents/playground/components/Page/) 
and the output doesn't render the default slot. The header and footer are on top of each other and the default slot isn't part of the shadow dom. 

![image](https://user-images.githubusercontent.com/50553626/122902901-2ca7be80-d34f-11eb-9928-2fc5bb8e3243.png)

![image](https://user-images.githubusercontent.com/50553626/122902217-996e8900-d34e-11eb-9d9a-920ba836bbc0.png)

Thank you

**Comment by NHristov-sap** [comment]
Hi @octavonu ,

Can you please give an isolated example that demonstrates the issue (in [https://codesandbox.io/](https://codesandbox.io/)? Sometimes it is hard to inspect/debug a screenshot :)

Best Regards,
Nikolay Hristov

**Comment by octavonu** [comment]
Hi @NHristov-sap 

Indeed, not so easy to debug a screenshot. :) My mistake

Please see an example here: https://codesandbox.io/s/ui5-page-example-dx4c1?file=/index.html
Thank you

**Comment by NHristov-sap** [comment]
Hi @octavonu ,

Thanks for the sample, it really hepled :).

You have to set width and height of the parents of the ui5-page, because it uses the whole space.
If you add **style="width: 100%; height: 100%"** (or via CSS), of the **HTML** and **BODY** tags, it will work!

Hope this helps :)

Best Regards,
Nikolay Hristov
