### ISSUE TITLE
^0.31.10 import of MediaRange in Page.js is giving compile error

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#3458]
### **Bug Description**

This import doesn't exist:
https://github.com/SAP/ui5-webcomponents/blob/7d1eac3770e4903f493274e903535132436a48cf/packages/fiori/src/Page.js#L4

I think the MediaRange.js missed to be merged to branch 0.31

**Comment by ilhan007** [comment]
Hello @codefactor, 
yes when downporting the [Page responsive paddings](https://github.com/SAP/ui5-webcomponents/pull/3412) we should have downport the MediaRange. 

It should be fixed with 0.31.11
https://unpkg.com/browse/@ui5/webcomponents-base@0.31.11/dist/MediaRange.js


Thanks for letting us know.
BR, ilhan
