### ISSUE TITLE
DynamicPage: a11y Flags elements whose role is none or presentation and which cause the role conflict resolution to trigger.

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#3486]
**Describe the bug**
Flags elements whose role is none or presentation and which cause the role conflict resolution to trigger.

**Isolated Example**
This issue occurs on slim-arrow-up/slim-arrow-down/pushpin-off etc. Also for slim-arrow-right/slim-arrow-left icon used in FlexibleColumnLayout

**Screenshots**
<img width="1920" alt="Screen Shot 2021-06-18 at 1 27 02 PM" src="https://user-images.githubusercontent.com/65705637/122613618-01b12800-d03a-11eb-8aad-d3fb042a63ef.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:~0.31.9
`@ui5/webcomponents-react` version: ^0.131.9
Operating System: Mac OS
Browser:Chrome

**Comment by plamenivanov91** [comment]
Hello Colleagues,

It seems the problem is coming from the `ui5-icon-root` svg DOM element inside the `ui5-icon` web component.
Steps to reproduce:

1. Download the axe tool from the Google chrome web store
2. Open https://sap.github.io/ui5-webcomponents-react/iframe.html?id=inputs-button--default-story&args=&viewMode=story
3. Run axe DevTools
4. See the minor error

This might be a bug in the axe tool itself, since it only removes the error if we remove the empty `aria-label` attribute as well as the `tabindex` attribute. This is not an option for us, since it makes the ui5-icon component focusable which is incorrect.

Could you please verify if we need to comply with the axe tool, and if so - check if this is not bug related to the axe devTool itself.

Regards,
Plamen Ivanov

**Comment by gmkv** [comment]
FYI @SAP/ui5-webcomponents-topic-p

**Comment by dobrinyonkov** [comment]
This seems to be fixed either by us or by the axe tool team, because the warning is no longer reported, following these steps:

1. Download the axe tool from the Google chrome web store
2. Open https://sap.github.io/ui5-webcomponents-react/iframe.html?id=inputs-button--default-story&args=&viewMode=story
3. Run axe DevTools
4. See the minor error (Flags elements...)

If you still find this inconvenient please reopen this issue and provide URL with reproducible flow.
