### ISSUE TITLE
TableCell: Text not selectable in Firefox/Safari

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents#3494]
**Describe the bug**
While Chrome allows you to select text in tables just fine, Firefox and Safari won't, even with `user-select` set to `text`. This problem ist most likely related to [this upstream issue](https://github.com/SAP/ui5-webcomponents/issues/1163); however, the mentioned workaround using `<span>` tags does not appear to work with the React wrapper.

**Isolated Example**
[Isolated example on `codesandbox.io`](https://codesandbox.io/s/quirky-euclid-b3eyf?file=/src/App.js).

**Expected behavior**
Text selection works as it would with standard text in Chrome, Firefox, and Safari.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `1.0.0-rc14`
`@ui5/webcomponents-react` version: `0.16.6`
Operating System: macOS 11.4
Browsers: Chrome 91, Firefox 89, Safari 14.1

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd 
This issue is about not being able to select text in the <ui5-table-cell> component.

There exists a workaround which was good enough for the last time this issue came up in #1163. 
The workaround was - wrap the text in a `span` element and you can now select the text, but only in Chrome.
Sample with and without the span: https://codesandbox.io/s/ui5-webcomponents-forked-33cvy?file=/index.html

Can you see how this issue can be fixed?

Kind regards,
Georgi

**Comment by AndrianStoikov** [comment]
Hello,

Is it possible to take a look at this issue? We at RBSC hit it as well.

Best regards,
Andy

**Comment by ilhan007** [comment]
Hello @goodefroi the fix has been released with 1.0.0-rc.15.

Note: there were a lot of breaking changes that have to be adopted before upgrading to rc.15
See the BREAKING_CHANGE section:  https://github.com/SAP/ui5-webcomponents/releases/tag/v1.0.0-rc.15
