### ISSUE TITLE
Dialog and (Responsive)Popover: declarative API for open/close

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3527]
### **Feature Request Description**
As part of the [Component API Review](https://github.com/SAP/ui5-webcomponents/issues/3107) we agreed to introduce declarative API to open/close popups (Popover, Responsive Popover, Dialog).

### **Background**
The requirement has been raised from different sources. It was discussed internally in order to make our popups closer to the native spec ([HTMLDialogElement Spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)).
But also, UI5 Web Components 4 react and our community asked for the declarative API.

### **Proposed Solution**

Using the "open" attribute, when set the popup should open, and when removed - should close.

**Dialog**:
```html
<ui5-dialog open />
```

For the Popover and Responsive Popover components, we will need another property to describe the "opener" element,
e.g. the  DOM element that the popup is opened from. And "opener", "for", "open-by" are possible options to pick from.

**Popovers**:
```html
<ui5-button id="info">Info</ui5-button>
<ui5-popup open opener="info"></ui5-popup>
```

### **Tasks**
- [ ] Popover
- [ ] Responsive Popover
- [ ] Dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Example**
Open the [sample](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_dialog_show_close)  and set the "open" attribute to the dialog element

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components 4 React

**Comment by ilhan007** [comment]
FYI @MarcusNotheis

**Comment by MarcusNotheis** [comment]
Hey colleagues,
do you already have an estimate when this feature request can be delivered?
Opening Dialogs in an imperative way is really painful (especially in the React world).

Thanks!

**Comment by codefactor** [comment]
@ilhan007 ,

This issue is half a year old. Is there any real plans to do this?

As @MarcusNotheis described, in a React application it takes a lot of extra code to fake a declarative opened dialog, and it is very difficult to do this in a safe way to ensure that no exceptions will happen and that the dialog is guaranteed to open.

The problem here is the timing issue about when will the virtual DOM get added as real DOM, and then when will the Web Component attach and create the shadowRoot, and then when will the functions to show/hide be available on the host tag.

The solution involves very delicate timing and has certain edge cases that one might not think about normally around cases where web components are lazily added to the page.

I've written a nice specialized Hook that hides away these messy details, but I don't think it will be possible for inexperienced teams to do this in a way that will work both in a Jest environment (JSDom) as well as a real WebKit environment (chrome/edge).

It is probably not a good idea to let this feature linger too long. Please let us know if this is planned, or if there are any blockers that prevent this behavior?
