### ISSUE TITLE
Label: Additional space is coming between text and colon

### ISSUE THREAD

**Issue by yoganjan** [SAP/ui5-webcomponents#3531]
**Describe the bug**
There is additional space is coming between Text and Colon

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-label--default-story .
When we add showColon attribute to Label , additional space is coming

**To Reproduce**
See the example https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-label--default-story 
Add showColon Attribute to Label

**Expected behavior**
There should be option to check whether the space is needed between text and colon Or space should be completely removed

**Screenshots**
<img width="483" alt="Label Space issue" src="https://user-images.githubusercontent.com/16238780/126636817-457ea49c-172f-4075-8987-1348028cdd25.png">

**UI5 Web Components for React Information**
"@ui5/webcomponents": "^0.31.11",
"@ui5/webcomponents-react": "^0.131.9"
Operating System: Windows
Browser: Chrome

**Additional context**
SuccessFactors

**Comment by fifoosid** [comment]
Hi all

The label should not have any space between the text and the colon.
FYI @SAP/ui5-webcomponents-topic-rd

**Comment by gmkv** [comment]
...except in French

**Comment by gmkv** [comment]
Related to #3558

**Comment by ericchan1983** [comment]
Hi @fifoosid,

I am from SuccessFactors Web Experience Shanghai team.

Our team is only allowed to use the SF version of ui5-webcomponent.
We can not use rc version of ui5-webcomponent.

If this issue is fixed in master branch. Can you please downport this feature to 0.31.x ? ( The current version is 0.31.17, maybe you can release 0.31.18 )

Regards,
Eric Chen

**Comment by ilhan007** [comment]
Fixed with 0.31.18
