### ISSUE TITLE
MultiComboBox: after clicking  arrow icon (to collapse MultiComboBox), with multiple selected items, do not show 'x more' message

### ISSUE THREAD

**Issue by gagarin880120** [SAP/ui5-webcomponents#3547]
**Describe the bug**
When selecting multiple items in MultiComboBox and clicking on the drop down again (to collapse it), the drop down displays the years when it should display "x more" (where x is the number of selected years).

**Isolated Example**
https://codesandbox.io/s/suspicious-silence-72qik?file=/src/App.js

**To Reproduce**
1. Click on arrow icon (to expand MultiComboBox).
2. Select multiple items.
3. Click on arrow icon (to collapse MultiComboBox).
4. See this: 
![image](https://user-images.githubusercontent.com/44781670/126972061-31fd06fa-b495-4efb-8be7-71ef7782186d.png)
5. Should be like here:
![image](https://user-images.githubusercontent.com/44781670/126972356-9115e129-b87f-4f30-ba22-ea23461b61c9.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by yanaminkova** [comment]
Hello @gagarin880120,

When you select multiple items and then click on the arrow to collapse MultiComboBox, focus is still on the control and you can edit you selection (remove items).
If you click somewhere outside of control, the focus is removed (you exit this "edit" mode) and the expected behavior works as it should.

I hope this helps!

Thanks and regards,
Yana
