### ISSUE TITLE
ui5-date-picker removes error value state by itself

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#3571]
### **Bug Description**
We are using a `ui5-date-picker` in with an error value state. When the selected date is changed to another invalid date, we want to keep the `Error` state. As the Date Picker is removing the error state by itself, we can't achieve this because React still thinks that the value-state is `Error` and not `None` 

### **Expected Behavior**
`value-state` should be fully controllable by end users

### **Steps to Reproduce**
1. Open https://codesandbox.io/s/naughty-visvesvaraya-63pd1?file=/src/App.js
2. Select a Date
3. Click `Set Error Value State`
4. Select another Date
5. Click `Set Error Value State` again
6. See: no error state but state "None"

### **Isolated Example**
https://codesandbox.io/s/naughty-visvesvaraya-63pd1?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.0.0-rc.14 (happens with rc.15 candidate as well)
- Affected component: `ui5-date-picker`, maybe other inputs as well?

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-b could you look at the issue, it is described fine and reproducible with the steps above.

**Comment by tsanislavgatev** [comment]
Hello @MarcusNotheis,

Тhis is the expected behaviour of the control, because it gives an option for a manual valueState change, but it also keeps the default validation. For example if you exclude the validation of the control, you can type something like '31233d1s2a3'( invalid date) and it won't take any action, and this won't be correct from component side. But there is an option, for example an event listener on 'change' event on the component should work for every change. I've forked the provided snippet into a one that gives the application developer control over the state based on a simple option.
https://codesandbox.io/s/dazzling-chaum-cr9pl?file=/src/index.js

Best Regards,
Tsanislav

**Comment by 2bno1** [comment]
@tsanislavgatev In the example https://codesandbox.io/s/dazzling-chaum-cr9pl?file=/src/index.js, the manual value state change (triggered by clicking `Change Value State to Error`) only takes effect at the first time. You can reproduce this by:
1. Click 'Change Value State to Error' button (Value State is set to Error)
2. Pick a date from date picker (Value State is set to None)
3. Click 'Change Value State to Error' button again (Value State is still None)

The reason is
1. When the button is clicked the first time, `isError` is changed from `false` to `true`, `App` is re-rendered, `ui5-date-picker` is re-rendered with `Error` value state. 
2. Picking a date from date picker, the ui5-date-picker set the value state to `None` internally. https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/DatePicker.js#L506
3. However, when the button is clicked the second time (or later), `isError` is kept `true`, `App` will not be re-rendered, so the value state of `ui5-date-picker` is kept `None`.

I've also submitted a similar issue #3516

**Comment by MarcusNotheis** [comment]
You can also compare the behaviour to the [SAPUI5 Date Picker](https://ui5.sap.com/#/entity/sap.m.DatePicker/sample/sap.m.sample.DatePickerValueState). The value state does not change automatically, no matter what you do with the `DatePicker`.

**Comment by phipsalabim** [comment]
Hi @tsanislavgatev

> Тhis is the expected behaviour of the control

If that's the case, then the expected behaviour should be revised. **As it currently stands, this behaviour makes it impossible to use databinding with the value-state prop, and ultimately makes this component unusable/extremely painful for react/angular/vue/svelte users. State can not be bound to the value-state prop if the component overwrites the value of that prop!**

As @MarcusNotheis noted, it is not the behaviour of the equivalent ui5 datepicker control

PS: I find it quite concerning how issues are being closed at light-speed, without any discussions or considerations

**Comment by fifoosid** [comment]
HI @phipsalabim , @2bno1 

As it is explained [here](https://github.com/SAP/ui5-webcomponents/issues/3516#issuecomment-893281504), we had to discuss how to proceed with this issue. We decided to work on it. I have reopened the other issue and you can keep track of progress there.

**Comment by phipsalabim** [comment]
Hi @fifoosid,

That's great to hear. Thanks!
