### ISSUE TITLE
ui5-color-picker: change event is not fired when changing opacity

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#3576]
### **Bug Description**
The `change` event is not fired when e.g the color spectrum or the opacity is changed.

### **Expected Behavior**
I would expect that the `change` event is fired when e.g. the opacity or the color spectrum is changed.

### **Steps to Reproduce**
1. Open https://sap.github.io/ui5-webcomponents/playground/components/ColorPicker/ and open the dev tools
2. execute `document.querySelector('ui5-color-picker').addEventListener('change', console.log)`
3. Change the color - console is filling with events (as expected)
4. Change the opacity or the color spectrum -> no change event fired

### **Isolated Example**
https://sap.github.io/ui5-webcomponents/playground/components/ColorPicker/

### **Context**
- UI5 Web Components version: 1.0.0-rc.14 (happens with `master` and `1.0.0-rc.15` candidate as well)
- Affected component: `ui5-color-picker`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

The issue is regarding the color picker component. There is no way the developer is notified, when changes in the opacity are made. Currently, the change event is only fired, when changes in the color are made. The documentation states the same, so I was not sure if this is a feature request or a bug. What is more, changes in the opacity in the UI5 Color Picker are included in the change event. 

Could you please check?

Elena
