### ISSUE TITLE
ComboBox: Popover position when scrollbar appears

### ISSUE THREAD

**Issue by davischmitz** [SAP/ui5-webcomponents#3584]
**Describe the bug**
When using the ComboBox with a number of ComboBoxItems that cause a scroll, the popover is being positioned on top of the input field.

Correct behavior (small number of items): 
![image](https://user-images.githubusercontent.com/11902967/127894087-3f636ffa-9886-4bbc-8142-637813d86211.png)

Incorrect behavior (scrollbar appears): 
![image](https://user-images.githubusercontent.com/11902967/127894172-07b10e38-99dd-4b5e-907c-454b6015b3f9.png)

**Isolated Example**
https://codesandbox.io/s/dazzling-bush-j7olt?file=/src/App.js

**To Reproduce**
1. Add Combobox
2. Add enough items that a scrollbar appears

**Expected behavior**
The popover with the items should appear below the input field.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc-14
`@ui5/webcomponents-react` version: 0.17.3
Operating System: macOs Big Sur 11.4
Browser: Chrome 92.0.4515.107

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

The issue is related to the popup showAt logic. As you can see in the below sandbox the originally reported issue is also reproducible with Input, Select also. All of them use the responsive popover, with the showAt method and pass the this reference. There are some issues in the css calculation of the position of the popup, when the popup reaches the end of the viewport (in the reported case, when the suggestion popover creates a scrollbar).

Please check https://codesandbox.io/s/ui5-webcomponents-forked-gbjoj

Could you please check?

Kind Regards,
Elena

**Comment by kskondov** [comment]
Hello @davischmitz,

Can you please confirm if the issue still exist with the latests version?

Best Regards,
@kskondov

**Comment by davischmitz** [comment]
Hi @kskondov!

Seems to be fixed using the latest versions.

Thanks and best regards,
Davi
