### ISSUE TITLE
Table: Ability to use aria-describedby to provide a table summary

### ISSUE THREAD

**Issue by DLaskov** [SAP/ui5-webcomponents#3597]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way of using `aria-describedby ` tag in order to give a table readable summary by computer software as MS Narrator and JAWS to read out loud the desired description of a table.

**Describe the solution you'd like**
Ideally, the Table should provide a native `aria-describedby` tag and the ability to give `aria-describedby` an id that refers to an element (eg. Text, Label, Title, etc.) from which to take the summary of the table.

**Additional context**
Please refer to https://www.w3.org/WAI/tutorials/tables/caption-summary/#using-aria-describedby-to-provide-a-table-summary in order to see how this is done in a native HTML table.
 
Internal ticket: https://support.wdf.sap.corp/sap/support/message/2180312086

**Comment by elenastoyanovaa** [comment]
Hello @DLaskov ,

As far as I understand the internal incident, the reported issue is that a provided caption is not associated with the table. Please provide an isolated example via codepen in order to be clear of the usage.

The approach for the aria-describedby is described as "This WAI-ARIA feature may not be as widely supported by assistive technology than other approaches for summaries on this page." in the link provided and is used for additional info for a table, not label. What is more aria-describedby would not be sufficient for the case of web components, since referencing elements via id, will result in invalid mapping, since the 'real' elements are in different shadow dom. In future, when the ARIA 1.3 is not a draft, but a standard, aria-description may be supported in order to give the possibility for the user to create description. You can check more info about this here https://github.com/w3c/aria/issues/891

If I correctly understand a more suitable approach would be providing an aria-label for table labelling, or providing a table header similar to the one in UI5 Responsive Table. What do you think?

Kind Regards,
Elena

**Comment by DLaskov** [comment]
Hi @elenastoyanovaa 

An `aria-label` on the Table level would be also sufficient in our case. But as far as I know `aria-label` is not supported currently on Table level, right? If that's the case we would like such a feature.

**Comment by elenastoyanovaa** [comment]
Hi @DLaskov,

Then I will mark it as a feature request. Thank you for reporting the issue!

Kind Regards,
Elena

**Comment by elenastoyanovaa** [comment]
Hello,

The same is reported also from SF: #4648
