### ISSUE TITLE
ui5-table-row: Add mouse cursor behavior for ui5-table-row which defines row-click event

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#3607]
### **Bug Description**
There is no mouse cursor when mouse over on table row which defines row-click event.

### **Expected Behavior**
Should show mouse cursor when mouse over on table row which defines row-click event.

### **Steps to Reproduce**
1. Go to 'https://github.wdf.sap.corp/pages/xweb/goalmanagementx/app.html?mock&noFirstTimeGuidance'
2. click any goal card and nav to goal detail page
3. click total number icon button on the button right of page to open the Goal Alignment dialog
4. mouse over on table row and there is no mouse cursor
![2021-08-06_11-26-50](https://user-images.githubusercontent.com/13098801/128451575-7289846b-f346-41d0-96b5-a413036f1829.jpg)

### **Context**
- UI5 Web Components version: {0.31.12}
- OS/Platform: {Mac OS}
- Browser: {Chrome}
- Affected component: {ui5-table-row}

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}

**Comment by elenastoyanovaa** [comment]
Hello @GongRichard ,

The row-click event is used for Active rows as described here https://sap.github.io/ui5-webcomponents/playground/components/Table/ . In order to set a row to active mode, you should ensure that the table was set in one of the provided selection modes. Then you will see an indication that the row is clickable, via the mouse cursor.

Does this suit your scenario?

Kind Regards,
Elena

**Comment by GongRichard** [comment]
Hi @elenastoyanovaa ,

I added mode="SingleSelect" in ui5-table and added type="Active" in ui5-table-row, but I didn't see the selection effect in my local. Is there any other thing which I missed?

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard this is a feature, available in the master and the latest stable release - 1.0.0-rc.15, but not downported in 0.31. I assume you test with 0.31?

**Comment by GongRichard** [comment]
Hi @ilhan007 ,

Yes, we are using 0.31.12.

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard 
could you discuss with your team about the option to upgrade to a RC.15 based version (we can release 0.33 for example)

RC.15  includes a lot of breaking changes, that are well described here in the BREAKING CHANGES section:
https://github.com/SAP/ui5-webcomponents/releases/tag/v1.0.0-rc.15

Sooner or later you will have to adopt them, do you think this is a good time to do that? Because downporting bigger changes to 0.31 becomes more and more difficult.

**Comment by GongRichard** [comment]
Hi @ilhan007 ,

Because we are close to SF releasing date, so I don't think we can upgrade to 0.33. That's ok, as this issue is a low-priority issue, we can fix it in our next release.

Thanks,
Richard

**Comment by ilhan007** [comment]
Hello @GongRichard I suppose you already updated, or you are about to update to 1.x  so I am closing the issue.
If this is not the case and you still face issues, please get back to us.
