### ISSUE TITLE
Add autocomplete field to the Input web component

### ISSUE THREAD

**Issue by DanieleStrafile** [SAP/ui5-webcomponents#3646]
### **Feature Request Description**
I could not find the autocomplete fieldin the Input component documentation. That would be really useful in order to implement the autofill card details scenario described here: https://developers.google.com/web/fundamentals/design-and-ux/input/forms#recommended_input_name_and_autocomplete_attribute_values 

### **Proposed Solution**
Add the autocomplete field to the Input web component

### **Proposed Alternatives**
No alternative for now, except using the html Input tag and forgo the web component

### **Priority**
- [x] Medium

**Comment by hristop** [comment]
Hi @DanieleStrafile ,

We have been looking into this case before and after some discussions with our architects we have decided that such feature could not be implemented on our side without it interfering with some of the other features we have in the components.
The problem is that the standard for autocomplete can be interpreted and implemented in different way by each browser and can even change between browser versions, which is completely out of our control.

Also it may (and probably will) introduce some security as well as usability issues with the components, which we will not be able to handle as they will be beyond our scope.

Best Regards,
Hristo
