### ISSUE TITLE
[ui5-table] row-click event binding not working anymore

### ISSUE THREAD

**Issue by tonyh1982** [SAP/ui5-webcomponents#3656]
### **Bug Description**
We are using UI5 WC in an Angular project where we used to bind the "row-click" event of the ui5-table to a function which handles navigation. Since the new release the function is not called anymore. I prepared a simple example in Codesandbox.io that shows the issue.

### **Expected Behavior**
When clicking on a ui5-table row a function should be called that has been bound via event binding.

### **Steps to Reproduce**
1. Go to the example I provided
2. Click on the table row
3. nothing happens --> not expected
4. in the "Dependencies" pane on the left side change the UI5 WC version to RC14
5. reload the UI
6. click on the table row
7. alert is being triggered as expected

### **Isolated Example**
https://codesandbox.io/s/ui5-wc-table-row-click-event-y9gki

### **Context**
- UI5 Web Components version: 1.0.0-rc.15, 0.31.15, 0.33.0

### **Log Output / Stack Trace / Screenshots**
n/a

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SAP Marketing
- Business impact: we have been waiting for some features that are available with RC.15, however, we can't use them because of this regression. Could you please provide a solution?

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible with the provided by the author steps.
The "row-click" event is not fire at all on RC.15 after the following feature: https://github.com/SAP/ui5-webcomponents/pull/2848

Reason:
Pressing over the row via mouse(_onrowclick) or keyboard(_onkeydown) will now, trigger the following check:
`const checkboxPressed = event.target.classList.contains("ui5-multi-select-checkbox");`

`checkboxPressed ` will result into `false`, when `mode="SingleSelect"`, as there is no checkbox rendered
corresponding to `the ui5-table-row` s.

As a result the "row-click" event is not getting fired at all.

There is no such issue with `mode="MultiSelect"`.

Either checkboxes need to appear in the SingleSelect mode or the described check is redundant in this mode.

Best Regards,
Boyan Rakilovski

**Comment by niyap** [comment]
Hello @tonyh1982,

Thanks for sharing your findings!
After the implementation of SingleSelect and MultiSelect mode as well as Active and Inactive row type, we have enhanced the row-click event handling according to the [sap.m.Table](https://sapui5.hana.ondemand.com/#/api/sap.m.Table) implementation. The event is fired only when the **ui5-table-row** type is set to "Active".
The default value of the row's type is "Inactive" as in the sample provided by you. You could change it to "Active" and you will notice how the event will be fired when you click over the row.
Here, you could find more information: https://sap.github.io/ui5-webcomponents/playground/components/Table/

Kind Regards,
Niya
