### ISSUE TITLE
Select component: The options can't be switched when the Narrator is turned on

### ISSUE THREAD

**Issue by kolew96** [SAP/ui5-webcomponents#3660]
**Description**
The options can't be switched with arrows when the Narrator is turned on
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-select--default-story

**Observed behavior**
The options can't be switched with arrows when the Narrator is turned on

**Expected behavior**
Тhe options must be able to be switched with arrows when the Narrator is on

**Steps to reproduce**
1. Go to [https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-select--default-story](url)
2. Turn on the Narrator
3. Tab until focus on the first example select
4. The options can't be switched with arrows

**Context**
Browser (if relevant): {...} Chrome

**Additional Context**
On accessing the items within the Select, the item count information is not conveyed.
[ACC-264.1_Central Business Configuration 2108 _ combo box_ Item count not read.docx](https://github.com/SAP/ui5-webcomponents-react/files/6982361/ACC-264.1_Central.Business.Configuration.2108._.combo.box_.Item.count.not.read.docx)

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is reproducible in the playground as well:
https://sap.github.io/ui5-webcomponents/playground/components/Select/
by following the provided by the author steps and via using Windows Narrator.

The options in the ui5-select component aren't reachable via arrow keys when Windows Narrator is on.

Best Regards,
Boyan Rakilovski

**Comment by nnaydenow** [comment]
Hi @kolew96,

Scan mode is enabled by default. Scan mode is equivalent to Virtual PC cursor mode of JAWS. You can toggle the mode with CAPS LOCK + SPACE.

Select works correctly when the scan mode is off.

Regards,
Nayden
