### ISSUE TITLE
Combobox component: tabIndex prop doesn't work

### ISSUE THREAD

**Issue by kolew96** [SAP/ui5-webcomponents#3661]
**Describe**
tabIndex prop  doesn't work

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version: v0.15.03

**Context**
Browser (if relevant): {...} Chrome

**Comment by unazko** [comment]
Hello @kolew96,

As @MarcusNotheis suggested could you please create simple snipped similar to the following: https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html
and provide steps so we can reproduce the issue.

Best Regards,
Boyan

**Comment by dimitar-trendafilov** [comment]
Hello @unazko 

Since the colleague who initially opened this ticket is no longer assigned to the project, I have double checked the issue. What I found is that this seems to be no longer reproducible. tabindex attribute is working correctly on the combobox field. This issue can be closed.

BR,
Dimitar

**Comment by fifoosid** [comment]
Closing as the issue is no longer reproducible as stated by the colleagues
