### ISSUE TITLE
TabContainer not working in Angular and WebComponents version 0.10

### ISSUE THREAD

**Issue by AlexandraHofmann** [SAP/ui5-webcomponents#369]
**Describe the bug**
When using the TabContainer within an Angular application and version 0.10, the TabContainer is not loading.

**To reproduce**
1. Import TabContainer dependency
2. Place TabContainer example from playground into application
3. TabContainer is not loading, error thrown in console

**Context**
- UI5 Web Components version: 0.10
- OS/Platform: OSX
- Browser *(if relevant)*: Chrome

**Affected components** 
TabContainer in version 0.10 (previous version 0.9 works fine)

**Log output / Any errors** in the console
![Screenshot 2019-05-02 at 09 11 24](https://user-images.githubusercontent.com/15103985/57060588-4b9fee00-6cba-11e9-9cb3-9f0e15513e4f.png)

**Comment by vladitasev** [comment]
Hello,

Thank you for bringing our attention to this! Since version 0.10 ui5-tab-container no longer automatically imports ui5-tab and ui5-tab-separator. We're in the process of updating our documentation to reflect this change.

Please import manually in your project:

import "@ui5/webcomponents/dist/Tab";

and, in case you're using it:

import "@ui5/webcomponents/dist/TabSeparator";

Regards,
Vladi
