### ISSUE TITLE
TabContainer tabs are not accessible via Tab key

### ISSUE THREAD

**Issue by dimitar-trendafilov** [SAP/ui5-webcomponents#3695]
### **Bug Description**
When using TabContainer with Tabs and trying to navigate with Tab key, the navigation goes through the tab contianer.

### **Expected Behavior**
The navigation should navigate through different Tabs.

### **Steps to Reproduce**
1. Click on any tab in the TabContainer.
2. Click tab key

### **Isolated Example**
Please use the example in the React UI5 Webcomponents storybook:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-tabcontainer--default-story

### **Context**
- UI5 Web Components version: 1.0.0-rc.14
- OS/Platform: Windows 10
- Browser: Chrome
- Affected component: TabContainer

**Comment by unazko** [comment]
Hello @dimitar-trendafilov,

The described behavior is by design.
In order to navigate between the tabs you could use the arrow left, arrow down or arrow up, arrow down keyboard keys.
If focus is on the tab container item then by pressing the Tab keyboard key focus will move to the next interactable element outside of the tab contaier.

Best Regards,
Boyan
