### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by darshanmarathe** [SAP/ui5-webcomponents#3702]
[This package](https://www.jsdelivr.com/package/npm/@ui5/webcomponents) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by fifoosid** [comment]
Hi @darshanmarathe 

All of our packages don't have a default file, because we don't target CDN usage. We don't even publish a bundle with all of our components. The reason for that is simple. If you import a bundle with all our components it will be quite huge. From this huge bundle, an application developer will only use just a couple of components which will lead to loading a lot of code without the need for it to be loaded at all.

The best approach is to use bundler(for example webpack, rollup...), install the needed package/s and import the used components. This way you will only bundle what is used in your app.
