### ISSUE TITLE
FileUploader changeEvent won't be triggered if i choose the same File twice

### ISSUE THREAD

**Issue by meierfelix2001** [SAP/ui5-webcomponents#3728]
### **Bug Description**
I want to upload the same file using <UI5-file-uploader> twice, but the change-Event is not triggered the second time. 
In my use cause I want to overwrite the first uploaded file with the second file.

### **Expected Behavior**
Uploading should be possible even if the file has been uploaded before. 
-> The change event should also be triggered when the same file is selected again.

### **Steps to Reproduce**
1. Go to the File Uploader
2. choose a File
3. Upload
4. Open File Uploader again
5. Choose the Same File
6. -> the Change event from the File Uploader won't be triggered

### **Context**
- UI5 Web Components version: {1.0.0-rc.15}
- OS/Platform: {Windows 10}
- Browser: {Edge - Chromium}
- Affected component: {File-uploader}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-b I am forwarding this issue to you in order you to check, whether this is an issue with the FileUploader or it is an expected behavior.

The problem is that, when you once upload a given file and immediately after that you try to upload again the same file (with the same name), it is not possible and the change event is not triggered. The only way you can upload again the same file is to open the FileUploader, click Cancel, and then once again open and upload the file.

Thanks and regards,
Iliana

**Comment by a-z-ivanov** [comment]
Hello @meierfelix2001,

The event name suggests that the filename should be changed before the event is fired. So, this is the expected behaviour.
The normal workflow in your case should be what Iliana suggested, to cancel and re-select the file.

Regards,
Alex
