### ISSUE TITLE
[SF][Popover]: Support margin config for the Popover

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents#3748]
**Is your feature request related to a problem? Please describe.**
As the screenshot shown, the popover lean tightly on the scroll bar, there is no space between them.
Is it possible to add margin config for the popover, please?
![image](https://user-images.githubusercontent.com/1614528/131109335-7e8fb3ba-df7f-48a9-b486-9a05f0022164.png)
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gmkv** [comment]
Hi @ericchan1983 

I see that the popover has a blocker layer below it, which leads me to believe it is "modal".
That scroll would not be clickable regardless of whether or not the popover is covering it.

Still, it looks like a visual bug on the screenshot, because the Popover has a 10px margin from the edges of the viewport.

Would you be able to re-create the issue in an isolated example with [codesandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)? A [sample in React](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34?file=/src/App.js) would work too.

Feel free to reach out to me in our internal comms on Teams or Slack.

Kind regards,
Georgi Minkov
