### ISSUE TITLE
[Android] Slider / RangeSlider tick marks and scale not responsive

### ISSUE THREAD

**Issue by hristop** [SAP/ui5-webcomponents#3793]
### **Bug Description**
Upon orientation change, the tick marks of the RangeSlider scale are not recalculated, which either leaves the component without scale or makes it so that the labels of the scale overlap.
Check the gif below (focus on the RangeSlider with tick marks and labels):
![RangeSliderScale](https://user-images.githubusercontent.com/14230119/131693963-ee93e886-8ae7-45c9-9768-19e6920c791a.gif)

### **Expected Behavior**
The scale should be responsive.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/RangeSlider/
2. Scroll down to the example of RangeSlider with Tick marks and Labels
3. Change the orientation of the device.

### **Context**
- UI5 Web Components version: master
- OS/Platform: Android 11, Samsung Galaxy Tab S7
- Browser: Chrome
- Affected component: RangeSlider

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
Hello Colleagues,

I have tested the reported issue on iPad, iPhone, Android Phone and Android tablet and it is not reproducible. When in portrait mode, the labels are hidden as expected, because there is not enough space, then changing again the orientation to landscape, they are visible again. 

Kind Regards,
Niya
