### ISSUE TITLE
ui5-messagestrip: Wrong alignment in RTL mode

### ISSUE THREAD

**Issue by elenastoyanovaa** [SAP/ui5-webcomponents#3812]
### **Bug Description**
The Message Strip has wrong alignment, when in RTL mode.
<img width="530" alt="Screenshot 2021-09-02 at 14 13 31" src="https://user-images.githubusercontent.com/11913394/131834116-c38a3e39-8738-4690-b413-bd59e88b0628.png">

### **Expected Behavior**
<img width="525" alt="Screenshot 2021-09-02 at 14 13 16" src="https://user-images.githubusercontent.com/11913394/131834140-190fc908-bacf-4935-b40c-b74925f0ec8e.png">

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
Hello Colleagues,

I think that the issue was reported as a result of a wrong testing -  adding dir="rtl" to the body in the developer tool and the components are not re-rendered, because in the playground, if you change the direction to rtl, the issue is not reproducible. Also, I checked the test page locally, adding the attribute to the body and the issue is not reproducible as well.

Kind Regards,
Niya
