### ISSUE TITLE
[ComboBox][A11Y]: Required ARIA attributes must be provided

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3827]
**Isolated Example**
![image](https://user-images.githubusercontent.com/78520316/131938017-2fa5c42f-d6d8-4403-b3be-92e883af0365.png)
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to https://qacand.hcm.ondemand.com/sf/omp?_s.crb=E4onb4sgvMm9KCThiv%252bbNf3m7hGdAJQZKh5vDU%252bTQ2s%253d#/manage
2. click "My Postings"
3. open Axe Devtools to scan page.

**Expected behavior**
no a11y issue

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.16
`@ui5/webcomponents-react` version: 0.131.16
Operating System:
Browser:

**Additional context**

**Comment by sfsf-xweb-sh** [comment]
Hi @Shtilianova 
Please promote this ticket's priority to high 
thanks

**Comment by elenastoyanovaa** [comment]
Hello @sfsf-xweb-sh ,

We are aware of this issue and other issues, related to setting relationships between accessible elements via IDrefs. Setting IDRef relationships are currently not possible due to the nature of the custom elements and their shadow DOM. The issue is present not only for UI5 Web Components, but for every framework creating custom elements and using shadow DOM. This is a gap in the accessibility support and there is a working draft for a new AOM (Accessibility Object Model), which addresses this issue and many more and aim a better, JS based accessibility support for all web element.

You can check the working draft here https://github.com/WICG/aom and the w3c specification here https://wicg.github.io/aom/spec/ (again draft). What is more, you can check out there explainer and see that https://wicg.github.io/aom/demos/#12 Issue 2 references the use case you mentioned and is one of the main issues, which lead to creating the AOM. In future, when this becomes complete and has support for all main browsers, we will have the possibility to adapt the components and make sufficient enhancements in the accessibility support, but until them we do not have any possibility to set there kind of relationships.

What is more, aria-controls does not affect the speech output and there will be no change in the usage of the element with or without the attribute and screen reader users will not be affected.

Thanks for understanding!

Kind Regards,
Elena
