### ISSUE TITLE
DatePicker react component `ref` current value issues

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#3832]
### **Bug Description**
DatePicker react component `ref` current value issues:
Example: <DatePicker ref={calendarRef} onChange={calendarHandler} />
1) When user changed date, then "calendarRef.current.value" is not current. It is showing previously selected value.
2) When user removed date, then "calendarRef.current.dateValue" is not null. It is showing previously selected value.

Issue was not present with below version
"@ui5/webcomponents": "0.31.14",
 "@ui5/webcomponents-base": "0.31.14"

### **Expected Behavior**
1) When user changed date, then "calendarRef.current.value" should be current
2) When user removed date, then "calendarRef.current.dateValue" should be null

### **Steps to Reproduce**
1. Go to 'https://codesandbox.io/s/immutable-mountain-syp5t'
2. Pick date from date picker
3. Check console.log for {ref} Values.

### **Isolated Example**
https://codesandbox.io/s/immutable-mountain-syp5t'

### **Context**
"@ui5/webcomponents": "0.31.16",
 "@ui5/webcomponents-base": "0.31.16",
- OS/Platform: Any
- Browser: Any
- Affected component: DatePicker

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2021-09-03 at 7 15 32 PM](https://user-images.githubusercontent.com/67934622/132079128-ea54784f-e2c8-4d2b-bbb7-23370658ea10.png)
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}
- Bussiness impact: {This issue is impacting our validation logic}

**Comment by fifoosid** [comment]
FYI @SAP/ui5-webcomponents-topic-b

**Comment by a-z-ivanov** [comment]
Hello @pankajpandey01 ,

Some time ago we made a feature for the DatePicker, this event to be preventable, meaning that you may choose to no change the value. Since, this preventing also happens in the event handler, then the component value is not changed yet. We understand that this behaviour happens to be a breaking change and we are truly sorry. The good news is that there is an alternative. You could simply use `ev.detail.value` as the future value.

Regards,
Alex
