### ISSUE TITLE
ComboBox: missing aria attributes

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#3925]
**Describe the bug**
Ensures elements with ARIA roles have all required ARIA attributes
`ui5-combobox #ui5-combobox-input`

**Isolated Example**
https://codesandbox.io/s/suspicious-fog-bwk9w?file=/src/App.js
**To Reproduce**
1. Go to https://codesandbox.io/s/suspicious-fog-bwk9w?file=/src/App.js
2. Verify with axe DevTools in chrome

**Expected behavior**
Elements with ARIA roles have all required ARIA attributes

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/133277275-1a2b19b5-d42b-4c30-9f02-51b993ca70c9.png)
![image](https://user-images.githubusercontent.com/5724592/133277323-29aa9cf8-8ad0-47e5-86d0-e7bb619a6410.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.17
`@ui5/webcomponents-react` version: 0.131.17
Operating System: MacOS
Browser: Chrome

**Additional context**
I am from SAP Successfactors, currently in our project we are using the ComboBox control, and our accessibility expert reported this issue before release A11y checking. Could you please help to fix? Thanks.

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-rl I checked the OpenUI5 ComboBox and it sets "aria-controls" once the dropdown opens, while the ComboBox component does not seem to set it at all. I guess we should add aria-controls pointing the the dropdown list as in OpenUI5

**Comment by niyap** [comment]
Hello @sleric1024  ,

The issue is already reproted: #3827

We are aware of this issue and other issues, related to setting relationships between accessible elements via IDrefs. Setting IDRef relationships are currently not possible due to the nature of the custom elements and their shadow DOM. The issue is present not only for UI5 Web Components, but for every framework creating custom elements and using shadow DOM. This is a gap in the accessibility support and there is a working draft for a new AOM (Accessibility Object Model), which addresses this issue and many more and aim a better, JS based accessibility support for all web element.

You can check the working draft here https://github.com/WICG/aom and the w3c specification here https://wicg.github.io/aom/spec/ (again draft). What is more, you can check out there explainer and see that https://wicg.github.io/aom/demos/#12 Issue 2 references the use case you mentioned and is one of the main issues, which lead to creating the AOM. In future, when this becomes complete and has support for all main browsers, we will have the possibility to adapt the components and make sufficient enhancements in the accessibility support, but until them we do not have any possibility to set there kind of relationships.

What is more, aria-controls does not affect the speech output and there will be no change in the usage of the element with or without the attribute and screen reader users will not be affected.

Thanks for understanding!

Kind Regards,
Niya
