### ISSUE TITLE
Very unlucky event name `selection-changed` in `Table.js`

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#3968]
### **Bug Description**
According to the documentation a table will fire a `selection-changed` event in MultiSelect or SingleSelect mode. This event will never arrive on the parent dom nodes.

The default config does not allow this event.

```js
"noConflict": {
                "events": ["selection-change", "header-click"]
            }
```

Removing selection-change in the config will enable this event on a lot of other components.
 
### **Expected Behavior**
Having a event like documented, while using the default configuration.

### **Context**
- UI5 Web Components version: RC15, next
- Affected component: Table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues in @SAP/ui5-webcomponents-topic-core ,
can you, please, advice on this request?

Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by fifoosid** [comment]
Hi @veith 

In order to understand how noConflict configuration setting works you can read [here](https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/#noConflict) (section noConflict). The main idea is that events fired from UI5 Web Components will not collide with events coming from other sources.

In a nutshell, If the event is added to the list of noConflict events, it means that it won't be fired as ```selection-change```, but as ```ui5-selection-change``` only.
