### ISSUE TITLE
[Urgent - WithIn One Week][SF][UI5-List][A11y] accessibleName ,accessibleNameRef ,accessibleRole is not available in ui5-list component ( 0.31.18 )

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#3973]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Bug Description**
accessibleName ,accessibleNameRef ,accessibleRole is not available in ui5-list component ( 0.31.18 )
The above attribute is available in RC.15 but not available in 0.31.18
We need these attributes to finish a11y function

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 
I downported the accessibleName, accessibleNameRef, accessibleRole to 0.31 with this [commit](https://github.com/SAP/ui5-webcomponents/commit/e84a3fa84a32d30eb3b59632f2433f9fcf65e5fb)

Note: the List's default role is "list" and you can change it via "accessibleRole", but the default role of the list items is "listitem", which is not currently configurable. So, if you plan to use a different role for the List component (other than  "list"), you might have a11y issues, because the role of the list items won't be compliant any more.

Can you share your use-case, do you need to also change the role of the list items?

**Comment by ilhan007** [comment]
Fixed with 0.31.19
