### ISSUE TITLE
[SF][Input] input event is triggered twice for each keystroke in FireFox

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#3982]
### **Bug Description**
In FireFox, `input` event is triggered twice for each keystroke.

### **Expected Behavior**
`input` event should be triggered just once for each keystroke.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-gd37n?file=/index.html
2. Input some characters in the input box
3. Notice the console log

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-gd37n?file=/index.html

### **Context**
- UI5 Web Components version: 0.31.18
- OS/Platform: macOS
- Browser: FireFox
- Affected component: ui5-input

### **Log Output / Stack Trace / Screenshots**
![Screen Shot 2021-09-23 at 6 19 44 PM](https://user-images.githubusercontent.com/1751846/134491467-f5770fc6-8f3e-4fd4-8b74-3a1cafe2992c.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @SAP/ui5-webcomponents-topic-rl ,
can you, please, take a look at this issue?
I reproduced it with version 0.31.18 and master as well, on FF on Windows OS.

Kind regards,
Petya Markova.
(UI5 Developer)

**Comment by d3xter666** [comment]
Hi colleagues,

This issue is a core issue rather than in the control itslef. The thing is that Firefox also sends the "native" event for the inner input.

This could be proven in a simple way:
- Get the WebComponents project locally
- Change the name of the "input" event in Input.js. For example, "input2"
- On the samples page subscribe to both of the events and put a debugger inside the event listener

**Observed results:** Both events are triggered and when you inspect the stack trace, you'd notice that the one is coming from the Web Components project and the other from the browser.

<img width="794" alt="Screenshot 2021-09-27 at 14 53 05" src="https://user-images.githubusercontent.com/3379948/134903111-794640ff-54ab-4538-9fac-a9d35c8c5773.png">

<img width="803" alt="Screenshot 2021-09-27 at 14 53 45" src="https://user-images.githubusercontent.com/3379948/134903049-e8d1c0c6-6f56-452f-90b3-d52fcd8235c9.png">

IMHO, this should not be considered as a Very High Priority issue as:
- the issue seems to be browser dependent
- it could be easily worked around by debouncing.

Cheers

**Comment by d3xter666** [comment]
Hi colleagues,

This issue is a core issue rather than in the control itslef. The thing is that Firefox also sends the "native" event for the inner input.

This could be proven in a simple way:
- Get the WebComponents project locally
- Change the name of the "input" event in Input.js. For example, "input2"
- On the samples page subscribe to both of the events and put a debugger inside the event listener

**Observed results:** Both events are triggered and when you inspect the stack trace, you'd notice that the one is coming from the Web Components project and the other from the browser.

<img width="794" alt="Screenshot 2021-09-27 at 14 53 05" src="https://user-images.githubusercontent.com/3379948/134903111-794640ff-54ab-4538-9fac-a9d35c8c5773.png">

<img width="803" alt="Screenshot 2021-09-27 at 14 53 45" src="https://user-images.githubusercontent.com/3379948/134903049-e8d1c0c6-6f56-452f-90b3-d52fcd8235c9.png">

IMHO, this should not be considered as a Very High Priority issue as:
- the issue seems to be browser dependent
- it could be easily worked around by debouncing.

Cheers
