### ISSUE TITLE
UI5Element: set focus on keyboard handling  only

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#3986]
### **Feature Request Description**
We would like to set focus over the focusable web components only on pressing keyboard keys. Currently we apply focus upon mouse interaction (click) as well. So, we would have to distinguish between these two cases and apply focus outline only in the first case.

### **Proposed Solution**
Handle this on UI5Element level  so all the components can benefit right away.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by boghyon** [comment]
Is there a consideration to make use of the [`:focus-visible` pseudo class](https://drafts.csswg.org/selectors/#the-focus-visible-pseudo) for this? I requested it originally at https://github.com/SAP/openui5/issues/1289#issuecomment-289203290. The `:focus-visible` (formerly `:focus-ring`) would help improving:

* Consistency of the ring visibility across the web platform.
* Accessibility for physically or visually impaired people, enabling them to make the focus ring always visible depending on their system (OS or browser) settings.
* (And more)

### Browser support `:focus-visible`
* Firefox, Chromium: ✔
* Safari: implemented but yet to be enabled by default (currently behind a flag) [according to Igalia](https://blogs.igalia.com/mrego/2021/06/07/focus-visible-in-webkit-may-2021/) in May 2021.

### Sample
1. Open https://jsbin.com/roputeb/edit?html,css,output on **Windows or Android** using a **Chromium**-based browser or **Firefox**.
2. We can see that elements styled with `:focus-visible` display the focus ring according to browser's heuristics which is basically:
   * Display the focus ring *always* if keyboard.
   * Display the focus ring *sometimes* if clicked on `<input>` or `<select>`. Otherwise, no focus indicator on click.


Any thoughts?

**Comment by ilhan007** [comment]
Hello @boghyon actually we will use [:focus-visible pseudo class](https://drafts.csswg.org/selectors/#the-focus-visible-pseudo) as suggested by you. Thanks for the interest. Finally, we are about to put this in progress.

**Comment by ilhan007** [comment]
After the initial research and the followed discussions , we decided to make use of the CSS `:focus-visible` solution and not implementing framework level solution, but implement the requirement in the components as much as possible.

The progress of the topic can be tracked in the following issues distributed by area of component ownership:
https://github.com/SAP/ui5-webcomponents/issues/5745
https://github.com/SAP/ui5-webcomponents/issues/5748
https://github.com/SAP/ui5-webcomponents/issues/5749
https://github.com/SAP/ui5-webcomponents/issues/5752

**Comment by boghyon** [comment]
@ilhan007 I enhanced the above JSBin sample (https://jsbin.com/roputeb/edit?html,css,output) with the case where users can move the focus programmatically but forcing the `focus-visible` style to apply (e.g. to immediately indicate the moved focus). This use case was first proposed in https://github.com/whatwg/html/issues/7830 which landed on the HTML spec [focus option focusVisible – HTML Standard (whatwg.org)](https://html.spec.whatwg.org/#dom-focusoptions-focusvisible:~:text=If%20the%20value%20of%20the%20focusVisible%20dictionary%20member%20of%20options%20is%20true%2C%20or%20is%20not%20present%20but%20in%20an%20implementation%2Ddefined%20way%20the%20user%20agent%20determines%20it%20would%20be%20best%20to%20do%20so%2C%20then%20indicate%20focus.):

> If the value of the `focusVisible` dictionary member of options is `true`, or is not present but in an implementation-defined way the user agent determines it would be best to do so, then indicate focus.

### Browser Support <code>myElement.focus({ <strong>focusVisible: true</strong> })</code>

* Firefox: ✔
* Chromium: ✔ (Chromium issue #<del>40834435</del> --> [462191849](https://issues.chromium.org/issues/462191849))
* Safari: ✔ (WebKit bug #[242456](https://bugs.webkit.org/show_bug.cgi?id=242456))
