### ISSUE TITLE
Documented Events do not traverse a shadow root border

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#4037]
### **Bug Description**
Using lit2 the "normalEvent" events from Ui5Element do not "bubble" across  a shadow root border. This is because the normalEvent have set `composed: false`. 

### **Expected Behavior**
Documented events which should bubble, should also bubble through the parent components. Like they did with older versions of lit-element.

It is much more efficient to write a event delegation like this:

```js
this.addEventListener("detail-click", (e) => {
      alert("detail-clicked on a list item");
    });
```

instead using a query selector or getElementById to find the element first and attach the event on the result.

### **Steps to Reproduce**
1. click on any enabled item on the isolated example

### **Isolated Example**
https://codesandbox.io/s/events-not-composed-ff6qn?file=/src/component.js

### **Context**
- Lit 2.0.0
- UI5 Web Components version: RC15
- OS/Platform: MacOS, maybe any 
- Browser: latest chrome, latest safari and latest firefox
- Affected component: ALL

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### Suggestion

@vladitasev Please change the normalEvent in UiElement to *(preffered variant)*: 
```js
const normalEvent = new CustomEvent(name, {
			detail: data,
			composed: true,
			bubbles,
			cancelable,
});
```

or make the behavior configurable like the noConflict exclude list.

**Comment by maltenorstroem** [comment]
In the case of higher value compositions, it is important that the events of the assembled components bubble over the shadow root borders. Otherwise, each event must be dispatched under a new event name.

It is not clear from the component documentation whether the event bubbles and have set composed=true.

I would very much welcome an adjustment.

**Comment by vladitasev** [comment]
Hello @veith , @maltenorstroem 

I don't understand what you mean by:
*Using lit2 the "normalEvent" events from Ui5Element do not "bubble" across a shadow root border. This is because the normalEvent have set composed: false.
.....
Like they did with older versions of lit-element.*

Events have never been `composed` in UI5 Web Components, regardless of the `lit-html` version we have used (if that's what you mean). I don't know of any change from lit-html 1 to 2, related to events. 

Composed events are "risky" in a sense that the shadow DOM is supposed to be a black box for the user of the web component, and it should not emit events, dependent on its inner workings. 

**Problem 1: an event might be fired several times**
Imagine the following scenario: You always dispatch events with `composed: true`. You have 3 levels of web components, nested into each other's shadow roots. The innermost one dispatches the `selection-change` event, then the middle one listens for it, and in turn dispatches `selection-change`, and finally the outermost component (the one the user is seeing) also listens for `selection-change` and upon it, dispatches the documented `selection-change` event. If an application developer does `addEventListener("selection-change", listener)` they will have their `listener` function executed 3 times, instead of the expected 1.

**Problem 2: events by inner components "leak" as an API**
You have `composed: true`. You build a web component that uses internally in its shadow root `ui5-select`. `ui5-select` fires a `select` event. Your web component listens for `select` and fires `selection-change` which is the official documented event of your web component. The app however subscribes to the `select` event, because it is `composed` and it is usable from the outside. Then however, you rework your web component and use internally not `ui5-select`, but `ui5-combo-box`, which fires not `select`, but let's say `change` event. Your component now listens for `change` and upon it, fires `selection-change` (again the documented event). The app will break although you did not change any public APIs. However, the internal implementation (`change` vs `select` events) leaked and became an implicit API for the app.  

In summary: the implementation inside shadow roots is "reserved" and not an API. If events are `composed: true`, we can never change the underlying implementation, because apps would rely on this behavior. For this reason, if you create a web component that composes other web components, the best practice is to listen to their events, and fire a documented public event that is guaranteed to never change (contrary to the shadow root implementation which may). There is a reason `composed` is `false` by default in the `EventConstructor` object (not only `UI5Element.js`). 

Now to your use case: I would strongly recommend you do not rely on composed events in your code, but rather build your web components in a way does not rely on events "leaking" through shadow roots, as an API. 

If you insist though, we can create some sort of configuration setting for you and you'll be able to turn it on for your use case. I did so quickly, to test the consequences, and I found some event handlers being called more times than expected already, which means that certain components might behave strangely.

Let me know what you think

Regards,
Vladi

**Comment by veith** [comment]
hi @vladitasev 

Thank you for the detailed response. 

Your points are **absolute correct**!

The strange thing is, that with older version of lit-element, i received every event, regardless if they were composed or not. By switching to lit2 i came from a noisy environment to an absolute silent environment.

I have done some tests and found a trivial solution. Instead of doing `this.addEventListener` i can do `this.shadowRoot.addEventListener`. With this simple change i can receive the UI5 events again.

Maybe some events from UI5 are important/interesting enough to have a `composed:true` setting, but this would be a different discussion topic.
