### ISSUE TITLE
ui5-shellbar, ui5-tabcontainer: add more stable selectors

### ISSUE THREAD

**Issue by JarrettChan** [SAP/ui5-webcomponents#4130]
### **Feature Request Description**
We would like stable selectors on any element as it makes sense to them put on.

### **Proposed Solution**
Add data-ui5-stable to ui5-shellbar elements:
1. `.ui5-shellbar-menu-button` Navigation/Mega Menu Button
2. `.ui5-shellbar-search-button` Search Button
3. searchField mobile view "Cancel" button
4. Shellbar items in the overflow popover

Add data-ui5-stable to ui5-tabcontainer elements:
1. left, right scroll buttons
2. overflow button
3. overflow dropdown items

Fix ui5-tabcontainer overflow ui5-button selector:
```		const button = this.overflowButton[0] || this.getDomRef().querySelector(".ui-tc__overflowButton > ui5-button");```
- switch to something stable like pure tag

### **Additional Context**
Previous request https://github.com/SAP/ui5-webcomponents/issues/1840

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by codefactor** [comment]
@ilhan007 ,
Here is a PR that you might use to get started on this one:
https://github.com/SAP/ui5-webcomponents/pull/4369

I didn't add stable selectors to the following places, though:
1. Shellbar overflow menu items
2. TabContainer overflow menu items

These are only nice to have for now, since they are not as straight forward to just add some stable selectors I didn't bother. EnableNow presumably can't really select for elements in a menu because the menu will disappear any time you click on enable now anyway, so it can't highlight those.

**Comment by codefactor** [comment]
One other thing - regarding what @JarrettChan wrote in the description:

> Fix ui5-tabcontainer overflow ui5-button selector:
> const button = this.overflowButton[0] || this.getDomRef().querySelector(".ui-tc__overflowButton > ui5-button");
> switch to something stable like pure tag

This appears to already be done.

Can you down-port the following change to 0.31?
https://github.com/SAP/ui5-webcomponents/commit/24ff1458020fb1ba1fa023fcfd33bf71132c7748

Thanks!

**Comment by ilhan007** [comment]
Fixes and Released.
