### ISSUE TITLE
Add min and max for Input with type number

### ISSUE THREAD

**Issue by d-schroeder** [SAP/ui5-webcomponents#4209]
Hi all,

Currently there seems to be no way to limit the value range of number type inputs. Having this would be a great help.

Using inclusive min and max parameters on a number-type input should limit the acceptable value range of the input.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Comment by d-schroeder** [comment]
Hello @MapTo0,

unfortunately the step input doesn't fit for our use case due to size limitations and logic discrepancies. Is the implementation of min and max restrictions for the number type inputs possible and realistic?

Kind Regards,
Daniel

**Comment by texttechne** [comment]
Hi @MapTo0,

I would challenge the categorization into "feature request". This is a bug, and a quite huge one in my opinion, since we're not getting a basic HTML feature: See [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#max). It's like not providing the "maxLength" attribute for regular inputs...

Any plan to implement this? This has a really high priority for us.

**Comment by lastmjs** [comment]
I just ran into the same desire, but the step input should work for me. That being said, I would expect the basic input type="number" attributes to work for `ui5-input`.

**Comment by hristop** [comment]
Hi @d-schroeder ,

Can you please let us know more information about your use case and why / what exactly makes the step input not applicable for it? 

Best Regards,
Hristo

**Comment by texttechne** [comment]
My use case is a custom component. But does it really matter?
As @lastmjs put it
>  I would expect the basic input type="number" attributes to work for ui5-input

If you don't support such attributes, then you're automatically limiting the possible use cases of that control.
Since WebComponents can be used quite freely in any technology it should be open for such scenarios. I also think that this is a different situation for WebComponents in contrast to UI5: In UI5 limiting the components makes sense, but WebComponents can be used as building blocks...

So instead of asking whether any particular use case is covered by any other component, components should support all HTML attributes / properties. Then they are truly open for use cases never even imagined in the beginning. I firmly believe that this should be the guiding principle for WebComponents: Being open for stuff that your users are about to invent / create.

**Comment by hristop** [comment]
Hi @texttechne ,

If you are developing custom component, why not extend the ui5-step-input as it already has the properties you need or implement them in the custom component? 

We have discussed this request with our architects and for now we do not see need to implement this in the input component when there is alternative already available. 

Best Regards,
Hristo
