### ISSUE TITLE
[SF][UI5-FlexibleColumnLayout][BUG][Medium] Visual issue - need to follow the Fiori guidelines

### ISSUE THREAD

**Issue by Joycelin02** [SAP/ui5-webcomponents#4213]
### **Bug Description**
Visual issue - need to follow the Fiori guidelines

### **Expected Behavior**
Please follow [Fiori Specs](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2043272416) for FlexibleColumnLayout. The current react component for padding, header background color and font size are not correct.

### **Isolated Example**
Fiori specs: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2043272416
Fiori sample: https://sapui5.hana.ondemand.com/#/entity/sap.f.FlexibleColumnLayout/sample/sap.f.sample.FlexibleColumnLayoutWithOneColumnStart

Current react component: https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--default-story

### **Context**
- UI5 Web Components version: {1.92}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {Flexible Column Layout}

### **Log Output / Stack Trace / Screenshots**
<img width="1658" alt="MicrosoftTeams-image (24)" src="https://user-images.githubusercontent.com/93315255/139228693-33f4e797-d675-4af7-b790-c6e32e017921.png">
React versus Fiori specs guidelines

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP Success Factors}
- Bussiness impact: {Assignment 2202}

**Comment by Joycelin02** [comment]
> Hey @Joycelin02
> 
> Isn't that setting of the Toolbar component? Check the `design` property of the [Toolbar API](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-toolbar--default-story)
> 
> The application needs to set the design and follow the guideline.
> 
> Regards, Martin


Hi @MapTo0, 

Thanks for your feedback. However, there is nothing to do with the Toolbar component. What I mean is the [FlexibleColumnLayout](https://sap.github.io/ui5-webcomponents-react/iframe.html?id=layouts-floorplans-flexiblecolumnlayout--default-story&viewMode=docs#flexiblecolumnlayout-with-different-columns) component. You can click on one of the list items to open the next column. 

As you can see, the background color for header is white, not grey color. Also, there is no divider between header and avatar. Please see Fiori guideline: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2043272416

 
![FlexibleColumnLayout](https://user-images.githubusercontent.com/93315255/139635174-e32117af-a8ca-479b-aaab-21e573e558ee.jpg)
Thank you Martin!

Joyce

**Comment by ilhan007** [comment]
Hello @Joycelin02, the visual part of the FlexibleLayout web component is just the arrows between the columns, nothing else. The app developers set the content for each column, sometimes they can use other web components, or pure DIVs.

Perhaps, you can look at the [DynamicPage React component](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--default-story), that UI5 Web Components For React provides - as it follows the guidelines you are referring to.
Otherwise, if pure HTML elements are used, it is up to the app developers set the proper background color and implement the floor-plan. If you don't use the [DynamicPage](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--default-story), or you can't for some reason, we can assist with finding the required CSS parameters, so the app developers have to apply on your side .

BR,
ilhan
