### ISSUE TITLE
Pixelated icons in shellbar 

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#4334]
### **Bug Description**
The icons in the shellbar appear more pixelated than the ui5 version of the component, especially the round edges.

UI5
![Screen Shot 2021-11-12 at 2 52 13 PM](https://user-images.githubusercontent.com/24360164/141592633-200cd633-a31d-49dd-8da1-0da5a9448969.png)

Web Component
![Screen Shot 2021-11-12 at 2 52 04 PM](https://user-images.githubusercontent.com/24360164/141592569-998b5d00-d994-4094-ac28-6464615cbe21.png)

images from customers:

UI5
<img width="209" alt="Screen Shot 2021-11-17 at 11 12 11 AM" src="https://user-images.githubusercontent.com/24360164/142267030-eb9c9ae5-c488-445a-817b-dc0bac92c56b.png">

Web Component
<img width="291" alt="Screen Shot 2021-11-17 at 11 11 32 AM" src="https://user-images.githubusercontent.com/24360164/142267154-9a1b10a7-8b7e-4cf7-919d-ef157fd0ac27.png">

### **Expected Behavior**
The icons should be equally clear in both version of the shellbar.

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/
2. Go to https://sapui5.hana.ondemand.com/#/entity/sap.f.ShellBar/sample/sap.f.sample.ShellBarWithSearch
3. Compare the icons in the header and notice the web component version appears to have rougher edges

### **Context**
- UI5 Web Components version: any
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Shellbar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

- Organization: SuccessFactors
- Bussiness impact: Multiple customer complaints after upgrading to web component version of the shellbar.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-p I am forwarding this issue to you, in order to check whether something could be done to make the svgs' edges more smooth-looking.

Regards,
Iliana

**Comment by pskelin** [comment]
The SVG icons we use are extracted from the icon font in UI5. In the icon font, the icons are drawn on a 512x512 grid (that is what the designers used when creating the individual icons).

The default ui5-webcomponents icon size however is 16x16, so the browser has to apply a downscaling algorithm and this causes some anti-aliasing. This makes the icons look blurred instead of crisp.

Here is one icon drawn at 16x16 and zoomed in to see the actual pixels:
<img width="467" alt="Screenshot 2021-11-23 at 9 55 18" src="https://user-images.githubusercontent.com/11073377/142988483-a15bd50d-c3f1-4639-b365-307f42a57427.png">

Here is the same icon drawn at 160x160 and no zoom (the browser has plenty of room to display it fine).
<img width="176" alt="Screenshot 2021-11-23 at 9 54 29" src="https://user-images.githubusercontent.com/11073377/142988511-202d44ab-4370-4558-a16b-fe1ae5d031bb.png">


The same problem should be apparent with the icons in UI5 (they use the exact same data and exact same 512x512 grid). The effect you report is probably dependent on the Operating system and what downscaling algorithms it applies to SVG and to fonts.

The real solution is to get a new design of all icons that is pixel perfect for a 16x16 grid. I will take this to the designers team, but this will probably be a huge undertaking, so don't expect anything soon.

**Comment by pskelin** [comment]
@ee92 can you share the browser and operating system of the second set of photos? possibly the kind of monitor these pictures were taken on? We might try some hand-crafted optimi`ations for often used icons, but on a Mac (like you reported) there is hardly any visible change.
