### ISSUE TITLE
Fix validation for date picker and date range picker components

### ISSUE THREAD

**Issue by Flora-manda** [SAP/ui5-webcomponents#4409]
### **Bug Description**
When I use a different format pattern on the date range picker or even date picker component, yyyy-MM-dd, and I change the month MM to an invalid month, say 17 or anything above 12, the component automatically changes to another date entirely and doesn't through an error. With the default format of Apr 1, 2021, it throws an error if I changed "Apr" to let's say "Rec". But not with this yyyy-MM-dd format.

### **Expected Behavior**
It should throw an error and say invalid entry.

### **Steps to Reproduce**
See above description and try it out with sandbox here: https://codesandbox.io/s/ui5-webcomponents-forked-8jmhr?file=/index.html

- Affected component: Date picker and date range picker (maybe any date component as well)

### **Priority**
- [x] Medium

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by gmkv** [comment]
Hello @SAP/ui5-webcomponents-topic-b 
There's an issue with the DatePicker component where entering value over the limit (`12` for months, `31` for days, etc.) would result in the date being changed, instead of reporting an invalid value.

https://user-images.githubusercontent.com/22086365/144384848-f7ddef17-c365-4b2c-abdc-3e842342e064.mov

[Sample here](https://codesandbox.io/s/ui5-webcomponents-forked-t0gw8?file=/index.html)
This behaviour doesn't occur in OpenUI5.

Please validate if the other date related components may have a similar issue.
Regards,
Georgi
