### ISSUE TITLE
[SF] [Link] Support rel for Link

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents#4436]
According to security requirements, rel="noopener" should be set to Link.  rel isn't supported right now.

**Comment by terezamch** [comment]
Hello @ChristyFei ,

I see that the issue comes from SF, so I have recognised the organisation. That is fine, but I will encourage you to follow our issue opening template and fill the organisation filed too in order make it easier for our dispatchers to recognise the impact of the issue and set the priority accordingly.

Thanks in advance!



Dear @SAP/ui5-webcomponents-topic-b ,

The issue could be reproduced in the playground with the first example https://sap.github.io/ui5-webcomponents/playground/components/Link/
The rel attribute has "noreferrer" value but does not have "noopener". 

Could you please take over?



Best regards,
Tereza

**Comment by unazko** [comment]
Hello @ChristyFei,

According to the following status document:
https://www.chromestatus.com/feature/6140064063029248
As of Chromium version 88, anchors with target="_blank" automatically get noopener behavior by default. Explicit specification of rel="noopener" helps protect users of legacy browsers including Edge Legacy and Internet Explorer.

Also according to the following specification regarding the "noreferrer": https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer
- rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
- rel="noreferrer" has the same effect but also prevents the Referer header from being sent to the new page. 

The ui5-link's anchor tag contains the noreferrer rel attribute, which should be enough to ensure security when navigating to a cross origin location. I've tested with IE version 19042.1348 and Firefox version 94.0.2 that window.opener is undefined.

Are you able to reproduce a vulnerability at your side in this regard?

Best Regards,
Boyan

**Comment by ChristyFei** [comment]
Hi Boyan,

Thanks for sharing this information. 

Christy
