### ISSUE TITLE
 2.0 suggested changes

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#4460]
## **Background**
This issue  lists all deprecated APIs and all APIs that we would like to improve and change before releasing next major version (2.0).

## **Deprecated modules**
- Assets-static.js in several packages should be removed

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation: Remove Assets-static.js from all packages

## **@ui5/webcomponents-base**

**Changes under discussion**:

- Remove fallback to default value 
- check and rework defaultValues of property types, input.value doesn't have default and it accepts null/undefined
- properties of type `Object` have `{}` by default, probably `undefined` will be a better default.
- Check `"allowList"` array and remove/rename properties if needed
- Revise all the events that have stopped bubbling. 

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation: CSP Support will be supported out of the box via the adopted stylesheets that are now supported everywhere.

### UI5Element

**Changes agreed**:
- [ ] [enhancement] Enable dynamic load of dependencies
- [ ] :exclamation: [breaking] :exclamation: Remove static get **render** (to be replaced by `renderer`)
- [ ] :exclamation: [breaking] :exclamation: Remove `getStaticAreaItemDomRef` as obsolete

### UI5ElementMetadata

**Changes under discussion**:
- Remove `processChildren`

**Changes agreed**:
- [ ] [enhancement] `manageSlot` to become per slot
 
### Device

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation:  Remove the `Device#isIE()` method
 
### Static Areа

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation: Remove Static Area and Static Area items

###  Form Support

**Changes agreed**:

- [ ] [enhancement] `attachInternals` to replace the hidden input https://github.com/SAP/ui5-webcomponents/pull/7909

## @ui5/webcomponents-tools

**Changes agreed**:

- [ ] :exclamation: [breaking] :exclamation: Remove the `support of JS development` from our tools , although the framework will still allow creating components with pure JS.
- [ ] :exclamation: [breaking] :exclamation: Remove the `JSDoc plugin`
- [ ] :exclamation: [breaking] :exclamation: Upgrade to new major `wdio` version would breaking for consumers of wdio.config.js - **check if needed as there is research to use Cypress in future**

## **@ui5/webcomponents-theming**

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation: Remove `Belize` theme

### Move components

**Changes agreed**:
- [ ] :exclamation: [breaking] :exclamation: - move the `Bar` component from `fiori` to `main` package.

### Grouping implementation 
- [ ] Review grouping of items in all list controls - List, ComboBoxes, Inputs, Selects https://github.com/SAP/ui5-webcomponents/issues/7732

### **Props**

**Changes under discussion**:

- Remove TabContainer's deprecated property showOverflow
- Review AriaHasPopup enum values. Which values are still relevant and shouldn't they be lowercase?

**Changes agreed**:

- Keep **IllustratedMessage#title** slot 
- Keep **IllustratedMessage#subtitle** slot
- [ ] :exclamation: [breaking] :exclamation: Remove **Option#disabled** - remove as UX and ACC standards suggest to not include any disabled items in the dropdown
- [ ] :exclamation: [breaking] :exclamation: Remove  **ProgressIndicator#disabled**- a disabled indicator can be part of disabled UI (Form, Panel), but does not make sense on its own. Also `aria-disabled` state is deprecated for the component, and it's not requested by a client.
- [ ] :exclamation: [breaking] :exclamation: Rename **SegmentedButtonItem#pressed**  to `"selected"`
- [ ] :exclamation: [breaking] :exclamation:`mode` properties in Table, List, SegmentedButton to become `selectionMode`
- [ ] :exclamation: [breaking] :exclamation:Change Calendar's event `selected-dates-change` to `selection-change `
- [ ] :exclamation: [breaking] :exclamation:  Change the Calendar's event details `values` and `dates` to `selectedValues` and `selectedDateValues`.
- [ ] :exclamation: [breaking] :exclamation:Change some enum values in TableMode, ListMode, SegmentedButtonMode: SingleSelect -> Single, MultiSelect -> Multiple
- [ ] :exclamation: [breaking] :exclamation: Change Enums' names: TableMode -> TableSelectionMode, ListMode -> ListSelectionMode, SegmentedButtonMode -> SegmentedButtonSelectionMode

### **Events**
**Changes under discussion**:

- [ ] Check the presence of the following events: `open-change`, `open`, `close`, `before-open`,  `before-close`, `after-open`, `after-close`. 

### **Event Details**

**Changes under discussion**:

- Check `targetRef` and `ref` presence and stick to the one or to the other.

### **Slots**

**Changes under discussion**:

- Check `icon` slot presence and rename to `"icons"`

### **Methods**

**Changes under discussion**:

- Check `openPicker`, `togglePicker` or similar methods and unify them

### Enums

**Changes agreed**:

- [ ] :exclamation: [breaking] :exclamation: Rename PopoverHorizontalAlign values - `Left`, `Right` --> `Start`, `End`
- [ ] :exclamation: [breaking] :exclamation: Rename PopoverPlacementType - `Left`, `Right` --> `Start`, `End`

### **Interfaces**
- [ ] - Revise existing interfaces, because many of them are implemented by only 1 component and seems redundant for the moment. Also many of the interfaces contain only 1 private property which name start with underscore and doesn't have jsdoc comment to describe it, for example: 
```
interface TestInterface {
    _test: string;
}
```

Let's discuss how to proceed with these interfaces.

## **@ui5/webcomponents-icons**

**Changes agreed**:

- [ ] :exclamation: [breaking] :exclamation: - Remove "soccor", keep "soccer"

## **@ui5/webcomponents-icons-business-suite**

**Changes agreed**:

- [ ] :exclamation: [breaking] :exclamation: - Remove "add-polygone", keep "add-polygon"

**Comment by gmkv** [comment]
Consider moving the Bar component from `fiori` to `main`.

**Comment by gmkv** [comment]
Remove TabContainer's deprecated property `showOverflow`

**Comment by dobrinyonkov** [comment]
Deprecate and remove the `image` property of the standard list item, since new slot `avatar` will be introduced. 
https://github.com/SAP/ui5-webcomponents/issues/5594

**Comment by dobrinyonkov** [comment]
Remove the `disabled` property from `ui5-option`. The property was used to set opacity and make the option non-focusable, but recently the accessibility standards suggest to not include any disabled items in the dropdow.

**Comment by nnaydenow** [comment]
Revise existing interfaces, because many of them are implemented by only 1 component and seems redundant for the moment.

**Comment by nnaydenow** [comment]
Revise all the events that have stopped bubbling.

**Comment by MapTo0** [comment]
Review grouping of items in all list controls - List, ComboBoxes, Inputs, Selects

**Comment by NHristov-sap** [comment]
As an outcome of our team Balkan research, the following API deprecations were found:

1. Button 
* Deprecated submits property, which is replaced by setting type property to Submit.

2. Calendar
* Deprecated selectedDates getter/setter

3. ColorPalettePopover
* Deprecated method openPopover, replaced by showAt method.

4. Menu
* There was a [PoC](https://github.com/SAP/ui5-webcomponents/pull/7954) on refactoring the Menu and MenuItem components – MenuItem will have menu slot that accepts Menu component instead of items slot that accepts MenuItem components. This will lead to incompatible change.

5. SegmentedButton
* Deprecated getter selectedItem, use selectedItems property instead; 
* Deprecated parameter selectedItem in selectionChange event, use selectedItems parameter instead.

After a discussion within the team, there are several proposals that might be taken in account:

1. Calendar, etc. (date-related controls)
* Timezones/UI5Date to be implemented in the date-related controls.

2. DateTimePicker
* Integration of the new/redesigned TimePicker as part of DateTimePicker

3. DynamicSideContent
* Adding sideContentWidth property and related functionality as in Classic UI5.

4. SegmentedButton
* As the SegmentedButtonItems use ToggleButton, preventing of ToggleButton’s click event will ease the 
SegmentedButtonItems manipulation.

5. ToggleButton
* Make click event preventable.

There were several proposals for our components above:

1. Consider moving the Bar component from fiori to main:
* we do not agree with this because Bar is layout component used by another layout components, most of them are in fiori library.

2. mode - property mode vs selectionMode, Enum value "Multi" vs "Multiple", Enum name "ListMode" vs "CalendarSelectionMode": 
* proposed are too general, and these are different types of behavior, we prefer not to change them that way.

3. SegmentedButtonItem#pressed - should be selected:
* as the SegmentedButtonItem extends ToggleButton, and there is related property press, it will be difficult to change press to selected. Also, this is Button in general, buttons are pressed, not selected.

**Comment by gmkv** [comment]
> Consider moving the Bar component from fiori to main:
>> we do not agree with this because Bar is layout component used by another layout components, most of them are in fiori library.

Hi @NHristov-sap could you provide examples where the Bar is used by another layout components, most of which are in the fiori library?

My motivation for moving the Bar component into main is that if you want to have a simple Dialog with a properly designed header and footer, you would use a Bar to achieve this. Because of this, the Bar is more "generic" in its usage and purpose, therefore I think it belongs to the more "generic" set of components, which the `main` package is for.

**Comment by NHristov-sap** [comment]
Hi @gmkv,

Page can use bar for header/footer, ViewSettiongsDialog uses Bar too.

Best Regards,
Nikolay Hristov

**Comment by gmkv** [comment]
@NHristov-sap  If we go by counting how many components are intended to accept a Bar in their header/footer slots, there are more components in the main package.
<img width="293" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/22086365/4f334cd7-7854-482f-b4c0-3edb8d1ca712"> 
<img width="257" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/22086365/8a4b2a45-ecb7-4de0-833f-3c02c0e7dd3c">

This proves that the Bar is more generic, rather than more "fiori-specific" and is more appropriate if it resides in the the `main` package.
By pure definition, the `fiori` package is [designed to contain components that](https://github.com/SAP/ui5-webcomponents/tree/main/packages/fiori#ui5-web-components---fiori) "provide essential building blocks, necessary to implement the Fiori UX concept, such as a common header (ShellBar)."
Please revise my suggestion again with this in mind.

**Comment by dobrinyonkov** [comment]
Review AriaHasPopup enum values. Which vaules are still relevant and shouldn't they be lowercase?

**Comment by hristop** [comment]
Hi, 

Here is the list with desired changes for 2.0 for the scope of Team Rila:
https://gist.github.tools.sap/I309691/3f7b55a6d8d838cad95f37bfd2832218

# Components

- Combo Box
  - `loading`: empty list if the property is set to true
  - `grouping`: items to be nested
  - `change` event should not be fired upon navigation. To be fired on click on an item, focus out and enter key
  - `input` event to remove `filterValue` docs
  - `selection-change` consider `preventDefault()` scenario
- Input
  - Numeric Input?
  - rename `suggestion-item-preview` to `selection-change`
  - remove `suggestion-item-select`?
  - remove `previewItem` getter
  - integrated `InputSuggestions` in Input
  - rework `suggestion-item-select` `preventDefault()` logic
- ~~Message Strip~~
- Multi Combo Box
  - `loading`: implment new property (after 2.0?)
  - `allowCustomValues`: rename to `noValidation`
  - `selection-change`: fire events before updates.
- ~~Multi Input~~
- Panel
  - toggle: move event firing before action to improve prevention
- ~~Rating Indicator~~
- ~~Range Slider~~
- ~~Slider~~
- ~~Text Area~~
- ~~Toast~~
- Wizard
  - Change naming of `changeWithClick` property
- Page
  - `disableScrolling` to become `noScrolling`
  - `floatingFooter` is boolean default true? Change name and implementation (`fixedFooter`)?
  - `default` slot might be a `Node`

# Elements
- ~~ComboBoxItem~~
- ~~ComboBoxGroupItem~~
- ~~MultiComboBoxItem~~
- ~~MultiComboBoxGroupItem~~
- SuggestionItem
  - remove `type` property
  - remove `description`
  - remove `icon`
  - remove `iconEnd`
  - remove `image`
  - remove `additionalTextState`
- ~~SuggestionGrouoItem~~
- ~~Token~~
  - remove `readonly` property
- ~~WizardTab~~
- WizardStep
  - revise `selected` + `disabled` scenario


# General Issues
- align `accessibleName` and `accessibleNameRef` default values
- revise `FormSupport`? Introduce native html elements as slots for all form elements
- compare `Positive` with `Success`. Do we need 10 different `Design` enums?
- grouping behaviour in `Select`, `Input`, `ComboBox`, `List`, etc. Nesting?
- `open-change` vs `open`, `close` (Select) vs `toggle`?
- `preventDefault()` should be aligned across all components
- `openPicker` discuss for general naming - `DatePicker`, `ComboBox`, `Input`, `Select`, etc

Best Regards,
Histo

**Comment by ilhan007** [comment]
Suggested Changes have been reviewed in the past months and refined to new list of Planned changes: 
https://github.com/SAP/ui5-webcomponents/issues/8461
