### ISSUE TITLE
ui5-date-picker calculate the wrong week year in "2021/12/30"

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#4506]
### **Bug Description**

When choosing "2021/12/30" in ui5-date-picker, it shows “2022/12/30” 

### **Expected Behavior**

Expect it shows “2021/12/30” 

### **Steps to Reproduce**
1. Create a DatePicker: `<ui5-date-picker format-pattern="dd/MM/YYYY"></ui5-date-picker>`
2. Choose  "2021/12/30"
3. The input will show “2022/12/30”

### **Isolated Example**

https://codesandbox.io/s/ui5-webcomponents-data-picker-bug-report-qcckk?file=/index.html

### **Context**
- UI5 Web Components version: {1.0.0-rc.12}
- OS/Platform: {MacOS Monterey}
- Browser: {Chrome}
- Affected component: {ui5-date-picker}

### **Log Output / Stack Trace / Screenshots**

Related code:

```js
// DateFormat.js    
for (var i = 0; i < this.aFormatArray.length; i++) {
    oPart = this.aFormatArray[i];
    sSymbol = oPart.symbol || '';
    aBuffer.push(this.oSymbols[sSymbol].format(oPart, oDate, bUTC, this));
}

// When we use Y, it's weekYear, and the oWeek will parse 2021 to 2022:
'Y': {
    name: 'weekYear',
    format: function (oField, oDate, bUTC, oFormat) {
        // bUTC: true 
        // oDate.getTime()
        // 1640822400000
        var oWeek = bUTC ? oDate.getUTCWeek() : oDate.getWeek();
    }
}
```

![image](https://user-images.githubusercontent.com/6975707/146706214-2a88e832-79f8-4994-b3ee-0402fdd1fd14.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP JAM / WorkZone}
- Bussiness impact: {User has report bug to us.}

**Comment by MapTo0** [comment]
Dear Colleagues,

The issue looks `DateFormat.js` parses 30.12.2021's year as 2022.
Take in mind that this might be also an openui5 issue as `DateFormat.js` is borrowed module.

Regards,
Martin

**Comment by NHristov-sap** [comment]
Hi @TinaC,

The issue you have reported, in fact is not an issue. Let me explain briefly.

When an uppercase letter **Y** is used in a formatting pattern for the year, this means **"Week of Year"**, and sometimes the result is different compared to lowercase **y**. The difference happens when week with number 1 starts in previous year. 

So, when the first week of an year starts in previous year, and **YYYY** (or **YY**) is set in the formatting pattern, the year is "taken" from the week number. As it is the first week of 2022, the year in the first Date Picker (where year part is formatted as **YYYY**) results to **2022**. In the second Date Picker (where year part is formatted as **yyyy**), the year is taken by the selected date's year - **2021**.

If you want to get exact year (as in the date), please use **yyyy** or **yy** in the formatting pattern.

You can find more information about this here: [http://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table](http://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table)

or just search about "Week of Year".

Best Regards,
Nikolay Hristov
SAP Development Support
