### ISSUE TITLE
MultiInput: Not showing valueState color on readonly mode.

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents#4520]
**Describe the bug**
When the MultiInput field is set as readonly, it should not allow typing in the field but should still show the change in valueState. The value state message shows up but the box color is not changing.

![image](https://user-images.githubusercontent.com/38140078/147036572-575b4514-7c3c-433f-802d-3fa57985f270.png)

**Isolated Example**
Please use the following link to reproduce the issue. https://codesandbox.io/s/suspicious-firefly-49jox?file=/src/App.js

**Expected behavior**
The color for the box should change as per the valueState even in the readonly mode.

**Comment by ndeshev** [comment]
Hello @mihirahlawat

Currently this is desired behavior specificated in the Fiori 3 UX guidelines -in short it states that when the user has no option to change of an input state it shouldn't be displayed.

**Comment by mihirahlawat** [comment]
Hi @ndeshev

Is there anyway to disable typing into a MultiInput box and still have the value state colors? I am providing a valuehelp dialogbox for insertion of data and hence want to disable input into the field through typing. I want to retain the value state functionality to give error in case no value is selected. Please help me find a resolution to this issue. Any help would be really appreciated.

**Comment by ndeshev** [comment]
Hello @mihirahlawat, 

 I know see that in the version you use there is a value state message shown (without the color change) which is a bug and it is fixed in the newer versions. In them even the value state text won't be shown. 

The best practice is that  If you are not using the input for collecting data from the user use another component (for display only purposes).  Otherwise, if you insist on using input components you should implement custom validation and value state functionality, but again, keep in mind - this is not Fiori compliant.
