### ISSUE TITLE
Can ComboBox be altered like MultiComboBox allowing only valid inputs?

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#4537]
In ComboBox we are allowed to enter invalid entries unlike in MultiComboBox where only valid input is allowed.

**Solution**
Can we have ComboBox behave the same way MultiComboBox is behaving

**Comment by TeodorTaushanov** [comment]
Hi @Arora05,

You can use the "ui5-select" component:
https://sap.github.io/ui5-webcomponents/playground/components/Select/

Best,
Teo

**Comment by Arora05** [comment]
I have a requirement for text search which is not possible in "ui5-select", so can you tell me if or when this can be fixed in ComboBox.

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-rl, there is a feature request for the "ui5-combobox".

**Comment by niyap** [comment]
Hello @Arora05,

ui5-combobox concept is to allow entering custom values by design.
As @TeodorTaushanov has mentioned, you can use ui5-select component, where you can navigate to the desired options, typing the first character of that option. 
If that does not fit your scenario, you can use ui5-combobox as well and use "change" event to add custom validation for the value in order to fulfil your use case.

Kind Regards,
Niya
