### ISSUE TITLE
[BUG][SF][Urgent][UI5-List][Version: 1.0.2] onSuggestionScroll event is missing in version 1.0.2 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4595]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. 

**The version of ui5-webcomponent is 1.0.2**

**Bug Description**

onSuggestionScroll event is missing in ui5-list

**Excepted Behavior**
add onSuggestionScroll event back, this event is mandatory for our project

**Comment by a-z-ivanov** [comment]
Hello, @SAP/ui5-webcomponents-topic-rl,

Have a look at this request, please.

Regards,
Alex

**Comment by wzyyvonne** [comment]
Hello, team. 
I'm the produce manager from SuccessFactors. 
In past release, we've used this control to serve the need to find item in large amount of data that need API call to fetch result back. This feature went live into production in b2111 which is a critical path for creating an object called 'assignment' in our business domain. I heard from our engineer that this feature will be removed soon and are really worried about this. Can we try  to retain the onScoll event so that we can continue serve the business needs to our customers? Please kindly consider this further.
Thanks a lot!

**Comment by nikolay-kolarov** [comment]
Hi @sfsf-xweb-sh,
Hi @wzyyvonne,

To my knowledge, the ui5-list does not have such an event, so I assume you are talking about the ui5-input?
Could you please provide more information about the use case and the exact components being used?

Thanks,
Nikolay

**Comment by 2bno1** [comment]
@nikolay-kolarov Yes, @wzyyvonne is talking about the `suggestion-scroll` event of `ui5-input`. I see actually this event is still supported now in 1.0.x (https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/Input.js#L439). But it is not mentioned in the development document (https://sap.github.io/ui5-webcomponents/playground/components/Input/).
As our products (sfsf) is still dependent on this event and haven't found an alternative solution. We hope this `suggestion-scroll` event can still be there.

Thanks,
Mintao

**Comment by niyap** [comment]
Hello Colleagues,

As discussed via the mail communication, we are not going to make the "suggestion-scroll" public again. The reason is that it was wrongly introduced and not conformant to the UX.

So, I am closing the incident.

Kind Regards,
Niya
