### ISSUE TITLE
[SF][1.0.2][ui5-popover][BUG][Expected within two weeks] Popover border is overlapped with screen left edge

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4598]
Dear UI5 team,

This is SuccessFactors Web Experience Shanghai team. We found this issue in the process of upgrading to the latest version of ui5-webcomponent, and it can be reproduced on mobile web.
The version of ui5-webcomponent is `1.0.2`

### **Bug Description**
Popover is not aligned in page center (mobile web) and its left border is overlapped with screen edge.

### **Expected Behavior**
Popover should be aligned in page center and have some space against screen edge.

### **Steps to Reproduce**

1. Open below link in **mobile** browser, log in with cgrant/pwd
https://qacand.hcm.ondemand.com/sf/goals?bplte_company=TALH2TGMM1&mock&sap-ui-theme=sap_horizon#/goal-list

2. There would be a popup opened automatically. Click "Start Tour"

3. Then you can see popover's left border is overlapped with screen left edge. Please see below screenshot:
![Image from iOS (1)](https://user-images.githubusercontent.com/78520316/150312537-439ba481-6a4f-47d3-8efa-0faaac92cb68.png)

**Comment by a-z-ivanov** [comment]
Hello, @sfsf-xweb-sh,

I think it's because of your css styles. This classes `.sf_common_comp-FirstTimeGuidance__Popover, :host(.sf_common_comp-FirstTimeGuidance__Popover.phone)` define and redefine the min-width css property for the whole popover element. I think you should also redefine the max-width to override this rule
`calc(100% - var(--_ui5_popup_viewport_margin)*2)`
this is what makes it wider.

Regards,
Alex
