### ISSUE TITLE
MediaGalleryItem: result must not have attributes

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#4610]
### **Bug Description**
When the Web Components core is booted and a `ui5-media-gallery-item` is added to the DOM, an error is thrown:
![image](https://user-images.githubusercontent.com/8775211/150608989-56789132-e430-428c-889c-6aecb3a692a2.png)

### **Expected Behavior**
There should be no error thrown

### **Steps to Reproduce**
1. Open https://codesandbox.io/s/angry-spence-gv19h?file=/src/App.js:215-234
2. Click on `Show Media Gallery Item`
3. See the error

It looks like this is only happening when the UI5 Web Components core is already booted - if you change the `useState` initial value to true the error isn't thrown

### **Isolated Example**
https://codesandbox.io/s/angry-spence-gv19h?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.1.0
- OS/Platform: macOS 12.1
- Browser: Chrome
- Affected component: `ui5-media-gallery-item`

### **Log Output / Stack Trace / Screenshots**
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at createElement (http://localhost:6006/vendors~main.iframe.bundle.js:111819:34)
    at createInstance (http://localhost:6006/vendors~main.iframe.bundle.js:113016:20)
    at completeWork (http://localhost:6006/vendors~main.iframe.bundle.js:122288:28)
    at completeUnitOfWork (http://localhost:6006/vendors~main.iframe.bundle.js:125634:16)
    at performUnitOfWork (http://localhost:6006/vendors~main.iframe.bundle.js:125606:5)
    at workLoopSync (http://localhost:6006/vendors~main.iframe.bundle.js:125526:5)
    at renderRootSync (http://localhost:6006/vendors~main.iframe.bundle.js:125489:7)
    at performSyncWorkOnRoot (http://localhost:6006/vendors~main.iframe.bundle.js:125112:18)
    at http://localhost:6006/vendors~main.iframe.bundle.js:114151:26
    at unstable_runWithPriority (http://localhost:6006/vendors~main.iframe.bundle.js:137667:12)
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### Additional Information
I think this error is related to these lines: https://github.com/SAP/ui5-webcomponents/blob/417bd6aad5829de578cc91487fa080af4699e450/packages/fiori/src/MediaGalleryItem.js#L182-L186
As far as I remember, it is not allowed to set attributes of a custom element in the constructor. I think we had a similar issue with the `ui5-button` long time ago (something with setting _isTouch or sth) - maybe @vladitasev remembers 🙂

**Comment by MarcusNotheis** [comment]
Also looks like the icon import for `background` is missing: 
https://github.com/SAP/ui5-webcomponents/blob/11e686ffd64fbabc1ed80cff3238a9ebd2d4c234/packages/fiori/src/MediaGalleryItem.hbs#L11-L13
![image](https://user-images.githubusercontent.com/8775211/150735885-17c66173-abc2-4c48-8507-b007fabf3a61.png)

**Comment by ilhan007** [comment]
Hello @SAP/ui5-webcomponents-topic-p could you take a look of this issue with priority. I will also ask @vladitasev if he remembers the case that Marcus described.

**Comment by pskelin** [comment]
@MarcusNotheis is right, I found the related previous PR https://github.com/SAP/ui5-webcomponents/issues/3073

Basically the properties should be set in `connectedCallback` instead of in the constructor.

Here is more information from the spec
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance

relevant parts:
- The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.
- In general, work should be deferred to connectedCallback as much as possible—especially work involving fetching resources or rendering. However, note that connectedCallback can be called more than once, so any initialization work that is truly one-time will need a guard to prevent it from running twice.
