### ISSUE TITLE
ui5-input: Get Selection / Selected Text

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents#4620]
### **Feature Request Description**
I couldn't find a way how to get the current cursor position or the selected text.
[Example CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-qxuu7?file=/src/index.js)

Use case: Would be required for a proper input mask like in UI5
Of course, there are much more use cases.

### **Proposed Solution**
- Add `selectionStart` and `selectionEnd` infos to the event object (must be copied from the original one)...
- make the `selection` event hanlder work

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, I'm forwarding you a feature request for the Input.

**Comment by nikolay-kolarov** [comment]
Hello @texttechne,

Could you please provide more information what is the exact use case and what you want to achieve?

Thanks,
Nikolay

**Comment by ndeshev** [comment]
Hello @texttechne,

You can get the `selectionStart `and `selectionEnd `properties from the inner (native) input in the the `ui5-input` shadowRoot like so:
`e.currentTarget.shadowRoot.querySelector("input").selectionStart
`
If it is necessary for your case, you can listen to its "select" event the same way.

The 'select' event is a special event for the native HTML 'input' and 'textarea' elements, but i'm not sure, if it will be a good choice to expose it through the `ui5-input` component, it may cause ambiguity.  It has selectable suggestion items and the "selection" and "select" is used mainly in their context. 

Kind Regards,
Nikolay

**Comment by texttechne** [comment]
Hi @ndeshev,

that's exactly what I wanted. Thanks!

Is this "API" safe to use?
I mean, it seems to work for manipulating stuff inside the shadow dom...

Does this work for all components?

Best Regards

**Comment by ndeshev** [comment]
Unfortunately, it is not - because we do it too, internally in the logic of the component. It is to be used as a workaround and only if there is no other way. 

For example, even if you do your customization, and everything is fine with it now, we may implement a feature in some newer version that has required to manipulate the same element and that to affect the behaviour you wanted to achieve. In other words you can't rely on backward compatibility.

**Comment by ndeshev** [comment]
Hi @texttechne, for that example you can use what I proposed. 

If you only read (check) the selection that is fine. Also in that case it won't make a difference if we expose a separate select event or not - the outcome will be the same because our select event and the native one, that you can use now, will return the same selection . 

My caution in the previous post was more about if you are making selections yourself, around some complicated custom logic, etc. But the thing is - in that case it also almost doesn't matter again if you use the native select or ours. 

The fact that this event is native for the input means that we are using it to develop and further evolve our component, meaning that there is a risk of backwards incompatibility and to provide a public API for something that we will keep backwards compatible is bad for everyone.
