### ISSUE TITLE
[SF-ACC][ui5-table] The keyboard navigation pattern in the data tables doesn't match the responsive table keyboard navigation pattern

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#4657]
SAP UI5 is going to change the keyboard navigability in the responsive tables as they are not currently adhering to WCAG recommended keyboard navigability. Please see the FIORI ticket
P1-19036

Since WC responsive tables mirror SAP UI5 responsive table behavior, we want ui5-table's behavior to be changed and in sync with UI5 as well. 

### **Context**
- UI5 Web Components version: 1.0.2
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, I'm forwarding you a feature request for the Table.

**Comment by nikolay-kolarov** [comment]
Hello Colleagues,
First, we need to clarify and implement the concept in UI5 Responsive Table and then we can plan and implement it in the ui5-table component.
Until then, this item is blocked.
Best Regards,
Nikolay

**Comment by 2bno1** [comment]
@hristop Is there any update or plan for this? Thanks.

**Comment by hristop** [comment]
Hi @2bno1 ,

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.
 
The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.
 
While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.
 
However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.
 
We are excited about the opportunities this transition will bring and the positive impact it will have on our product.
 
Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.
 
Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component. 

Best Regards,
Hristo

**Comment by 2bno1** [comment]
@hristop Thanks for your reply. One and half month passes since your reply. Is there any update now? What's the status of new `table` development?

Thanks

**Comment by hristop** [comment]
Hi @2bno1 ,

The new table is developed in another team, but after some discussions with them I got that the table is in progress, but it is still not sufficient for initial preview. 

Best Regards,
Hristo

**Comment by simlin** [comment]
Hi @2bno1 ,

In the 2.0 version of the UI5 Web Components we introduced a new Table component:
https://sap.github.io/ui5-webcomponents/nightly/components/Table/

The table is still in an experimental phase and certain APIs might slightly change. Nevertheless we ask you to try out the new component already now. The earlier we get some feedback the better :)

The functionality you requested is already considered, see
https://sap.github.io/ui5-webcomponents/nightly/components/Table/#keyboard-handling

Best Regards
Jens
