### ISSUE TITLE
[SF][A11y][MultiInput] aria-roledescription is only used on elements with an implicit or explicit role

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents#4729]
### **Bug Description**
With MultiInput control Axe is complaining for aria-roledescription is only used on elements with an implicit or explicit role

### **Expected Behavior**
Axe dev tool should not complain about this.

### **Isolated Example**
If possible, please provide an isolated example by forking 
https://codesandbox.io/s/youthful-pike-l8cv0
https://l8cv0.csb.app/

### **Context**
- UI5 Web Components version: 1.0.2
- - UI5 Web Components react version: 0.21.2
- OS/Platform: Mac Os
- Browser: Browser
- Affected component: MultiInput

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)
Organization: SAP Successfactors

**Comment by alexandar-mitsev** [comment]
Hello @saorabhkr ,

Currently we are researching this behaviour of the AXE tool, since it is contradicting.
It reports the problem on the "input" element which does have an implicit role of textbox. So this follows correctly the aria standard for aria-roledescription and it seems to be a problem in the tool itself.

Will get back to you when we have more info, but it seems it is a false positive from the tool.

Regards,
Alexandar Mitsev

**Comment by alexandar-mitsev** [comment]
Hi @SAP/ui5-webcomponents-topic-rl ,

Forwarding this ticket to you so you can handle it when we have results from the accessibility experts research.

Regards,
Alexandar Mitsev

**Comment by elenastoyanovaa** [comment]
Hello @saorabhkr ,

Actually the complain is not an error, but a flag, which needs a review. The solution from the report is the following:

> "Fix the following:
> Check that the aria-roledescription is announced by supported screen readers"

The roledescription is read out by JAWS and all major screen readers therefore this is not an issue.
What is more, the following error is reported several times to axe-core:

https://github.com/dequelabs/axe-core/issues/1843
https://github.com/dequelabs/axe-core/issues/234
https://github.com/dequelabs/axe-core/issues?q=aria-roledescription

The issue is not with the web components, but an AXE issue.

Kind Regards,
Elena
