### ISSUE TITLE
StepInput: Setting the value-state in the `change` event doesn't work with React state

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4791]
### **Bug Description**
When using ui5 web components in React and setting the `value-state` depending on the value returned by the `change` event, the value state isn't updated correctly. When updating the `value-state` via the HTML attribute, it is working as expected.

### **Expected Behavior**
It should be possible to update the value state by using the React syntax.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/solitary-cookies-kyzjj6?file=/src/App.js)
2. Increase the number of the first StepInput to `3` and see that the value state changes to `"None"` (expected)
3. Increase the number once more and see that the state changes to `"Error"` again.

EventListener:
```js
    ref.current.addEventListener("change", (e) => {
      if (e.target.value >= 3) {
        setValueState("None");
      } else {
        setValueState("Error");
      }
    });
```

https://user-images.githubusercontent.com/9749730/154933777-f5fd5d38-f394-4d11-97df-6174c2202214.mp4

### **Isolated Example**
https://codesandbox.io/s/solitary-cookies-kyzjj6?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.1.2
- Framework: React

### Possible root cause
https://github.com/SAP/ui5-webcomponents/blob/84eb014e9e32476e5623c4882332992799e7af4e/packages/main/src/StepInput.js#L493-L500
Here some internal validation is taking place, maybe this is overwriting the attribute set by React again. (not confirmed, just guessing ;) )

### Additional informations
May be related to: https://github.com/SAP/ui5-webcomponents/issues/4684

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The div wrappers for the columns slots are rendered even if the slots are not defined. Those divs are with role region which may be invalid from accessiblity POV.

We should remove the role attribute or even not render the empty divs, if possible.

Regards,
Dobrin

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

this issue is probably caused by the fact that we don't update the `this._previousValueState` property when the `value-state` attribute changes. There are cases when the last up to date value of `this._previousValueState` is set when the `_validate` method is called (if min and max are undefined) and that may not be the correct `value-state`.

Note: I guess that react does not always call setAttrbute because the `valueState` variable/hook is not updated, therefore no change is detected and the setAttribute is not called by the react DOM update logic. 

Could you please look at this issue?

Regards,
Dobrin

**Comment by tsanislavgatev** [comment]
Hello,
We've introduced new event called - value-state-change. It is preventable so you can prevent it when no internal validation is needed.
