### ISSUE TITLE
[SF][ViewSettingsDialog] Expose _currentSettings as a property so that one can provide both a "current config" and "initial config"

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#4896]
### **Feature Request Description**
Currently, to set the initial config of the ViewSettingsDialog, we need to pass the `selected` attribute to the SortItem that we want to be selected by default, as you can see here: https://codesandbox.io/s/ui5-webcomponents-forked-ugcgwn?file=/src/index.js

Pressing "reset" button after selecting another value will select the initial one, which is fine.

However, in some instances, we may want to save and reuse the user's "current configuration" but keep a different "initial value".

For example, let's say that initially we want to order by "Name Ascending" but a user presses "Position Descending" and we store this value somewhere. When reopening the ViewSettingsDialog at another time, then the user will want to see its "Position Descending" value preselected but the "Reset" will be disabled as the "Position Descending" will become the initial value.

For this use-case we would like to be able to provide both the initial configuration AND the "current" configuration.

### **Proposed Solution**

Expose the `_currentSettings` (see here: https://github.com/SAP/ui5-webcomponents/blob/master/packages/fiori/src/ViewSettingsDialog.js#L472) as a property so that we can provide a separate "current config" and "initial config".

Here's an example where "Name" is selected by default as it is the "initial config" (and will reset to Name) but "Position Descending" is the "current config"

```
<ui5-view-settings-dialog id="vsd" current-sort-value="Position" current-sort-order-descending="true">
    <ui5-sort-item slot="sortItems" text="Name" selected></ui5-sort-item>
    <ui5-sort-item slot="sortItems" text="Position"></ui5-sort-item>
    <ui5-sort-item slot="sortItems" text="Company"></ui5-sort-item>
    <ui5-sort-item slot="sortItems" text="Department"></ui5-sort-item>
</ui5-view-settings-dialog>
```

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-b, please take a look of this feature request - if it is possible to provide a separate public state for the current settings of the ViewSettingsDialog component.

**Comment by tsanislavgatev** [comment]
Hello @Neeeko,

With latest update we will return the picked sortItem as a DOM ref, not only as a string.

The view settings dialog has 3 configurations holders.
currentSettings, confirmedSettings and initialSettings.
Current are the ones which are the 'live' settings, this variable keeps the state of the selection during the interaction of the user.
Confirmed are the ones which are saved after the confirmation button is clicked.
Initial are the ones set initially to the control.

These variables should not be changed while interacting with the control. You can always collect and keep the information about the confirmed settings during users interaction, because in the event, we provide information about the state of the viewsettingsdialog.

If i understand correctly you want to make the confirmed settings act as initial settings and the reset button to recover to confirmed and not initial settings. To help you with this we can create a public method which on call will align the initialConfig to the confirmedConfig. (*)

Otherwise if the cancel button is clicked, the control returns to last confirmed settings. And this is by specification, OK button changes the confirmed settings replacing them with the current settings and the Cancel button removes the current selection and loads the last confirmed selection.
The Reset button resets the values to their initial state.

Please update us if such method(*)  would help you achieve the result you want.

If you have any questions about this, please feel free to ask.

Best Regards,
Tsanislav

**Comment by Neeeko** [comment]
Hello @tsanislavgatev, thank you for your thorough reply!

To be honest, I'm not sure if the method you suggested will help. Let me try to explain our use-case in an easier way:

Step 1-
![Screenshot 2022-03-21 at 14 47 09](https://user-images.githubusercontent.com/7316793/159274762-d20ea9cf-bccb-49e5-bfb1-f285ac97ed4b.png)
User opens the Dialog. By default, "Team Name" "Ascending" are selected. These are the default filters provided by our project.
Thus:
`currentSettings` and `initialSettings` = `{ sortBy: "Team Name", sortOrder: "Ascending"}`
`confirmedSettings` = {}

Step 2-
![Screenshot 2022-03-21 at 14 47 23](https://user-images.githubusercontent.com/7316793/159275368-073d6039-afe7-4e1d-bd07-cdbf9a0d08d1.png)
User makes the following selection and press Save. The reset button is **enabled**.
Thus:
`initialSettings` = `{ sortBy: "Team Name", sortOrder: "Ascending"}`
`currentSettings` and `confirmedSettings` = `{ sortBy: "Team Name", sortOrder: "Descending"}`

Until this step, everything is fine and works as expected with the current implementation of the ViewSettingsDialog. This is where it gets trickier:

Step 3-
Let's say the user quits the website and comes back the day after. His previous selection (from Step 2) has been saved in our database.
When the user opens the ViewSettingsDialog, he expects to see his previous selection similar to Step 2:
![Screenshot 2022-03-21 at 14 47 23](https://user-images.githubusercontent.com/7316793/159275368-073d6039-afe7-4e1d-bd07-cdbf9a0d08d1.png)

So here, the values should be:
`initialSettings` = `{ sortBy: "Team Name", sortOrder: "Ascending"}`
`currentSettings` = `{ sortBy: "Team Name", sortOrder: "Descending"}`
`confirmedSettings` = {}

The reset button should be **enabled** if he wants to reverts to the project defined `initialSettings` ("Team Name" "Ascending") but still see his previous selection already check ("Team Name" "Descending")

However, with the current implementation, we're only able to pass values for the `initialSettings` but not the `currentSettings`.
That's the reason why we asked to expose the `currentSettings`, so that we can keep the `initialSettings` defined at the project level ("Team Name" "Ascending") but still pre-populate the `currentSettings` based on the user previous actions.


Please let me know if it's unclear, I know it's a bit difficult to explain and understand 🙂

**Comment by tsanislavgatev** [comment]
Hello after discussion and research,

A solution that we can propose is to create a setter for the currenet settings that will give the application developer a chance to set the current settings in specified format. This setter would be good to use after opening as the initial settings are set with the initial opening of the view settings dialog. Open even will be provided as well.

If you have any questions feel free to ask. Also you can verify if this solution would work for you.

Best Regards,
Tsanislav
