### ISSUE TITLE
[Input] - add showExceededText and maxlength

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents#4910]
### **Feature Request Description**
Could we add the following properties to the **Input** component: `showExceededText` and `maxlength` similar to the **TextArea** component?

### **Proposed Solution**
Add `showExceededText` and `maxlength` to Input

### **Additional Context**
![Screen Shot 2022-03-16 at 14 53 08](https://user-images.githubusercontent.com/11576789/158697537-2bc24f65-2ad0-4831-a304-c24bca976bab.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl, could you take a look of this feature request.

Kind regards,
Nikolay

**Comment by nikolay-kolarov** [comment]
Hi @rchrdchn ,

If you want to achieve this, you can use the ui5-textarea with rows=1.

The ui5-input and the ui5-textarea have two different purposes and I do not think it makes sense to add those options to the input:
- textarea - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea - represents a multi-line plain-text editing control, useful when you want to allow users to enter a sizeable amount of free-form text.
- input - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input - used to create interactive controls for web-based forms in order to accept data from the user.

Best Regards,
Nikolay
