### ISSUE TITLE
ValueHelp Only option for MultiInput Field

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5045]
We have a very commonly used usecase in our applications wherein the user is allowed to choose for inputs only via value help. He should not be allowed to enter any data directly by typing in the inputbox of MultiInput field component. This feature is required in atleast 20 instances in our apps like in filterbar, as a input in create/edit mode, etc.

Currently, with the features provided by React UI5 components (https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multiinput--default-story) , we can have this usecase using the workaround of setting the readonly property of multiinput component to true. 

However, this has led to multiple other non-required consequences:
1) The Validation state not getting shown in 'SAP Horizon' theme. While in other themes, the erroneous red highlighted state is depicted with a grey highlight. User has no chances of identifying the error easily.
2) The UI layout in SAP Horizon theme looks like a mess with just labels floating around. 
![image](https://user-images.githubusercontent.com/90389521/162892446-18b1986f-38a5-4f55-b94c-57128c967ee4.png)

Fiori / SAPUI5 provides this feature for multiInput (https://sapui5.hana.ondemand.com/#/api/sap.m.MultiInput%23methods/isValueHelpOnlyOpener). Request you to please add the feature for react component too. We have multiple accessibility incidents raised regarding this feature. Hence, request you to please fix this as soon as possible.

**Comment by stbodurov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Please take a look of this feature request.

Regards,
Stanislav

**Comment by nikolay-kolarov** [comment]
Hello @PriyaPowar,

Thanks for raising this feature request.
Could you please provide more information about the use case and why you use so much value help only multi-inputs?

This is not so convenient for power users and assistive technology users. There was even a discussion to deprecate this functionality in UI5 due to this reasons. Therefore, I am not so confident that we can provide such a functionality in the UI5 WebComponents.

On top, what you are currently doing relies on a bug that the value help icon is visible in readonly multi-input.
Therefore, I would recommend to leave the users to decide either to type the value or use the value help dialog. It only requires to do a validation of the typed in input and will be better for the users.

Thanks and Best Regards,
Nikolay

**Comment by PriyaPowar** [comment]
Hi [nikolay-kolarov](https://github.com/nikolay-kolarov),

We have usecases where-in the user can choose a node from the hierarchical set of data as an input/filter. The table shown inside the valuehelp  is a custom implementation of treetable like structure. If users are allowed to freely enter the text, then it is hard for us to map the data, especially if user opens the valuehelp agai; since we can not trace back to the root node of the manually entered text and mark it as selected/ unselected in the valuehelp. This would simply add performance overhead just to map all freely entered texts. Hence, we went forward with selection of data using value help only where in we keep note of hierarchy data.

Hence request to please consider the feature where in valuehelp only cases are considered.

Regards,
Priya
