### ISSUE TITLE
DateTimePicker : Error state not updating

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents#5121]
**When we set the DateTimePicker to an error state it is not reflected in the component**
When we update the valueState to Error is not reflecting 

**Isolated Example for Input state update vs DateTimePiker state update**
*https://codesandbox.io/s/immutable-moon-w7tsoh?file=/src/App.js*

**Comment by niyap** [comment]
Hello Colleagues,

The issue is reproducible both for ui5-date-picker and ui5-datetime-picker components.
If you try to change the value state onChange from "None" to "Error" it is then reset back to "None".
The issue could be reproduced both in the codeSandbox provided: https://codesandbox.io/s/ui5-webcomponents-forked-8crdq8?file=/src/index.js:614-644 and in the sample page, if you try to do the same in one of the samples on "change".
If you debug it, you will notice how the value state gets "Error" and then "None" again.

Could you please check?

Kind Regards,
Niya

**Comment by tsanislavgatev** [comment]
Hello,

The control itself provides a bahaviour with predefined validations of dates, ranges, formats of date/time. It comes by default with the control, that's why you receive this removing of the value state. Because of this we've introduced the preventable behaviour, for the developers who don't need our checks, to give them the opportunity to implement their validation and value setting. That's why we are suggesting preventing the default behaviour and taking full control over the validation and value setting on your side.

Best Regards,
Tsanislav
