### ISSUE TITLE
MultiComboBox gets an ugly additional scroll bar in its drop down with content density = cozy

### ISSUE THREAD

**Issue by vlad-ti** [SAP/ui5-webcomponents#5126]
**Describe the bug**
see bug title

**To Reproduce**
Go to: https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multicombobox--default-story
Select content density = cozy
When Click on the MultiComboBox sample to open its drop down list
Then you will see the ugly scroll bar
When you make the browser window small enough, so that not MultiBomboBoxItems can be shown at once in the dropdown menu
Then you will see the true scroll bar of the drop down + plus the second ugly looking one.

**Expected behavior**
The ugly looking scroll should not appear

**Screenshots**
![bug MultiComboBox2](https://user-images.githubusercontent.com/14087901/165343910-d5d888a2-a2e3-450b-8b53-bce208972390.png)
![bug MultiComboBox1](https://user-images.githubusercontent.com/14087901/165343934-0d384c30-5b0a-47e7-a751-54d581f8786a.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.23.0
`@ui5/webcomponents-react` version: 0.23.0
Operating System: Windows
Browser: Chrome 

**Additional context**
The problem did not exist in 0.21.5

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible via the described by @vlad-ti steps and in the react playground sample.
In order to reproduce the double vertical scrollbar issue you would have to reduce the browser window width so that when the
ui5-multi-combobox select dialog gets opened it won't have enough space to display fully in the window.

Best Regards,
Boyan Rakilovski
