### ISSUE TITLE
Ability to add a custom ui5-suggestion-item for Input with show-suggestions

### ISSUE THREAD

**Issue by ekeyur** [SAP/ui5-webcomponents#5128]
### **Feature Request Description**
A clear and concise description of what feature is missing.
Is your feature request related to a problem? Please describe.

In case of showing suggestions, i would like to add a custom suggestions, something like a custom-li for listing the suggestions. I see there is an ability to create a ui5-suggestion-item, but that does not fulfill the need. Maybe a slot instead of or a child ui5-suggestion-item might fulfill the request. 

I would think this should work just like the ui5-custom-li under ui5-li. There is already a use case for displaying person card when searching for people in the search input. People have implemented this using handlebars, but i think should be part of the library.  

### **Proposed Solution**
A clear and concise description of the solution you would like to have.

### **Additional Context**
Add other context or screenshots related to the feature request here.
![image](https://user-images.githubusercontent.com/19393644/165361839-231c078c-7902-4cc5-9c4d-6d2756d6db26.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.
This is a part or 2211 release 
### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

This is a feature request I've dispatched to your component for review.

Best Regards,
Boyan Rakilovski

**Comment by nikolay-kolarov** [comment]
Hi,

Here is an update on the topic:
We started to work on the topic. Still, it is quite big and complex.
The current plan is to create a new component for suggestion list, then we will integrate it in the input and connect the whole story together.
And in order to do this with the needed quality, we would need more time.
We have already started the work on some initial POCs.

I will update the item with the progress and adjust the milestone (if needed) once we have more clarity.

Best Regards,
Nikolay

**Comment by nikolay-kolarov** [comment]
Hi,

After further digging into the topic, we realized that this could take even more time than initially anticipated.
We will need a full UX spec to cover the feature and we might even need to create a new component to support the use case.
I will keep you up to date.

Best Regards,
Nikolay

**Comment by nikolay-kolarov** [comment]
I am marking this item as blocked, as discussions with UX are ongoing and we will depend on when they will provide a spec.

**Comment by ilhan007** [comment]
Hello @ekeyur  
Since UI5 Web Components version 2 there is [SuggestionItemCustom](https://sap.github.io/ui5-webcomponents/components/SuggestionItemCustom/) available to add create custom suggestion like shown in the following [example](https://sap.github.io/ui5-webcomponents/components/Input/#custom-suggestions).

**Note:** keep in mind that version 2 is a new major version and there are also breaking changes to be adopted. Read more on version 2 [here](https://github.com/SAP/ui5-webcomponents/releases/tag/v2.0.0).
