### ISSUE TITLE
[SF]Cannot get the correct value of DateRangePicker after editing in the input box

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents#5137]
### **Bug Description**
Cannot get the correct value of DateRangePicker after editing in the input box.
We put the DateRangePicker inside a Dialog. When the close button of dialog is called, we want to get the current value of DateRangePicker. The code works fine in 1.0.2. But after upgrading to 1.2.4, we found out that if the user use keyboard to edit the value of DateRangePicker in the input box, at the time of closing dialog, we cannot get the updated value.

I created two code sandbox to show the problem.
@ui5/webcomponents version 1.2.4, do not work: https://codesandbox.io/s/falling-smoke-lytpx9?file=/src/App.js
@ui5/webcomponents version: 1.0.2, work as expected: https://codesandbox.io/s/gifted-violet-xilgek?file=/src/App.js

### **Expected Behavior**
After changing the value of DateRangePicker by editing the input box, when the user unfocuses the input box, we should be able to get the updated date range immediately.

### **Steps to Reproduce**
1. Open https://codesandbox.io/s/falling-smoke-lytpx9?file=/src/App.js
2. First open dialog, select a date range, click filter. The selected date is updated.
3. Then open dialog again, press Ctrl + A and Backspace key to clear the date range. Click filter. The selected date should be cleared. But it is not cleared.
![2022-04-28_13-43-53](https://user-images.githubusercontent.com/55808904/165684920-83b03934-3d75-4e3b-8f97-a229dacdbd18.gif)

### **Isolated Example**
https://codesandbox.io/s/falling-smoke-lytpx9?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.2.4
- OS/Platform: Windows 10
- Browser: Chrome Version 98.0.4758.54 (Official Build) beta (64-bit)
- Affected component: DateRangePicker

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP SuccessFactors
- Business impact: In the filter dialog of our application, after user uses keyboard to clear the selected date range, we cannot get the updated date range immediately at the time of closing the filter dialog.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Could you please look over the issue?
The "change" event is not fired when the value is empty. I tried in the components test page and I managed to reproduce the issue with small difference. When I select a range from the picker and move the focus somewhere else, then access the ui5-daterange-picker again, select the value with Ctrl + A and delete it, on focus out the "change" event is fired but after that on each next time that I repeat the mentioned steps it is not fired anymore with an empty value.
Please check the isolated samples provided from the reporter. The issue is reproducible from the first time as well there.

Thank you in advance!

Kind Regards,
Niya

**Comment by Todor-ads** [comment]
Hi @QiuranHu ,
We've submitted fix that solving the issue.
A problem is solved with this change: #5769
Best Regards,
Todor
