### ISSUE TITLE
ui5-card-header: a11y - Provide option to specify header title as link

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5138]
### **Bug Description**
This is followup for https://github.com/SAP/ui5-webcomponents/issues/4814#issuecomment-1050898637. It is closed without any update.
The whole header should not receive the tab focus if there is no role announced for it. Rather the title of the tile should get the first focus which can have the "link" role , then on next tab the focus should go to next focusable element.

### **Context**
- UI5 Web Components version: 1.1.0
- OS/Platform: NA
- Browser: Chrome
- Affected component: ui5-card-header

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/1995447/165687675-7c44e524-40d3-455c-a70b-29f16730ef80.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

Could you please check whether it is expected to have the focus over the title or over the whole header, as there were many discussions on that topic in the past?

Thank you in advance!

Kind Regards,
Niya

**Comment by GerganaKremenska** [comment]
Hello @BennyHuang,

The whole header SHOULD recieve the focus it does not matter if it is interactive or not.

This is the statment from the accessibility experts:
"After further consultation with our ACC experts, the behavior of having the focus on the card header is always correct. Even if the property headerInteractive is false.

This is recommended for two reasons:

The ARIA standard allows for inactive elements to be focusable in some contexts. Especially inside of composite widgets. In the case of the card header it is actually recommended, because if the header is not focusable, it will hide its presence from the screen reader users. If we do not focus the header aways we will loose some screen reader announcements. This is described in more details in this part of the [ARIA documentation](https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls).
A common usage of the cards is to have several of them on a single page - like a dashboard. If you have a mix of cards which are interactive and cards which are not interactive next to each other, we still want to be consistent in where the focus lands. This will make it easier for people with disabilities to navigate.
If you have further questions please reopen the issue."

aria-roledescription is added on both interactive and non interactive header.
![Screenshot 2022-04-29 at 11 47 27](https://user-images.githubusercontent.com/22882174/165914076-f897a801-6f50-415e-a0d8-3ab59605c080.png)
![Screenshot 2022-04-29 at 11 47 17](https://user-images.githubusercontent.com/22882174/165914084-40a11b65-7eb5-4cef-888c-438cb90c81aa.png)

If it is not announced it is a problem with the screen reader not with the Card component. We are following all aria-specifications.


Best Regards,
Gergana

**Comment by anuvenkatesh1** [comment]
@GerganaKremenska Could you please clarify one thing
"Especially inside of composite widgets. In the case of the card header it is actually recommended"
This is because you can facilitate arrow key navigation through the stack of cards if you can see here
https://ui5.sap.com/#/entity/sap.ui.integration.widgets.Card/sample/sap.ui.integration.sample.CardsLayout
which I apparently do not see in WC https://sap.github.io/ui5-webcomponents/playground/components/Card/
In a composite widget, arrow key navigation facilitates quick navigation through the cards. If we are adapting open UI5 specs for card header focus, shouldn't we also have arrow key navigation through the stack of cards via the card headers as in open UI5?

**Comment by GerganaKremenska** [comment]
Hello @anuvenkatesh1,

We are targeting the same accessibility for UI5 controls as UI5 webcomponents, so users can have the same look and feel regardles of the technology they are using. As far for functionality(arrow key navigation) which comes from othere UI5 controls, as the UI5 Card control does not support arrow navigation on its own., but this comes from the layout control. It is safe to say that we have the same behavior for UI5 web components Cards as UI5 control Cards.

Best Regards,
Gergana
