### ISSUE TITLE
[SF][ui5-dialog]: the header text does not adhere to Horizon design

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#5230]
### **Bug Description**
The header text does not adhere to Horizon design. 
Here is the design https://www.figma.com/file/SILcWzK5uFghKun9jx6D7c/Horizon-Web-UI-Kit?node-id=1101%3A2437 provided by our UX.
Here is sample page of sap ui5 https://sapui5.hana.ondemand.com/?sap-ui-theme=sap_horizon#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog

It seems font-family should be 72-Bold.

### **Expected Behavior**
The header text should adhere to Horizon design. 

### **Context**
- UI5 Web Components version: 1.3.1
- Affected component: ui-dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)
- Organization: SF

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rd   I am forwarding this issue to you, because:
"the [dialog](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2698913313) consumes the [bar design](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2698912554), and the bar header should consume the [--sapFontHeaderFamily](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2637291548), which results in bold headers."
