### ISSUE TITLE
[SF] TreeItem - Implement "disabled" property so that individual tree items can be prevented from being selected by the user

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#5254]
**Is your feature request related to a problem? Please describe.**
The Tree and TreeItem components allow the user to select an item. However, currently there is no option to disable the selection for a particular item, to prevent the user from selecting it (in case they do not have permission to select it, etc.).

**Describe the solution you'd like**
Implement a "disabled" property similar to that of the "checkbox" component.

**Comment by MarcusNotheis** [comment]
Thanks for reporting! I'll forward this issue to our UI5 Web Components Colleagues as the affected component is developed in their repository.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-p, have a look at this feature request.

**Comment by ilhan007** [comment]
Hello @jdichev @dobrinyonkov @PetyaMarkovaBogdanova
perhaps it's a good idea to raise this to the VD/UX colleagues, because as far I know, there is no such spec,
so before even planning, this should be specified. I even remember that such request has been rejected in the past for the ListItem, but it won't hurt to raise it once again. (And I guess if this is specified for the TreeItem, it will be also done for the ListItem and so on).

Thanks,
ilhan

**Comment by dobrinyonkov** [comment]
Hello,

This functionality is not implemented in UI5 and there are no plans to implement it in UI5 and in UI5 WebComponents, due to the following reasons:

- Consistency to other applications which does not have disabled actions.
- The selection is the base for many different kinds of actions (e.g. also things like copy or D&D). Some actions would work with the items, others not.
- The user does not get the information why the item (list) can not be interacted.
- Similar behavior like on Windows File Explorer, etc. - you can mark some file but maybe you can not delete it (e.g. it is currently opened).
- Special ACC handling required. ARIA does no have build-in support for "only some" selectable items.
Issues in support of mass data handling cases - select all, range selection, ...

The recommendation is to solve this either by additional visualizations (for states) or via information to the user when an action is triggered, see e.g:
https://experience.sap.com/fiori-design-web/responsive-table/#enablingdisabling-actions

Best Regards,
Dobrin
