### ISSUE TITLE
[SF] [ui5-table] Growing button doesn't take full width in MultiSelect mode

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#5272]
### **Bug Description**
When using the `ui5-table` with the growing button feature and the `MultiSelect` mode, the "Show More" button width is incorrect and stops before the last column (see screenshot below)

<img width="689" alt="Screen Shot 2022-05-24 at 4 25 44 PM" src="https://user-images.githubusercontent.com/7316793/170149031-b1448943-d496-492b-a93d-e75446d65905.png">

### **Expected Behavior**
The width of the Growing Mode Button should take the full width of the table regardless of the selection mode selected.

### **Isolated Example**
See an example here:
https://codesandbox.io/s/ui5-webcomponents-forked-7j1f8r?file=/index.html

The background color applied on the table shouldn't be visible.

### **Context**
- UI5 Web Components version: latest
- OS/Platform: MacOS
- Browser: Google Chrome
- Affected component: ui5-table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by terezamch** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

When the Table is in MultiSelect mode and with growing on, the growing area button is smaller that it should be (see screenshot above).

Here you can see the issue: https://codesandbox.io/s/ui5-webcomponents-forked-7j1f8r?file=/index.html
The issue is reproducible in the [playground](https://sap.github.io/ui5-webcomponents/playground/components/Table/) too with the 5th sample named "Growing Table with "More" button" if you change the mode to MultiSelect.

Maybe the colspan property of the td tag of the growing button area should be increased by 1, when the table is in MultiSelect mode.

So, please have a look.

Best regards,
Tereza

**Comment by niyap** [comment]
Hello Colleagues,

The issue is already known and fixed #5256

You can check in the Playground changing the mode to MultiSelect of "Growing Table with "More" button" sample

Kind Regards,
Niya
