### ISSUE TITLE
TreeItem: Style prop is not applying to component

### ISSUE THREAD

**Issue by yoshitamagoshi** [SAP/ui5-webcomponents#5346]
**Describe the bug**
When a `style` prop is applied to the `TreeItem` component it does not modify the components style.

**Isolated Example**
[Code Sandbox demonstrating issue](https://codesandbox.io/s/thirsty-mcclintock-qpnlwu?file=/src/App.js)

**To Reproduce**
1. Go to [Code Sandbox demonstrating issue](https://codesandbox.io/s/thirsty-mcclintock-qpnlwu?file=/src/App.js)
2. Observe that TreeItem's are not bold

**Expected behavior**
Bold TreeItem text.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: See Code Sandbox
`@ui5/webcomponents-react` version: See Code Sandbox
Operating System: See Code Sandbox
Browser: See Code Sandbox

**Comment by yoshitamagoshi** [comment]
Thank you @Lukas742!

**Comment by ilhan007** [comment]
Hello @yusmenrashidov unfortunately you can't just add style or class to the TreeItem as it has not its own DOM, it's abstract due to specifics of the Tree web component. Based on the TreeItem props we render TreeListItems.

One thing that may work for you, depending to what extent you want to customize is to make use of the CSS Shadow parts we offer.

part="native-li" the container, the item rectangle
<img width="245" alt="Screenshot 2022-06-10 at 09 22 42" src="https://user-images.githubusercontent.com/15702139/173003508-67a660ed-79c0-4c13-a625-b22f42205a58.png">

part="title"
<img width="377" alt="Screenshot 2022-06-10 at 09 23 12" src="https://user-images.githubusercontent.com/15702139/173003581-f0c8f43d-112f-4df9-a5d6-be634c6215ae.png">

part="additional-text" (if you have additional-text set)
<img width="553" alt="Screenshot 2022-06-10 at 09 24 14" src="https://user-images.githubusercontent.com/15702139/173003744-55114871-dc39-4e61-b8cf-82d53309bd31.png">


You can make use of  standard [CSS Shadow parts selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) to apply styles to these DOM elements.

```css
ui5-li-tree:part(native-li) {
    font-weight: bold;
}
```
<img width="240" alt="Screenshot 2022-06-10 at 09 27 04" src="https://user-images.githubusercontent.com/15702139/173004145-51a4d76e-06df-47f0-93dd-e8d35865398c.png">
