### ISSUE TITLE
Support for custom icons

### ISSUE THREAD

**Issue by PMudra** [SAP/ui5-webcomponents#5347]
### **Issue Description**
I wonder if it is currently possible and supported to register custom icons?
I want to be able to provide an icon collection and use the icons everywhere I can usually use icons in ui5 web components (e.g. ui5-icon, ui5-button, etc).
The icon collection I want to use provides an icon font and also svgs.

I tried using the `registerIcon` function that I have found in the source code.
That function seems to be used internally by the ui5 icons collections.

One problem with that approach is that the provided svgs are not as "clean" as the SAP icons. They sometimes consist of more than a single path element. So I can't really use `registerIcon`.

Is there another (obvious) approach to register a custom icon collection?
If so, some documentation would be highly appreciated.
If not, I would like to request a new feature that allows me to register custom icons.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @PMudra 
with this change https://github.com/SAP/ui5-webcomponents/pull/5630 we described how you can register custom SVG icon collection and furthermore we allow usage of SVGs with multiple paths.

It's going to be released at the end of the month with 1.7.0

BR,
UI5 WC Team

**Comment by PMudra** [comment]
Hello @ilhan007,
thank you for working on this issue. The new documentation helps a lot.

In my original post I have said:

> One problem with that approach is that the provided svgs are not as "clean" as the SAP icons. They sometimes consist of more than a single path element. So I can't really use registerIcon.

To be honest, this was not a very good description of my issue. Let me say that the icon svgs that I have to use are structured in an unpredictable way:

* I might have many `path` elements in the svg
* `path` elements might be grouped in a `g`
* There might be other elements like `polygon`, `rect` and `circle`
* The `viewBox` of the `svg` tag is **not** fixed to `"0 0 512 512"`
* Some `style` information might be included

I believe some (and maybe all) of this "unpredictable" content can be addressed by processing each svg and generate a clean svg that only has a single path. But this does not seem like a feasible solution to me (?).

So my question is: can you also enable registering custom "full" svg files as icons?

I would be happy to create a new feature request if this is something you would consider. I'd also be happy to assist and provide more information you need.

**Comment by PMudra** [comment]
> I believe some (and maybe all) of this "unpredictable" content can be addressed by processing each svg and generate a clean svg that only has a single path.

I have tried out some things and I have found this tool which seems to be used by many other libraries under the hood: https://github.com/svg/svgo. I might be able to use this to create optimized svgs that consist only of one or multiple `path`s.

But still the `viewBox` would not be the same. Now again, I might be able to find a tool to transform the paths data. But maybe as a small fix in your code, you could make the `viewBox` configurable? If you do not have the time, would you accept a pull request for that change?

**Comment by pskelin** [comment]
@PMudra this certainly makes sense, i see a lot of optimized icons that use SVG features and a single path is not sufficient.

We will extend the framework to accept custom icons. It is a bit tricky that we need to render the `svg` tag for adding accessibility features and let the developer add some custom content. It will look something like this in code:

```svg
<g fill="none" stroke="currentColor" stroke-width="2">
    <path stroke-linecap="round" stroke-linejoin="round" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" fill="aqua"/>
    <path stroke-linecap="round" stroke-linejoin="round" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
</g>
```

and then this is what will be rendered:
<img width="56" alt="Screenshot 2022-08-29 at 11 14 55" src="https://user-images.githubusercontent.com/11073377/187155942-2aacf67a-ffcf-43e5-84e7-7f2567ace1bd.png">

and the corresponding DOM
<img width="507" alt="Screenshot 2022-08-29 at 11 15 50" src="https://user-images.githubusercontent.com/11073377/187156187-a7693559-a3bc-41d5-bc73-155d67a5551b.png">

You get to define a `<g>` element, where you can apply all attributes like `stroke` and `fill` that could be declared on an SVG tag. The the ui5-icon will render the corresponding svg like it does now but put the custom content inside. Also notice this icon has a `0 0 24 24` viewport, so that should become customizable as well.

Passing a style element might make the API too complex, and this could also clash with CSP security where inline styles are not allowed. I propose that in cases you need to style individual elements of the icon, you use attributes directly like i show in the example with `fill="aqua"`.

Would that cover all of your requirements? Any additional feedback is welcome during the implementation.
