### ISSUE TITLE
Token component document is missing

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents#5352]
### **Issue Description**

Token document exists in ui5-webcomponents-react:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-token--default-story

But is missing in ui5-webcomponents:
https://sap.github.io/ui5-webcomponents/playground/components/Token

Code:
https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/Tokenizer.js

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by ilhan007** [comment]
Hello @TinaC 

The Token is not meant to be used standalone, but as part of the MultiInput web component, that's why it is documented as part of the MultiInput web component API

Go to https://sap.github.io/ui5-webcomponents/playground/components/MultiInput/ and scroll to the bottom of the page after the MultiInput's API
<img width="917" alt="Screenshot 2022-06-10 at 08 38 00" src="https://user-images.githubusercontent.com/15702139/172997702-d8c6209b-09d6-40e7-8adc-bac95cdfd946.png">
