### ISSUE TITLE
ui5-messagestrip close button aria label reads "Decline" instead of "Close"

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5386]
### **Bug Description**
The close button of the message strip reads "Decline" instead of "Close" which can cause confusion for non-sighted users, since the name doesn't reflect the action.
The "Decline" message is also read out twice.

### **Expected Behavior**
Expect the message strip close button to have aria label with "Close" instead of "Decline" like the one in UI5: https://sapui5.hana.ondemand.com/#/entity/sap.m.MessageStrip/sample/sap.m.sample.MessageStrip

### **Steps to Reproduce**
0. Using a screen reader (JAWS or NVDA)
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/MessageStrip/
2. Tab to the close button of the first message strip
3. Notice the screen reader outputs:
"Information Bar Closable Information MessageStrip Decline Note"
"Decline Button"

### **Context**
- UI5 Web Components version: 1.4.0
- Affected component: ui5-messagestrip

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SuccessFactors

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please take a look at this case? @SAP/ui5-webcomponents-topic-rl 

I see that the icon root has a aria-label="Decline" and this might cause the addition of the "Decline" to the information read out.

Best Regards,
Tsani

**Comment by ivoplashkov** [comment]
Hello,

The issue seems to be caused by the ui5-button, since when a tooltip is set, the button is setting role="img" to the icon which is incorrect, also aria-label should not be present in this case. Тhis leads to incorrect speech output of the icon’s aria-label “Decline” instead of the tooltip of the Button. In UI5, when an icon only button has a title, the icon is rendered with role presentation and no aria-label.

Best regards,
Ivaylo
