### ISSUE TITLE
Click ESC will close whole ui5-dialog when focus on the popup menu of ui5-select when JAWS open

### ISSUE THREAD

**Issue by mydavidzhang** [SAP/ui5-webcomponents#5403]
### **Bug Description**
Click ESC will close whole ui5-dialog when focus on the popup menu of ui5-select when JAWS open. 
NOTE: without JAWS open click ESC will correctly only close popup menu.

### **Expected Behavior**
Expected is menu closed only and dialog will be still open. 

### **Steps to Reproduce**
1. Create one ui5-dialog which contains ui5-select. 
2. Open JAWS and then open the dialog. 
3. Use keyboard to open select menu and focus on one option, then click ESC. 
4. Whole dialog is closed. 

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-hwhj6o?file=/index.html

### **Context**
- UI5 Web Components version: 1.4.0. "@ui5/webcomponents-react": "~0.25.0",
- OS/Platform: Windows
- Browser: Chrome

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: Successfactors

**Comment by tsanislavgatev** [comment]
Hello. @mydavidzhang ,

I've tried both options. With and without JAWS(2022), and the behaviour is the same, only the select is closed and the popover needs one more press of the ESC button to close.

Can you please re-test it on your side?
And if the issue is still reproducible, can you provide more information like JAWS version and anything helpful to reproduce the issue?

Best Regards,
Tsanislav

**Comment by mydavidzhang** [comment]
Hello. @tsanislavgatev, this issue could be close since we verified JAWS 2022 works fine. Thanks
