### ISSUE TITLE
DatePicker: ‘Next’ and ‘Previous’ buttons within the calendar are not reachable via keyboard

### ISSUE THREAD

**Issue by sparkypro** [SAP/ui5-webcomponents#5406]
**Describe the bug**
The ‘Next’ and ‘Previous’ buttons within the calendar are not reachable via keyboard

**UI Link**
visit https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-datepicker--default-story

**To Reproduce**
1. Go to DatePicker
2. Use keyboard tab key to reach next/previous arrow buttons

**Expected behavior**
The ‘Next’ and ‘Previous’ buttons within the calendar are not reachable via keyboard

**Screenshots**
<img width="106" alt="image" src="https://user-images.githubusercontent.com/108118034/175528233-d0f85677-1d17-4ca9-b69a-1af4605932e2.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.3.1
`@ui5/webcomponents-react` version: 0.23.2
Operating System: Windows 11
Browser: Chrome

**Comment by pskelin** [comment]
That's by design, it works the same way in UI5 as well
https://sapui5.hana.ondemand.com/#/entity/sap.m.DatePicker/sample/sap.m.sample.DatePicker

This is because Page Up / Page Down change the month/year/year range which is faster and more convenient than tabbing to the arrows and pressing enter (one click vs two).

Please check the bottom of the page you linked for ui5-webcomponents-react, as well as the ui5-webcomponents, section "keyboard navigation".

Note that the same goes for opening via keyboard - you use F4/Alt-down instead of tabbing to the calendar icon and pressing enter.
