### ISSUE TITLE
Combobox: User should be able to filter additional text too

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#5423]
**Is your feature request related to a problem? Please describe.**
Customer has raised a requirement to allow the user to filter the combobox options based on both text and additional texts too. Currently, user can filter only based on data passed in text property. 

**Describe the solution you'd like**
combobox should provide filtered data even if the filter input is present in additional texts.

**Comment by nnaydenow** [comment]
Hi @SAP/ui5-webcomponents-topic-rl,

Could you please take a look? In SAPUI5 / OpenUI5 you can filter additional text if Contains filter is used but in ui5-combobox it is not possible.

Regards,
Nayden

**Comment by PriyaPowar** [comment]
Hi @gmkv, 
Any update regarding when this feature would be available. I need to provide a time line to the customers.
Regards,
Priya

**Comment by nikolay-kolarov** [comment]
Hi @PriyaPowar,

We have checked if this is possible to be done with the current APIs on the component, but at the moment this is not feasible.
So we will need to spend more time and decide how to add support for this case.

I need more info in order to see when to execute the tasks: How do you see this from priority perspective and what are the expectations of the customer?

Thanks,
Nikolay
