### ISSUE TITLE
MultiComboBox: ReadOnly hides data

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents#5540]
**Describe the bug**
When the MultiComboBox is in readOnly mode, the data selected previously is hidden. 

**Expected behavior**
The data must be visible when the MultiComboBox is in ReadOnly mode.
<img width="1792" alt="Screenshot 2022-07-20 at 15 17 00" src="https://user-images.githubusercontent.com/54435646/179952440-84b29d47-f7a8-4b4a-aaeb-61acf5deaeed.png">

**Comment by stbodurov** [comment]
Hi @I516406,

This behavior is actually coming from the way [Storybook](https://storybook.js.org/) (the documentation engine and UI explorer) works. Every time you change a property using a "control" (the `[Set Boolean]` button next to `readonly`), it reloads the whole component, instead of simply rerendering it.

Even if you were to do this on a completely unrelated component, like `ui5-input`, it will do the same. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story and type something, then toggle the readonly property - the data is lost.

If you try inspecting the MultiComboBox and setting the `readonly` property by adding an HTML attribute, no data will be lost.

Regards,
Stanislav
