### ISSUE TITLE
[SF] TableRow - Implement "disabled" property so that individual rows can be prevented from being selected by the user when the table is in MultiSelect mode 

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#5649]
### **Feature Request Description**
The Table component allow the user to select multiple rows in MultiSelect mode. However, currently there is no option to disable the selection for a particular row, to prevent the user from selecting it (in case they do not have permission to select it, etc.).

### **Proposed Solution**
Implement a "disabled" property similar to that of the "checkbox" component. When the check all button of the table is clicked, all the rows except for the disabled rows would be checked.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by jatinthaker** [comment]
What is the plan on fixing this issue? Priority of medium is ok. In agreement with Stoehr.

**Comment by ilhan007** [comment]
Hello @jatinthaker to my knowledge, there is no VD design for **disabled** state of the TableRow.
So, first this should be raised to the SAP Design, and specified before planning and implementing.

@nikolay-kolarov do you plan to include this in the UX/VD regular sync?

BR,
ilhan

**Comment by nikolay-kolarov** [comment]
Hello,

This functionality is not implemented in UI5 and there are no plans to implement it in UI5 and in UI5 WebComponents, due to the following reasons:
* Consistency to other applications which does not have disabled actions.
* The selection is the base for many different kinds of actions (e.g. also things like copy or D&D). Some actions would work with the items, others not.
* The user does not get the information why the item can not be selected.
* Similar behavior like on Windows File Explorer, etc. - you can mark some file but maybe you can not delete it (e.g. it is currently opened).
* Special ACC handling required. ARIA does no have build-in support for "only some" selectable items.
* Issues in support of mass data handling cases - select all, range selection, ...

The recommendation is to solve this either by additional visualizations (for states) or via information to the user when an action is triggered, see e.g:
https://experience.sap.com/fiori-design-web/responsive-table/#enablingdisabling-actions 

Best Regards,
Nikolay
