### ISSUE TITLE
Option to disable individual checkbox in a multiselect table based on a state or boolean value.

### ISSUE THREAD

**Issue by crollioac** [SAP/ui5-webcomponents#5662]
### **Feature Request Description**
Currently we cannot disable select box/checkbox in a table with multiselect mode. If we want to block user from selecting particular row based on some condition then we cannot do it with available features.

### **Proposed Solution**
An option to disable/enable particular checkbox based on a condition in the rowdata object. In multiselect mode all the select boxes can be enabled but we should be able to disable if don't want user to select based on some condition. 
Eg. rowData.enabled = false should disable the select box of that row. 

### **Additional Context**
In this screenshot, we want to disable only the colored selectbox.
![table_ss](https://user-images.githubusercontent.com/4299153/184097778-867cfd89-4de6-45b7-b3df-027cc38b96ca.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SAP successfactors}
- Business impact: {Currently we are not able restrict users from selecting incorrect rows based on the status of the row}

**Comment by hristop** [comment]
Hi @crollioac ,

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.
 
The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.
 
While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.
 
However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.
 
We are excited about the opportunities this transition will bring and the positive impact it will have on our product.
 
Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.
 
Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component. 

Best Regards,
Hristo

**Comment by simlin** [comment]
Hi @crollioac ,

disabling the selection for certain items came up already several times in the past in the context of UI5 classic controls and it was declined from our design area. The reasons were mainly
* Consistency to other applications which does not have disabled actions.
* The selection is the base for many different kinds of actions (e.g. also things like copy or D&D). Some actions would work with the items, others not.
* The user does not get the information why the item can not be selected.
* Similar behavior like e.g. in a File Explorer, etc. - you can mark some file but maybe you can not delete it (e.g. it is currently opened).
* Special ACC handling required. ARIA does no have build-in support for "only some" selectable items.
* Issues in support of mass data handling cases - select all, range selection, ...

Therefore such a functionality does not exist for a list or table in UI5 classic and there are also no plans to change this so far. 

The recommondation is to solve this either by additional visualizations (for states) or via information to the user when an action is triggered, see e.g.
https://experience.sap.com/fiori-design-web/responsive-table/#selection

Best Regards
Jens
