### ISSUE TITLE
Draggable dialog

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents#5668]
**Describe the bug**
Content inside a draggable dialog is not selectable using mouse drag.

**To Reproduce**
1. Go to [Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story).
2. Set the **draggable** property of dialog as **true**.
3. Try selecting the dialog content with mouse drag.

**Expected behavior**
The text should get selected.

**Screenshots**
![A7652889-893D-40B7-A5FB-E683E4868C52_1_201_a](https://user-images.githubusercontent.com/93638146/184282167-65f5ea33-0e8e-4889-b426-0b5a3c4f260f.jpeg)

**Comment by gmkv** [comment]
This is a weird one.

The only way not being able to select text inside the dialog is if the attribute `draggable` has a value `true`:
```html
<ui5-dialog draggable="true">...</ui5-dialog>
```
[Sample](https://codesandbox.io/s/ui5-webcomponents-forked-0e4ohd?file=/index.html)

If it has the attribute `draggable` without any value to it, text selection of the content works as expected.
```html
<ui5-dialog draggable>...</ui5-dialog>
```
[Sample](https://codesandbox.io/s/ui5-webcomponents-forked-4tyykd?file=/index.html)

Is this a browser bug?

**Comment by gmkv** [comment]
No. It turns out to be a clash with the HTMLElement attribute draggable which clearly defines that is can accept `"true"` or `"false"` and the browser will provide additional interaction.
Setting `draggable="true` to the ui5-dialog element will cause the browser to have its own "drag event handler" which listens on the whole element, and any drag action on the element (except for the header, where we have set our own drag handler) will make the whole element dragged.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

@Lukas742 To fix this in ui5-webcomponents-react, do not set `"true"` to the attribute `draggable`.

We have not explicitly stated in [the documentation](https://sap.github.io/ui5-webcomponents/playground/getting-started/understanding-components-apis/#properties) that a boolean property should have the string `"true"` in its HTML. I don't think it is appropriate for this indicidental use to be fixed/prevented on the ui5-webcomponents side.

**Comment by Lukas742** [comment]
Hi @gmkv 

thanks for the explanation, but this is not only an issue with the wrapper, but with React in general. When you set a React prop without value, it defaults to `true`. So for React it wouldn't be possible to bind it without value in the React way, you would have to set `draggable` to an empty string (or actually to any unsupported string which includes all strings except "true" and "false").

https://codesandbox.io/s/wc-react-template-forked-3fnk5j?file=/src/App.js

As the linked docs of the global `draggable` attribute mentions, it should also always receive a value, otherwise it has no effect and the default behavior will be used.  That's why it's working in the playground. 
I guess its main goal is to tell the underlying header element, that it's draggable, but as it still is a global attribute, I would suspect that you should use it in the same way as it's described natively.

Also, in the [description](https://sap.github.io/ui5-webcomponents/playground/components/Dialog/) of the prop, you state that it's only draggable if it's set to true:
> Determines whether the component is draggable. If this property is set to true, the Dialog will be draggable by its header.
And the type should be boolean which is also wrong then.

This also deviates from the supposed usage.

If the behavior is intended, I would expect at least a note in the description, that it doesn't follow the native implementation and also that it's necessary that no value is set (to disable the native behavior). Also the type needs to be adapted as it's not pure `boolean`.
In my opinion it would be better to disable the native behavior, or create a new prop so it doesn't use the native behavior, as in the current way it's very confusing for users and also cannot be used in React like every other boolean property. 

Btw, the SAPUI5 Dialog doesn't use `draggable` at all, probably for the same reason ;)

**Comment by pskelin** [comment]
discussed to rename this attribute as it should not collide with HTML attributes.
working proposals:
- rename to some synonym like `movable`, `floating`, ... more suggestions from team
- change default to always draggable and make property `static`, `fixed` or some other name
  - this will introduce a tab stop on the header that is not there with `draggable=false`. We can either accept this or make the header tab stop be the last one after the content is tabbed.

**Comment by TeodorTaushanov** [comment]
Hi @Bilal3120,

The issue is fixed in the "main" branch. When

`<ui5-dialog draggable="true"`

only the ui5-dialog custom logic ("draggable by its header") will work.

Please, note that in our case the "draggable" property is a boolean type. To represent a false value, the attribute has to be omitted altogether.

Best,
Teo
