### ISSUE TITLE
ui5-menu change text color

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#5739]
Hello,

I just created a ui5-menu component with the html code below:

```
<ui5-menu id="basicMenu">
  	<ui5-menu-item text="New Workspace" id="newWorkSpaceSubmenuItem" icon="dimension" ></ui5-menu-item>
  	<ui5-menu-item text="Rename Workspace" id="renameWorkSpaceSubmenuItem" icon="activate" ></ui5-menu-item>
  	<ui5-menu-item text="Store Workspace" id="storeWorkSpaceSubmenuItem" icon="drill-up" ></ui5-menu-item>
  	<ui5-menu-item text="Delete Workspace" id="deleteWorkSpaceSubmenuItem" icon="contacts"></ui5-menu-item>
  </ui5-menu>
```

I would like to change the text and the icon color of ui5-menu-item . I tried the code below but it did not work.

```
<ui5-menu id="basicMenu">
  	<ui5-menu-item text="New Workspace" id="newWorkSpaceSubmenuItem" icon="dimension"  style="color: #fff;"></ui5-menu-item>
  	<ui5-menu-item text="Rename Workspace" id="renameWorkSpaceSubmenuItem" icon="activate"  style="color: #fff;" ></ui5-menu-item>
  	<ui5-menu-item text="Store Workspace" id="storeWorkSpaceSubmenuItem" icon="drill-up"  style="color: #fff;" ></ui5-menu-item>
  	<ui5-menu-item text="Delete Workspace" id="deleteWorkSpaceSubmenuItem" icon="contacts"  style="color: #fff;"></ui5-menu-item>
  </ui5-menu>
```

Is there any solution to this issue?

Best,
George

**Comment by ndeshev** [comment]
Hello @geokas7 
You can change the appearance of the Web Components by using [Using CSS custom properties (variables)](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

For example, in your case you have to change the value of the CSS parameters for the menu item text which is `--sapTextColor ` and the icon - `--sapContent_NonInteractiveIconColor`.

You can do that in the header of the page creating another style element like:

	<style>
		* {
			--sapTextColor: red;
                        --sapContent_NonInteractiveIconColor: blue;
		}
	</style>

**Comment by ilhan007** [comment]
Hello @geokas7 I wanted to add some general thoughts on styling web components.

One of the core principles of Web Components is the **encapsulation**. The html and styles are encapsulated in the ShadowDOM, this avoids clashes with any css, brought by the rest of the app, but also makes custimization harder.

However there are some general patterns to style web components:

- **Styles on tag level**: we designed some components such as Title, Label, Badge, Input and few more in such way, that it is possible to set styles/classes on the custom elements like “ui5-input {color: red}” that will take effect.
 You can try this yourself here: https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Input/

- **Shadow Parts** : For more complex components, the styling on tag level is not possible, therefore we introduced shadow parts on specific elements in the components’ Shadow DOM, that the user can restyle, using standard CSS syntax for shadow parts
For example: you can change the appearance of the Card’s heading, subheading and status with the CSS shadow parts syntax:
```css
  #myCard::part(status) {
    color: red;
  }
```

- **Changing CSS Vars:**  The UI5 WebComponents leverage CSS variables, so if you inspect the elements, you will probably find which variable you need to change.
This the list of all Base CSS Variables, that we use in the components - you can see it [here](https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/css_variables.css).
Sometimes, we define some internal variables with prefix --ui5_* (they are not in the list), you may see them, they are private in a sense, but still you can alter their value the same way.

- **Custom Theme schema:** To change the entire colour scheme, the users can create their own theme. 
More details on how to do that, you can find here:
https://sap.github.io/ui5-webcomponents/playground/customizing/theme/

- **JS API: addCustomCSS**
We have added a special method that can insert CSS for any of our web components. 
You can import & use it like this:
```js
import { addCustomCSS } from "@ui5/webcomponents-base/dist/Theming";
addCustomCSS("ui5-select", ".ui5-select-root { background-color: red; } ");
```

**_Note_**: This is rather private API, so use this method with caution, because it might be changed/removed in the future.



Best,
ilhan
