### ISSUE TITLE
ui5-dialog with state and footer: Inconsistent announcement with NVDA

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#5781]
### **Bug Description**
When using the `ui5-dialog` with a footer and the `state` attribute, the aria announcements with NVDA are inconsistent:
When using state `None`, `Success` or `Information`, the dialog content is not announced:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/8775211/188372339-6b2d9eac-3120-4f87-9869-9a0dfb8647a8.png">

Using the state `Warning` or `Error`, the content is announced:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/8775211/188372420-dd01aed6-2710-4af5-9d2d-cecb48aa5763.png">

In addition I recognised that the announcement of the dialog content is always working fine if I don't render the footer.

### **Expected Behavior**
Dialog Content show be announced in all value states. Otherwise, you could also add a `accessibleRole` attribute which would allow to set `role="alertdialog"` by the user.

### **Steps to Reproduce**
1. Open https://codesandbox.io/s/unruffled-meadow-fdqmmi?file=/src/App.js
2. Click on the individual buttons and listen to the NVDA screen reader

### **Isolated Example**
https://codesandbox.io/s/unruffled-meadow-fdqmmi?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.7.0
- OS/Platform: Windows 10
- Browser: Edge 105
- Affected component: `ui5-dialog`

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React

**Comment by MarcusNotheis** [comment]
Having looked a little further into this issue, I think adding the `accessibleRole` attribute would be the best solution for our use case (building a MessageBox of top of the `ui5-dialog`).

**Comment by LidiyaGeorgieva** [comment]
Hello @MarcusNotheis I think the solution is described by GerganaKremenska here: https://github.com/SAP/ui5-webcomponents/issues/5350
Please try it and confirm.

**Comment by MarcusNotheis** [comment]
Hey @LidiyaGeorgieva,
I think this is a different issue:
In #5350 it was about that the Dialog is not reading the content at all, here it is depending on the `state` attribute: The content is read out when using the `Warning` and `Error` state, but not in the other states.
And, there's also a feature request about supporting the `accessibleRole` attribute.

**Comment by LidiyaGeorgieva** [comment]
Hello @MarcusNotheis , thank you for creating separate issue for the feature request.

For the current issue:
The goal is _"Dialog Content show be announced in all value states."_
The solution is _"When we have static content in the dialog we should add a reference to it with accessibleNameRef"_

I tested with Jaws and NVDA and they read the dialogs differently.
Jaws don't read the content in all cases, so I suspect the announcement from NVDA for the "warning" and "error" states is interpretation from the screen reader.

_"In addition I recognised that the announcement of the dialog content is always working fine if I don't render the footer."_ - yes, when you remove the footer you remove the only focusable element in the dialog (the button). This is expected behavior.
