### ISSUE TITLE
[RadioButton] Cannot receive focus if dynamically rendered with JSX

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents#5803]
**Describe the bug**
Hi team,

When a Radio button group is dynamically rendered with JSX, you are not able to focus on any of the buttons. However, if you wrap the radio buttons in a div and control the display of the div via css class dynamically, then it is able to focus.

**Isolated Example**
Issue reproducible -> https://codesandbox.io/s/suspicious-moore-w4pfym?file=/src/App.js:493-1021
Workaround control display with css class -> https://codesandbox.io/s/jolly-fast-bc91hb?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/suspicious-moore-w4pfym?file=/src/App.js:493-1021
2. Tab to the switch. Enter to show the secondary options. Tab to the secondary options.
3. From my trials, the first time will work. Now tab back to the switch. Enter to hide the options. Enter again to show the options
4. Tab to the secondary options. You should find that you are unable to focus on the radio buttons

**Expected behavior**
Keyboard only users can tab to radio button groups when they are dynamically rendered. 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27
Operating System: w10
Browser: Only tested on Chrome

**Comment by tsanislavgatev** [comment]
Hello @allen138 ,

I am not able to reproduce the issue. I can focus both of the radio button groups in both of the samples.

Can you please check again, and if it's still not reproducible, can you give more details?

Best Regards,
Tsanislav

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,
This issue is reproducible.
Upon re-rendering of the radio group, at least one of the radio buttons, should get tabindex="0", but this doesn't happen.

To reproduce:
https://codesandbox.io/s/ui5-webcomponents-forked-dx3uqp?file=/src/index.js
 1. Flip the switch to add the radio buttons in the DOM.
 2. Focus the radio button group with Tab.
 3. Flip the switch again to remove them from DOM.
 4. Focus the radio button group with Tab - this time it won't work.
