### ISSUE TITLE
Tree Component missing navigation option in mode prop

### ISSUE THREAD

**Issue by stefanomantova** [SAP/ui5-webcomponents#5816]
**Describe the bug**
When checking the documentation and use cases of Tree component on WebComponents for React and comparing it to the Fiori Guidelines, it seems to not be possible to include Icon `"navigation-right-arrow"` in `mode` prop, which should be possible according to the navigation section of Fiori Guidelines:

https://experience.sap.com/fiori-design-web/tree/
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--default-story

**Expected behavior**
The navigation icon should be available as an option for `mode` prop according to Fiori Guidelines.

**Screenshots**
![image](https://user-images.githubusercontent.com/44717272/190259394-d5864382-d6c1-41cb-a5ea-0d3f15e028a4.png)
![image](https://user-images.githubusercontent.com/44717272/190259681-aa17c80d-0864-4529-b78c-d645ad3ef3b3.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-p ,

I mark this issue as a feature request since I don't think it was implemented in the first place.

The user wants to have an option to have a navigation arrow at the right end of a given tree item.

In OpenUI5 this is achieved with 'type' property to the StandardTreeItem with value 'Navigation'.

I noticed that in SAP WC the navigation visual effect works a bit different.
In the [List Sample](https://sap.github.io/ui5-webcomponents/playground/components/List/) you can see that we add two attributes to the 'ui5-li' web component tag. The a attributes are 'icon="navigation-right-arrow"' and 'icon-end'.
Unfortunately this doesn't work as expected with a TreeItem component.

Could you please decide how we should expose this functionality since it's available in the OpenUI5, and more importantly it's available in the 'ui5-li' (List Item) component.  We also promote it in our Guidelines.

Regards,
Plamen Ivanov

**Comment by dobrinyonkov** [comment]
Internal reference: BGSOFUIPIRIN-5916

**Comment by dobrinyonkov** [comment]
PR is merged https://github.com/SAP/ui5-webcomponents/pull/6024
