### ISSUE TITLE
ui5-dialog: footer has extra border-top when using ui5-bar

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#5823]
### **Bug Description**
When a ui5-bar is used in the ui5-dialog footer slot, there is an extra border-top. 

### **Expected Behavior**
If a bar with design="Footer" is inside a dialog "footer" slot, it should not have a border-top because the slot already has it.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-x9ui4f
2. Open dialog
3. Notice the footer has an extra border-top

### **Context**
- UI5 Web Components version: 1.7.1
- Affected component: ui5-bar, ui5-dialog

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info**

- Organization: SuccessFactors

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rd ,

I am forwarding this issue to you, because the top border of the Bar is correct by visual specification (with "Footer" design).

My only guess is that it should be removed in the cases when it's slotted in the Dialog's Footer (therefore in the Dialog style files).

If you think that the top border should be removed from the Bar's side, please don't hesitate to forward the issue to team Balkan.

Regards,
Plamen Ivanov
