### ISSUE TITLE
[SF][A11Y][Button] - JAWS Repetitive announcement when button is in disabled state

### ISSUE THREAD

**Issue by zijies1** [SAP/ui5-webcomponents#5839]
### **Bug Description**
"Button unavailable" is announced twice by JAWS.

### **Expected Behavior**
"Button unavailable" should only be announced once.

### **Steps to Reproduce**
1.  Go to https://sap.github.io/ui5-webcomponents/playground/components/Button/
2. Open JAWS version greater than 2020 with virtual PC cursor mode on
3. Press tab to focus on default button 
4. Press arrow down key twice
5. "Button unavailable" is announced twice by JAWS.

### **Isolated Example**
If possible, please provide an isolated example by forking [CodeSandbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html).

### **Context**
- UI5 Web Components version: 1.6.0
- OS/Platform: Windows 10
- Browser: Chrome
- Affected component: Button

### **Log Output / Stack Trace / Screenshots**
https://user-images.githubusercontent.com/25004172/191692971-5d2bf2c7-26f5-4fe4-a39d-d8d395aaa2b4.mp4

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization:  SuccessFactors

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-b , 

It seems like the virtual cursor focuses the outer line (button itself) when it first lands on it, and then a second time the inner text which seem to trigger a second speech out (incorrect).

Could you please look it up?

Regards,
Plamen Ivanov

**Comment by NHristov-sap** [comment]
Hi @zijies1 ,

Unfortunately, this is a JAWS issue, and we already know about this, because the same happens in the Classic UI5 too. It does not depend on UI5 or UI5 Web Components, it is reproducible even with plain HTML, you can check this sandbox:

[https://codesandbox.io/s/vb0bp9?file=/index.html](https://codesandbox.io/s/vb0bp9?file=/index.html)

Listen the JAWS announcements with virtual cursor - only the button "Disabled 2" have doubled announcement, and this is because of presence of ID attribute in the inner SPAN tag and there is inner BDI tag with the text, other two disabled buttons doesn't have such IDs, and there is no doubled announcement.

Best Regards,
Nikolay Hristov
