### ISSUE TITLE
SF_ACC_RatingIndicator: Cannot display in Safari browser

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#5842]
**Describe the bug**
The RatingIndicator cannot be displayed in Safari browser

**Isolated Example**
https://w8ug3o.csb.app/

**To Reproduce**
1. Go to https://w8ug3o.csb.app/ with Safari browser
2. The RatingIndicator is invisible

**Expected behavior**
RatingIndicator should display correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/191897023-917f4806-dc6e-4971-bc2a-d35fa24f1b86.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.1
Operating System: MaxOS
Browser: Safari

**Additional context**
I am from Successfactors, this issue can block b2211 release currently.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues from @SAP/ui5-webcomponents-topic-rl ,
I can reproduce the issue in Safari with https://sap.github.io/ui5-webcomponents/playground/components/RatingIndicator/ - the star icons in ui5-ratingIndicator are not present.
I am not sure about the root cause, but when I remove **display:flex** style of the indicator's ui5-icon they are shown.

Best regards,
Petya Markova.
(UI5 Dispatcher)
