### ISSUE TITLE
[SF] [Wizard] - Not scroll to next step automatically when current step has big height

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#5857]
### **Bug Description**
If current wizard step's heigh is big ( > 4000px), it does not scroll to next step automatically when it is turned selected.

### **Expected Behavior**
It always scroll to next wizard step when it is turned selected.

### **Steps to Reproduce**
1. Go to https://fslnby.csb.app/
2. Scroll down wizard step to bottom
3. Click 'Step 2' button
4. Observe 'Step 2' tab is selected, but the wizard does not scroll to 'Step 2' content

### **Isolated Example**
https://codesandbox.io/s/wizard-step-fslnby?file=/index.html

### **Context**
- UI5 Web Components version: 1.7.1
- OS/Platform: macOS
- Browser: Chrome
- Affected component: Wizard
- 
### **Log Output / Stack Trace / Screenshots**

https://user-images.githubusercontent.com/1751846/192795056-0290773f-70cd-401b-b056-26794d7fa461.mov

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The isssue is reproducible. Please open the CodeSandbox: https://codesandbox.io/s/wizard-step-fslnby?file=/index.html and scroll to the end of step 1 and press the button "Step 2".
Observed behaviour: The ui5-wizard is not scrolled to the Step 2 content.
If you change the height of the first step from 4400px to 2000px for example, the issue is not reproducible.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya
