### ISSUE TITLE
Bar(Horizon): the top and bottom border of Buttons are concealed when used inside a Bar

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#5863]
### **Bug Description**
When a Bar is rendered in Horizon design (Morning or Evening - HC seems fine) and buttons are used inside of it, the block border is concealed for all designs except "Emphasized" when hovering.

### **Expected Behavior**
Since the Bar component is often used for displaying buttons, it shouldn't be necessary to add a margin or height to it to display buttons correctly.

### **Steps to Reproduce**
1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-zl6hs3?file=/index.html)
2. See that top and bottom border of the buttons are not displayed when hovering

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-zl6hs3?file=/index.html

<img width="107" alt="image" src="https://user-images.githubusercontent.com/9749730/192989600-07b86945-8643-492e-af2c-d9f5b3c5079b.png">

### **Context**
- UI5 Web Components version: 1.7.1

### **Stakeholder Info** (if applicable)
- Organization: UI5 Web Components for React

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue described could be easily reproduced in the Bar sample page. Just resize the window to smaller width, in order to be added the style class "ui5-bar-root-shrinked". Then the style overflow:hidden is applied and the issue is reproducible.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya
