### ISSUE TITLE
Is it possible to change the text displayed for months in the date picker?

### ISSUE THREAD

**Issue by JPStrydom** [SAP/ui5-webcomponents#5931]
### **Issue Description**
I would like to know if it's possible to change the text that's displayed for months in the date picker. For example, if I want to show a translated calendar, could I display 'Oktober' instead of 'October', 'Januarie' instead of 'January', etc.?

### **Issue Type**

- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by Todor-ads** [comment]
Hello @JPStrydom,

Тhe text in the Month Picker is bound to the calendar types and cannot be changed to something different.

The component supports several calendar types - Gregorian, Buddhist, Islamic, Japanese and Persian. By default the Gregorian Calendar is used. In order to use the Buddhist, Islamic, Japanese or Persian calendar.
(https://sap.github.io/ui5-webcomponents/playground/components/Calendar/)

Regards,
Todor
