### ISSUE TITLE
FlexibleColumnLayout custom layout

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents#5966]
Hi everyone,

I would like to modify the width of certain columns in the FlexibleColumnLayout component, but seems like we are restricted to the layouts created by.

Would it be possible to create a custom layout where we can set the width by column?

I created a fix for this, but it does not work flawlessly.

```
const flexibleColumnLayoutRef = useRef();
const startDiv = flexibleColumnLayoutRef.current ? flexibleColumnLayoutRef.current.shadowRoot.querySelector('.ui5-fcl-column--start') : null;
const startDivWidth = startDiv && startDiv.style.width ? startDiv.style.width : null;

useEffect(() => {
	if (startDiv && startDivWidth && setStartColumnWidth) {
		const newWidth = setStartColumnWidth(startDivWidth);
		if (newWidth) startDiv.style.width = startDiv.style.width = '20%';
	}
}, [startDiv, startDivWidth]);
```

Thank you!

**Comment by kineticjs** [comment]
Hi @vital487,

Thank you for this feature request. Before forwarding it further, I'd like to get some extra information on the use-case behind:

-- do you have a use-case when the first column in particular **does not require much space to show its content** => on Desktop and Tablet you want it to take only 20% of the screen width
OR
-- in the cases when 2 and 3 columns are displayed, you want to squeeze the first column **in order to leave more space for the remaining columns**
-- in the end, do you want to be able to offset columns with **a small amount of width** (few pixels to the left of right) **OR with a larger difference** from the original layout?

Any additional explanation of the background will be helpful!

Thanks,
Diana

**Comment by vital487** [comment]
Hi @kineticjs,

It is the first option. We wanted to decrease the width of the first column.

But about the other options you mentioned, I think it would be great to have, for example, a setter for the `columnLayout` property. The link below shows what I mean.

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--default-story#readonly-properties

If more information is needed I will provide you.

Thank you!

**Comment by jdichev** [comment]
Hello,

We had similar request multiple times in the past also in relation with the FlexibleColumnLayout control and also provided PoC to SAP UX but this was rejected. Therefore we would rather not add such a possibility.

The reasoning is that the FlexibleColumnLayout helps achieve a specific scenario in which a user navigations into  a data model via 3 steps.

Due to the appearance of the FCL component it has been used in use cases where a vertical splitter or a list-navigation pattern would apply.

I you agree and would recommend to rather look for other options in the provided functionality or raise a request for a new and more generic component that better fits into your use use. 

Thanks and best regards,
Jordan
