### ISSUE TITLE
Tab component to offer image instead of text

### ISSUE THREAD

**Issue by giladvidal** [SAP/ui5-webcomponents#5995]
### **Feature Request Description**
Today, Tab can have text or icon. But we need to set an image instead.

### **Proposed Solution**
Create image property for Tab component that can have value like the import below and replace text property.
import MY_IMAGE from '@/images/image1.png';

### **Additional Context**
Add other context or screenshots related to the feature request here.

### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

We offer third-party data and look better to have the third-party logo instead of simple text in the Tab.

### **Stakeholder Info** (if applicable)

- Business impact: the Source Agent by SAP system is soon going to be released to customers.

**Comment by gmkv** [comment]
Hi @giladvidal
The [Fiori Design Guidelines](https://experience.sap.com/fiori-design-web/icontabbar/) do not suggest using images instead of written text as Tabs. If we consider this suggestion, it would be very likely that we will introduce accessibility concerns for the users if a Tab's descriptive text was replaced with an image.
