### ISSUE TITLE
Icon shows tooltip for show-tooltip="false"

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#6016]
### **Bug Description**
Icon shows tooltip even if show-tooltip="false" is set.

### **Expected Behavior**
No tooltip should be shown on hover for show-tooltip="false", the same as when not including show-tooltip at all.

### **Steps to Reproduce**
- ```<ui5-icon name="information" show-tooltip="false" accessible-name="Show Explanation"></ui5-icon>```
- hover the mouse cursor over the icon
 
### **Isolated Example**
https://jsfiddle.net/4upnswby/

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is reproducible via the provided by the reporter snippet: https://jsfiddle.net/4upnswby/
Hover over the icon:

_Exprected:_
Tooltip isn't displayed.

_Actual:_
Tooltip is displayed.

The <code>showTooltip</code> property is true even if the <code>show-tooltip</code> attribute if <code>false</code> is set. It seems that because the property is boolean when a <code>false</code> is given a string attribute it is interpreted by the component as truty. In order to support setting the value via attribute the <code>showTooltip</code> property should be of type </code>string</code>.

Best Regards,
Boyan

**Comment by plamenivanov91** [comment]
Hello @mhchem ,

To disable the tooltip either delete the **show-tooltip** argument from the icon tag or use the public boolean API of the element **showTooltip**.

Regards,
Plamen Ivanov

**Comment by mhchem** [comment]
Do you really think `show-tooltip="false"` should show a tooltip? I'd say: If the user intention is crystal clear, it should behave like the user intended. UI5 has Boolean properties as well, and you can set them to false with `="false"` in UI5 XML.
