### ISSUE TITLE
ui5-combobox  show behind modal

### ISSUE THREAD

**Issue by rvalentini1** [SAP/ui5-webcomponents#6028]
Hi , 
when the component is used on a modal, the list appears behind it.  

I have attached sample screenshots. The version used is 1.9 

![screen](https://user-images.githubusercontent.com/33550577/200806734-f280586a-36ef-4f5a-9390-2aaa965b475b.png)

Thanks

**Comment by unazko** [comment]
Hello @rvalentini1,

Is couldn't find such sample in the playground.
Could you please send us a short snipped like the following:
[codesanbox](https://codesandbox.io/s/71r1x5o51q?fontsize=14&module=%2Findex.html)
so we could reproduce the issue easily.

Best Regards,
Boyan

**Comment by rvalentini1** [comment]
@gmkv Hi, i use bootstrap modal.

**Comment by gmkv** [comment]
Reproducible sample: https://codesandbox.io/s/billowing-surf-xcz696?file=/index.html
1. Click Open modal
2. Show ComboBox suggestions
3. Popover is displayed behind the modal.

Since the suggestions popover is opened internally (from within the ComboBox module code), I don't think it's possible to easily use React Portals or a similar concept to avoid this.

**Comment by rvalentini1** [comment]
Thanks for reply.
So there is no solution?

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 

There is an issue with the ComboBox popover when used with other css libraries.
The popover is rendered behind the modal.
Steps to reproduce are described above.
This likely affects all other suggestion popovers.

Would you have a look?

**Comment by ndeshev** [comment]
Hello @rvalentini1 

UI5 WebComponents is maintaining a common z-index for all UI5 WebComponents instances and OpenUI5. You can see more here #2980

The z-index of the `ui5-combobox` popover is handled by the `ui5-popup` which uses a `PopupUtils.js` helper module to calculate it. PopupUtils.js part of the base project and the framework itself is concerned with z-index management.

In your case the issue is that the z-index of the Bootstrap modal is set to a hardcoded 1055 which is quite a big number, higher than our Popup's one , we could not take that into consideration. 

You should use custom CSS to override one of the z-index properties of the colliding libraries.

**Comment by rvalentini1** [comment]
Thanks for reply.

I use this component in an angular project. Is it possibile to Change at
runtime the z-index prop?

Thanks

Il giorno gio 17 nov 2022 alle 05:22 Nikolay Deshev <
***@***.***> ha scritto:

**Comment by niyap** [comment]
Hello @rvalentini1,

One of the core principles of Web Components is the **encapsulation**. The html and styles are encapsulated in the ShadowDOM, this avoids clashes with any css, brought by the rest of the app, but also makes custimization harder.

However there are some general patterns to style web components:

- **Styles on tag level**: we designed some components such as Title, Label, Badge, Input and few more in such way, that it is possible to set styles/classes on the custom elements like “ui5-input {color: red}” that will take effect.
You can try this yourself here: https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Input/
Unfortunately, this can't be done for all components, because it depends on the complexity of the DOM structure.

- **Shadow Parts** : For more complex components, the styling on tag level is not possible, therefore we introduced shadow parts on specific elements in the components’ Shadow DOM, that the user can restyle, using standard CSS syntax for shadow parts
For example: you can change the appearance of the Card’s heading, subheading and status with the CSS shadow parts syntax:

```
  #myCard::part(status) {
    color: red;
  }
```

- **Changing CSS Vars**: The UI5 WebComponents leverage CSS variables, so if you inspect the elements, you will probably find which variable you need to change.
This the list of all Base CSS Variables, that we use in the components - you can see it [here](https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/css_variables.css).
Sometimes, we define some internal variables with prefix --ui5_* (they are not in the list), you may see them, they are private in a sense, but still you can alter their value the same way.

- **Custom Theme schema**: To change the entire colour scheme, the users can create their own theme.
More details on how to do that, you can find here:
https://sap.github.io/ui5-webcomponents/playground/customizing/theme/

- **JS API: addCustomCSS**
We have added a special method that can insert CSS for any of our web components.
You can import & use it like this:

```
import { addCustomCSS } from "@ui5/webcomponents-base/dist/Theming";
addCustomCSS("ui5-select", ".ui5-select-root { background-color: red; } ");
```
Note: This is rather private API, so use this method with caution, because it might be changed/removed in the future.

Kind Regards,
Niya
