### ISSUE TITLE
Popover and Dialog: Zoom level calculates wrong css and fire wrong events

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#6063]
### **Bug Description**
If you set a css zoom level to the body (see index.html), the body should zoom the content like you press CTRL + or CTRL -
There is a problem with the popover and the dialog and maybe other modals which do not calculate the correct position to render within the sceen.
Additional, if you try to click on the popover, the popover fires onAfterClose event but shouldn't. The button is not clickable.

### **Expected Behavior**
A correct zoom like if you zoom with CTRL + or CTRL -

### **Steps to Reproduce**
1. Go to the example
2. Click on the avataricon on the right
3. See that the popover is not completly rendered within the page
4. Try to click the button and see, that the popover disappers but shouldn't. The button does not fire an clickevent

### **Isolated Example**
https://codesandbox.io/s/zen-leftpad-33tmrl?file=/src/App.js

### **Context**
- UI5 Web Components version: {...}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by dobrinyonkov** [comment]
Hi @C3ntraX, 

The CSS [zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) property is marked as `Non-standard` and the general reccomendation is to not be used. It is also not supported well by all of the browesers.

However, the specification says that unlike [transform: scale()](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale) the css zoom property will also affect the layout size of the elements, meaning that it is not the same as with CTRL +/- and responsiveness (spacing between of elements) will be weird (magnified) like with your example. 

Could you please provide more inrfomation about your use case and why it is necessary to use the CSS `zoom` property?
I'm also able to click the button inside the dialog and I see the log in the console, so please can you explain what is the issue with that?

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/22766569/202478369-77295de4-3d6d-4b97-94b4-fb4b2c48d6bf.png">


Kind Regards,
Dobrin

**Comment by C3ntraX** [comment]
Hello @dobrinyonkov,

In the example if you click the button in the popover which opens onClick on the avatar (top right) then the popover does not work and the button does not fire the event.

The usecase is, that I want to offer the user the opportunity to set the zoom level of the page. The zoom level should be saved per user and will automatically apply if the user signs in.
Especially for older users.

I looked into zoom. This works for all browser but mozilla. For mozilla I would set additional css:

.zoom {
    zoom: 2;
    -moz-transform: scale(2);
    -moz-transform-origin: 0 0;
}

What do you think? The zoom and transform does not work for UI5Webcomponents Popover and Dialogs, but the other elements are working, so I want thinking this is a bug or should be improved?

**Comment by C3ntraX** [comment]
If I shouldn't use `zoom` then I want to use `transform: scale(2)` with `transform-origin: 0 0`

**Comment by C3ntraX** [comment]
I changed the codesandbox to be more standard.
https://codesandbox.io/s/zen-leftpad-33tmrl?file=/public/index.html

Now I have even more problems. The width of the page does not scale corretly.

**Comment by dobrinyonkov** [comment]
Hello @C3ntraX,

We discussed this with our accessibility team, and we apologize that we will not support this functionality because we expect that simulating the browser magnifier behavior would be too difficult to execute and at the end would not be identical to the browsers default behavior.

Zooming as implemented in modern browsers consists of “stretching up” pixels. That is, the width of the element is not changed from 128 to 256 pixels; instead the actual pixels (devicePixelRatio) are doubled in size. Formally, the element still has a width of 128 CSS pixels, even though it happens to take the space of 256 device pixels.
This is hard to be simulated via css as it will require proportianal resizings on many dom levels.

What is more such function already exist and it is packed of most browsers by default. It also keeps users prefers of zooming levels after the page/browser is closed and it zooms the page in the same zoom level, the next time it is loaded.

Kind Regards,
Dobrin
