### ISSUE TITLE
[SF_ACC] List Delete Mode Tabbing

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#6088]
### **Bug Description**
When tabbing in List while on Delete Mode there is a delete Icon which I except to be able to tab into.

### **Expected Behavior**
A clear and concise description of what you expect to happen.
Being able to tab into inter-actable Icons
### **Steps to Reproduce**
1. Go to [UI5 WebComponent Playground](https://sap.github.io/ui5-webcomponents/playground/components/List/)
2. Scroll down to 'List in Delete Mode'
3. Tab in the list and notice that you cant tab into the Delete Icon

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: MacOs
- Browser: Chrome
- Affected component: List

### **Log Output / Stack Trace / Screenshots**

<img width="1439" alt="DeleteIconA11Y" src="https://user-images.githubusercontent.com/62973847/203630577-d07094ce-21b1-48ff-a4a8-c7d04b3619d4.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

When we have `ui5-list` with `Delete` mode and delete button is presented for each item, there is no way to move the focus to the delete button via keyboard.
The issue is reproducible both in the sample page and in the playground: https://sap.github.io/ui5-webcomponents/playground/components/List/

In the documentation, it is written that an item can be deleted via Delete key and the same behaviour is presented in OpenUI5 -  the delete button could not be focused and an item could be delete when it is focused and Delete key is pressed.

Could you please check whether there is an issue or that is the expected behaviour?

Thank you in advance!

Kind Regards,
Niya

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @IrvinDelgado ,
according to Accessibility specification, the delete button of ui5-list-item should not be focusable,
also the delete action (in Delete mode) can be performed by mouse click on the delete button, or using Delete key (Fn+Delete for MAC users), when list item is focused. This is the designed behaviour.
There is also a similar [issue](https://github.com/SAP/ui5-webcomponents/issues/2964) on the subject.

Kind regards,
Petya Markova.
(UI5 Web Components Developer)

**Comment by mhchem** [comment]
FYI
List behavior of [UI5](https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListDeletion) (delete button focusable via keyboard) and UI5 Web Components (delete button not focusable) differs.
Latest stable version of the accessibility spec states that the delete button should _not_ be focusable.
However, the work-in-progress version of the accessibility spec considers changing that.

**Comment by kgogov** [comment]
Hello @mhchem, @IrvinDelgado,

A quick update on this one — as @mhchem noted at the time, the accessibility specification for List delete mode was being revised, and that revision has since landed. We've now aligned the `ui5-list` behavior with the updated spec through #13411 and #12700.

In short: the list item enters an edit mode via `F2` / `F7`, and from there the internal interactive elements — including the delete button — are reachable through `Tab` / `Shift + Tab`. The `Delete` key shortcut is still supported as well, so the previous interaction is preserved.

In addition, the corresponding documentation has been published via #13900 and is already live, including a sample that demonstrates the behavior.

[Docs (ui5-list)](https://ui5.github.io/webcomponents/nightly/components/List/#keyboard-handling)
[Sample (ui5-list)](https://ui5.github.io/webcomponents/nightly/components/List/#keyboard-handling-1)
[Docs (ui5-li-custom)](https://ui5.github.io/webcomponents/nightly/components/ListItemCustom/#keyboard-handling)

With this in place, we feel good about considering this one done and will go ahead and close it for now. If any related concerns come up or the spec evolves further, please feel free to reach out and we'll happily pick it back up.

Best regards,
Konstantin
