### ISSUE TITLE
Avatar icon attribute is hard coded to "employee" since 1.9.0

### ISSUE THREAD

**Issue by veith** [SAP/ui5-webcomponents#6101]
### **Bug Description**
The avatar component uses always employee as icon, because it is hard coded in the sources since 1.9.0

### **Expected Behavior**
The same behavior like in 1.8.0 and before. This means that setting an icon like `icon="share"` should display the share icon, 

### **Isolated Example**
https://codesandbox.io/s/ui5-webcomponents-forked-hbmzqz?file=/index.html

### **Context**
- UI5 Web Components version: 1.9.0 + 1.9.1
- Affected component: Avatar

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by veith** [comment]
I imported the icons with `import "@ui5/webcomponents-icons/dist/AllIcons.js";` 
The error does not apear anymore, i think it was something from the codesandbox.

The bug still exist. If you switch the `@ui5/webcomponents` version to 1.7.1 and lower, the correct icons are displayed.

**Comment by Lukas742** [comment]
Hi @LidiyaGeorgieva 

@sleric1024 reported the same issue (#6110). ([codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-nh09sf?file=/src/index.js))

**Comment by dimovpetar** [comment]
Hello @veith,

This issue is the same as https://github.com/SAP/ui5-webcomponents/issues/6043. It is fixed with https://github.com/SAP/ui5-webcomponents/pull/6060.
As a workaround until the fix is released, you can set the `initials` attribute of your avatar. When you set it to correct value, the icon will appear. For example `initials="AC"`.

Best regards,
Petar
