### ISSUE TITLE
Input onChange: unclear if enter or focusout, detail property is null

### ISSUE THREAD

**Issue by KevinRoosSAP** [SAP/ui5-webcomponents#6127]
### **Bug Description**
Using the `onChange` event of the Input component there seems to be no indication in the `CustomEvent` if the user pressed enter or if the user focussed out of the Input. This is especially needed because these 2 events seem contrary from a user standpoint:

- Press Enter: The user wants **something** to happen
- Focus Out: The user wants something else, i.e. **nothing** to happen here

### **Expected Behavior**
Provide the information during runtime what happened, `enter` or `focusout`. Especially the `detail` property is null in both cases.

### **Steps to Reproduce**
1. Implement a simple `onChange` handler
2. Check the `CustomEvent` if enter pressed and if focused out

### **Isolated Example**
I implemented a simple `onChange` handler, the `CustomEvents` look completely identical

Enter pressed:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/119597767/205054346-622d374c-c809-4b46-a70d-7a5736bc80b5.png">

Focused out:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/119597767/205054477-4dcc9e60-07e0-4b9f-95df-3925be936259.png">

### **Context**
- UI5 Web Components version: any / most recent
- OS/Platform: Safari
- Browser: Chrome
- Affected component: Input

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

Please evaluate this feature request - whether to provide information in the `change` event of the Input component that it was triggered by focusout or Enter keydown. Its counterpart, [sap.m.Input](https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/api/sap.m.InputBase%23events/change) doesn't provide such information.

Best regards,
Petar

**Comment by niyap** [comment]
Hello @KevinRoosSAP,

If you check the native "change" event, you will notice that the same behaviour is presented there.
You can rely on keydown event and check whether "Enter" key is pressed as well as on focusout event.
On the other hand, if you have to use the `ui5-input` change event in order to fulfil your use case, you can check the active element when the event is fired (if "Enter" key is pressed, the active element will be the component and if the event is fired on focusout the active element will be something else)

Kind Regards,
Niya
