### ISSUE TITLE
Button UI Type not read by Screen Reader within Table Row

### ISSUE THREAD

**Issue by adrianalbrechtgit** [SAP/ui5-webcomponents#6139]
Hello,

I am working on an accessibility bug that was reported because the Button UI Type is not read by Screen Reader like Jaws within Table Row. Would it be possible that a Button was not taken into account as use case for a table?

Thanks!

**Comment by NHristov-sap** [comment]
Hello @adrianalbrechtgit ,

Can you please provide an isolated example (https://codesandbox.io/) that demonstrates the issue?

Best Regards,
Nikolay Hristov

**Comment by adrianalbrechtgit** [comment]
Hi Nikolay,

thanks for your response. Here is the isolated example: https://codesandbox.io/embed/confident-sammet-9wyfpb?fontsize=14&hidenavigation=1&theme=dark

Thanks,
Adrian

**Comment by elenastoyanovaa** [comment]
Hello,

The information passed to the table row as aria-label is limited and gives a overview of the content of the row and information relevant for the row itself. In order to hear the whole information inside a table cell you could simply focus on a row and then press tab to place the focus inside the table cell if focusable elements are present. 

In your example if you focus on the first row and press TAB once, the button will be focused and all of the information regarding the button will be read out correctly.

Kind Regard,
Elena
