### ISSUE TITLE
[SF][Table] Header Text Color CSS Variable

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#6184]
### **Bug Description**
I'm not 100% if this is a bug or by design.

Some customers are saying that their Theme aren't properly applied.

The `ui5-table` column header text color uses the `--sapTextColor` CSS variable. However, at least in SuccessFactors, when customer define their theme, the color is set to the `--sapList_HeaderTextColor` CSS variable.

Shouldn't the `ui5-table` column header use the `--sapList_HeaderTextColor` CSS variable instead?

<img width="584" alt="Screenshot 2022-12-13 at 11 46 30 AM" src="https://user-images.githubusercontent.com/7316793/207429834-45cee1be-a29a-4672-9902-c33eef043f6f.png">

### **Context**
- UI5 Web Components version: latest
- OS/Platform: MacOS
- Browser: Chrome
- Affected component: ui5-table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Customer's theme isn't applied properly

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Both `--sapTextColor` and `--sapList_HeaderTextColor` CSS variables are evaluated to `#1d2d3e` hex value in our Playground.

But it seems that when the customer is creating a custom theme and changing the header color, the `--sapList_HeaderTextColor` is being altered.

Should we use the `--sapList_HeaderTextColor` instead of `--sapTextColor` as CSS variable for the header text color?

Regards,
Plamen
