### ISSUE TITLE
[SF_ACC][Input] Support opening suggestion list using hot key (Arrow + Up/Down]) like ComboBox

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#6190]
### **Feature Request Description**
We use ui5-input + suggestion as our input fields in which the value is selected from a long list. Typing in input box trigger a remote search API to fetch the result list. Selecting an item from the suggestion list dismiss the list. As a keyboard user, I'm not able to reopen the list unless I change the text in input, but changing the text will trigger a re-searching which may return different result as before.

![image](https://user-images.githubusercontent.com/1751846/207809999-95d3eda2-e9e8-48ce-bdc9-620855edc0a6.png)

### **Proposed Solution**
It would be helpful if ui5-input can support opening suggestion list using hotkey (Arrow + Up/Down) like ui5-combobox.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by hristop** [comment]
Hi @2bno1 ,

The described behaviour is exactly what is expected from the suggestions and the suggestions list by design. It is expected that when you select something and then write something else the list of suggestions may change. 

Currently there is an API to show the available suggestions in the ui5-input with the "openPicker" method, which can be called in an event listener.

We have a feature request to make the Arrow Down / F4 keys call the value help functionality of the inputs that support and this is something that may be useful to you once implemented: https://github.com/SAP/ui5-webcomponents/issues/4908
but currently there are no plans to make those shortcuts open the suggestions list by default. 

Best Regards,
Hristo
