### ISSUE TITLE
Support use of UI5WC within Node.js

### ISSUE THREAD

**Issue by scameron** [SAP/ui5-webcomponents#6192]
### **Feature Request Description**
Today UI5WC cannot be run inside Node.js because it relies on browser-specific objects like **window** and browser-specific APIs like **fetch**.  For purposes of testing (via Jest, for example) or potentially server-side rendering, it would be nice to be able to use UI5WC inside Node.js instead of a browser.

### **Proposed Solution**
I'm not exactly sure what an exact solution would look like, but presumably it would need to internally use alternatives for browser-specific objects and APIs where possible, if such objects/APIs are found to not be available at runtime.

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-team,

The reporter would like to use UI5 Web Components outside of the browser (Node.js).

Is that feasible? Can you please take over?

Regards,
Plamen Ivanov

**Comment by ilhan007** [comment]
Hello @scameron 


With this [change](https://github.com/SAP/ui5-webcomponents/pull/8184) the web components use shim for node/ssr environment and available since version 1.22.


<img width="789" alt="Screenshot 2024-07-10 at 17 17 59" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/f20d7fea-5409-412a-901f-2e303d221e92">
