### ISSUE TITLE
<ui5-page> is getting rendered in single block and contents are missing

### ISSUE THREAD

**Issue by gb-githb** [SAP/ui5-webcomponents#6259]
### **Bug Description**
`<ui5-page>` UI5 Page is getting rendered in single block and the contents are missing

### **Expected Behavior**
It should get rendered as UI5 Page Sample

### **Steps to Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents/playground/components/Page/
2. Copy the sample code and import all the dependencies
3. You will notice the Header and footer are getting rendered in single block and the content is missing 

### **Isolated Example**
Example : https://09458x.csb.app/

### **Context**
- UI5 Web Components version: Latest
- OS/Platform: Windows 10
- Browser: Chrome
- Affected component: {...}

### **Log Output / Stack Trace / Screenshots**
```
![image](https://user-images.githubusercontent.com/66545559/211309192-3732c8f8-c94a-4f35-a0cd-e67f0f402a96.png)

```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Business impact: Medium

**Comment by kineticjs** [comment]
Hi @gb-githb,

Thank you for providing a reproducible sample of the issue!

On inspection we see that the issue occurs because ui5-page is placed in a container with auto height 
i.e. a container with height that is determined by (/equal to) the height of its **content**. 

At the same time, the ui5-page has height of "100%" => it requires to be placed in a container with given height (usually 100%, as the page is usually fullscreen)

If you give height to the ui5-page containers, the layout will be correct,
e.g. add CSS:
`body, html {
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
}`

**Comment by gb-githb** [comment]
Thank you @kineticjs for the quick response.
It has helped me to solve this issue.

However , would it be possible to provide this functionality out of the box?
For example : Fiori Fundamental Dynamic Page , does it automatically without any css. 
https://sap.github.io/fundamental-ngx/#/core/dynamic-page 

Many Thanks !
