### ISSUE TITLE
Button: A disabled button executes the onClick action

### ISSUE THREAD

**Issue by jannislmml** [SAP/ui5-webcomponents#6372]
**Describe the bug**
I have updated the npm package @ui5/webcomponents-react from version 1.7.1 to 1.8.0. In version 1.7.1 the disable functionality of a button worked correctly. After the update, a disabled button, which is also displayed disabled on the web page, can still be clicked and the onClick action is executed.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.0
Operating System: win10
Browser: chrome

**Comment by kskondov** [comment]
Hello @SAP/ui5-webcomponents-topic-b,
There is an issue where a disabled button still fires an event on click you can check the sample provided by @Lukas742  [code sandbox](https://codesandbox.io/s/ui5-webcomponents-forked-hull0o?file=/index.html). Is this desired behaviour?
Best Regards,
Konstantin

**Comment by MarcusNotheis** [comment]
Hey colleagues,
we've just received another issue in the UI5 Web Components for React Repo facing exact the same issue (https://github.com/SAP/ui5-webcomponents-react/issues/4062). Do you have already any estimate when this will be fixed and released with a patch release?

**Comment by ilhan007** [comment]
Hay @MarcusNotheis the team has started working on it, we will keep you updated.

**Comment by SenPavel** [comment]
Hello @ilhan007,

Is there a timeline when for the fix to be released?

Thanks.
Best regards,
Pavel

**Comment by ilhan007** [comment]
Hi @SenPavel 

**Background**
At the end of the month we release stable versions : 1.11.0 1.12.0...
Every week (on Thursday) we have a pre-release version: 1.11.0-rc.1, 1.11.0-rc.2
In between, we release patches on demand - 1.10.3, 1.10.4...

Considering 
- 1.11.0-rc.2 - already has the fix since today
- 1.11.0 - will have the fix at the end of Feb
- 1.10.4 - and in addition, due to high demand, we released on-demand 1.10.4 stable version (@ latest) that also includes the fix

So, you have to upgrade to one of the following to consume the fix immediately:
- 1.11.0-rc.2 (includes a lot of fixes and features on top of 1.10.3) 
- 1.10.4 (includes only selected fixes on top of 1.10.3).
