### ISSUE TITLE
Add noHeader prop to Card component

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#643]
**Is your feature request related to a problem? Please describe.**
I would like to use the Card in a similar layout like the sap.m.Tile control.

**Describe the solution you'd like**
Add the noHeader prop to the Card, so that I can use the content slot only.

**Describe alternatives you've considered**
Create own Tile component.

**Comment by ilhan007** [comment]
Hello @Lukas742 
Thanks for you request, we will consider it.

To help us better understand your needs, could you please answer these questions.
In case you don't need the header, do you actually need ui5-card?
Do you need it because of the ui5-card border you get?

Because, 
you can just use the content html that you would set to the ui5 -card content slot, 
directly in your page with the same result.

Best,
ilhan

**Comment by ilhan007** [comment]
Hello @Lukas742

In addition to my previous comment, I want to inform you that we prepared a change  https://github.com/SAP/ui5-webcomponents/pull/646,
that removes the header part of the `ui5-card`, if  the properties `heading` `avatar`, `subtitle` and `status` (all defining parts of the header) are not used/set. In other words, if you don`t use anything related to the header, a header will not be rendered.

I think that the change might also meet your needs, without adding a dedicated property `noHeader`.
What do you think?

**Comment by Lukas742** [comment]
Hi @ilhan007 

Thanks this is exactly what I needed. And yes you were right, I could've just used the html in the content slot, but this way it's easier to implement. 

Kind regards,
Lukas
