### ISSUE TITLE
[SAP] [Accessibility] [DateRangePicker] : No keyboard support

### ISSUE THREAD

**Issue by vraguna** [SAP/ui5-webcomponents#6439]
As @kskondov suggested in https://github.com/SAP/ui5-webcomponents/issues/6370, I am creating it as a separate issue.

**Describe the bug**
There is no keyboard support for the subcomponent within the following main components

The "Open Picker" in the DateRangePicker component

**Steps to reproduce the behavior:**

1. Open Google Chrome
2. Go to the corresponding examples
[Open Picker](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-daterangepicker--default-story)

![Snag_1eb302](https://user-images.githubusercontent.com/42251879/217270627-0269ea03-8102-486f-9477-75e91fec22d4.png)

3. Click on the Keyboard tab to get the focus on the above component.

You can notice the sub component is not focusable.

**Expected Behavior:**
Clickable elements must be focusable

**Comment by dobrinyonkov** [comment]
Hi @vraguna,

the icon on the right has aria-hidden=true which makes it decorative and is not specified to receive the browser focus.
According to the keyboard specification, in order to open the dropdown the `F4` key can be pressed.

If you're using Mac you may need to combine this with the Function key ( `Fn` + ` F4` ). I'm testing this now and it seems to work as expected, therefore I'm closing this issue.

Please, reopen it and let us know if you still encounter issues with that behaviour.
