### ISSUE TITLE
timepicker scrolling is too fast when using trackpad

### ISSUE THREAD

**Issue by axel-xciv** [SAP/ui5-webcomponents#6459]
### **Bug Description**
When using the timepicker with a macbook trackpad, the scrolling is way too fast. Minimal movement of the fingers on the trackpad scolls over 5-10 items at the same time. Picking the right time is therefore random and can't be used properly.

### **Expected Behavior**
Scrolling speed is the same when using trackpad and mouse

### **Steps to Reproduce**
1. Use Macbook (MacBook Pro 16" from 2019) in my case
2. Open Time Picker and try to select 

### **Isolated Example**
no description

### **Context**
- UI5 Web Components version: current
- OS/Platform: macOS
- Browser: Safari, Chrome, i guess all others as well
- Affected component: TimePicker

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [] Medium
- [x] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-b, this issue is about the ui5-timepicker wheel scroller. As described above, using the timepicker with a trackpad (macbook in this case), the scrolling happens too fast. 

1. https://sap.github.io/ui5-webcomponents/playground/components/TimePicker/
2. Use Macbook (MacBook Pro 16" from 2019) in my case
3. Open Time Picker and try to select

@axel-xciv We have re-evaluated the priority to medium as it is still possible to change the values easily with the keyboard arrow keys.

Kind Regarsd,
Dobrin
