### ISSUE TITLE
[SF_ACC][ui5-table] - Table has Empty Header

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#6470]
### **Bug Description**
Following Axe Error Occurs:
Table header text should not be empty
Issue Description
Ensures table headers have discernible text
![Screenshot 2023-02-13 at 14 49 35](https://user-images.githubusercontent.com/1751846/218389993-f8e268f0-abd5-4e37-a970-c4e7df4cb971.png)

### **Expected Behavior**
Table Header should not be empty

### **Context**
- UI5 Web Components version: 1.9.1
- OS/Platform: macOS
- Browser: Chrome
- Affected component: ui5-table

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

**Comment by niyap** [comment]
Hello @2bno1,

Thanks for sharing your findings!

I checked the issue described, but it is no more reproducible in the latest version. Please, check and test the sample: https://sap.github.io/ui5-webcomponents/playground/components/Table/ "Table with grouping (SingleSelect - click on item to set navigated)"
Previously, the <th> element was visible for the assistive technologies which was not correct and fixed with the following PR #5998. As a result, the issue in not reproducible anymore.

Kind Regards,
Niya
