### ISSUE TITLE
Option: Acessibility properties not available for Option tags under Selection dropdown

### ISSUE THREAD

**Issue by stefanomantova** [SAP/ui5-webcomponents#6471]
**Describe the bug**

The Acessibility properties, such as accessibleName, accessibleNameRef and name are not available to be used on `<Options>` component inside a `<Select>`. This disables the possibility of setting accessible names for screen reader in cases where it is necessary to use a text different from the tag content.

In the below example, I would like to set an accessible name for the first option tag, which should not display any text message, to be read with Screen Readers. However, this is not possible as the referred properties are not available.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/44717272/218190114-98216f34-38dd-4799-a926-3e96fb4e47f3.png" />
When intenting to read the <Option> content, the current behavior works fine.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/44717272/218190083-0a0ad82b-71e5-4fa2-9fff-bf9365bfd27b.png" />

When needing to use Screen Reader to get a name of an empty <Option> or to read something different than the content, no settings or properties are available.

**Isolated Example**
(https://codesandbox.io/s/eloquent-almeida-ye14ri)

**To Reproduce**
Use arrows to navigate through dropdown items while using a screen reader. The empty <Option> should not return any accessible name.

**Expected behavior**
A property or workaround should be available to enable setting accessible names for options inside a select dropdown.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.0
Operating System: MAC OS Ventura 13.2
Browser: Google Chrome 109.0.5414.119

**Comment by niyap** [comment]
Hello @stefanomantova,

Actually, that is the expected behaviour of the component. When an item is focused, its text and its position should be read out. According to the Fiori Guidelines, if you need to indicate that none of the selection options are selected, or you need to allow users to not select an option, offer an appropriate option, such as (Not Selected) or (No Values Selected): https://experience.sap.com/fiori-design-web/select/ instead of empty one.
Also, if you need to be able to have an empty input without any selected item, it is more appropriate to use <ui5-combobox> component instead of <ui5-select>

Kind Regards,
Niya
