### ISSUE TITLE
ui5-slider: Missing documentation of events

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6478]
### **Issue Description**
The ui5-slider documentation in the playground is lacking the information about the events this component offers. I only found in the ui5-avatar-group examples by inspecting the script that the slider offers an "input" event. Please add this missing information to the documentation.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Since the "input" and "change" event are defined in the SliderBase, their documentation is not visible in the playground: https://sap.github.io/ui5-webcomponents/playground/components/Slider/

Could you please check and enhance the documentation for the ui5-slider events?

Thank you in advance!

Kind Regards,
Niya

**Comment by ilhan007** [comment]
I think this is an issue of the Playground @nnaydenow ?

**Comment by nnaydenow** [comment]
Hi @ilhan007, in the JSDoc everything seems to me marked and linked correctly. I'll check if this is a playground issue.

**Comment by nnaydenow** [comment]
The problem doesn't appear on local build of the playground. It will be fixed with the next release.

**Comment by ilhan007** [comment]
Hello @kaistephanrichter 
on the "main" deployment this is already fixed
https://sap.github.io/ui5-webcomponents/main/playground/components/Slider/

On the "latest" deployment it will be fixed later this month.

BR,
ilhan
