### ISSUE TITLE
ui5-tabcontainer: expose the shadow part of tab container header

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6487]
### **Feature Request Description**
We are looking for a way to customize the styles of tab container header. Could you please expose the header shadow part of tabContainer like the part of content?

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

A clear and concise description of the impact/urgency of the required feature.

### **Stakeholder Info** (if applicable)

- Organization: {SF}

**Comment by niyap** [comment]
Hello @BennyHuang,

Could you please give some more information about the use case? What exactly you are trying to achieve?

Thank you in advance!

Kind Regards,
Niya

**Comment by Neeeko** [comment]
Hi @niyap, we're using the TabContainer with another component (ui5-webcomponent-react's [DynamicPage](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--default-story)) which already comes with its own box-shadow.

<img width="855" alt="Screenshot 2023-02-14 at 2 55 14 PM" src="https://user-images.githubusercontent.com/7316793/218882023-c5685d37-0b51-4c9a-97f7-d107aa74e197.png">

We'd like to be able to remove the TabContainer's box-shadow since it creates a duplicated shadow on top of its parent component but we don't want to use `addCustomCSS` since it breaks the web components encapsulation.

Best,

Nicolas

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The reporter ask for introducing a part for the header of the TabContainer. For further information about the exact use case, please check the last reply.
Could you please take a look of that feature request? 

Thank you in advance!

Kind Regards,
Niya

**Comment by LidiyaGeorgieva** [comment]
Hello @Neeeko , please send us isolated example of your use case.
