### ISSUE TITLE
[ui5-icon]: icon is shrunk to be a small size if there is no enough space left

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6489]
### **Bug Description**
The icon is shrunk to be a small size if there is no enough space left

### **Expected Behavior**
The size of Icon should not be changed.

### **Isolated Example**
https://codesandbox.io/s/boring-meadow-efzoe9?file=/src/App.js

### **Context**
- UI5 Web Components version: {1.10.3}
- OS/Platform: {MacOS}
- Browser: {Chrome/Safari}
- Affected component: {ui5-icon}

### **Log Output / Stack Trace / Screenshots**
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1995447/218609756-b6c48dca-e466-41ec-ae18-832cf23858b9.png">

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SF

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

Could you please look over the issue? Is it expected to have the same size of the icon, no matter of the width of the container? I did not find any information about that use case, both in the visual design and in the documentation.

Thank you in advance!

Kind Regards,
Niya

**Comment by kgogov** [comment]
Hello @BennyHuang,

Can you please provide a working isolated example so we can trace the issue if occurs.
It seems that your [link](https://codesandbox.io/s/boring-meadow-efzoe9?file=/src/App.js) points to another codesandbox sample or might have changed with the time.

I've tried reproducing the example from the screenshot you've provided and I found that the icon size did not shrinked.

Thank you!

**Comment by kgogov** [comment]
Hello @Neeeko,

Thank you for reaching out and bringing up this issue. After reviewing the example and analyzing the code, I would like to explain that the problem you're experiencing is actually a matter of configuration and responsibility on your end.

The UI5 Web Components library aims to provide users with the freedom to customize and adapt components according to their specific needs and requirements.

In this particular case, the icon shrinking issue occurs because of the styles applied to the parent `div` element container, specifically `display: flex`.

To prevent the icon from shrinking, I recommend one of the following solutions:

- Add `flex-shrink: 0` to the `ui5-icon` element. This CSS property ensures that the icon retains its original size and doesn't change when there's limited space available.
- Alternatively, you can set a `min-width` of your desired choice to the `ui5-icon` element. This ensures that the icon maintains a minimum width, preventing it from shrinking excessively.

Please feel free to reach out if you have any further questions or need additional assistance.

Best regards,
Konstantin
