### ISSUE TITLE
ui5-color-palette-popover: page starts with the wrong tag

### ISSUE THREAD

**Issue by kaistephanrichter** [SAP/ui5-webcomponents#6496]
### **Issue Description**
The documentation page of theui5-color-palette-popover starts with the tag <ui5-color-palette> and not the correct tag <ui5-color-palette-popover. 

### **Issue Type**

- [ ] Documentation is unclear
- [x] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Comment by niyap** [comment]
Hello @kaistephanrichter ,

May I ask you to provide a screenshot or a detailed description, where exactly is the problem in the documentation?

Thank you in advance!

Kind Regards,
Niya

**Comment by kaistephanrichter** [comment]
Hi @niyap ,
all playground pages usually start with the tag for the respective element. On the page for the [ui5-color-palette-popover](https://sap.github.io/ui5-webcomponents/playground/components/ColorPalettePopover/) the tag that is displayed is `<ui5-color-palette>` and not `<ui5-color-palette-popover`.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/46745939/218981569-79c6b753-8760-4aef-aea4-3d5d787b46ac.png">

Just a minor thing though.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

In the Playground documentation of the <ui5-color-palette-popover> it is written <ui5-color-palette> instead.
The issue comes from the ColorPalette sample page and especially this part "<div class="control-tag">&lt;ui5-color-palette&gt;</div>"

Could you please check and enhance the documentation page accordingly?

Thank you in advance!

Kind Regards,
Niya
