### ISSUE TITLE
[SF_ACC][ui5-responsive-popover]Content within the ui5-responsive-popover are not read

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents#6501]
### **Bug Description**
Content within the ui5-responsive-popover are not read

### **Expected Behavior**
Once user opens a ui5-responsive-popover, dialog is displayed and text inside should be read.

### **Steps to Reproduce**
1. Go to https://codesandbox.io/s/exciting-moser-i0csq6?file=/src/App.js
2. Tab to "open popover" button
3. Press "Enter" on keyboard and inspect the JAWS speech history(Windows, Chrome, JAWS2022.2211.7)
4. See the content inside the ResponsivePopover is not read by JAWS
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/27538066/218965488-67f76d21-36d5-44c7-b066-2afc68ba5125.png">

### **Isolated Example**
https://codesandbox.io/s/exciting-moser-i0csq6?file=/src/App.js

### **Context**
- UI5 Web Components version: 1.10.3
- OS/Platform: Windows
- Browser:Chrome
- Affected component: ui5-responsive-popover

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

### **Stakeholder Info** (if applicable)

- Organization: SuccessFactors
- Business impact: Medium

**Comment by niyap** [comment]
Hello @ksblklu,

In order to be read out static content, you have to provide a reference. Here, you can find more information: https://sapui5untested.int.sap.eu2.hana.ondemand.com/demokit/test-resources/sap/m/demokit/accessibilityGuide/webapp/index.html#/overview/applicationDeveloper/labeling (Provide labels for Popups section)
You can achieve that using the accessible-name and accessible-name-ref properties of the component: https://sap.github.io/ui5-webcomponents/main/playground/components/ResponsivePopover/

Kind Regards,
Niya
