### ISSUE TITLE
Two-way binding in an angular application with origami does not work

### ISSUE THREAD

**Issue by Smux** [SAP/ui5-webcomponents#651]
A colleague as well as myself noticed that the two way binding that is described in this tutorial:
https://github.com/SAP/ui5-webcomponents/blob/master/docs/Angular-tutorial.md
is not working.
We have done all the required steps, but none of the bound values will update with ui5-input.

Could you please recheck whether there is something missing in the guide?

I tested it on Angular 5.2.0 and the latest Angular version.

**Comment by ignipae** [comment]
Hi,
I noticed this as well. 
Additionally, the tutorial is missing the part where the origami module needs to be imported, but thats a minor thing.

**Comment by fifoosid** [comment]
Hi guys,

This PR adds the missing step in the docs: #730

And this PR fixes the problems with two way data binding: #706

Best regards,
Filip

**Comment by fifoosid** [comment]
Hi,

#706 is in master now and will be available in the next release.

Best regards,
Filip

**Comment by CemYil03** [comment]
I am currently trying to use ui5-web-component in an angular project.
I still have major issues getting two-way-data-binding to work.
As in the first comment here https://www.gitmemory.com/issue/SAP/ui5-webcomponents/697/519089526 described, I had to add ngDefaultControl to the ui5-input-tag to get it to work. But I think that this is not the recommended way. Is it?
Working with Origami as described in the official documentation simply does not work https://sap.github.io/ui5-webcomponents/playground/tutorials/angular/ instead I had to import the Angular Forms Modul:
import { FormsModule } from '@angular/forms';

In any case, since following the step by step instruction leads to nothing, you should either fix the library, fix the documentation or remove the documentation until it works.

Angular CLI: 12.1.1
Node: 16.6.1
Package Manager: npm 7.20.3
OS: darwin x64
