### ISSUE TITLE
[SF_ACC][ui5-dialog]: not focused on header when opening resizable dialog by using mouse

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#6526]
### **Bug Description**
It won't focus on the header when opening resizable dialog by using mouse.
But if you use keyboard "Enter" key to open the resizable dialog, it will focus on the header. 

### **Expected Behavior**
Should focus on the header when opening resizable dialog by using mouse.

### **Steps to Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents/playground/components/Dialog/'
2. find "Open Draggable/Resizable dialog" button
3. use mouse to click the button and you will find it won't focus on the header

### **Context**
- UI5 Web Components version: {1.10.3}
- OS/Platform: {...}
- Browser: {...}
- Affected component: {ui5-dialog}

### **Log Output / Stack Trace / Screenshots**
```
{...}
```
### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SAP SuccessFactors}
- Business impact: {...}

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible as described by the reporter.
Please, check the example: https://sap.github.io/ui5-webcomponents/playground/components/Dialog/ (Draggable and Resizable Dialog sample). The focused element is different, when the Dialog is open via mouse and via Enter key.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya

**Comment by gmkv** [comment]
Hi @GongRichard 
This is an intentional change, part of the design evolution.
The dialog will show the focus outline only when it was invoked using the keyboard.
The focus is still on the same element as before, but the outline is not drawn anymore.
You can read more about this here https://github.com/SAP/ui5-webcomponents/issues/5749.
