### ISSUE TITLE
Table Column Header is not coming as Bold as shown in Sample

### ISSUE THREAD

**Issue by gb-githb** [SAP/ui5-webcomponents#6531]
### **Bug Description**
Table header is not coming as Bold

### **Expected Behavior**
It should get displayed as given in the sample

### **Steps to Reproduce**
1. Go to 'https://yds2x3.csb.app/'
2. Find the copied code from the Sample from https://sap.github.io/ui5-webcomponents/playground/components/Table/
3. You would find that the Column Header text are not Bold as available in Documentation
4. Moreover , the Weight Data is not highlighted

### **Isolated Example**
https://yds2x3.csb.app/

### **Context**
- UI5 Web Components version: Latest
- OS/Platform: Windows 10
- Browser: Chrome

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SAP
- Business impact: Low

**Comment by niyap** [comment]
Hello @gb-githb,

Thanks for sharing your findings!

Actually, for SAP Quartz theme which is the one used within your sample, it is not expected for the column header text to be bold. You can check the sap.m.Table sample as well: https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table
There is a difference with the referenced sample, as the theme of the sample is SAP Horizon. If you apply the same theme (Horizon) to the sample, the column header text will be bold, which is expected for that theme by design specifications.

For the second issue mentioned, we will update our samples.

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

In our sample page of the ui5-table component in the Playground, we apply color: #2b7c2b to the content of the "Weight" column of each sample, which we do not show in the code snippet of that samples. 
Please, update the code snippets with the style used within the table.

Thank you in advance!

Kind Regards,
Niya

**Comment by gb-githb** [comment]
> Hello @gb-githb,
> 
> Thanks for sharing your findings!
> 
> Actually, for SAP Quartz theme which is the one used within your sample, it is not expected for the column header text to be bold. You can check the sap.m.Table sample as well: https://sapui5.hana.ondemand.com/#/entity/sap.m.Table/sample/sap.m.sample.Table There is a difference with the referenced sample, as the theme of the sample is SAP Horizon. If you apply the same theme (Horizon) to the sample, the column header text will be bold, which is expected for that theme by design specifications.
> 
> For the second issue mentioned, we will update our samples.
> 
> Kind Regards, Niya

Thank you for the explanation !
