### ISSUE TITLE
Table: Provide a column or cell level  attribute option for normal word break

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#6551]
**Describe the bug**
Default behavior of the cells is to break at fixed length, e.g. if email address is long it will break the email at some pre-determined length.

**Expected behavior**
Provide an attribute at column/cell level to allow line break at the end of the word only. e.g. if email address is long it should not line break anywhere in the email, should display the whole email on the same line. currently we are working around it using
`
ui5-table-cell::part(cell) {
  word-break: normal;
}
`

**Screenshots**
![image](https://user-images.githubusercontent.com/65705637/220160621-41a38793-4934-408f-ada6-2913a1cfd865.png)

**Comment by NHristov-sap** [comment]
Hi @gurkirpalgill ,

Can you please provide an isolated example that demonstrates the issue (or what you are requesting)?

Best Regards,
Nikolay Hristov

**Comment by NHristov-sap** [comment]
Hi @Lukas742 ,

Can you reproduce this with pure UI5 web components, as the issue looks strange and probably is Safari bug?

Best Regards,
Nikolay Hristov

**Comment by nnaydenow** [comment]
Hi @gurkirpalgill,

The solution that you've provided fixes the issue if I correctly understand it. If you want to apply the style to a specific cell you can extend the selector by adding a CSS class for example.

Please edit the [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-fwvokr?file=/index.html) if the issue is not resolved with your code so we can process it.
