### ISSUE TITLE
ui5-shellbar: search button is placed outside search field

### ISSUE THREAD

**Issue by pankajpandey01** [SAP/ui5-webcomponents#6577]
### **Bug Description**
ui5-shellbar: search button is placed outside search field

### **Expected Behavior**
According to https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697898394
search button should be placed within search field

### **Steps to Reproduce**
- Go to 'https://sap.github.io/ui5-webcomponents/playground/components/ShellBar/'
- Verify the search button placement

### **Context**
- UI5 Web Components version: {1.10.0}
- OS/Platform: {All}
- Browser: {All}
- Affected component: {ShellBar}

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {SuccessFactors}

**Comment by TeodorTaushanov** [comment]
Hi @SAP/ui5-webcomponents-topic-p, can you check this one? Probably just the example page should be improved.

**Comment by kgogov** [comment]
Hello @pankajpandey01,

The visual difference in the shellbar component for the search icon that you reported will not be changed due to the way it is implemented.

We discussed this issue with the design team and agreed not to change it.
I will notify the design teams to update the images in the documentation to prevent further confusion.

Thank you for the report.
