### ISSUE TITLE
[SAFARI] Missing ScrollBar in Safari using Tree Component

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents#6586]
### **Bug Description**
When scrolling through a list of Tree Items there is no viewable scrollbar

### **Expected Behavior**
There should be a scroll bar when scrolling through a list of Tree Items

### **Steps to Reproduce**
1. Using Safari
2. Go to [CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-gr0tcb?file=/index.html).
3. When scrolling note that there is no scroll bar
4. Using Chrome follow the same steps and see that there is a scrollbar

### **Isolated Example**
[CodeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-gr0tcb?file=/index.html).

### **Context**
- UI5 Web Components version: 1.10.0
- OS/Platform: Mac
- Browser: Safari
- Affected component: Tree

### Safari
<img width="660" alt="Screenshot 2023-02-24 at 3 27 39 PM" src="https://user-images.githubusercontent.com/62973847/221320348-5a5f1cef-6a0c-421b-a76d-33e5d203967e.png">

### Chrome
![ScrollBar](https://user-images.githubusercontent.com/62973847/221320633-95e9cdaa-bba2-41ab-901a-897cea66d336.png)

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: {...}
- Business impact: {...}

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p, 

I am forwarding this issue to you, because it is reproducible on Safari browser. Please check.

Best Regards,
Nikolay Hristov

**Comment by kgogov** [comment]
Hello @IrvinDelgado,

I have looked carefully at the problem you reported and have come to the conclusion that the missing scrollbar is not related to ui5-tree component.

I looked at the example you gave in the description and it seems the missing scrollbar issue comes from the styling of the CodeSandbox iframe element where the project loads.

And actually if you try to [open](https://gr0tcb.csb.app) the project in a new window the scrollbar is there both on Chrome and Safari browsers.

And since it got interesting I decided to try the same example but in another code sharing platform - [StackBlitz](https://stackblitz.com/edit/js-zvxkfc).

You can observe that there is no missing scrollbar there viewing the project in the platform and also opening it in a new tab.

Thank you for your time! 😊
