### ISSUE TITLE
Expose a configuration where user can set or unset tabIndex for More button in the Table component

### ISSUE THREAD

**Issue by kilgharsap** [SAP/ui5-webcomponents#6691]
### Is your feature request related to a problem?

We have a business requirement which requires us to skip the focus for the More button while tabbing through the elements for the better accessibility experience. 

### Describe the solution you'd like

Currently the for the More button section's tabindex="1", and because of that the user has to tab through this button/link, we need a way to dynamically remove this tabindex attribute or set the tabindex="-1" so that we can skip 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @kilgharsap ,

The 'More' button of which ui5 component are you talking about? Could you please give us an example?

Also keep in mind that excluding the more button from the tab chain ,would actually violate the accessibility of the application, because as per the accessibility standards every intractable element should be accessible with mouse and with keyboard and you are going to exclude the accessibility via keyboard.

Kind Regards,
Elena
