### ISSUE TITLE
Menu/MenuItem: cannot access sub item when first item is disabled

### ISSUE THREAD

**Issue by cmealares** [SAP/ui5-webcomponents#6709]
### Bug Description

When the first menu items of a submenu is disabled, the user cannot access the subemenu. The submenu is closed as soon as the mouse passes on the first (disabled) item.

### Affected Component

Menu

### Expected Behaviour

The user should be able to access the submenu and select the items that are not disabled.

### Isolated Example

https://codesandbox.io/s/priceless-tom-irg9v8?file=/src/App.js

### Steps to Reproduce

1. Click on 'ShowMenu' button
2. Open sur menu 'Two' and try to select item 'bbb'

### Priority

Medium

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Additional Context

Organization: SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

The issue is reproducible with mouse, with the keyboard everything works find and the user can select the submenu menu item. 

When the user tries to select an item in a submenu with the mouse, and the first submenu item is disabled, once you try to move the mouse to the submenu, the menu closes.

Can you please have a look?

Kind Regards,
Elena
