### ISSUE TITLE
[MultiComboBox | all frameworks | latest ]:

### ISSUE THREAD

**Issue by Calvin451** [SAP/ui5-webcomponents#6742]
### Bug Description

We are using `@ui5/webcomponents-react` in our project. During the usage of the MultiComboBox, we noticed the following usability concerns:  

1. After selecting an element from the dropdown it is not possible to continue typing to filter the list further. Doing so requires an extra click inside the input field.
2. If I enter an invalid string I get the "Invalid entry" message, however, I can not see what I entered. This could lead to confusion with different keyboard layouts (e.g z instead of y on a German keyboard). 
3. We would expect the list to be empty for invalid inputs

This behavior can also be observed in the official [UI5 Demos](https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox)

### Affected Component

MultiComboBox 

### Isolated Example

https://sapui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox/sample/sap.m.sample.MultiComboBox

### Steps to Reproduce

Scenario 1:
1. enter "Mo" into the field
2. select the first entry via the checkbox
3. continue typing the word "Mouse"

Scenario 2: 
1. enter "z" into the field
2. error pops up and there is no indication to what I typed
3. after a while the input is reset to the last valid entry

Scenario 3:
1. enter "Mous" into the field
2. finish by typing "Mousw" 
4. error pops up but again no indication. And the list still shows results for the last valid string.

### Priority

High

### UI5 Web Components Version

latest

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @Calvin451 ,

All those three points regarding the MultiComboBox component/control are how it should working by design. 

Here are our answers to all points:
1. You need an extra click as in contrast with the other input controls, the MultiComboBox requires the real focus to be moved to the list, thus leaving the input field. This is needed for proper accessibility and we cannot change that. 
2. The MultiComboBox allows for input that **only** matches particular item in the list. It does not allow for free text entering. You cannot see what you have typed in, but there is clear indication that whatever was entered cannot result in selection and the control gives you the opportunity to continue writing without the need to delete invalid input.
3. This point is direct result of the answer to point 2: As the user cannot enter text that does not match an item from the list, the list cannot be empty. 

Hope this clears things a bit.

Best Regards,
Hristo
