### ISSUE TITLE
[Feature Request][ui5-panel]: please provide a way to customize the accessibleName for the Expand/Collapse Button

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents#6745]
### Feature Request Description

![image](https://user-images.githubusercontent.com/1995447/226497591-151a7ab1-19fb-413e-8bd3-9e18b46be2ff.png)
We are showing multiple Panels in the page. We have to have a way to differentiate the buttons in different Panels.

### Proposed Solution

Please expose a property to customize the accessible name for the button.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please take a look at this feature request?

Best regards,
Siyana

**Comment by elenastoyanovaa** [comment]
Hello @BennyHuang ,

We have an internal property called "useAccessibleNameForToggleButton". If you set an accessible name to the panel and your panel is rendered with a header slot and you set this property to true, the panel button will be labelled and will display correctly in the JAWS buttons dialog. The reason why we don't expose this property is that it leads to a double announcement of the accessible name value on forward navigation to the panel button. This is expected since the accessible name is set on the panel container (and since the panel is a region when you enter the region information about it is announced) and on the button as well. On backward navigation using Shift+Tab inside the panel the double announcement won't be present. You can use it in the following way:

```
<ui5-panel accessible-name="My new panel with header SLOT and button" use-accessible-name-for-toggle-button >
		<div slot="header" class="header">
			<ui5-title>Accessible name test</ui5-title>
		</div>
		<ui5-title ui5-title="">Lorem ipsum!</ui5-title>
</ui5-panel>
```

Is this suitable for you?

Kind Regards,
Elena

**Comment by BennyHuang** [comment]
@elenastoyanovaa thanks. It should work. But we are using the react wrapper and this prop is not exposed in react wrapper Panel. Could you help to move the ticket to web-components-react and see whether they can expose this prop?
