### ISSUE TITLE
[SF] TreeItem - additionalText is hidden when text is too long

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents#6757]
### Bug Description

In the TreeItem component, when the text for the item is very long, the text is truncated but the additionalText part which is supposed to show at the end of the item, is now hidden.

<img width="631" alt="Screenshot 2023-03-21 at 2 32 03 PM" src="https://user-images.githubusercontent.com/36656306/226745881-5cd8de19-4f48-42ed-b117-ef3db95f87c7.png">

### Affected Component

TreeItem

### Expected Behaviour

The additionalText should be visible for the TreeItem

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-treeitem-additionaltext-is-hidden-0gi7ri?file=/index.html

### Steps to Reproduce

1. Go to https://codesandbox.io/s/ui5-webcomponents-treeitem-additionaltext-is-hidden-0gi7ri?file=/index.html
2. The first tree item has the additionalText hidden because the text is too long
3. The other two tree items display the additionalText properly

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The ui5-tree's additional-text gets cut off and does not visualize properly if the ui5-tree-item's text is too long. The issue is reproducible on the given [example](https://codesandbox.io/s/ui5-webcomponents-treeitem-additionaltext-is-hidden-0gi7ri?file=/index.html) and also on the Tree's [playground page](https://sap.github.io/ui5-webcomponents/main/playground/components/Tree/) if you manually set the additional-text and text proporties with the dev tools. However, I could not reproduce it that way via the Tree's [test page](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Tree/).

Could you please take a look at this?

Best regards,
Siyana
