### ISSUE TITLE
Tab Container - Focus on More Button is not correct 

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6763]
### Bug Description

Focus on More Button is not correct

### Affected Component

Tab Container

### Expected Behaviour

The Focus on the 'More' Button (overflow behavior) should be outside of the More Button and not inside (as it is currently). Please see VD spec.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/

### Steps to Reproduce

1. Click on the more button of the sample Text only End Overflow
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="191" alt="image" src="https://user-images.githubusercontent.com/6813930/226912766-74a23d71-0102-4d10-8c14-5a8da892ddc4.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,

The focus outline on the overflow button of the TabContainer does not visualize properly. The issue is reproducible on the [playground page](https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/), see the "Text only End Overflow" example and focus on the "More" button. It seems that the focus outline is also incorrect and gets cutt off on Quartz theme too:
![image](https://user-images.githubusercontent.com/72251110/227237428-f46d2019-798b-41f1-aa67-dc535dc1907f.png)

Could you please take a look at this?

Best regards,
Siyana

**Comment by gmkv** [comment]
Hi @blaesius 
Where are you seeing this new alignment issue?
