### ISSUE TITLE
[Table]: bottom border of table headers is not visible when sticky column header is enabled

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents#6767]
### Bug Description

When stickyColumnHeader option is used, bottom header of the table header is not visible.

### Affected Component

Table

### Expected Behaviour

Bottom border should be visible

![Screenshot 2023-03-22 at 10 44 42 AM](https://user-images.githubusercontent.com/65705637/226993578-bfd50ea1-a6b2-4996-98d9-29c1b19e96b5.png)

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue of Table's header not having correct border when sticky header is enabled can be reproduced on the [Table's test page](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/Table/?sap-ui-theme=sap_horizon) on the Horizon theme.

Could you please take a look at this?

Best regards,
Siyana

**Comment by elenastoyanovaa** [comment]
Hello,

Based on my analysis based on comparing the styles of the UI5 Responsive Table, where the border is visible and the ui5-table I think that the issue comes from the predefined styles of the table element (the ones that come by default depending on the type of html elements). Those styles are overwritten in UI5, more specifically  -  border-collapse: collapse; is border-collapse: separate; If I set this style to collapse in UI5, the border is not visible when the header is sticky. Unfortunately if I apply the same styling ( border-collapse: separate;) the issue is not fixed for the component, maybe something else is missing.

**Comment by hristop** [comment]
Hi @gurkirpalgill ,

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.

The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.

While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.

However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.

We are excited about the opportunities this transition will bring and the positive impact it will have on our product.

Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.

Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component.

Best Regards,
Hristo
