### ISSUE TITLE
Checkbox - Missing “Esc” key function by canceling events on focused element (ACC)

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6772]
### Bug Description

Missing “Esc” key function by canceling events on focused element (ACC)

### Expected Behaviour

Only “Shift” key works by canceling event triggered from “Space” key. “Esc” should work as well.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/CheckBox/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-p,

Could you please check this? If click action is triggered by SPACE key user is not able to discard it by pressing SHIFT / ESCAPE key.

**Comment by dobrinyonkov** [comment]
Hi @blaesius, as per our accessibility specifications, we have determined that the use of the SHIFT key for canceling actions provides sufficient support. We kindly request that you direct us to a W3C standard that we may 
reference in order to address this feedback to our accessibility specification owners.
