### ISSUE TITLE
ProgressIndicator - Opacity of disabled progress indicator not correct

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6773]
### Bug Description

Opacity of disabled progress indicator not correct

### Expected Behaviour

when progress indicator is disabled, the opacity should set to be 0.4 instead of 0.5. Please check VD wiki for details

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/ProgressIndicator/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="580" alt="image" src="https://user-images.githubusercontent.com/6813930/227139684-1657184c-0a42-406d-9ee4-2aa5459f3851.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

On the playground page of the [ProgressIndicator](https://sap.github.io/ui5-webcomponents/playground/components/ProgressIndicator/), when the progress bar with `disabled ` attribute from the first "Basic Progress Indicator" example is inspected via dev tools, it can be seen that the opacity of the `.ui5-progress-indicator-root` is different than that listed on the specification [here](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2650676572) (sapContent_DisabledOpacity). The issue is reproducible also on [the test page](https://sap.github.io/ui5-webcomponents/main/playground/main/pages/ProgressIndicator/?sap-ui-theme=sap_horizon) for both Horizon and Fiori 3 themes - opacity is 0.5 instead of 0.4 as stated in the specification.

Could you please take a look at this?

Best regards,
Siyana
