### ISSUE TITLE
Page - Wrong alignment of the title

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#6787]
### Bug Description

The title is center-aligned in Web components. It should be left-aligned

For the right alignment parameters, check the VD Wiki.

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Page/

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

<img width="660" alt="image" src="https://user-images.githubusercontent.com/6813930/227213154-9632e1f3-97d5-48f1-85a3-ba57931e78ce.png">

### Priority

Medium

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The Page's title is incorrectly aligned - you can reproduce the issue on the [playground page](https://sap.github.io/ui5-webcomponents/playground/components/Page/)'s first example, where the title is centered instead of left-aligned, as is stated in the [specification](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697897161).

Could you please take a look at this?

Best regards,
Siyana

**Comment by elenastoyanovaa** [comment]
Hello,

The page in the ui5-webcomponents receives a header slot and the header content is managed by the application, so this is actually not a bug in the page web component. Rather the example should be adjusted in order to fit the specification.

I have prepared a sample for you showing that by using the API's provided by the different web components, you could achieve the desired visual representation https://codesandbox.io/s/ui5-webcomponents-forked-yefo1x?file=/index.html

Nevertheless, we noted your finding and will improve the sample.

Kind regards,
Elena
