### ISSUE TITLE
[Breadcrumbs] Infinite loop when rendering

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6802]
### Bug Description

We have a strange bug while rendering `ui5-breadcrumbs` in a `ui5-li-custom`. Its symptom is a console error, but the bigger problem is that it completely breaks the application once it occurs:

![image](https://user-images.githubusercontent.com/110408767/227975233-91e07847-c2cd-42d4-a67c-2bd8b60e765a.png)

I was able to create a reproducible [sandbox](https://codesandbox.io/p/sandbox/upbeat-lumiere-cj2ykh?file=%2Fsrc%2FApp.tsx) (open sandbox, press F12 to open console, click on button -> error).

<b>NOTE 1:</b>
The bug doesn't occur if the line `import "@ui5/webcomponents-icons/dist/AllIcons.js";` is removed. Without the import, however, I have the following error in the console:

![image](https://user-images.githubusercontent.com/110408767/227976412-d1844295-ee47-4feb-9def-37919513fd25.png)

I don't know why this import is necessary at all, since the example doesn't use any icons.

<b>NOTE 2:</b>
The bug disappears if you replace the strings "H" & "B" in the breadcrumb items by "HHH" & "BBB", respectively.

<b>NOTE 3:</b>
The bug is reproducible as well with the breadcrumb items "(all)" & "Arkansas" instead of "H" & "B", which goes against my theory that it is related to the length of the strings.

Thanks in advance!

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is also reproducible via the following snippet:
https://codesandbox.io/s/ui5-webcomponents-forked-67ibio?file=/index.html

It seems that the <code>import "@ui5/webcomponents-icons/dist/AllIcons.js";</code> package is needed for the drop down arrow icon, which is rendered when the <code>ui5-breadcrumps</code> are placed in a <code>ui5-li-custom</code>.

This issue isn't reproducible when the <code>ui5-breadcrumps</code> are used standalone or the text node inside the <code>ui5-breadcrumps-item</code> is longer than a single character as @ej612 described in detail.

Best regards,
Boyan
