### ISSUE TITLE
[Breadcrumbs] Collapsing despite having plenty of space

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#6803]
### Bug Description

There seems to be an issue with the `ui5-breadcrumbs` component: When rendered inside a `ui5-list`, and despite having plenty of space, it collapses and moves part of the breadcrumbs into an overflow popover:

![image](https://user-images.githubusercontent.com/110408767/227986892-43e15b15-47d4-491f-9770-f55994886191.png)

I have created a sandbox: https://codesandbox.io/s/young-dust-3hmpw4?file=/src/App.js

### UI5 Web Components Version
1.10.3

### Browser
Chrome

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is also reproducible via the following snippet:
https://codesandbox.io/s/naughty-curie-ld3cic?file=/src/App.js

By design the links in the breadcrumb should only overflow if there isn't enough horizontal space like with the sap.m.Breadcrumbs:
https://jsfiddle.net/tr7haoe5/1/

Instead the <code>ui5-breadcrumbs</code> does overflow even if there is enough horizontal space.
If we were to set the <code>width</code> attribute of the `<ui5-breadcrumbs>` element to `100%` the links will overflow properly. The `ui5-li-custom` container with class "ui5-li-content" does take all the available screen width, which isn't used properly by the `ui5-breadcrumbs`.

Best regards,
Boyan
