### ISSUE TITLE
[Tree]: In Multiselection mode selected items are getting read twice by screen Reader

### ISSUE THREAD

**Issue by vidyakore** [SAP/ui5-webcomponents#6878]
### Bug Description

In Tree component,
if we select the child component using "Enter" key, screen reader will read the child component twice.

Kindly Note: This is for SAP internal consumption
Tool used is **Jaws**.

### Expected Behaviour

Item should get read only once after selection.

### Isolated Example

can be reproduced in https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs

### Steps to Reproduce

1. go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs
2. select the multiselect mode
3. turn on the screen reader (jaws)
4. select the child "Tree 1.1.1" using enter key
5. Screen Reader is reading that element twice

### Log Output, Stack Trace or Screenshots

![image](https://user-images.githubusercontent.com/56337652/230339307-5f0c5f65-7f21-403a-8ff6-c4dfd19bc1d2.png)

### Priority

None

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

In the `Tree` component, when child element is selected with "Enter" key, screen reader announce the information twice. The issue is also reproducible it the item is selected with "Space" key.

### Steps to Reproduce

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--docs
2. Select the multiselect mode
3. Select the child "Tree 1.1.1" using enter/space key
5. Screen Reader is reading that element twice

Could you please have a look at it?

Thanks and Kind regards,
Yana

**Comment by Vivek-Vishal** [comment]
@yanaminkova - any updates on this issue ?

**Comment by akshilverma** [comment]
@yanaminkova is there an expected date to fix this issue?

**Comment by yanaminkova** [comment]
Hello @akshilverma and @Vivek-Vishal ,

Please excuse the delay in my answer.
At the moment we are working on the fix for the issue.
Once it is ready, you will be updated here.

Thanks and Regards,
Yana
