### ISSUE TITLE
[SF][A11y][ui5-dialog][ui5-popover] All dialogs and popovers close on press of esc key

### ISSUE THREAD

**Issue by bonnieso** [SAP/ui5-webcomponents#6884]
### Bug Description

When multiple dialogs or popovers are open on a given page, pressing the "escape" key closes all of the dialogs and popovers. This happens when different cores of ui5-webcomponents exist on a page and different cores control different dialogs and popovers. So when then "escape" key is pressed, this line https://github.com/SAP/ui5-webcomponents/blob/63986f557a78ac14674d2e618ed40967ed5a1102/packages/main/src/popup-utils/OpenedPopupsRegistry.ts#L48 executes for all of the open dialogs and popovers because the open components are being tracked by this variable https://github.com/SAP/ui5-webcomponents/blob/63986f557a78ac14674d2e618ed40967ed5a1102/packages/main/src/popup-utils/OpenedPopupsRegistry.ts#L9 and the dialogs loaded from different cores aren't aware of each other. In order to solve this issue, we are proposing to add a registry that is shared across different cores.

### Affected Component

ui5-dialog

### Expected Behaviour

On press of the "escape" key, only the component (ui5-dialog or ui5-popover) that is in focus closes. 

### Steps to Reproduce

1. Create a page that opens a ui5-dialog
2. Create a separate component that includes a ui5-popover in a different repository
3. Add an instance of the ui5-popover component to the ui5-dialog
4. Open the ui5-dialog
5. Open the ui5-popover
6. Press the "escape" key
7. Observe that both the ui5-dialog and ui5-popover close

### Log Output, Stack Trace or Screenshots

N/A

### Priority

Medium

### UI5 Web Components Version

1.9.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by codefactor** [comment]
Another thought we might explore that OpenUI5 is doing is capturing the keydown event on the Dialog level and the prevent the event from propagating up when the Dialog thinks it's on top, and then close the Dialog. That way we wouldn't have multiple Popups handling the same keydown event because the one that is focused will handle it and prevent other UI5 cores from getting the event when listening on the window.

**Comment by yanaminkova** [comment]
Hello @bonnieso,

Thank you for sharing this finding!

Could you please provide a test system or an isolated example where the issue is reproducible?

Kind Regards,
Yana

**Comment by codefactor** [comment]
@yanaminkova ,

Here is an isolated example:
https://codesandbox.io/s/ui5-webcomponents-forked-h45gbn?file=/src/index.js

NOTE: this requires that there be 2 versions of UI5 web components on the page - so to achieve this, I created a small bundle that exposes a global function called "openInnerDialog"

You can find this code here:
https://github.com/codefactor/issue-6884/blob/master/main.js

Steps to produce the bundle:
Clone/fork the repository, run `npm install` and then `npm run build` and copy the resulting index-XXX.js from the dist folder.

To reproduce the problem
1. click on the button "Open Dialog"
2. click on the button "Open Inner Dialog" which opens the other bundle's dialog
3. press Escape Key.

Expected:
only the top-most dialog will close

Actual:
both dialogs close at the same time

Reason:
There are 2 copies of the `OpenedPopupRegistry` file active, each with their own copy of the `openedRegistry` array variable. Both UI5 copies are listening to the `keydown` event on the `window` and when the escape key is pressed, both copies actively try to close whatever Popup is on top, and both believe the current Dialog is on top.

Suggestions For Fixing:
1. Allow multiple UI5 copies to coordinate a central shared registry for which Popup is on top, rather than having multiple copies that will mislead Popups into believing they are on top, when they are in fact not on top.
2. Listen to the keydown event within the Popup's shadowRoot, if the Popup receives the escape key down event AND the Popup believes it is on top (even if technically it is not), then call `evt.stopPropagation()` and close the Popup internally, so that way the window will NOT receive the event and the Popup registry is never actually used in most cases.

NOTES:
- There might be other problems that happen when a Popup wrongfully believes they are "on top" so having a more coordinated central registry might resolve other problems
- We may also want to consider an `OpenUI5Support` interaction which could also detect when UI5 Popups are on top as well.
- The fact that the Popup was in focus at the time user pressed Escape key should take precedence over other global events received - which we have use cases where UI5 Popups activate OpenUI5 dialogs in Production as well
