### ISSUE TITLE
SegmentedButton: setting `width` is not supported.

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#6897]
### Bug Description

Applying a custom `width` is not supported for the `SegmentedButton` component. 

### Affected Component

SegmentedButton

### Expected Behaviour

It should be possible changing the width of the component without having to use another element.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-br8o51?file=/index.html

### Steps to Reproduce

1. Go to [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-br8o51?file=/index.html)
2. See that the first SegmentedButton has a width of `100%` even though `400px` was set via inline style and stylesheet.
3. When wrapping the SegmentedButton and applying the custom width to the wrapper element, it works as only the given width is available inside the container.

### Priority

None

### UI5 Web Components Version

1.12.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue is reproducible as described by the reporter. It can be reproduced in the playground as well.
The width seems to be getting overwritten by the control, although according to the documentation, this should happen only if no width is set.

Could you please have a look?

Best regards,
Ivaylo
