### ISSUE TITLE
[Framework]: uncaught error - `require is not defined` 

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#6916]
### Bug Description

With the latest release 1.12.1, production builds of UI5 Web Components are throwing an error while development builds are running fine:
```
UI5ElementMetadata.ts:380 Uncaught ReferenceError: require is not defined
    at UI5ElementMetadata.ts:380:1
    at index.js:11:9
    at index.js:11:9
```

### Affected Component

all components

### Expected Behaviour

Should not throw an error in the production build.

### Isolated Example

https://codesandbox.io/s/relaxed-hoover-6h2xpq?file=/src/App.js

### Steps to Reproduce

The error is not reproducible in the sandbox and it has to be downloaded
1. Open the [CodeSandBox](https://codesandbox.io/s/relaxed-hoover-6h2xpq?file=/src/App.js) and download it
2. install dependencies with `npm install`
3. run a prod build: `npm run build`
4. serve the build result: `npx serve -s build`
5. Open the URL shown in the terminal in a browser and see the error.

### Log Output, Stack Trace or Screenshots

<img width="374" alt="image" src="https://user-images.githubusercontent.com/8775211/231715830-4a112b16-cf0f-48f2-8ea6-11c6b4e01b8f.png">

### Priority

Very High

### UI5 Web Components Version

1.12.1

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

All

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
Hi Marcus,

when I switch off source maps, I can see that the error is in the file `StaticArea.ts`, which gets some `require` statements with babel helpers about `createClass`.

Somehow, during the build, babel or react-tools does not correctly treat this file as an ES6 module as the rest of the modules and is incorrectly transpiling it.

Until we find out why this happens, I found a workaround. Simply change the browserslist in package.json to "defaults".

```json
  "browserslist": [
    "defaults"
  ]
```

I'm pretty sure this is not caused by the web components update as we didn't make any change in this file.

**Comment by pskelin** [comment]
> I'm pretty sure this is not caused by the web components update as we didn't make any change in this file.

Yep, changing to 1.12.0 in the project gives the same error

**Comment by vladitasev** [comment]
I think this is our only module that neither imports, nor exports anything, it only has a side effect:

```ts
if (!customElements.get("ui5-static-area")) {
	customElements.define("ui5-static-area", class extends HTMLElement {});
}
```

This could explain why some tools misjudge it, maybe if they expect commonjs by default.

I'll prepare a fix asap

**Comment by MarcusNotheis** [comment]
If this file has a side-effect, maybe it helps to list it as `sideEffect` in the package.json? Compilers should be able to use that hint, e.g.:

https://github.com/SAP/ui5-webcomponents-react/blob/a7396962ca311dec31a9d3eaee57fa4f3780aac2/packages/main/package.json#L16-L19

**Comment by pskelin** [comment]
@MarcusNotheis I tested what browser is giving the problem, and found that because of the
`>0.2%` browser query, `android 4.4.3-4.4.4` is included.

When I remove it manually, the build is fine.

Where is this browserslist query coming from? Is it from codesandbox, or from create react app? In all cases, I think support for android 4.4.3 is out of scope and a fix should not be necessary.

**Comment by MarcusNotheis** [comment]
Thanks for digging into that @pskelin!
This is the default browserslist which come with create-react-app, I'll exclude this browser then for our apps 🙂
