### ISSUE TITLE
[MultiComboBox]: User unable to see the complete additional text if it is lengthy

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents#6937]
### Describe the bug

Hi Colleagues,

We have received an incident raised by accessibility testing team. We have a multicombobox provided to the user. The options have text and additional text property being set. In scenarios where the additional text is lengthy , it gets wrapped and ellipses are shown.

User never gets to see what the complete text was. Could there be a possibility of providing a tooltip kind of feature which shows complete text when user hovers over the option.

Changing the element width is not a full proof solution as we may not know what the max length is.

### Isolated Example

https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-0m7i8r?file=/src/App.js

### Reproduction steps

open the dropdown to see the issue where additional text is wrapped.

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @SAP/ui5-webcomponents-topic-rl  please hhave a look.

**Comment by MapTo0** [comment]
The issues is not reproducible in OpenUI5: https://jsbin.com/bebevuteyi/edit?html,output
Therefore I consider that as a bug, not a FR.

**Comment by MapTo0** [comment]
After some debugging I noticed that all the styles that should be changed belong to the `ui5-list`
The popover needs its content to grow in order to be wider.
In this case the `additional-text` of the list item is set to truncate instead of grow the list item itself.
I managed to reach the desired behaviour after removing some styles.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/5821279/233671861-405c82d1-c152-4815-b689-e22c288ddb03.png">

@SAP/ui5-webcomponents-topic-p  Could you please check?

Best regards,
Martin
