### ISSUE TITLE
[SF][ui5-table] Alignment issue in popin and MultiSelect modes

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents#6952]
### Bug Description

According to the [Fiori Guidelines for the Responsive Table](https://experience.sap.com/fiori-design-web/responsive-table/#responsiveness), in popin mode and in "MultiSelect" mode, the column content should be aligned below the first column data, leaving a margin to the left of the popin columns:

<img width="776" alt="Screenshot 2023-04-25 at 5 46 53 PM" src="https://user-images.githubusercontent.com/7316793/234438034-4fedaa34-63d1-4719-97e6-1d6a2d1b9209.png">

However, the ui5-table aligns the popin columns with the selection checkbox instead:
<img width="379" alt="Screenshot 2023-04-25 at 5 41 06 PM" src="https://user-images.githubusercontent.com/7316793/234438163-3a2fc269-fda5-4834-86c4-28a4d8f66b50.png">

Also, the margin below the the first row data and the popin columns shouldn't be so large.

### Affected Component

ui5-table

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-vym8di?file=/index.html

### Steps to Reproduce

1. Go to https://codesandbox.io/s/ui5-webcomponents-forked-vym8di?file=/index.html
2. Reduce the window width to show popin mode
3. See that the popin columns are aligned with the selection checkbox of the row instead of being aligned below the first column data as it should be according to the Fiori Guidelines.

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Indeed there is a difference between openui5 and webcomponents,
Can you please take a look?

Best Regards,
Tsanislav

**Comment by hristop** [comment]
Hi @Neeeko  ,

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.

The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.

While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.

However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.

We are excited about the opportunities this transition will bring and the positive impact it will have on our product.

Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.

Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component.

Best Regards,
Hristo
