### ISSUE TITLE
DateTimePicker: Invalid value for property "maxDate"

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7022]
### Describe the bug

I have the error message:
`Invalid value for property "maxDate": May 5, 2023, 15:07:08 is not compatible with the configured format pattern: "MMM d, yyyy, H:mm:ss"`

```
<DateTimePicker
        formatPattern="MMM d, yyyy, H:mm:ss"
        maxDate={dayjs().format("MMM D[,] YYYY[,] H:mm:ss")}
        value={dayjs().format("MMM D[,] YYYY[,] H:mm:ss")}
      />
```

I dont understand the problem, the formats should be correct.

### Isolated Example

https://codesandbox.io/p/sandbox/sparkling-microservice-9geblb?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A14%7D%5D

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44802503/236466151-f09ef5f2-4aca-49fe-8a05-a708e1914b13.png)

### UI5 Web Components for React Version

~1.14.0

### UI5 Web Components Version

~1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

Could you please look over the issue?
It could be easily reproduced in the CodeSandbox: https://codesandbox.io/s/ui5-webcomponents-forked-loi56h?file=/index.html:103-128https://codesandbox.io/s/ui5-webcomponents-forked-loi56h?file=/index.html:103-128
As described by Lukas, it is not reproducible if the language is set to English.

Thank you in advance!

Kind Regards,
Niya

**Comment by hinzzx** [comment]
Hi @C3ntraX,

The issue is not reproducible for me in this [snippet](https://codesandbox.io/s/ui5-webcomponents-forked-loi56h?file=/index.html:103-128). Could you please, check if the issue is still relevant for you ?

Best Regards,
Stoyan

**Comment by C3ntraX** [comment]
Hi @hinzzx 

please change your browser language.

> As described by Lukas, it is not reproducible if the language is set to English.

Its the same problem as in the other story:

**Comment by hinzzx** [comment]
Hello @C3ntraX , 

For me the issue is not reproducible in any of the code snippets provided, even after changing the browser language to DE.

https://github.com/SAP/ui5-webcomponents/assets/88034608/745a5126-1d84-472e-b379-a6a8cf4bde58

**Comment by C3ntraX** [comment]
I don't know whats wrong with your environment. 

@Lukas742 do you know how you reproduced this behaviour?

I mean we have to find a solution, its simple to say its not working, but others are able to reporduce this issue. The same for story #6993.

Ask your teammembers?

**Comment by Lukas742** [comment]
Hi @C3ntraX 

the issue is not reproducible for me in the given sandboxes as well. Also it seems like that you have accidentally overwritten your initial codeSandbox example. I was baffled as well, because I know that it didn't work in my codeSandbox provided [here](https://github.com/SAP/ui5-webcomponents/issues/7022#issuecomment-1544170274) (which @hinzzx also referenced, including German language), but then I realized that the only thing changed was the date you're passing to the values. So, when setting the date to May (de: Mai) instead of June (de: Juni), it is showing the error again. --> [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-swfgh5?file=/src/index.js)

I think I also found the error you're facing, because the date is not correctly formatted for the given locale. If you format it by leveraging the `formatValue` method, the error should be gone and the picker should work as intended. --> [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-forked-25hss6?file=/src/index.js)
I didn't find another way than waiting for the custom-element to be defined and I don't know how practical that is. Since the `formatValue` method is only available on the instance of the web component, you would have to do the same in React.

**Comment by C3ntraX** [comment]
Hi @Lukas742 

thanks for the clarification. DayJs is the problem okay thank you 👍 
But one issue I found in your example (which is not a bug)

> const currentDateTime = dayjs().subtract(1, "month")
document.getElementById("date").textContent = currentDateTime; 

This will always return the language in english. You have to format currentDateTime to get the correct language. But this lang has to be imported and set globally.
I noticed this, because I have to load the locale dynamically somehow (or not, if I know my locales)

See: https://codesandbox.io/s/ui5-webcomponents-forked-vplsyc?file=/src/index.js

**Comment by hinzzx** [comment]
Hi @C3ntraX 

The DayJS() API is proposing a solution to the locale problem. They are offering a `localized formats` plugin, which you could use with the dayJS, when getting the currentDateTime.

```ts
dayjs.extend(LocalizedFormat)
dayjs().format('ll LTS') // results in a dynamic locale 'MMM D, YYYY h:mm:ss A' according to the localized-formats table
```

Links:
https://day.js.org/docs/en/plugin/localized-format
https://day.js.org/docs/en/display/format#localized-formats
