### ISSUE TITLE
[ui5-label]: wrapping-type="Normal" sometimes adds extra space

### ISSUE THREAD

**Issue by gmkv** [SAP/ui5-webcomponents#7042]
### Bug Description

When writing text with newlines inside a `ui5-label`, enabling wrapping-type="Normal" will result in extra space between the text and the colon.

```html
<ui5-label show-colon wrapping-type="Normal">
    UI5 Web Components are here
</ui5-label>
```

This doesn't happen when the text is written without newlines.

```html
<ui5-label show-colon wrapping-type="Normal">UI5 Web Components are here</ui5-label>
```
The only difference between the two are the whitespace characters.

### Affected Component

Label

### Expected Behaviour

Seemingly, there should be no difference between the two usages. The native label doesn't do this.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-j43ij4?file=/index.html

### Priority

Low

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @gmkv,

This behavior is caused by the new line between the text and the enclosing`</ui5-label>` tag. The same behavior is observed with native html elements:
```html
<div>
     <label>
         UI5 Web Components are here
     </label>
     <span>:</span>
</div>
````
Result: "UI5 Web Components are here :"

Seems that the new line is preserved as space, regardless of the `white-space: normal` style.
In normal circumstances the developer would minify the html or the element would be created via JS APIs, therefore such issue would be avoided.

Best regards,
Petar
