### ISSUE TITLE
MenuItem max width should be customizable/ auto adjust based on text

### ISSUE THREAD

**Issue by sneha-ajit** [SAP/ui5-webcomponents#7082]
### Bug Description

Internally a max width of 20rem is set for the MenuItem and hence the text is truncated.
<img width="1115" alt="Screenshot 2023-05-24 at 1 50 00 PM" src="https://github.com/SAP/ui5-webcomponents/assets/120373717/bc52bf6a-bbd2-418f-898f-f994215a19fa">

### Affected Component

Menu

### Expected Behaviour

MenuItem max width should be customizable or it should auto adjust based on text

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Organization

SAP

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Relates to #6795

**Comment by petyabegovska** [comment]
Hi @DMihaylova,

The feature request is that the menu width should be based on the content as in OpenUI5 (see also VD section Menu Width):

![image](https://user-images.githubusercontent.com/8136099/227518313-75b2f346-7d12-43db-87f5-bb5adfea75f7.png)

Currently, the Menu component is truncating the text, because it is internally using the List component. Please consider refactoring of the ui5-menu to use ui5-li-custom instead of ui5-li.

There is the same feature request in #6795, but also a bug with overlapping the arrow button, that is not reproducible in the List component, but only in the Menu.

Best regards,
Petya
