### ISSUE TITLE
[MultiInput]:can't change "more" to "items"

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#7083]
### Describe the bug

![image](https://github.com/SAP/ui5-webcomponents-react/assets/120740457/1ca7e24c-4376-444b-8496-10c5b36987ad)
Need to modify "9 More" to "9 Items"
refer: https://codesandbox.io/s/magical-carson-c04jdd?file=/src/App.js
### Isolated Example

(https://codesandbox.io/s/magical-carson-c04jdd?file=/src/App.js)

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/120740457/04ad76e3-9df5-456f-926b-9015b1a5f161)

### UI5 Web Components for React Version

1.7.3

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by hristop** [comment]
Hi @roshnijalan97new ,

We have brought this to feature request to our UX colleagues and after discussing the requirement, they have rejected it. Such customisation may lead to undesirable results: longer texts, translation problems are only part of this. Meaning and inconsistency is also something that was considered and would have had a huge impact. 

Best Regards,
Hristo

**Comment by FRicardi** [comment]
@hristop  @niyap 
Albeit changing the label to "items", or any other copy text, for all cases can be troublesome, on the [fiori guidelines](https://experience.sap.com/fiori-design-web/multiinput/#reviewing-tokens), it is stated that, when the first item is greater than the input and only the suggestion token is shown, it should show "X Items" label instead of "x more". 

All of this while out of focus on the component. Not sure if I got it wrong the statement there, but if this is correct, can we make this change? Currently, it shows "X More" despite the size of the first token, as per my tests. 

Here's a code sandbox that i've used for other purpose but might serve well for this case
https://codesandbox.io/s/multi-input-test-w0zii7?file=/src/App.js:2522-2724

![image](https://github.com/SAP/ui5-webcomponents/assets/13752954/9273cae2-0b84-4557-b0e9-4ed3b00d9d40)

**Comment by hristop** [comment]
hi @FRicardi ,

We will let the design team know that the guidelines are out of data and should be updated. 

The second point has specific behaviour mentioned in the Fiori guidelines as well but it is still under development. It is currently being implemented and can be tracked here: [5229](https://github.com/SAP/ui5-webcomponents/issues/5229)

Best Regards,
Hristo
