### ISSUE TITLE
Menu - Wrong alignment in RTL mode

### ISSUE THREAD

**Issue by blaesius** [SAP/ui5-webcomponents#7095]
### Bug Description

RTL: right side of the menu should be aligned with the right border of the reference button

### Affected Component

ui5-menu

### Expected Behaviour

![image](https://github.com/SAP/ui5-webcomponents/assets/6813930/9967657a-542d-4c50-85f8-26847de95bff)

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/components/Menu/

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.13

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-b ,

Please check the detailed description of the issue provided by the reporter. It can be easily reproduced in : https://sap.github.io/ui5-webcomponents/playground/components/Menu/

Could you please look over?

Thank you in advance!

Kind Regards,
Todor

**Comment by hinzzx** [comment]
Hi @blaesius,

I could not reproduce the issue. This is what I observe while trying to reproduce the scenario:
![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/15da9e75-cc4e-47a3-bb26-930998e4c7ed)

To me it seems like the Menu while in RTL mode is aligned properly now. Could you please check if the issue is still relevant ? Thank you in advance !

Best Regards,
Stoyan
