### ISSUE TITLE
[MultiComboBox]: With allowCustomValues=true. Unable to input some custom texts

### ISSUE THREAD

**Issue by anshul-031** [SAP/ui5-webcomponents#7125]
### Describe the bug

MulticomboBox Feature Link: https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multicombobox--docs

Suppose we have a MultiComboBox (allowCustomValues=true) with List items ["**I**tem1","**I**tem2","**I**tem3","**I**tem4","**I**tem5",] i.e., all starting with capital "**I**"

Now I want to add a custom token with value "**i**tem6" i.e., starting with small "**i**". I can't add. 
**Issue:** As all the previous list items were starting with Capital "**I**". It would not allow me to write any text starting with small "**i**". Whenever I would try to write "**i**tem6", it would automatically convert the text to "**I**tem6" i.e., capitalize the "**i**"  & Hence I would not be able to add the text with small "**i**".

Similarly, if the List items has ["**i**tem1","**i**tem2","**i**tem3","**i**tem4","**i**tem5",]  i.e., all starting with small "**i**". It won't allow me to add any text stating with capital "**I**"

### Expected Behaviour

As it's a Editable input field, it should editing any kind of input.

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12

### Browser

Chrome, Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
I managed to reproduce the described problem by adding allow-custom-values property to the ui5- multi-combobox in the basic sample and trying to type "item", which always lead to autocompletion of "Item" with capital letter. Can you, please, confirm if it is the desired behaviour of the control or it is an issue?
Thank you!
Kind regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by ivoplashkov** [comment]
Hello,

Thank you reporting this issue.

Considering your use case, we would recommend you to use ui5-multiinput, instead of ui5-multicombobox, since the multicombobox is used mostly to validate items which are already part of the list. The ui5-multiinput is the better option when you want to add tokens which are not part of the list, which is your use case.

You can check https://sap.github.io/ui5-webcomponents/playground/components/MultiInput/, the section "Multi Input and token creation onChange" where this is demontstrated. However to completely cover your case, you might want to set "noTypeahead" property to true.

Best regards,
Ivaylo
