### ISSUE TITLE
OpenUi5Support: Cannot read properties of undefined (reading 'getNextZIndex')

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents#7128]
### Bug Description

Some pages are throwing fatal exceptions when trying to open popups like Dialogs or ValueState error messages on inputs, but only when OpenUI5 is being used. The root cause is OpenUi5Support has a dependency on sap/ui/core/Popup but does properly require the dependency.

OpenUi5Support uses sap.ui.require Probing function:
```
  const Popup = window.sap.ui.require("sap/ui/core/Popup") as OpenUI5Popup;
```

> When called with a single string, that string is assumed to be the ID of an already loaded module and the export of that module is returned. If the module has not been loaded yet, or if it is a Non-UI5 module (e.g. third-party module) without a shim, undefined is returned.

Documentation: https://openui5.hana.ondemand.com/api/sap.ui#methods/sap.ui.require

The caller should use OpenUi5Support#init() before using web components that require Popups; however, if that is not done in time there are fatal exceptions.

It can also be improved that OpenUi5Support#init() could somehow be called automatically so that consumers don't need to call that.

### Affected Component

OpenUi5Support

### Expected Behaviour

1. If Popup is undefined then no errors should occur - perhaps treat as if ui5 is not loaded
2. The init function should be optional, there should be ways to automatically initialize feature without requiring something to call init()

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-j88zw8?file=/src/index.js

### Steps to Reproduce

1. Use the isolated example and press the button to open the dialog

Actual Behavior: The page breaks with an exception

### Log Output, Stack Trace or Screenshots

```
Cannot read properties of undefined (reading 'getNextZIndex')
    at OpenUI5Support.getNextZIndex (https://j88zw8.csb.app/node_modules/
ui5/webcomponents-base/dist/features/OpenUI5Support.js:92:18
    at getNextZIndex (https://j88zw8.csb.app/node_modules/
ui5/webcomponents-base/dist/util/PopupUtils.js:114:27
    at HTMLElement._open (https://j88zw8.csb.app/node_modules/
ui5/webcomponents/dist/Popup.js:264:50
    at HTMLElement.show (https://j88zw8.csb.app/node_modules/
ui5/webcomponents/dist/Dialog.js:71:17
```

### Priority

Medium

### UI5 Web Components Version

1.13.0

### Browser

Chrome, Edge, Firefox, Safari

### Additional Context

This can be fixed by consumer to call init() function.

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by PetyaMarkovaBogdanova** [comment]
Hi team,
can you, please, take a look at the error thrown, when using Popups with OpenUI5Support?
Thank you!
Best regards,
Petya Markova.
(UI5 WC Dispatcher)

**Comment by ilhan007** [comment]
Hello @codefactor 
yes in order to make the feature work, it should be imported before all components' imports, so that init() is called when first event component definition takes place.

If you add the import on top - the exception won't be thrown anymore.
However, we missed to document that part in the related article https://github.com/SAP/ui5-webcomponents/blob/main/docs/2-advanced/04-OpenUI5-integration.md
so we can at least do so and even document it on more visible place, not in the advanced section only.
Also, we will throw a warning to inform you what you need to do to fix it - e.g to import the feature before the components.


We need this as first import because  based on that we reuse a lot of things from OpenUI5 
When you import the above OpenUI5Support module:
- OpenUI5 configuration takes precedence over UI5 Web Components configuration for all common entities (theme, language, etc.). In addition, changing the theme in OpenUI5 will also change the theme in UI5 Web Components.
- Fonts will not be loaded twice (just once by OpenUI5, and reused).
- Locale data assets will not be fetched twice (just once by OpenUI5, and reused).


and if the feature is not registered during framework boot (which is done with the first component definition), the reuse won't happen.

**Comment by i832513** [comment]
I am fine with a solution that only involves better documentation, thanks for the follow-up.
