### ISSUE TITLE
[tabcontainer | segmented-button]:

### ISSUE THREAD

**Issue by nicolas-coelho-sap** [SAP/ui5-webcomponents#7158]
### Bug Description

There is a tab container with two tabs. Each tab contains a segmented button (exactly the same way to build them).
When I change from a tab to the other, the size of the segmented button quickly changes. If you switch between the two tabs, you can see something like a flicker with the segmented buttons.

### Affected Component

tabcontainer and/or segmented-button

### Expected Behaviour

The size of the segmented buttons should not change and no flicker should be visible

### Isolated Example

https://codesandbox.io/s/ui5-web-components-issue-qvcvlb

### Steps to Reproduce

1. Go to the sample provided in the [codesandbox container](https://codesandbox.io/s/ui5-web-components-issue-qvcvlb)
2. Switch between the two tabs
3. Observe change of the size of segmented buttons

### Priority

Medium

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Operating System

Windows

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-b ,

Can you check if the visual glitch coming from the rendering of the segmented button, when a tab is changed could be somehow avoided? Perhaps not, but please double check as it is easily noticeable.
Lowering the priority suggested by the author as the issue is only visual and present for less than a second. (also tried with slow internet).

Kind Regards,
Elena
Github Dispatcher

**Comment by hinzzx** [comment]
Hi @nicolas-coelho-sap ,

Could you please check if the issue is still reproducible using the latest verison, as I am not able to reproduce the issue locally, as well as in the provided snippet after changing the version to **"latest"**.

BR,
Stoyan
