### ISSUE TITLE
[theming]: Many css variables are no longer exposed

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7182]
### Bug Description

For the calculation of some of my own components I use your CSS variables.

The following are no longer accessible, but they were in version 1.13.0:

var(--_ui5_shellbar_root_height) - very important to calculate an empty div element, so that the shellbar can displayed "fixed"

Im using Toastify as library and customize the theming based on your toast theming:
"--toastify-color-light": "var(--_ui5_toast_background)",
"--toastify-color-dark": "var(--_ui5_toast_background)"

The variables are also no longer available, please give us a way to access them or give me other possiblities to archive the same behaviour.

### Expected Behaviour

A way to safely access the variables - I dont know, why they are no longer accessible

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.14.2

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-core 

This issue is in relation to the recently introduced scoping of our CSS variables.
Since the variables are now defined under a generated attribute instead of directly on the `:root` element.
Please also verify if these variables are intended to be allowed for access by outside code.
I thought the idea of the underscore prefix - i.e. `--_ui5_toast_background` was a sign for this.

Could you take a look?

**Comment by C3ntraX** [comment]
I mean some variables are more important than other, If there is any way to access scoped css variables, it would be very nice.
Like an public api to access scoped css variables. If I can access the scoped variables from the Component via import it would be good enought.

But some important variables like the shellbar height are important ones. Currently Im imporing important css varaibles via 
import { ThemingParameters } from "@ui5/webcomponents-react-base"; @Lukas742 
or using them directly in css.

**Comment by C3ntraX** [comment]
Hi @ilhan007,

thanks for the  --_ui5_toast_background equivalent. I didn't know about this.

I created https://codesandbox.io/p/sandbox/css-variables-n4r7m5?file=%2Fpackage.json%3A16%2C27
But it seems, that the variable is available there but not for my app thats wreid.

![image](https://github.com/SAP/ui5-webcomponents/assets/44802503/b9f7c1d9-524d-4cfb-9b45-b5111dead0b0)

And in my app the variable is not defined:

![image](https://github.com/SAP/ui5-webcomponents/assets/44802503/38626cb0-8f54-46d6-ae07-b77554c54707)

Leaving aside the case that I shouldn't use the variable, I don't understand why the variable isn't available to me even though I have exactly the same structure of the components.

**Comment by Lukas742** [comment]
> The wreid thing is, with the exact same versions, the codesandbox has still access to the property but not my own app.

I'm not sure why this is happening, maybe they are still registered somewhere else. Let's wait for input from one of the ui5-webcomponents members about this topic.

> Should I raise an FR for the CSS variables I need (Toolbar and Shellbar in this case) in the react repo or better in this repo?

We (ui5-webcomponents-react) will only offer public variables of the [theming-base-content](https://github.com/SAP/theming-base-content) repo (--> `ThemingParameters`) and no other CSS variables. This has mainly two reasons:

1. Consistency between apps: The variables of the `theming-base-content` are used across many applications and are there to ensure the same look and feel. If we would add our own CSS vars, then it could happen that we introduce discrepancies between React apps (or microfrontends) and other apps using SapUI5 or ui5-webcomponents. In general you can say, that if a CSS variable is not exposed in the `theming-base-content` we recommend not to change it.
2. Maintainability: We decided not to offer any other CSS Variables than the official `theming-base-content` variables because we treat our components as public API but not their styling (components may evolve with design iterations while keeping their APIs stable). So if we would add our own CSS vars then there's a whole new step in adjusting components, even if it would be just a simple change. Also, we would have to not only consider our components, but also how the public CSS vars are going to be used, which would be challenging as well.

> I use the Horizon theme for this heights. I dont define cozy or companct so I should have the compact size I guess.

`Cozy` is the default content density. You can try it out in our [Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/getting-started--docs), or in the ui5-webcomponents' [Playground](https://sap.github.io/ui5-webcomponents/playground/getting-started). (See screenshots below)

<img width="301" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/bb84652a-aaff-4f47-95aa-37c4d9ed5679">
<img width="573" alt="2023-06-13_12-29-12" src="https://github.com/SAP/ui5-webcomponents/assets/9749730/ada3d35b-f5d3-492a-9424-e9b790dcd68c">

**Comment by ilhan007** [comment]
Hello @C3ntraX 

0. Checked the codesandbox (this is my fork https://yfvclm-5173.csb.app/ but without any change in the code or versions) and it seems you have to restart the codesandbox to refresh node_modules and everything. After doing it, the variable is no longer available and no padding-top is applied:

<img width="1214" alt="Screenshot 2023-06-13 at 19 33 57" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/6ac1f92c-f981-48c9-83da-708c24288ec0">


1. With the latest @ui5/webcomponents version (latest ui5/webcomponents-react is based on it) as Lukas said the CSS variables are scoped to the custom elements.

Before they were defined:
```css
:root {
--_ui5_*
}
```

Now the selector is more specific
```css
:root [_ui5rt0] { /* _ui5rt0 is a system attribute set on the custom element */
--_ui5_*
}
 ```
 
 2. All variables besides --sap* are private, are not documented, are subject to change and shouldn't be used.
 
 3. @ui5/webcomponents (and  ui5/webcomponents-react) will offer only the public/central SAP Desgin CSS Variables, maintained in [theming-base-content](https://github.com/SAP/theming-base-content) project and any requests, questions on the CSS Variables should be addressed to the [theming-base-content](https://github.com/SAP/theming-base-content) colleagues
 
 4. There are some JS workarounds
 - read the variable value by using the custom element instance as the variables are now scoped to the custom elements:
 `getComputedStyle(<ui5-shellbar>).getPropertyValue('--_ui5_shellbar_root_height')`
 - or via getBoundingClientRect
 `document.getElementById('shellbar').getBoundingClientRect(). height`
 

 BR,
 ilhan
