### ISSUE TITLE
[Timeline]:Can't give colour to Icons 

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#7188]
### Bug Description

In the timelineItem, Can't give color to Icons.
Please refer: https://codesandbox.io/s/magical-carson-c04jdd?file=/src/App.js:268-276
![image](https://github.com/SAP/ui5-webcomponents/assets/120740457/6ff89621-1eeb-48b9-9ecd-3083526fc2c4)
need to give above error sign "blue" color and below error sign "red" color.

### Affected Component

Timeline

### Priority

Medium

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
Please check out this feature request for the Timeline component. It is about adding different colors to the icons of timeline items.
I checked the visual design specification and it currently states that the color of these icons should not be styled:
> Timeline (Horizon):
> > Only one style can be applied to the whole timeline. **No mixture of styles is allowed.**

**Comment by roshnijalan97new** [comment]
Hi @ilhan007, If there is a style component then we can use it.

**Comment by ilhan007** [comment]
Hi @roshnijalan97 not sure what you mean by `style component`.

As explained in the article above, one of the options to style a component is via `Shadow Parts`. Imagine we introduce a shadow part in the TimelineItem, called "icon". 
Then, with standard CSS, you will be able style the icon within the TimeLineItem:

```css
ui5-timeline-item::part(icon) { /*add this in you app css file */
color:red;
}
```

And let me give you one example with existing part so that you can test it.
The Card exposes several parts, one of them is called `status`
```css
ui5-card::part(status) {  /* add this in you app css file */
color:red;
}
```

Even if you are using the React wrappers(@ui5/webcomponents-react), not the pure web components (@ui5/webcomponents), you can still leverage the shadow parts.

Once more I suggest reading the [article](https://sap.github.io/ui5-webcomponents/main/playground/customizing/styles/) if this is the first time you hear about CSS Shadow Parts.

If that would work for you, we can add a shadow part for the icon of the TimelineItem and allow you to restyle it.
