### ISSUE TITLE
Suggestion Item Images do not fit list items

### ISSUE THREAD

**Issue by Sergey-Shapovalov** [SAP/ui5-webcomponents#7206]
### Bug Description

When using images in suggestion items for an input, by default the images are stretched to 48*48 pixels regardless of their size. The items themselves, however, do not follow the height of the image. As a result, we have two problems:

1. Images in the list are overlapped.
2. Scroll container of the list receives the Y-overfllow and shows a scrollbar. If we have large number of items, it results in double vertical scrollbar. 

There is a related issue. We can control the size of the item images by changing the --_ui5_list_item_img_size CSS variable. However, the content div of the item (ui5-li-content) has a hard-coded height of 3rem if the item contains an image. It results in the double scrollbar issue even if we use smaller images.

### Affected Component

Input, SuggestionItem

### Expected Behaviour

The height of list items should follow the height of the image to prevent image overlapping and double scrollbar issue. The content div height for items with images should be defined by the same variable as image size itself. 

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-f3vffl?file=/index.html

### Steps to Reproduce

Click on the input control to see the suggestion list.

### Priority

Medium

### UI5 Web Components Version

1.10.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-rl 
This issue is about using larger images for the Suggestion Items in the Input.
And if you have even more suggestions, this results in a popover with two scrollbars:
<img height="300" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/22086365/99779fda-171f-4a44-be18-d136df98634b">

Would you take a look?

**Comment by elenastoyanovaa** [comment]
Hello @Sergey-Shapovalov ,

Thank you for reporting! Unfortunately the style causing the cut of the item is not due to a style applied to ui5-li-content. If I remove it nothing is changed, but it is coming from the following style: height: var(--_ui5_list_item_dropdown_base_height); which is set to each ui5-suggestion ui5-suggestion-item element, which is actually expected. Depending on the theme and on the density mode we have a specific height which should be set for the suggestion item. This height is by visual specification and should be applied. Unfortunately the visual spec links are private and I cannot send you a link here, but you can check our css files and see a --_ui5_list_item_dropdown_base_height css var which has a specific value for each theme.
The Suggestion item custom element is not meant to grow depending on the size of the content inside it. This case would be met when a custom list item is used instead. We already have a feature request to support custom list items and you can check the progress there: #5128 
For now it is blocked for development after our initial evaluation, since we are waiting for a design specification.

Kind Regards,
Elena
