### ISSUE TITLE
[Input]: focus border color and weight does not match the documentation

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents#7222]
### Bug Description

When input or button components are focused, the border weight and color does not match the border color in the documentations 

### Affected Component

Input

### Expected Behaviour

border color should be blue and weight should be more than 1px

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-g39gpz?file=/src/index.js

### Steps to Reproduce

1. add ui5-input component to codesandbox example.
2.
3.
...

### Log Output, Stack Trace or Screenshots

focus border in documentation:
https://github.com/SAP/ui5-webcomponents/assets/6120010/41fda87e-c3c1-4a26-8837-61d1f02b5a76

focus border on code-sandbox example: 

https://github.com/SAP/ui5-webcomponents/assets/6120010/fad3ff2c-bba4-469f-8606-2a8af294c4a5

### Priority

None

### UI5 Web Components Version

1.14.3

### Browser

Edge, Firefox

### Additional Context

focus border in documentation:
https://github.com/SAP/ui5-webcomponents/assets/6120010/41fda87e-c3c1-4a26-8837-61d1f02b5a76

focus border on code-sandbox example: 

https://github.com/SAP/ui5-webcomponents/assets/6120010/fad3ff2c-bba4-469f-8606-2a8af294c4a5

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @sachinbhutani,

I've edited the provided sample so that sap_horizon theme gets used:
https://codesandbox.io/s/ui5-webcomponents-forked-ylnhjy?file=/src/index.js
Then we would have a 2px border for the ui5-input and the ui5-buttons.

The initial sample uses the default sap_fiori_3 light theme, with 1px dotted border.

From my point of view the border is displayed as per visual specification.

Please re-check with the other themes as well:
https://sap.github.io/ui5-webcomponents/playground/advanced/configuration/#imports

If there is still an issue you could re-open this incident.

Best regards,
Boyan
