### ISSUE TITLE
Styling does not work in shadow dom since recent version | theming

### ISSUE THREAD

**Issue by knuspertante** [SAP/ui5-webcomponents#7227]
### Bug Description

Hey, 

unfortunately since I updated the version of ui5 components and lit, theming / styling does not work anymore. 

Unfortunately I can't figuring out which version / combination worked together last. 

I create a simple reproducer here: https://stackblitz.com/edit/vitejs-vite-fnnfdk?file=src%2Fmy-element-no-shadow.ts

If I disable the shadow dom, the components are perfectly styled but without no styling is applied to the components.  

Disable shadow dom in lit: 
```typescript
protected createRenderRoot(): Element | ShadowRoot {
    return this;
  }
```

Is this behavior on purpose? Do you have any idea, that I could get back the old behavior?

Thanks! 

### Affected Component

all

### Expected Behaviour

Styling also work with shadow dom

### Isolated Example

https://stackblitz.com/edit/vitejs-vite-fnnfdk?file=src%2Fmy-element-no-shadow.ts

### Priority

None

### UI5 Web Components Version

1.14.3

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @knuspertante,

Thanks for reporting the issue!

With https://github.com/SAP/ui5-webcomponents/pull/7044 we are storing variables used inside components (not theme specific) inside `:root [_ui5rt0]` instead of `:root` and seems this causing the problem. To work as expected we `[_ui5rt0]` and [_ui5host] attributes. These attributes are used to resolve visual glitches when when multiple runtimes with different versions are used.

As a workaround until we find how to fix that you can simply add these attributes to your component as following:
 - [_ui5host] is static attribute and you can simply add it
 - [_ui5rt0] is dynamically generated attribute which is generated on base in which runtime the component is defined. To get the current runtime you can use [packages/base/src/Runtimes.ts#L41](https://github.com/SAP/ui5-webcomponents/blob/main/packages/base/src/Runtimes.ts#L41) and to use following template '_ui5rt${ getCurrentRuntimeIndex() }'

**Comment by veith** [comment]
Hint for people using lit or native web components: 

Add the `_ui5host` attribute to your top component and every component inside and below will work as expected.

```<app-shell _ui5rt0></app-shell>```
