### ISSUE TITLE
[ui5-li-custom]: Horizon theme - buttons in custom list items have some of their borders cut off on hover

### ISSUE THREAD

**Issue by winterkind** [SAP/ui5-webcomponents#7234]
### Bug Description

When having `ui5-button` components inside a `ui5-li-custom` using the Horizon theme, then part of the borders of the buttons are cut off when you hover over the buttons.

### Affected Component

ui5-li-custom

### Expected Behaviour

Nothing should be cut off on hover. For example, the Fiori 3 theme works fine.

### Isolated Example

See steps to reproduce, step 1

### Steps to Reproduce

1. Go to example: https://svelte.dev/repl/5ca8bcc5402c4925bfbdf4ef439f24a7?version=3.59.1
2. Wait until all imports are resolved. That can take a while. When it is done, you will see the buttons "Show Lists" and "Switch Theme".
3. Click the button "Show Lists" when it is available. You will see two lists using compact and cozy layout custom list items.
4. The lists initially use the Fiori 3 theme. Hover over the buttons with your mouse. Everything looks as expected.
5. Use the button "Switch Theme" to switch to the Horizon theme.
6. Hover over the buttons with your mouse again. You will now see that parts of the borders of the buttons are cut off.

### Priority

Low

### UI5 Web Components Version

1.14

### Browser

Chrome, Edge

### Operating System

Win 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible with _sap_horizon_ theme via the following snippet:
https://codesandbox.io/s/ui5-webcomponents-forked-rhn5ls?file=/index.html

If a `ui5-button` is used inside a` ui5-li-custom` the border (box-shadow) gets drawn outside (offset) of the `ui5-button` tag and gets cut as there is not enough space around the button in the `ui5-li-custom` element.

A possible solution would be to draw the box-shadow inside with the following style:
`inset 0px 0px 1px 1px grey`

Best regards,
Boyan

**Comment by hinzzx** [comment]
Hello @winterkind,

I've tested and tried to reproduce the problem in the provided sample, as well as locally, but I werent able to achieve the reported problem. Could you please check if it is still relevant or reproducible using the latest version, as I suspect it is fixed.

BR,
Stoyan

**Comment by winterkind** [comment]
Hello @hinzzx, you are right, this seems to be resolved by now. Last time I checked from my end was a few releases ago, but now it is resolved. We can close this issue. Thanks!

**Comment by hinzzx** [comment]
Thank you @winterkind for the fast reply.

Best Regards,
Stoyan
