### ISSUE TITLE
[Feature Request]: <ui5-table-row> Drag and drop rows inside a table

### ISSUE THREAD

**Issue by axelrzm** [SAP/ui5-webcomponents#7240]
### Feature Request Description

In the web component `Table`, it is actually not possible to drag and drop a table row. 
Meanwhile it is possible to drag a `tree-item` from the `Tree` web component.

### Proposed Solution

Add the possibility to drag a `table-row`

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

take a look of this feature request.

Best regards,
Boyan

**Comment by Roba1993** [comment]
I would be also interested in this feature 👍

**Comment by hristop** [comment]
Hi @axelrzm ,

We are writing to inform you about an important development regarding our ui5-table component. After careful consideration and received feedback, we have decided to focus on re-implementing and improving the existing table component based on the gathered feature requests and requirements.
Here are some details about this decision and how it may affect our ongoing development efforts.
 
The decision was made based on several factors, including scalability, performance, accessibility and the ability to meet future feature requirements. Our team has recognised the limitations of the current table component and after careful consideration, we concluded that it would be more effective to develop a new table component from scratch rather than invest more time in enhancing the current one.
 
While this decision allows us to provide a better user experience and meet evolving needs, I want to acknowledge that it may have some implications for the feature requests that have been made for the current ui5-table component. We understand that stakeholders have invested time and effort in suggesting improvements and new features. Rest assured that we value your input, and we will make every effort to take these feature requests into consideration during the development of the new ui5-table component.
 
However, it is important to note that the new table component may introduce backward incompatible changes. These changes may impact the way the current table component functions, including its API and visual representation. We understand that this may require adjustments and adaptations on your end. Our team will strive to provide documentation and guidance to facilitate a smooth transition to the new table component.
 
We are excited about the opportunities this transition will bring and the positive impact it will have on our product.
 
Should you have any questions or concerns regarding this transition or its implications, please don't hesitate to reach out.
 
Thank you for your understanding and continued support as we embark on this important transition.
Unfortunately for now we are not able to provide concrete timelines but we are currently working on a first preview version of the new WebComponent which should already offer a first impression of the concepts behind. We have gathered the feature requests and we surely have them in mind while developing the new component. 

Best Regards,
Hristo

**Comment by boydwilson** [comment]
This is an issue we are facing as well

**Comment by boydwilson** [comment]
Forgot to ask, do you have an eta on the first preview version?

**Comment by hristop** [comment]
Hi,

The new table is developed in another team, but after some discussions with them I got that the table is in progress, but it is still not sufficient for initial preview. 

Best Regards,
Hristo

**Comment by simlin** [comment]
https://sap.github.io/ui5-webcomponents/components/Table/#drag-and-drop
