### ISSUE TITLE
[Button]: Buttons can trigger click events even though they are disabled on mobile

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7249]
### Bug Description

I'm able to click button even though they are disabled.....

The wreid thing is, if you click on corner of button 1, you'll click button 2 and vice versa.

This causes very wreid behaviour if you click buttons when they are not disabled. You can click 2 buttons on the same time! And the focus is jumping very wreid around.

Currently I can only simulate this behavior on mobile devices

### Affected Component

Button

### Expected Behaviour

No clickevent should happen

### Isolated Example

https://codesandbox.io/p/sandbox/reverent-boyd-k4w9wm?file=%2Fpackage.json%3A14%2C35-14%2C41

### Steps to Reproduce

1. Click on the corners of the buttons
2. Click on the buttom right corner of button 1 triggers button 2 (???) and vice versa
...

### Log Output, Stack Trace or Screenshots

![Animation](https://github.com/SAP/ui5-webcomponents/assets/44802503/83412c6e-e510-43de-9dfb-6bf36ddf6b14)
![Animation2](https://github.com/SAP/ui5-webcomponents/assets/44802503/dbd725b0-122d-4397-9a03-a7bd8c386bdf)

### Priority

High

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-b,

The issue is reproducible via the provided sample.
It is also reproducible on mobile via a single ui5-button element.
If there are more than one ui5-button's it's easier to reproduce by pressing between them.

All event listeners are attached to the inner button element and we are pressing outside of it.
Still a custom "click" event gets fired.

Disabling the pointer events and touch events with CSS didn't help.

It seem that the issue is coming from the `PassiveEventListenerObject`.

Best regards,
Boyan
