### ISSUE TITLE
[Toolbar]: Toolbar overflow does not work correctly if the toolbar is not 100% of the screen width

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents#7268]
### Bug Description

If you `SideNavigation` on the left site and a toolbar on the right site, then the `toolbar` overflow does not work anymore.

### Affected Component

Toolbar

### Expected Behaviour

I think a ResizeObserver is missing?

### Isolated Example

https://codesandbox.io/p/sandbox/cranky-fire-v8jtwm?file=%2Fsrc%2FApp.tsx%3A21%2C32

### Steps to Reproduce

1. Resize the browser
2.
3.
...

### Log Output, Stack Trace or Screenshots

![OverflowNotWorking](https://github.com/SAP/ui5-webcomponents/assets/44802503/a21f1f4e-7cff-4bd6-91ef-004fe305e22c)

### Priority

None

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Hello @C3ntraX thank you for reporting this.

However, the issue should be filed in the UI5 Web Components For React repository:
https://github.com/SAP/ui5-webcomponents-react

For example, we don't even have a Toolbar web component (some of the components, provided by UI5 Web Components For React are wrappers of the web components, but some are only available as React components). 
Still, if the UI5 Web Components For React colleagues decides that the problem is in the pure web components implementation, they will forward the issue to us. 
 
That's why I suggest you always file your issues in the above mentioned repository if you are not sure the issue is for the underlying pure web components.

Best Regards, 
ilhan
UI5 Web Components team
