### ISSUE TITLE
[ui5-side-navigation]: Forced top border radius in Side Navigation

### ISSUE THREAD

**Issue by kozubikmichal** [SAP/ui5-webcomponents#7308]
### Bug Description

With the new version of Web Components, Side Navigation component has the top border radius applied. This radius cannot be changed and it also does not correspond with the ShellBar design.

### Affected Component

Side Navigation

### Expected Behaviour

Border should be aligned with the ShellBar OR it should be possible to change it via CSS

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-sidenavigation--docs

### Log Output, Stack Trace or Screenshots

![image](https://github.com/SAP/ui5-webcomponents/assets/26189327/525e724d-f3c9-49b7-9413-74867bf58cc3)

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Operating System

MacOS

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by s-todorova** [comment]
Hello colleagues,

Due to the border-radius on the ui5-side-navigation, when used in combination with ShellBar, the top border-radius does not align well. You can see it in the examples here: https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-sidenavigation--docs.

Could you please take a look at this?

Best regards,
Siyana

**Comment by gmkv** [comment]
Hi @kozubikmichal 
I just merged the above change which allows you to set a custom CSS rule for the border-radius. For example:
```css
ui5-side-navigation {
   border-radius: 0;
}
```

As far as the description for this issue is concerned, this is now solved.

Additionally, we tried to reach out to you on our internal comms to find out the bigger picture with regards to your implementation intent. Let's continue the conversation there.
