### ISSUE TITLE
Popover placementType issue on iOS Devices

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-webcomponents#7331]
### Bug Description

Currently using an Popover 
```
<ui5-popover id="info-popover" placementType="Bottom">
```
that should be shown below anchor.

This works as expected inside browsers anc even in chrome device simulator for phone

![CleanShot 2023-07-17 at 09 08 15](https://github.com/SAP/ui5-webcomponents/assets/2110971/dce8b78a-a01e-462b-9600-a5c80d21915d)

but on a real iOS iPhone and iPad it will be rendered to the right side like this:

![image](https://github.com/SAP/ui5-webcomponents/assets/2110971/552e34ff-cb98-449f-b88a-2da299ffcacb)

### Affected Component

Popover

### Expected Behaviour

Rendering the placementType cross devices as defined

### Isolated Example

https://btp.udina.de/tools/api-explorer.html

### Steps to Reproduce

Just press the "I" Info Button right next the Packages to show the Popup on an Apple iPhone Safari.
Apple iPad show similar behavior.
  

### Priority

None

### UI5 Web Components Version

1.15.1

### Browser

Safari

### Operating System

Apple iOS Phone 14 Pro

### Organization

UNIORG Group

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @SAP/ui5-webcomponents-topic-rd,

The issue is reproducible and very well described, can you check?

Best regards,
Petya

**Comment by gmkv** [comment]
Hi @hschaefer123 
The anchor in question which opens the Popover does not show when I load your link.
Could you check it?

Also, the syntax for the placementType attribute when used in HTML should be written in kebab case: `placement-type="Bottom"` not `placementType="Bottom"`.

**Comment by hschaefer123** [comment]
Hi,

in the meantime, i also created some updates and with my update yesterday,
i removed the info button by directly showing this topics.

The issue was still present on iPad, but wirth a former update it has gone on iPhone?!?

I also figured out, that even if i set an anchor, depending on scrolling, available space etc,
you just seem to change the anchor position.

But anyhow, sadly you can not test the button at the moment, because the dev continued.

Maybe you should close the ticket, but there is still some struggling with iOS inside containers using max-with.

Regards
Holger

**Comment by gmkv** [comment]
Hi @hschaefer123 
Would you be able to provide a reproducible sample outside of the above app?
You could use this as a starting point: https://codesandbox.io/s/ui5-webcomponents-forked-vhx8cp?file=/index.html

**Comment by hschaefer123** [comment]
Hi @gmkv 

i just deployed a new version with the button visible (iPhone/iPad).

Let me know, if you figured the issue out, so that i can disable the button.

https://btp.udina.de/tools/api-explorer.html

![IMG_2267](https://github.com/SAP/ui5-webcomponents/assets/2110971/a76738fa-2ff4-4789-a460-21268e6c42b3)

Regards
Holger

**Comment by gmkv** [comment]
Hi @hschaefer123 
I opened the page in Safari and inspected the Popover element in Devtools.
Notice the incorrect spelling of the HTML attribute `placement-type` shown in the first statement I ran:
![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/2af87d7d-4f3a-4622-b7dc-17d2f7c9d0f2)

Same page but in Chrome with Devtools:
Spelling of the `placement-type` attribute is correct here:
![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/837fee02-4abd-4a12-b2e7-4a7558cf5c33)
To me this seems more related to how you render your HTML for the page (based on a browser?).

Could you check the implementation of your app?
I don't think this bug is caused by this UI library.

**Comment by hschaefer123** [comment]
Hi @gmkv
strange?!?

I also see the wrong placement-type, but where does it come from?!?

Inside the static exported code, there is still the ui5-popover with placementType="Bottom".

**Who will render this to placement-type?!? UI5 WC?**

The code is SSR generated as static asset with placementType.
The is nothing in between?!?

Regards
Holger

**Comment by gmkv** [comment]
Hi @hschaefer123 
I don't know this SSR framework you are using so unfortunately I can't point you where to look at.
What I know is that the attribute `placement-type` should be written in kebab-case like any other HTML attribute, and not `placementType`.
I repeat this because the code example you gave in your initial comment to this issue has the wrong syntax - not using kebab-case for the placement type:
![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/d8746d7f-edbd-4455-8ec2-2858e36ca68e)
Try to double-check your syntax in your view code to make sure you are using the Popover correctly.

**Comment by hschaefer123** [comment]
Hi @gmkv,

you are totally right! I should RTFM ;-)

I was using camelCase property like shown in the docs and it was working inside chrome.

I was wrongly using property names instead attribute names.

Sorry for all the irritation and thanks to point me into the right direction.

Best regards
Holger
