### ISSUE TITLE
[Dialog]: Wrong colors in Belize theme

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7353]
### Describe the bug

Current implementation:
<img width="336" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/2633c0e1-f581-4985-9242-beed3af7485e">
https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--docs&globals=theme:sap_belize;contentDensity:Compact

Reference implementation:
<img width="565" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/1669f24f-6fcb-4e3e-b58d-89c9ba58050e">
https://sapui5.hana.ondemand.com/?sap-theme=sap_belize#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog

Notice the color differences for header and footer.

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by didip1000** [comment]
Hello @SAP/ui5-webcomponents-topic-rd, 

The header background color should be @sapUiGroupContentBackground in belize, can you please check if it's set to the correct value? 

Thanks, 
Diana

**Comment by mhchem** [comment]
... and the footer
Background: @sapUiPageFooterBackground
border-top: 1px solid @sapUiPageFooterBorderColor
respectively
background: --sapPageFooter_Background;
border-top:  0.0625rem solid --sapPageFooter_BorderColor;

**Comment by LidiyaGeorgieva** [comment]
> ... and the footer Background: @sapUiPageFooterBackground border-top: 1px solid @sapUiPageFooterBorderColor respectively background: --sapPageFooter_Background; border-top: 0.0625rem solid --sapPageFooter_BorderColor;

Hello @mhchem ,

I prepared a pull request to fix the header styles. 
The ones in the footer that you wrote are correct and already applied.
The values can be seen in this file: https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_belize/css_variables.css

The design of the dialog in Web Components project is more similar to the design of the Message dialog from openui5, than the dialog:
https://sapui5.hana.ondemand.com/?sap-theme=sap_belize#/entity/sap.m.Dialog/sample/sap.m.sample.DialogMessage

Best Regards,
Lidiya

**Comment by LidiyaGeorgieva** [comment]
Hello @mhchem,
 
We had an architecture and product discussion on the enablement of contrast containers in Belize for UI5 web components project.
Implementing the contrast containers is complex solution, which affects multiple components - Bar, Page, Button, Dialog, Popover and other. In addition to that it is a concept that was further rejected design and technology wise and is no longer existing in newer theems. It will also bring very high complexity within the web components project. Our main goal is to keep the ui5 web components lightweight and we would avoid implementation such complex solution that affects single theme which will be soon outdated. 
Therefore, due to other high prio topics within the project incl. recent implementations for SAP Design system and new Horizon theme updates we cannot proceed with this request. We strongly recommend the usage of theme Horizon, which is modern and soon will be the default theme for UI5.

Best Regards,
Lidiya
