### ISSUE TITLE
[Dialog]: using Belize Theme, the visual design of the Dialog is not correct

### ISSUE THREAD

**Issue by ehn-sap** [SAP/ui5-webcomponents#7387]
### Describe the bug

Background colors for footer and header are the right ones, according to Belize theme.

### Isolated Example

https://64onzz.csb.app/

### Reproduction steps

1. Set the theme to Belize ("sap_belize")
2. Create a Dialog, with a header and a footer
3. Pay attention to the background colors of the header and footer
4. Compare these colors with the SAPUI5 sample and demo 
[Web components:](https://sapui5.hana.ondemand.com/#/entity/sap.ui.webc.main.Dialog/sample/)
[UI5](https://ui5.sap.com/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog)

### Expected Behaviour

Background colors should comply to the Belize theme 

### UI5 Web Components for React Version

^1.16.0

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd , I am forwarding this issue to you, because it seems Dialog is not using the correct theme parameters for header and footer backgrounds. Please, double-check from your side but it looks to me that sapUiGroupContentBackground and sapUiPageFooterBackground should be used.

Regards,
Iliana

**Comment by LidiyaGeorgieva** [comment]
Hello @ehn-sap ,
Reported issue is duplicate with https://github.com/SAP/ui5-webcomponents/issues/7353
I'm closing this one. Please follow the progress there.
Best Regards,
Lidiya
