### ISSUE TITLE
[SF][A11Y][RadioButton]: Interactive Controls Must not Be Nested

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#7419]
### Bug Description

Hi Team,
When using `ui5-radio-button` component and running "axe Dev Tools" browser extension to scan the page to test a11y issues, the following issue is detected. Please take a look. Thanks!

<img width="1676" alt="Screenshot 2023-08-07 at 8 52 18 AM" src="https://github.com/SAP/ui5-webcomponents/assets/32254036/6e3792ce-f113-46dd-9a97-03ca6bf81031">

### Affected Component

RadioButton

### Expected Behaviour

We shouldn't be getting the above a11y error.

### Steps to Reproduce

1. Go to https://qacand.hcm.ondemand.com/sf/scriptintegrationsettings page. Will share the credentials in the slack channel
2. Add chrome extension "axe devTools"
3. Scan the entire page

You can find more information on this issue here: 
https://dequeuniversity.com/rules/axe/4.5/nested-interactive?application=axeAPI

### Priority

None

### UI5 Web Components Version

1.14.2

### Browser

Chrome

### Operating System

Mac OS Ventura 13.4.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @ui5-webcomponents-topic-rd ,

The issue is reported for "axe Dev Tools" chrome extension, but I tested with Access assistant tool and there is similar issue:
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/7875d859-27ec-4a45-8efc-d74ec50b937d)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/607952f5-1ab1-4b5f-98af-88e57074bce6)
I used this page for testing: http://localhost:8080/packages/main/test/pages/RadioButton.html 

Please have a look.

Best Regards,
Lidiya

**Comment by rama1990br** [comment]
Hi Team, can we please get an update on this issue?

**Comment by rama1990br** [comment]
@gmkv 
Which version of ui5-webcomponents do I need to upgrade to in order to get this issue fix?

**Comment by gmkv** [comment]
Hi @rama1990br 
The latest available version includes the fix: https://github.com/SAP/ui5-webcomponents/releases/tag/v1.17.0
