### ISSUE TITLE
[SF_ACC] [Input] SuggestionItem text is getting truncated in 320px wide screens:

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#7599]
### Bug Description

SuggestionItem text gets truncated on small viewports. A tooltip should be added when the text gets truncated so that the user is able to retrieve the full text.

### Affected Component

Input

### Expected Behaviour

On hover, the user should be able to see the full text that was truncated in the suggested items list.

### Isolated Example

https://lgww49.csb.app/

### Steps to Reproduce

1. Open the example in a 320px wide screen.
2. Type "Some extremely long country name" into the input field
3. Observe that text is truncated and that there is no way to retrieve the full text on hover.

### Priority

None

### UI5 Web Components Version

1.14.5

### Browser

Chrome

### Operating System

MacOS 13.5.2

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The user would like to have tooltip on Input hover when the text is truncated.

I noticed that no such functionality exists in OpenUI5 so it's up to you if the feature request will be fulfilled.

Regards,
Plamen

**Comment by hristop** [comment]
Hi @bonniegso ,

We have introduced wrapping in the suggestion items and the issue is no longer reproducible in the latest version of the web components. 
<img width="320" alt="Screenshot 2023-09-21 at 10 37 03" src="https://github.com/SAP/ui5-webcomponents/assets/14230119/7ce435ab-cbf1-4460-80d0-9b9ee9fa3b8b">

You can check this issue: #5323 

Best Regards,
Hristo
