### ISSUE TITLE
[SF_ACC] [Input] Additional text in SuggestedItems are not being read

### ISSUE THREAD

**Issue by bonniegso** [SAP/ui5-webcomponents#7607]
### Bug Description

When navigating with a screen reader and keyboard through the suggested items in the Input component, only the "text" attribute is read and not the "additionaltext". It is expected that all visible text is read to screen reader users. SuggestionItem  does not currently allow for custom aria-labels to be defined by consumers. An enhancement will be needed to either add the additionalText as part of the announcement for the item or functionality to allow consumers to define this aria-label.

### Affected Component

Input

### Expected Behaviour

It is expected that all visible text is read to screen reader users. 

### Isolated Example

https://lgww49.csb.app/

### Steps to Reproduce

1. Turn on JAWS Screenreader
2. Open example in a browser
3. Type something into the input field
4. Using your keyboard navigate through the suggested items
5. Observe that the additional text is not being read

### Priority

Medium

### UI5 Web Components Version

1.14.5

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

When a we navigate toward suggestion item with jaws (with turned off virtual cursor) only the texts is read but not the additionalText.

If I turn on virtual cursor, the additional text is read as well.

Is this expected behavior? If not, please review it as dev request.

Regards,
Plamen Ivanov
