### ISSUE TITLE
ui5-table popin-change event not fired when columns pop out

### ISSUE THREAD

**Issue by vladitasev** [SAP/ui5-webcomponents#7620]
### Bug Description

`popin-change` is not fired when columns pop out (only when they pop in).

### Affected Component

ui5-table

### Expected Behaviour

`popin-change` is fired when columns pop in or out.

### Steps to Reproduce

Open the regular test page for Table: http://localhost:8080/packages/main/test/pages/Table.html
Shrink the browser, you'll see:
<img width="272" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/15844574/0c1d04a0-d244-4ffe-935a-ecdc6e3d4a5f">

Then resize the browser back to normal: the input says the same (doesn't go back go "0 popped in columns"

### Priority

Medium

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @SAP/ui5-webcomponents-topic-rl ,

There seems to be an issue with the `popin-change` event. When there are no hidden column (imagine there were 2 popined columns and the table is resized to its original size and there are no popined columnd now) the popin change event is not fired.

The issue is in `popinContent` method:
```
	if (hiddenColumns.length) {
		this.fireEvent<TablePopinChangeEventDetail>("popin-change", {
			poppedColumns: this._hiddenColumns,
		});
	}
```

here when the table is restored to its size when there is no need of popin columns hiddenColumns becomes zero and the event is not fired, but it should be.

Please follow Vladi's description for steps to reproduce.

Kind Regards,
Elena

**Comment by ilhan007** [comment]
Hello colleagues, just fyi we have also a stakeholder that reported this issue - SAP Build Process Automation.
