### ISSUE TITLE
[ui5-color-picker]: Not corresponding colors

### ISSUE THREAD

**Issue by xdenser** [SAP/ui5-webcomponents#7660]
### Bug Description

Current color does not correspond to main color and hue slider.

### Affected Component

ui5-color-picker

### Steps to Reproduce

Set R:0, G:255, B:0 manually. 
Then move hue slider to the left slowly, main color becomes orange, but current color stays greenish.

### Priority

None

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by gmkv** [comment]
Hi @SAP/ui5-webcomponents-topic-b 
This issue is about the Color Picker component.
When changing the Hue, the handle that is dragged across the Hue track shows one color, but the color outputted is different.

Reproduce:
1. https://codesandbox.io/s/ui5-webcomponents-forked-szwhv2?file=/index.html
2. Change Hue to the left until you reach orange.
3. The color does not match what the slider for Hue shows.

https://github.com/SAP/ui5-webcomponents/assets/22086365/26754acd-82cd-43c7-91b3-8b941bbc915d


Would you have a look?
