### ISSUE TITLE
[ui5-input]: click event handler of link inside valueStateMessage is not working

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#7689]
### Bug Description

Clicking the `ui5-link` in `valueStateMessage` slot, the corresponding event handler is not called.
<img width="232" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/1751846/e61a59eb-bc5c-4613-9b71-6ef0edc4d54a">

### Affected Component

Input

### Expected Behaviour

The corresponding event handler of the `ui5-link` in `valueStateMessage` slot should be called.

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-tp92jy?file=/index.html

### Steps to Reproduce

1. Open https://codesandbox.io/s/ui5-webcomponents-forked-tp92jy?file=/index.html
2. Focus the input
3. Click the `Clear` link in the popover
4. Observe that nothing happens (an alert is expected)

### Priority

High

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

macOS

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Todor-ads** [comment]
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-rl ,
the issue is reproducible in https://codesandbox.io/s/ui5-webcomponents-forked-tp92jy?file=/index.html

Best regards,
Todor

**Comment by 2bno1** [comment]
@niyap Thanks for working on this issue. Can you provide an estimation about when this can be done?
Thanks.

**Comment by hristop** [comment]
Hi @2bno1 ,

We have discussed this with our architects and the is known limitation of the Web Components framework. 

From what we could learn, in order for this to be resolved properly, we will need the HTML popover API to be fully supported and adopted in the framework. Then some of the limitations / workarounds that are introduced in order to achieve the design specifications will be removed and we will be able to provide native event support for such elements in the popups. Very rough estimation for this would be mid of next year, but this really depends on outside vendors, so it may shift indefinitely.

One point I would like to mention is that this feature was introduced in order to allow more information to be displayed in separate page for the cases of machine learning suggestions and error that would require such, not to have functionality in the form of event handlers. 

Best Regards,
Hristo
