### ISSUE TITLE
Failed to fetch dynamically imported module: http://127.0.0.1:8081/node_modules/@ui5/webcomponents/dist/Button.js

### ISSUE THREAD

**Issue by pwasem** [SAP/ui5-webcomponents#77]
**Describe the bug**
I want to create a custom element extending [lit-element](https://github.com/Polymer/lit-element).
Within this element I want to use `<ui5-button/>`.
Unfortunately my initial import for the button fails:

`import('@ui5/webcomponents/dist/Button');`

**Log output / Any errors** in the console
```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8081/node_modules/@ui5/webcomponents/dist/Button.js

Failed to load module script: The server responded with a non-JavaScript MIME type of "application/json". Strict MIME type checking is enforced for module scripts per HTML spec.
```
Root cause seem to be the import calls for json files in `Button.js`, 
e.g. `import belize from './themes/sap_belize/Button.json';`

**To reproduce**
```javascript
import { LitElement, html } from 'lit-element';
import('@ui5/webcomponents/dist/Button');
export class MyElement extends LitElement {
  render() {
    return html`
      <ui5-button>Hello world!</ui5-button>
    `;
  }
}
customElements.define('my-element', MyElement);
```

**Expected behavior**
import call should just work as expected

**Context**
- UI5 Web Components version: 0.7.0
- Browser: Chrome 72.0.3626.109
- Other information: polymer-cli 1.9.6, lit-element 2.0.1

**Affected components**
all

**Comment by pskelin** [comment]
Hi @pwasem,\
thanks for reporting the issue, there is a lot to address here.

On a high level, there are two main issues:
1. ui5-webcomponents use certain assets (like the styles, but also texts, icon fonts, CLDR data) that are exposed as ES6 imports so whoever is using the components can bundle these assets. The polymer-cli seems to understand only JS imports, so it fails. So far we have only provided working configuration examples for rollup and webpack.

2. lit-element and ui5-webcomponents use different versions of lit-html and this breaks.

I'll provide the steps to get your example running, and we will address these issues in one of the next releases to make the consumption of ui5-webcomponents easier.

## 1. Using rollup for building the project
I couldn't find at a first glance a way to configure polymer-cli to handle non-JS imports, so I suggest you switch to rollup or webpack for your project. There is a starter project here: https://github.com/PolymerLabs/lit-element-build-rollup

Once you clone it, you should also install ui5-webcomponents

```shell
npm install @ui5/webcomponents --save
```

now to handle the asset imports, you need two plugins

```shell
npm install rollup-plugin-json --save
npm install rollup-plugin-url --save
```

Then add to rollup.config.js
```js
import json from 'rollup-plugin-json';
import url from 'rollup-plugin-url';

// snip

    plugins: [
        json(),	   // <-- add this
        url({      // <-- and this
            limit: 0,
            include: [
                /.*cldr\/.*\.json/,
                /.*sap.ui.core.*\/SAP-icons.*/,
                /\.properties$/,
            ],
            emitFiles: true,
            fileName: "[name].[hash][extname]",
        }),        // <-- till here
        resolve(),
        babel()
    ]
```

with these changes, rollup knows how to import the assets. You should be able to run the project with

```shell
npm run build
npm run start
```

If you followed the steps above, the project will build successfully, but ui5-button will render with the plain text "[object Object]".

## 2. Using the same lit-html version

This is caused by having lit-html@0.14 by the ui5-webcomponets and lit-html@1.0.0 by lit-element. We have already updated the lit-html version used by ui5-webcomponents to 1.0.0 so this will be fixed in the next npm release. Until then, you can solve it like this:

1. add the following to your package.json
	```json
	"resolutions": {
	    "lit-html": "1.0.0"
	}
	```
2. remove node_modules and package-lock.json to start clean
3. run 
	```shell
	yarn
	```
	to get a single lit-html version
4. run
	```shell
	npm run build
	npm run start
	```
	and open the project in the browser

It's a bit inconvenient at the moment so we'll work to improve this.

A final touch is to add a `dev` script so rollup can watch your changes and you don't need to build each time. In your package.json add a new entry called `"dev"` under `scripts`:
```json
"build": "rm -rf build && mkdir build && npm run copyindex && npm run copywc && rollup -c",
"dev": "rollup -c -w",
"start": "serve build"
```

Then you can start both
```shell
npm run dev
npm run serve
```
to have a fast dev refresh experience similar to polymer-cli

And a final remark, you should remove the brackets from the import so it works with other tools as well.
```js
// old
import('@ui5/webcomponents/dist/Button');
// new
import '@ui5/webcomponents/dist/Button';
```

Let us know in case something does not work out.

Regards,
Petar

**Comment by pwasem** [comment]
@pskelin Thanks for the quick reply and detailed explanations!
Though I might wait for a next release and an easier consumption as the the current boilerplate is quite heavy.

Bests,

Pascal

**Comment by pwasem** [comment]
@pskelin what about converting the imported *.json files to *.js files? :bulb:
['import'](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import) API seems be only supported for *.js files anyway!

**Comment by MapTo0** [comment]
Hey @pwasem 

We already did some work in that direction - https://github.com/SAP/ui5-webcomponents/commit/1a3fb2e28f6b093873703d18c8920a0c45b649b7

Waiting for the next release :/

**Comment by pskelin** [comment]
What @MapTo0 mentioned will still not solve the whole problem.

@pwasem you are right that import API supports only JS. But this is the browser API only. In addition to it, there are build tools which are more capable than the browser and can handle other import types via plugins that are also configurable.

Let me provide more background into the kinds of assets that are necessary alongside the javascript:
- CLDR data (locale specific data for the date formatting components)- inlining them will increase bundle size by 1.6 MB (72 locales)
- Translations (texts that components show according to the current language) - inlining them will increase bundle size by 16KB (42 languages)
- Icon fonts (to display icons)
- styles (they are theme specific, but we already inlined them)
- we might be adding some svg or images in the future

We have considered the two possible alternatives for assets:
1. use them in imports like now - capable build tool is needed to process them, but whoever is using the webcomponents doesn't need to know all assets we have and it generally works correctly out of the box for the major application development setups (react, angular, vue).
2. don't use them in imports - needs additional configuration so it will be broken out of the box without developers first copying the needed assets into the build folder and then configuring the web components where to find the assets. Not only are there now two steps (copy and configure), but app developers also need to know what assets need to be copied. This is solved when we list them as imports, so one step less.

My proposal is still to switch to a more capable build tool. The PWA starter kit by the polymer team has also mentioned this in the FAQ:
https://pwa-starter-kit.polymer-project.org/faq
> Using webpack/other build tools
pwa-starter-kit is written with ES modules which is compatible with a variety of JavaScript build tools. For example, take a look at the webpack branch.
https://github.com/Polymer/pwa-starter-kit/tree/webpack
https://github.com/Polymer/pwa-starter-kit/tree/rollup

There is also the link from my previous reply:
https://github.com/PolymerLabs/lit-element-build-rollup

It is clear that the polymer team has also thought about supporting more capable production workflows. I really suggest to check them out.

For simplifying the development experience (for a browser workflow or a dev scenario like you mentioned), we might provide a pre-made bundle with the assets that only takes a configuration for the base URL, but this will really be only intended for development as it will contain even unused webcomponents.

For production, rollup and webpack are still the way to go with less configuration than a JS-only import approach.

I hope you understand the background. Feel free to chime if you have something to add or need more help with setting your project up.

**Comment by pwasem** [comment]
@pskelin Thx again!

But ideally any web component should just work like this
- `npm install @ui5/button`
- `import '@ui5/button`
- ```<ui5-button/>```

As a consumer I just want a ready to use component with no additional build boilerplate.
Just like:
- [material-components-web](https://github.com/material-components/material-components-web) or
- [vaadin-components](https://vaadin.com/components)

Otherwise this would really break the whole idea about web components.

**Comment by pskelin** [comment]
@pwasem: you have a valid point, thanks for bringing it through.

I did a bit more reasearch and I think we can achieve for most components to be JS-only imports without an additional configuration, so I'll post an update here soon.

**Comment by pwasem** [comment]
@pskelin 
I am sure you will make it work and I am just excited to start using the new ui5-webcomponents.
Your support is really appreciated!

**Comment by pskelin** [comment]
@pwasem the latest release on npm (0.8.0) should now work for your setup (datepicker, panel and text area will be addressed in a future release, but the rest should be fine now).

Could you give it a try and let me know if there are any problems?

**Comment by pwasem** [comment]
@pskelin after updating to 0.8.0 it is working as expected!
Thx for the quick fix!

**Comment by davidmartinezros** [comment]
Hi @pskelin,
How are you doing? I hope well.
I have one issue referent to this incidence with one of my components.

Here you can see the component: https://www.npmjs.com/package/app-draggable-portlets-template

And here the demo: https://plnkr.co/edit/REhfoeZ3CaoYOneY?preview

I try to install https://www.npmjs.com/package/next-update, but continue to don't work.

Any suggestion?

Thanks in advanced,

David

**Comment by RilDev** [comment]
Hi there, I got this issue when trying to use `client:load` on a Svelte component. The JavaScript was simply not working.

![image](https://user-images.githubusercontent.com/13135150/130330330-e21b7f4b-931c-419f-bd50-50df67f0022d.png)

Turns out, there was a problem with my SnowPack aliases.

```js
// snowpack.config.mjs
export default {
  // alias: {
  //   $: "./src",
  //   "#": "./public",
  // },
};
```

I commented out the aliases, used relative path for the imports and restarted the server. That it !
