### ISSUE TITLE
ui5-tabcontainer accessibility

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#771]
**Describe the bug**
Dear colleagues,
I would like to report an accessibility bug with the "ui5-tabcontainer". I have incorporated the tab container into my angular application where it is necessary to comply with accessibility.
Thats why I found this bug.

The issue is, that when working with multiple tabs, only the first tab gets an tabindex=1. The other tabs receive tabindex=-1 which leads to the point, that they are not reachable via keyboard. Additionally, it is not possible to set this tabindex by myself on a tab. This property gets ignored and overwritten by the logic of the webcomponent.

Another thing I saw is, that the text property of a tab gets not projected to aria-label. This leads to the fact, that even the first tab will not be readed out loud. Equals to the tabindex, I am not able to set this property on my own, as it gets overwritten.

**To reproduce**
1. Implement a tabcontainer with multiple tabs
2. Try to navigate to the second tab via keyboard (no arrow keys only tab & shift+tab)
3. Use a screen reader (for example chrome vox) to read out the first tab

**Expected behavior**
I would expect that a sight disabled person can navigate through the tabs of the tab container (by providing a proper tabindex or at least projecting a defined value) and that this person gets the text property of the tab read out (by projecting the text property to the aria-label or at least projecting defined values)

Projecting defined values:
This means, that if I define aria-label / tabindex on a webcomponent it should be considered.

**Context**
- UI5 Web Components version: 1.0.0-rc.2
- OS/Platform: MacOS
- Browser *(if relevant)*: Chrome

**Affected components**  
ui5-tabcontainer
ui5-tab

Best regards,
Julian

**Comment by ilhan007** [comment]
Hello @ignipae, thanks for the issue and for trying our web components.

One note regarding the navigation between the ui5-tabs. 
By design:
(1) you can navigate between the ui5-tabs with the `arrow keys` (Up/Down and Left/Right).
(2) And, pressing the `TAB` key should skip all the ui5-tabs.

So, this part is implemented by design and it`s the way it works in the latest release (rc2)
and can be observed [here](https://sap.github.io/ui5-webcomponents/playground/components/TabContainer/).

More details about the design and the tab chain can be found here:
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-19

About the reading and the aria-label stuff, we will check it out.
