### ISSUE TITLE
[Feature Request]: for consumers using Webpack, would be nice to have well-defined names specified for dynamically loaded bundles

### ISSUE THREAD

**Issue by scameron** [SAP/ui5-webcomponents#7716]
### Feature Request Description

There are very few places where ui5-webcomponents does it's own dynamic imports internally.  One of the most prevelant is the localization bundle loading, which is typically generated from a script here:
https://github.com/SAP/ui5-webcomponents/blob/17a5b122926720c3c2b07fc322cb480e867eb63a/packages/tools/lib/generate-json-imports/i18n.js#L59C13-L59C13

This one is especially important because localization bundles can be very large, especially when they are localized into 40+ different languages.

Today, if you use Webpack to build an application consuming ui5-webcomponents (or other related projects), you end up with anonymous, unnamed bundles being created.  This makes debugging and validation more difficult because there is no way to easily see which language bundles are loaded, nor to automatically detect them with tooling.

In Webpack, it is possible to name the bundles by using a magic comment called `webpackChunkName`.  This comment, when added into a dynamic import, will specify a name to use in the resulting bundle file (called a "chunk" in webpack):
https://webpack.js.org/api/module-methods/#magic-comments

For example, you can do this to cause meaningful bundle names to be used:

```
case "bg": return (await import(/* webpackChunkName: "ui5-webcomponents-messagebundle-bg" */ "../assets/i18n/messagebundle_bg.json")).default;
case "ca": return (await import(/* webpackChunkName: "ui5-webcomponents-messagebundle-ca" */ "../assets/i18n/messagebundle_ca.json")).default;
case "cs": return (await import(/* webpackChunkName: "ui5-webcomponents-messagebundle-cs" */ "../assets/i18n/messagebundle_cs.json")).default;
```

You can, of course, use whatever name is meaningful for the context, but it should be something that has a high likelihood of being unique with an application build.

I understand that this is very Webpack specific and not everybody uses Webpack.  But since from a code point of view these are just comments, they will be ignored by non-Webpack environments and, as comments, they will also be stripped out completely during minification anyway.  So I was hoping it might be OK to have support for this added.

Would it be possible to enhance the i18n code generation scripts to bake in this magic comment for bundle naming?

### Proposed Solution

Add Webpack magic comments into the generated dynamic localization imports.  See above for details.

### Organization

SAP

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
Hi @scameron ,
you make a good point and we should add this. I was looking for a more standard way or at least a way how other bundlers can benefit from it. The only thing I found is a vite plugin that can use the same comments, so this kind of becomes a standard way of annotating chunk names.
https://github.com/CaptainLiao/vite-plugin-webpackchunkname

Are you able to contribute a PR for this since you already have thought this through? This is the relevant position where the imports are generated, and the package name is already extracted in a variable in the same file.

https://github.com/SAP/ui5-webcomponents/blob/a2cbfa03f06d8c7b405bcc91583f5934a1fc6d92/packages/tools/lib/generate-json-imports/i18n.js#L59

There should be one also for the themes:
https://github.com/SAP/ui5-webcomponents/blob/a2cbfa03f06d8c7b405bcc91583f5934a1fc6d92/packages/tools/lib/generate-json-imports/themes.js#L25

And possibly for locale data even though this is hardcoded and not package specific
https://github.com/SAP/ui5-webcomponents/blob/a2cbfa03f06d8c7b405bcc91583f5934a1fc6d92/packages/localization/lib/generate-json-imports/cldr.js#L7

It would be faster if you can contribute this. Let me know if we should add this on our backlog.

**Comment by scameron** [comment]
Hi @pskelin ,

Sure, if it's an easy one I can try to give contributing a try.  I found this documentation about contributing, so I'll take a read through that, but let me know if there's anything else I should be aware of.
https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md

Thank you for being open to this change!  I'm really pleased that you think this is a good idea.

**Comment by pskelin** [comment]
`git clone` and `yarn build` should be enough, then check the generated files in the `dist` folder and we will get the rest through the review.
