### ISSUE TITLE
font-family '72Black' does not support Polish character `ń`

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents#7800]
### Bug Description

font-family '72Black' does not support Polish character `ń`.

**Steps to reproduce:**
1. Log into the instance, the details of which are provided in #sap-tech-ui5-wc-sfsf channel [here](https://sap-successfactors.slack.com/archives/CTHEMAZ8C/p1699056404058479).
2. Click on the user icon in the header, click on "Settings" option, and then click on "Change Language" option and then switch to "Polish" language. 
3. Reload the home page and then note the greeting on the banner image in Polish > where it says "Dzień" - note the last character ń is a different font - not as thick as the other characters. This is happening since font-family '72Black' is being used, but the Polish character `ń` is not supported by this font-family because of which it is falling back to '72Blackfull` for this character.

Please help provide support for these kind of characters in '72Black' font family.

### Expected Behaviour

font-family '72Black' should support the Polish character `ń`.

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

![Support_demo_2h2023_same_issue_SFHUB000208](https://github.com/SAP/ui5-webcomponents/assets/32254036/bee7cb90-b070-483f-b47b-75d549872253)

### Priority

Medium

### UI5 Web Components Version

1.114.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-core,

Can you have a look? Styled heading is used for the text, not a component.

“72Black” contains only a subset of the glyphs that are supported in order to reduce the loading time of the font to make the texts appear as quick as possible. Therefore it’s needed to set the “font-family” with fallbacks such as “72Blackfull” after “72Black” to support the glyphs that don’t exist in the reduced version “72Black”. However, browsers try to display some glyphs that don’t exist in a font by composing them using other existing glyphs which causes wrong appearance of those glyphs. Therefore, we have to explicitly define the Unicode range that are supported by the reduced version “72Black” to prevent the browser’s own composition. Both the fallback and the Unicode-range are needed in order to make the “72” series fonts work correctly. You can find the CSS code in the theming-base-content repository for both aspects.
 
Unicode-range of the reduced version: 
https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/baseTheme/base.less#L7819

Font-family fallback:
https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon/base.less#L611

Best regards,
Petya

**Comment by rama1990br** [comment]
Hi Team,
Can we please have an update on this issue?

**Comment by ilhan007** [comment]
Hello @rama1990br sorry did not have the capacity to pick it up, but we will work on it in the upcoming two weeks and get back to you.

**Comment by ilhan007** [comment]
Hello @rama1990br fix has been merged into the "main" branch and will be part of the upcoming 1.20 release (1 dec - 4 dec).

**Comment by rama1990br** [comment]
Hi @ilhan007,
Is it possible to downport the fix for this to version 1.18.0?

**Comment by ilhan007** [comment]
Released with 1.17.3
