### ISSUE TITLE
[checkbox]: mouse cursor and keypressed state for readonly checkbox

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents#7807]
### Bug Description

I think readonly checkboxes should neither show a "space pressed" state nor have a "klick me" mouse cursor on hover, because they are not interactive and cannot be changed.

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

v1.19.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please check this issue?
On space pressed there is a change of color and also cursor change on mouse hover.
https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-check-box--basic&args=readonly:!true

Best Regards,
Tsanislav

**Comment by plamenivanov91** [comment]
Hello @mhchem ,

Thanks for the issue.

I checked some guidelines, emailed some of me colleagues and checked the OpenUI5 project as well.

You can see this guideline here:
https://experience.sap.com/internal/fiori-design-web/ui-element-states/#read-only

Basically the element should be interactive but without the option to change its state.

This is why I fixed only the "active" state on "Enter" or "Space" key down because it's quite misleading to indicate change of value.

Regards,
Plamen Ivanov
