### ISSUE TITLE
[Feature Request|A11y]: DateTimePicker dialog title is not getting announced by screen reader

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents#7825]
### Feature Request Description

When opening the date and time picker, jaws screen reader is reading the chrome tab title. There is a accessibleNameRef but this only affects the input. Please help implement something that when dialog box is activated screen reader announces the title text that indicates what the dialog is intended for, titles need to describe topic or purpose of that window 

### Proposed Solution

accessibleNameRef effects both the input and the dialog popup for selecting date and time.

### Organization

SAP SuccessFactors

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can we check and evaluate this case?

Best Regards,
Tsanislav

**Comment by unazko** [comment]
Hello @lormanlau,

I'm not sure that I get the requirement right.
JAWS would read the Chrome tab title when in virtual cursor mode only.
The virtual cursor mode gets switched on by default with JAWS and it is not
the correct mode to navigate through a component with a complex accessibility semantics like the `ui5-datetime-picker` .
When in regular mode no title gets announced when the date time picker gets opened.
That is correct though as the opened popover doesn't have a visual title.
It is not a good practice to provide additional information for the screen reader users that is not present for the rest of the users.

The `accessibleNameRef` property affects the `ui5-datetime-picker` input announcements as that is the part all users have to go
through before they can open the value help dialog. Also this is the place the users receive the context information.
The next step would be for the users to press "F4" and open the date picker value help, in order to choose easily a date and time,
but at this point they already do know the context they are in.

Could you please elaborate in more detail?

Best regards,
Boyan
