### ISSUE TITLE
[SF][Bar, ObjectPage, FlexibleColumnLayout, Popover]: The position of popover is not correct if it's target is in a Bar residing in ObjectPage in FlexibleColumnLayout

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents#7826]
### Bug Description

If a popover's target is in a Bar residing in ObjectPage in FlexibleColumnLayout, it doesn't position beside it's target.
<img width="852" alt="Screenshot 2023-11-09 at 15 44 21" src="https://github.com/SAP/ui5-webcomponents/assets/1751846/df6cea54-4e17-4a9d-b8d8-6496f155ed28">

### Expected Behaviour

Popover should be positioned beside it's target.

### Isolated Example

https://99vlt7.csb.app/

### Steps to Reproduce

1. Open https://99vlt7.csb.app/
2. Click "Open" button
3. Observe the position of the popover

### Priority

None

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello @2bno1,

I don't have access to the application (Your connection is not private!  <- error, ), can you please provide a sample in codesandbox where we can reproduce the issue?

Best Regards,
Tsanislav

**Comment by 2bno1** [comment]
@tsanislavgatev 
Here's a sample in codesandbox: https://codesandbox.io/s/flexible-column-layout-popover-99vlt7

Best regards

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd,
It seems there is an issue with the positioning of the opened ResponsivePopover, when placed in a Bar residing in ObjectPage in FlexibleColumnLayout. Could you please have a look?

Regards,
Iliana

**Comment by Lukas742** [comment]
Hi @2bno1 

since you're using `@ui5/webcomponents-react` I'm jumping in here although this will also occur when using ui5-webcomponents without our wrapper. 

It's not recommended mounting popover or dialogs inside components, especially when used inside of slots. Please mount the Popover outside, or use `createPortal` (not supported inside slot props) as described [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-faq--docs#why-is-my-popover-or-dialog-not-rendered-correctly).

https://codesandbox.io/s/flexible-column-layout-popover-forked-pv47qn?file=/src/App.js

**Comment by gmkv** [comment]
Hi @2bno1 

When using elements such as Popovers and Dialogs, React recommends the usage of [`createPortal`](https://react.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal) when you want to render elements that will float on top of the page.
In the above comment, Lukas gives a very good example of the correct usage.
