### ISSUE TITLE
Icon "TntSuccess" does not load

### ISSUE THREAD

**Issue by lucerodv** [SAP/ui5-webcomponents#7833]
### Bug Description

To reproduce:

1. Go to https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-illustrated-message--docs
2. Select:
name='TntSuccess'
size:"Dialog"

as pictured here: 

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

![Screenshot 2023-11-09 at 10 14 58 AM](https://github.com/SAP/ui5-webcomponents/assets/150395020/a2d7dada-4cce-4311-8c94-8c908f278184)

### Priority

High

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Organization

SAP Joule

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please have a look?
You need the following settings to reproduce:
name = 'TntSuccess'
size ="Dialog"

Best Regards,
Tsanislav

**Comment by plamenivanov91** [comment]
Hello @lucerodv ,

The issue is already fixed and it is about to be released.

Here you can check the current "nightly" version which is pre-release in this case:
https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/fiori-illustrated-message--docs

The Success illustration works as expected, there are also a lot new TNT illustrations which will be available with the next release of the ui5-webcomponents.

Regards,
Plamen Ivanov
