### ISSUE TITLE
Date / DateTime / Time Pickers dateValue not available when setting programmatically the value

### ISSUE THREAD

**Issue by ybesnehard** [SAP/ui5-webcomponents#7877]
### Bug Description

When setting programmatically the value in a DatePicker the dateValue is not available (undefined) where when the value is picked by hand in the picker the dateValue is available.

### Affected Component

DatePicker DateTimePicker TimePicker

### Expected Behaviour

The dateValue should be available after having set programmatically the value

### Isolated Example

https://codesandbox.io/s/ui5-webcomponents-forked-dccy4g?file=/src/index.js

### Steps to Reproduce

1. Open the sandbox
2. See that the dateValue is undefined at initialization
3. Pick a date in the picker
4. See that the dateValue is not undefined after picking it

### Priority

Medium

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Operating System

Windows

### Additional Context

In the context of SAP Build Process Automation we would need to be able to get the date object on the picker after setting the value programmatically

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MapTo0** [comment]
Hello @ybesnehard,

You are trying to call a getter for the `dateValue` before the component is upgraded as Web Component at all.
Therefore non of the component API is working at that time.
I would suggest you to use a util to parse your date to an object instead of the component API.
Or wait until the component is upgraded.

Best Regards,
Martin

**Comment by ybesnehard** [comment]
Many Thanks for the info, will do that !
