### ISSUE TITLE
Tabulator in UI5-Textarea

### ISSUE THREAD

**Issue by fmabap** [SAP/ui5-webcomponents#7878]
Hi,
I want to create a ui5-textarea, where the user can enter tab delimited text.

But when I press the tabulator key in the ui5-textarea, then the focus switches to the next control on the html site.

I found for a html standard textarea [this solution](https://benborgers.com/posts/textarea-tab) , but the setRangeText function is not available for the ui5-textarea.

How can I make it possible, that a user can enter a tabulator in a ui5-textarea?

Best regards
Frank

**Comment by fmabap** [comment]
I found this hack to get the wrapped html standard textarea and called the method setRangeText of it as workaround.
```Typescript
const wrappedStandardTextarea: any = uI5TextArea.shadowRoot.querySelector('#ui5wc_2-inner');
```
 (I found the id '#ui5wc_2-inner' in the inspector). But I hope that there is a better solution...

**Comment by MapTo0** [comment]
Hello @fmabap 

The `ui5-textarea` is design to contain texts and spaces only. Native textarea elements does not support tabulators as well, therefore I would not expect to have that feature implemented in the `ui5-textarea`.

Workaround:

In case you really want to have that behaviour you can attach to the inner texarea as metioned above.
```js
const te = ui5TextArea:shadowRoot.querySelector("textarea");
```
would be better selector than selecting it by id (since ui5wc_2 is dynamic).

Keep in mind that this will break the accessibility in your app.
Tab chain will not be working anymore.

Best regards,
Martin
