### ISSUE TITLE
[UI5 Web Components 2.0] Changes suggestion list [Topic P]

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#7887]
### **Issue Description**
The goal is to gather a list with breaking changes that you are willing to do to improve/simplify the components API.

- list deprecated APIs within your components that should be removed with 2.0
- list APIs that we would like to improve and change before releasing 2.0

There is already this issue https://github.com/SAP/ui5-webcomponents/issues/4460 with changes we already identified, so first take a look of it - it could be that some of your suggestions are already proposed.

**Comment by dobrinyonkov** [comment]
Internal Reference: BGSOFUIPIRIN-6407

 - IllustratedMessage#title property deprecate prior 2.0 and remove after 2.0 (slot is available)
 - IllustratedMessage#subtitle property deprecate prior 2.0 and remove after 2.0 (slot is available)
- Progress Indicator: Disabled property removal
- Select Option: Disabled proeprty removal
- Toolbar Popover API Redesign:  (not sure here because items need to be displayed differently in both places, maybe a hybird solution) The introduction of the popover API can replace abstract items concept for the Toolbar popover. This will enable a more flexible and dynamic approach to managing toolbar items.
- ToolbarItem Class Structure: We are considering the replacement of the base class for ToolbarItem with an interface. This should be done if the popover API is implemented. Phisycal items can implement the new interface and fit toolbar API as supported components.
- TreeItem Component: A custom TreeItem component was developed that allows for custom content. The existing TreeItem capabilities can also be covered by it. (perhaps the content slot should be made default and subnodes slot may need to be inroduced) 
Flexible Column Layout Update: The hideArrows feature will become redundant and therefore removed following the introduction of drag-and-resize functionality..
ShellBar Component Enhancement: This includes the deprecation or rename of copilot, copilotDomRef, and showCoPilot properties. Also refactoring can increase customizability through slots. (Not sure about the customization impacts and risks)

**Comment by nnaydenow** [comment]
Investigate how we can simplify ListItems' hierarchy

**Comment by dobrinyonkov** [comment]
With the modern themes, the List modes values seems to be just 3 now. Deprecate the redundant ones:

![image](https://github.com/SAP/ui5-webcomponents/assets/22766569/c7862d03-64e0-4300-9256-5b9085eca67b)

**Comment by ilhan007** [comment]
Transferring from the central item

"Deprecate and remove the `image` property of the standard list item, since new slot avatar will be introduced.
https://github.com/SAP/ui5-webcomponents/issues/5594"

**Comment by ilhan007** [comment]
Extarnal feedback



**ui5-breadcrumbs:**

- design: is used to differentiate between showing or hiding the current page. It would be safer to use a boolean attribute here that could be called hide-current-page. This would from my perspective be more consistent with other attributes. 

- separator-style: there is another attribute for the ui5-list called separator that accepts setting the separator style, maybe this could also be used here instead of having a similar attribute.


**ui5-illustrated-message:**

- size: the ui5-illustrated-message component also offers a size attribute which is set with semantic values “Auto”, “Base”, “Spot”, “Dialog”, “Scene”, which for me could also be values for a mode or design attribute instead as the size aspect of this property is not directly clear. 
?Change: size -> design | mode?


**ui5-list**

- busy: how to handle the busy state with the components is very different. Only 3 components have a busy state, all others require the combination with the busy-indicator component. It would be good to have more consistency here. 
Table, List – discuss to rename busy to loading
