### ISSUE TITLE
Provide CDN bundle of UI5 Web Components

### ISSUE THREAD

**Issue by valentinvieriu** [SAP/ui5-webcomponents#7936]
### Feature Request Description

The UI5 WebComponents currently require developers to install and bundle them for use in projects. To make the components more easily consumable, a CDN bundle should be provided that can be directly referenced in HTML pages

### Proposed Solution

Generate and publish a bundle containing all UI5 WebComponents to a CDN like unpkg. This would allow adding something like:
html
<script src="https://unpkg.com/@sap-webcomponents/bundle"></script> 

And then being able to use the web components directly in HTML without any bundling.
This bundle should be versioned and cached appropriately to avoid issues outlined in
[2](https://blogs.sap.com/2021/05/28/getting-started-with-ui5-web-components-in-2021/)
.

### Proposed Alternatives

There can be 2 separate bundles, one js and one CSS. Would be great if we could import component by component using ES6 imports via CDN

### Organization

Kyma

### Additional Context

Having an easy to consume CDN bundle would lower the barrier to start prototyping and building apps with UI5 WebComponents. It would be a big improvement over having to install and configure bundling before being able to use the components.

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by vladitasev** [comment]
Hi @valentinvieriu 

We do not provide CDN on purpose, because due to being "too convenient", it reinforces bad practices. If we uploaded an "official" bundle on the CDN, it would be quite big, say, 5MB, as it would include all possible components. Over time, as we add more and more components, the bundle would only grow. At the same time, apps usually require just 10-20 components, sometimes more, sometimes less, but never literally all components. And if you build an app with a CDN bundle now, even worse - more components will be added in the future that you're not using so your bundle will grow even more.

There are a few other aspects with bundling:
 - you can bundle only a few icons that you'll be using (and there are 3 icon families in total - SAP Icons, TNT Icons, Business Suite icons that would make the bungle grow even more)
 - same with the illustration assets

Therefore, it's always best to create an own optimized bundle for your app. It takes some setup, but it is very minimal, especially with modern bundlers offering zero-configuration options.

Regards,
Vladi

**Comment by pskelin** [comment]
For step-by-step instructions on how to create a bundle, follow the getting started guide:
https://sap.github.io/ui5-webcomponents/playground/?path=/docs/docs-getting-started-first-steps--docs

Using vitejs makes creating bundles very easy.
