### ISSUE TITLE
[ui5-input]: If Input type="Number" then typing . (dot) causes value to disappear

### ISSUE THREAD

**Issue by martinkma** [SAP/ui5-webcomponents#8023]
### Bug Description

If I type . (dot), that is not supposed to be a decimal separator, then value disappers.
Tested on: https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-input--basic&args=value:Input;type:Number

### Affected Component

ui5-input

### Expected Behaviour

Value does not disappear, should work same, like if I type other special characters e.g. !,",$, ...

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-input--basic&args=value:Input;type:Number

### Steps to Reproduce

1. https://sap.github.io/ui5-webcomponents/playground/?path=/story/main-input--basic
2. change type of control to number
3. type 123.
...

### Priority

Low

### UI5 Web Components Version

v1.18.0

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

The issue is reproducible in the latest storybook also: https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/main-input--docs using the described steps of the reporter.

Best regards,
Petya

**Comment by elenastoyanovaa** [comment]
Hello,

The issue is known to us as it is was previously reported here: https://github.com/SAP/ui5-webcomponents/issues/5983
As described there it will be handled as part of the linked feature request https://github.com/SAP/ui5-webcomponents/issues/4353 as it needs focus and complex development from our side.

Thank you for reporting you can track the process of the feature request.

Kind Regards,
Elena
