### ISSUE TITLE
[ComboBox][SF]: Support for pagination functionality in combobox when the number of options are large

### ISSUE THREAD

**Issue by Ankitadoshi** [SAP/ui5-webcomponents#8032]
### Feature Request Description

We have a requirement for a paginated combobox component. 
Whenever the number of options are huge, we have an API to fetch the options which is paginated so it returns the first page of results. The expected behaviour is that when user scroll downs the option list, it should call the API to fetch the options of next page and so on. Also when the user types something on the combobox, we need to invoke an API to return the matched search results (Also paginated). 
The options list is configurable and hence the number of options varies for different fields.
We tried exploring the input with suggestion component for this use case but the issue with that is the user might not know exactly what to type in the input so that he can see the suggestions. There is no way for the user to see the suggestion items without typing something in the input field
So we need a dropdown behaviour where the user can see the options as well

### Proposed Solution

The ComboBox can add a onScrollToEnd props (or another better name), which will be called when user scroll down to end of ComboBoxItem list and we can make an API call for the same

### Organization

SF

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Ankitadoshi** [comment]
Hi team,
Any updates for this request?

**Comment by ndeshev** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please take a look at that feature request, thanks.

**Comment by hristop** [comment]
Hi @Ankitadoshi ,

Thanks for contacting us regarding this feature. 
As we lack Ux/VD/ACC specifications for such feature and we will require such for its implementation, can you please contact your design team and let them sync with Central Design so that the proper specs can be provided? 
It would be nice to provide the number of the design BLI here for reference once such has been created. This way we can monitor the progress as well. 

In case you are not familiar with the process - there is pinned link in the slack channel. 

Best Regards,
Hristo
