### ISSUE TITLE
[Question][ui5-product-switch] Row size of ProductSwitch

### ISSUE THREAD

**Issue by floa93** [SAP/ui5-webcomponents#8107]
Hey,

the row size of the product switch with its items currently seems to be either 3 or 4 based on the amount of product-switch-items. Is it possible to adjust the row size so we can display more than 3 or 4 ProductSwitchItems inside a row?

Best regards

**Comment by niyap** [comment]
Hello @floa93,

According to our visual specification, that is the expected visualisation: "Desktop or very large screen has a maximum of 4 columns. It is for all screens valid that when the popover contains a lot of items it grows until it reaches the window size minus 76px  (toolbar + padding) after that, vertical scrolling starts"
As the component behaves like expected, we could not consider the reported issue as a bug. 
If you need more items on a single row, please create a feature request in order to be analysed and discussed with the responsible designers.

Kind Regards,
Niya
