### ISSUE TITLE
ui5-shellbar - title vanishes when screen is too small

### ISSUE THREAD

**Issue by ignipae** [SAP/ui5-webcomponents#811]
Dear colleagues,

I would like to report a behaviour, where I am not sure wether this is a bug or intended.
Like the title says, it seems that the primary-title and the subtitle vanish when the screen is too small.

It would be nice if this would be configurable at least or documented that this is intended.

Best regards,
Julian

**Comment by MapTo0** [comment]
Hello @ignipae 

I just checked the visual and interaction design of the ShellBar and it looks like it is kind of "By design"

![image](https://user-images.githubusercontent.com/5821279/66039837-a7e39400-e51e-11e9-8ead-03242533d493.png)

Anyway I think that we need to somehow inform the user that a breakpoint changes so he can react based on that event. Could you please tell us more about your use case so we can collaborate and add an API that fits you best?

Regards,
Martin

**Comment by ilhan007** [comment]
Hello @ignipae,
thanks for reporting this issue.

The primary-title and the secondary-title hide on certain screen widths,
defined by the Fiori design.

We will update the the API Doc to make it clear ([update](https://github.com/SAP/ui5-webcomponents/pull/854)). 

Regarding your suggestion to make this configurable: as the component is kind of semantic and the UX is more or less predefined we decided not provide any configuration regarding this behaviour.

Best,
ilhan
