### ISSUE TITLE
[Feature Request]: Home-End doesn’t work on values when drop-down is closed

### ISSUE THREAD

**Issue by sanketzad** [SAP/ui5-webcomponents#8236]
### Feature Request Description

Impacted components: <code>ui5-combobox</code> and <code>ui5-multi-combobox</code>

When the drop-down is closed, clicking on the `Home` and `End` buttons should display the first and last entry in the list. Instead, the cursor is moving from the left end to the right end of the text in the input field.

### Proposed Solution

Ideally, when the input is focused, pressing the `Home` and `End` buttons should display the text properties of the first and last item in the list.

### Organization

Ariba

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @sanketzad,

The expected behavior of the `ui5-combobox` component is as it follows:

If focus is on the text input and the `Home` button is pressed:
      -  The caret is moved before the first character in the text input. 
      -  If no value is in the text input: the first list item’s value is selected into the text input. 
      
 If focus is on the list box and the `Home` button is pressed:: 
      - The focus is moved to the first list item

If focus is on the text input and the `End` button is pressed:
      -  The caret is moved after the last character in the text input. 
      -  If no value is in the text input: the last list item’s value is selected into the text input. 
      
 If focus is on the list box and the `End` button is pressed:: 
      - The focus is moved to the last list item
      
 So the component behaves as expected.
 
 Thanks and Kind regards,
 Yana
