### ISSUE TITLE
TimelineItem, unfortunate check for default slot leads to empty slot-content

### ISSUE THREAD

**Issue by maltenorstroem** [SAP/ui5-webcomponents#8269]
### Bug Description

The generated TimelineItemTemplate.lit.js checks in block0 whether this.textContent is not null.
Standard Build/minifier remove all spaces and set the HTML to one line. A custom element without TextContent e.g. <my-detail data="${}"></my-detail-data> returns zero during the check and is not displayed.

### Affected Component

@ui5/webcomponents-fiori/dist/TimelineItem.js

### Expected Behaviour

According to the documentation, an array [Nodes] can be inserted in the default slot. I would expect these elements to be displayed in the TimelineItem.

### Isolated Example

https://js-nte7ud.stackblitz.io

### Steps to Reproduce

1. use the Timeline
2. add a custom element (with no TextContent) to the default slot of TimelineItem

### Log Output, Stack Trace or Screenshots

![Screenshot from 2024-02-12 14-40-49](https://github.com/SAP/ui5-webcomponents/assets/9052672/ff46799d-fee7-413f-a463-d50cd4c7e126)

### Priority

High

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Operating System

Linux norstroem 6.7.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nikoletavnv** [comment]
Hi @maltenorstroem, 

I opened your sample and from what I notice the timeline items are not rendered correctly.

![timeline_formatting](https://github.com/SAP/ui5-webcomponents/assets/31706628/66b01ba8-7805-46dc-ae92-2048d96f9204)

Can you please check the formatting in your html page, especially the last timeline item. Also can you send the editor URL from Stackblitz project in order to look at your sample. Thanks!

Best regards, 
Nikoleta

**Comment by maltenorstroem** [comment]
**Editor URL:** https://stackblitz.com/edit/js-nte7ud?file=my-component.js

**Comment by maltenorstroem** [comment]
`<ui5-timeline-item><my-component name="Nobody"></my-component></ui5-timeline-item></ui5-timeline>
  <ui5-timeline-item><my-component name="Nobody">&nbsp;</my-component></ui5-timeline-item></ui5-timeline>`
These are the important two lines. &nbsp; is a workaround that the component is rendered correctly (because of the check). I have intentionally left out all attributes.

**Comment by nikoletavnv** [comment]
Hello @SAP/ui5-webcomponents-topic-b, 
Please take a look at this issue. I was able to reproduce it on our test pages with ui5-icon and ui5-avatar components as well. In order to reproduce the issue, just put a component e.g. <ui5-avatar size="XS" initials="XS"></ui5-avatar> inside ui5-timeline-item without any spaces or newlines and you will notice that the avatar will not be displayed. 
Best regards, 
Nikoleta
