### ISSUE TITLE
remove on* handlers from components

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#834]
- [x] Make the on* hanlders opt-in via metadata for standalone components

Switch all components to @ hanlders in template

- [x] Button
- [ ] CalendarHeader
- [x] CheckBox
- [ ] CustomListItem
- [x] DatePicker
- [ ] DayPicker
- [ ] GroupHeaderListItem
- [x] Input
- [x] Label
- [x] List
- [ ] ListItem
- [ ] ListItemBase
- [ ] MonthPicker
- [ ] Popup
- [x] RadioButton
- [x] Select
- [ ] ShellBar
- [ ] StandardListItem
- [x] Switch
- [x] Table
- [ ] TableRow
- [x] TextArea
- [ ] Timeline
- [ ] YearPicker

**Comment by vladitasev** [comment]
Background: Currently the framework provides "magic" event handlers that are "on"+EVENT_NAME, such as "onclick", "onkeydown". If the web component prototype has such event handlers, the framework will call them (similarly to OpenUI5).

The problem: In order for this to work, we register event listeners on the document. This is to be avoided generally since we don't own the document, unlike OpenUI5. Furthermore, having so much "magic" may lead to unexpected results if web component developers write methods that start with "on" and coincide with the name of an event.

The solution: Refactor all web components (each in a separate pull request) so that they register event handlers locally, rather than using the global framework-driven events. In the .hbs file, use the @syntax for events to register listeners on an appropriate HTML element (most commonly the top-level HTML element in the shadow root). They give these event handlers names that don't need to start with "on".

Finally when all Web Components have been refactored, we can remove the DOMEventHandler from boot, and make it optional.

**Comment by ignipae** [comment]
Hi colleagues,

This is quite interesting. Within some frameworks I receive the following error when using the ui5 webcomponents:
TypeError: "'set onclick' called on an object that does not implement interface HTMLElement."

Would this be connected with your background for this issue? I was unable to find anything similar, but your description sounds like it is connected somehow.

My background is, that I created an "own" webcomponent, which incorporated several ui5 webcomponents (predefined dialog) using stenciljs.
And when I use that webcomponent it works everywhere except typescript based frameworks.

Thanks!
Julian

**Comment by pskelin** [comment]
Hi @ignipae ,
the background for this was to have more explicit way of calling handlers instead of calling them by convention (less magic). With the .hbs templates, it is possible to attach events to child elements with the `@event` syntax, which also makes the handler simpler (you no longer need to lookup the target if it was a nested element).

I have also seen such errors however, and they are caused by transpiling for legacy browsers. Web components extend the HTMLElement class and are supposed to be written as ES6 classes. When a transpiler creates code for ES5, the way it assigns overridden methods (directly) is not valid. Some build tools (like rollup) do the correct prototype assignment (by redefining the method via Object.define), some do not.

If you control the build environment, you have to look for the correct build options. For babel, there is this plugin (I used it to run a preact app which was broken out of the box):
https://www.npmjs.com/package/babel-plugin-transform-custom-element-classes

For typescript, I am not sure what the correct option would be. If you need this running more urgently, please open an issue with an example and I can try to figure it out. Otherwise this change will effectively remove the problem (I think, because there seem to be other issues with the constructor function as well).

So feel free open an issue in case you have a specific usage where the web components do not work.

**Comment by ignipae** [comment]
Hi @pskelin 
Thank you for the swift answer! And I am happy to hear that this might be connected.
It was really tough for me, initially, to somehow find a direction why this is happening.

There is no urgent case which needed to go live yesterday, but of course it would be nice, if it would be resolved with that change. :)

I will check your proposal with the build options, however I would also be interested to contribute to those changes. As far as I saw, its basically updating this hbs file with the mapping and renaming the function.

**Comment by vladitasev** [comment]
Hi @ignipae 

Your contribution to this story would be very welcome!

Regards,
Vladi

**Comment by ignipae** [comment]
Hi colleagues,
great that we made good progress here. :)
I wanted to do the Popup implementation next, however I am not too sure how to do that there.

It seems that there is no "hook" to register the @events. Maybe someone could shed some light in here.

And for the ListItem, ListItemBase and such, I guess a combined pull request would be required as they are connected.

Thanks!
Julian

**Comment by vladitasev** [comment]
https://github.com/SAP/ui5-webcomponents/pull/1046
