### ISSUE TITLE
Child Element Height Not Considered in Group Skipping If Parent's Height or Width Set to Zero

### ISSUE THREAD

**Issue by kavya0212** [SAP/ui5-webcomponents#8354]
### Bug Description

If the parent's height or width is set to zero while the child element has a defined height, it doesn't consider the child's height for group skipping in keyboard accessibility as we use [data-sap-ui-fastnavgroup="true"]

### Affected Component

@ui5/webcomponents-base/dist/features/F6Navigation.js

### Expected Behaviour

The expected behavior is for F6 (group skipping) to also take into account the child element's height and set the focus to that div accordingly.

### Isolated Example

https://codesandbox.io/p/devbox/jj84sw

### Steps to Reproduce

1. Try group skipping using F6
2. div1 and div2 works fine with F6 
3. child1 and child2 are not accessible as parent div has set height to zero

### Priority

High

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by tsanislavgatev** [comment]
Hello colleagues,

Can you please have a look at this case?

**Comment by PrasadGhodke23** [comment]
hi Team,
any update here?

thanks
Prasad

**Comment by nnaydenow** [comment]
Hi @kavya0212, @PrasadGhodke23,

In my understanding elements with `height: 0;`  and their children are typically intended to be hidden from the view and these elements should be excluded from the f6 groups because there are no assurance of their visibility. For example if you simply add `overflow: hidden` to the element with `id: header` this case will be invalid because children will have explicitly height different than 0 but they will be hidden. Could you please revise the structure of your application and how it's build or please provide more information why this is needed.

Thanks,
Nayden

**Comment by S-kavyasri** [comment]
Hello Team,

Thank you for providing the information.
We've revised the structure and implemented the necessary changes in our application. We confirm that we are ready to close the issue.

Thanks and regards,
Kavyasri

**Comment by petyabegovska** [comment]
@S-kavyasri, great!
