### ISSUE TITLE
TabContainer: A11y-In 320px size, the tab text is truncated

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents#8384]
### Describe the bug

<img width="508" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/5724592/dd4c9001-e3fd-4984-9a28-3c7e1e4c1a61">
The tab text is truncated.

### Isolated Example

https://stackblitz.com/edit/github-wg67fg?file=src%2FApp.tsx

### Reproduction steps

1. Click the URL of demo
2. Change the browser screen side to 320px
3. The tab text is truncated
...

### Expected Behaviour

The text should fully displayed

### Screenshots or Videos

demo code url:
https://stackblitz.com/edit/github-wg67fg?file=src%2FApp.tsx

### UI5 Web Components for React Version

~1.25.0

### UI5 Web Components Version

~1.22.0

### Browser

Chrome

### Additional Context

I am from SF Web Team, the issue is reported by a11y export before release.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-topic-rd  , I am forwarding this issue to you to check whether ui5-tab text should be truncated on 320px screen size. 
I am not able to open the example of the author. That's why I have prepared a different one.
Sample (minimize to 320px): https://codesandbox.io/p/sandbox/ui5-webcomponents-forked-5r23h8


Regards,
Iliana

**Comment by GerganaKremenska** [comment]
Hello @sleric1024,

The current implementation is by design. 
The workaround is to put a shorter label.

Internally the design is reviewed: FIORIDESIGN-484

Best Regards,
Gergana
