### ISSUE TITLE
[MultiComboBox]:Count is not displaying for selected items

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents#8493]
### Bug Description

when the user selects multiple items from the drop down and the click outside the combo box. It displays the count.
<img width="1472" alt="Screenshot 2024-03-21 at 2 10 36 PM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/2c281012-12c2-413c-aec7-2c05b1bb15b0">
If the user again click on the number and unselects some items
<img width="1488" alt="Screenshot 2024-03-21 at 2 12 23 PM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/717b7584-ebbc-4357-8b53-9e6fbc05c637">
Then it is observed that the count is not displayed.
<img width="1488" alt="Screenshot 2024-03-21 at 2 12 23 PM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/4ffdee01-f0f5-4167-b975-65e50544ac08">

### Affected Component

MultiComboBox

### Expected Behaviour

Count should always be displayed for the selected items in the combo box.

### Steps to Reproduce

1. Go to https://codesandbox.io/p/sandbox/still-snow-65xrvf?file=%2Fsrc%2FApp.tsx
2. when the user selects multiple items from the drop down and the click outside the combo box. It displays the count.
3. If the user again click on the number and unselects some items
4. Then it is observed that the count is not displayed.

### Priority

Medium

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by petyabegovska** [comment]
Hi @roshnijalan97new,

Clicking outside the multi combo box, always displays the count, I tried with selection and deselection. Can you give more details how to reproduce it? Do you expect the count to be displayed before clicking outside of the multi combo box?

Can you reproduce it in the latest version: [latest sample with multi combo box](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzNTBweDtcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LW11bHRpLWNvbWJvYm94IHBsYWNlaG9sZGVyPVwiVHlwZSB5b3VyIHZhbHVlXCIgc2hvdy1zZWxlY3QtYWxsPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gc2VsZWN0ZWQgdGV4dD1cIkFyZ2VudGluYVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJCdWxnYXJpYVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJEZW5tYXJrXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkVuZ2xhbmRcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiR2VybWFueVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJQaGlsaXBwaW5lc1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJQb3J0dWdhbFwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJUaGUgVW5pdGVkIEtpbmdkb20gb2YgR3JlYXQgQnJpdGFpbiBhbmQgTm9ydGhlcm4gSXJlbGFuZFwiPjwvdWk1LW1jYi1pdGVtPlxuICAgIDwvdWk1LW11bHRpLWNvbWJvYm94PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sInRlc3QudHMiOnsibmFtZSI6InRlc3QudHMiLCJjb250ZW50IjoiIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTXVsdGlDb21ib0JveC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTXVsdGlDb21ib0JveEl0ZW0uanNcIjsifX0)

Best regards,
Petya

**Comment by roshnijalan97new** [comment]
Hi @petyabegovska, The steps are as follows:
1) select as many elements as you can, ex: selected 7 elements
<img width="1446" alt="Screenshot 2024-04-01 at 11 24 01 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/eb1c9ad2-08ba-439d-a1a9-e6a0a12c701d">
2) Click outside the combo box. it should the no of elements as expected.
<img width="1428" alt="Screenshot 2024-04-01 at 11 24 13 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/1fd71fc7-d573-42a7-89e0-c15ca1f0c1f4">
3)Now, click on 6more. the drop down will be show like below image, showing only 7 items which we selected.
<img width="1402" alt="Screenshot 2024-04-01 at 11 24 25 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/29d5ff06-aec4-4d85-aafc-fc16455df858">
4) Now, deselect as few items from the list.
<img width="1300" alt="Screenshot 2024-04-01 at 11 24 32 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/0a87f492-25e0-41b6-a980-e034e2ebfefc">
5) Click outside the combo box. The display of items is not as expected
<img width="1420" alt="Screenshot 2024-04-01 at 11 24 37 AM" src="https://github.com/SAP/ui5-webcomponents/assets/120740457/570c2280-ac48-4762-8585-171ced0993be">

**Comment by dobrinyonkov** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

this issue is reproducible in the following [snippet](https://sap.github.io/ui5-webcomponents/nightly/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzNTBweDtcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LW11bHRpLWNvbWJvYm94IHBsYWNlaG9sZGVyPVwiVHlwZSB5b3VyIHZhbHVlXCIgc2hvdy1zZWxlY3QtYWxsPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJBbGJhbmlhXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gc2VsZWN0ZWQgdGV4dD1cIkFyZ2VudGluYVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJCdWxnYXJpYVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJEZW5tYXJrXCI-PC91aTUtbWNiLWl0ZW0-XG4gICAgICAgIDx1aTUtbWNiLWl0ZW0gdGV4dD1cIkVuZ2xhbmRcIj48L3VpNS1tY2ItaXRlbT5cbiAgICAgICAgPHVpNS1tY2ItaXRlbSB0ZXh0PVwiR2VybWFueVwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJQaGlsaXBwaW5lc1wiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJQb3J0dWdhbFwiPjwvdWk1LW1jYi1pdGVtPlxuICAgICAgICA8dWk1LW1jYi1pdGVtIHRleHQ9XCJUaGUgVW5pdGVkIEtpbmdkb20gb2YgR3JlYXQgQnJpdGFpbiBhbmQgTm9ydGhlcm4gSXJlbGFuZFwiPjwvdWk1LW1jYi1pdGVtPlxuICAgIDwvdWk1LW11bHRpLWNvbWJvYm94PlxuICAgIDwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuICAgIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIm1haW4uanNcIj48L3NjcmlwdD5cbjwvYm9keT5cblxuPC9odG1sPlxuPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuIn0sInRlc3QudHMiOnsibmFtZSI6InRlc3QudHMiLCJjb250ZW50IjoiIn0sIm1haW4uanMiOnsibmFtZSI6Im1haW4uanMiLCJjb250ZW50IjoiLyogcGxheWdyb3VuZC1oaWRlICovXG5pbXBvcnQgXCIuL3BsYXlncm91bmQtc3VwcG9ydC5qc1wiO1xuLyogcGxheWdyb3VuZC1oaWRlLWVuZCAqL1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTXVsdGlDb21ib0JveC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTXVsdGlDb21ib0JveEl0ZW0uanNcIjsifX0) in the playground.

1. Select 4 items
2. Click outside the dropdown
3. **Click exactly on the 3 more link/label**
4. Deselect an item
5. Click outside the dropdown

**Result**
"N more" label is not shown anymore

Could you please have a look?

Thanks,
Dobrin
