### ISSUE TITLE
[ui5-multi-combobox]: not updating hidden text on user interaction

### ISSUE THREAD

**Issue by nnaydenow** [SAP/ui5-webcomponents#8567]
### Bug Description

Deleting all tokens from multi combobox doesn't change the text to "no tokens"

Please uncomment the tests related to this issue mentioned in: https://github.com/SAP/ui5-webcomponents/issues/3541

https://github.com/SAP/ui5-webcomponents/assets/31909318/1dd0c3a7-d042-482c-bc87-8761a36d4af2

### Affected Component

ui5-multi-combobox

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello @nnaydenow ,

As discussed the invisible text is intended to be read out once the component is focused to indicate to the screen reader user whether tokens are present in the multi combobox in order for him to navigate to them if desired.
Regarding the unstable tests it seems that WDIO getText is not a reliable way to test non interactive/hidden content as it sometimes returns empty string, even though there is text content inside the element. Please check: https://webdriver.io/docs/api/element/getText/
As a result I have adjusted the tests in order to test the scenario correctly and reliably: #8867

Kind Regards,
Elena
