### ISSUE TITLE
[ui5-select]: Required ARIA attributes not present: aria-expanded, aria-controls

### ISSUE THREAD

**Issue by ee92** [SAP/ui5-webcomponents#8626]
### Bug Description

AXE detected issue on the ui5-select:
![image](https://github.com/SAP/ui5-webcomponents/assets/24360164/7f6876ca-13ca-47ab-b00b-2727ae6ff890)

### Affected Component

ui5-select

### Expected Behaviour

aria-expanded and aria-controls attributes are required for role combobox

### Isolated Example

https://sap.github.io/ui5-webcomponents/playground/?path=/docs/main-select--select-overview

### Steps to Reproduce

1. run Axe DevTools on the playground page and you will see the same issue from the screenshot

### Priority

None

### UI5 Web Components Version

1.23.0

### Browser

Chrome

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hello @ee92,

This issue was also reported before: https://github.com/SAP/ui5-webcomponents/issues/3827

We are aware of this issue and other issues, related to setting relationships between accessible elements via IDrefs. Setting IDRef relationships are currently not possible due to the nature of the custom elements and their shadow DOM. The issue is present not only for UI5 Web Components, but for every framework creating custom elements and using shadow DOM. This is a gap in the accessibility support and there is a working draft for a new AOM (Accessibility Object Model), which addresses this issue and many more and aim a better, JS based accessibility support for all web element.

You can check the working draft here https://github.com/WICG/aom and the w3c specification here https://wicg.github.io/aom/spec/ (again draft). What is more, you can check out there explainer and see that https://wicg.github.io/aom/demos/#12 Issue 2 references the use case you mentioned and is one of the main issues, which lead to creating the AOM. In future, when this becomes complete and has support for all main browsers, we will have the possibility to adapt the components and make sufficient enhancements in the accessibility support, but until them we do not have any possibility to set there kind of relationships.

What is more, aria-controls does not affect the speech output and there will be no change in the usage of the element with or without the attribute and screen reader users will not be affected.

Note: `aria-expanded` is set and changed accordingly and I guess that axe is reporting both the attrbiutes as missing even if only one is missing.

Thanks for understanding!

Kind Regards,
Dobrin
