### ISSUE TITLE
 Breadcrumb Navigation: The breadcrumb navigation feature does not appear to be rendering correctly in the Firefox browser, despite an adequate amount of available screen space.

### ISSUE THREAD

**Issue by shouryaa28** [SAP/ui5-webcomponents#8688]
### Bug Description

I am reopening the issue - https://github.com/SAP/ui5-webcomponents/issues/8360 as we are still encountering the problem specifically related to Custom UI5 WebComponents in Firefox (as reproduced in the GitHub code linked below). This is not a problem with in a regular UI5 web components that is consumed in any JS framework.
 
To provide further detail, this issue occurs only when the breadcrumbs are removed from the screen during re-renders and added again. Here is the error message encountered in console:

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/16d6ac38-093f-4362-8d39-b12587e2d437)
![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/6c365f52-3774-41a1-ae11-d61134773899)

This issue appears to be reproducible everytime a second breadcrumb is added after re-render.

Despite discussions with @plamenivanov91, we have not yet found a solution, making this a long-pending and high priority task for us.  We have also followed his suggestion to maximize the container width to ensure breadcrumbs occupy the entire space, but it did not solve our problem. 

Here is the repository for the same - https://github.com/shouryaa28/ui5-wc-breadcrumbs-test.

We kindly request your consideration, assistance and guidance in resolving this issue.

Thank you for your attention to this matter.

### Affected Component

Web components in Firefox browser.

### Expected Behaviour

The behavior of Firefox browser should be like this :

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/100cadea-21fa-4a27-a77f-bd6974b74f25)

### Current Behaviour

The behavior of Firefox browser is like this:

![image](https://github.com/SAP/ui5-webcomponents/assets/75392661/79774968-df7c-46d1-abc1-6f4fb20aff72)

### Isolated Example

https://github.com/akshilverma/ui5-wc-breadcrumbs-test

### Steps to Reproduce

1. Clone the repository given in the isolated example.
2. Run the commands - npm install and then npm start.
3. Run it on firefox browser. 

### Priority

Very High

### UI5 Web Components Version

1.24.0

### Browser

Firefox

### Additional Context

SAP Build Actions

### Organization

SAP Labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue was already reported: https://github.com/SAP/ui5-webcomponents/issues/8360
The reporter also mentions a discussion with a colleagues from your team, but even trying the proposed solutions, the issue still persist.
Following the steps to reproduce, it can be easily reproduced in Firefox. If you open the console, you can notice the errors.

Could you please look over?

Thank you in advance!

Kind Regards,
Niya

**Comment by dobrinyonkov** [comment]
Hi @shouryaa28,

It seems there might be some confusion regarding the way of using hbs templates with UI5 Web Components. While lit does support setting HTML instances directly, the recommended approach, is to use tags declaratively in the hbs template. Passing the html directly would bypass the rendering logic of ui5 webcomponents and my lead to such side effects.

So instead of :
```hbs
        {{breadcrumbsRoot}}
```
You would define the ui5-breadcrumbs
```hbs
        <ui5-breadcrumbs>
            {{#each items}}
                <ui5-breadcrumbs-item>{{this}}</ui5-breadcrumbs-item>
            {{/each}}
        </ui5-breadcrumbs>
```

And in your JS logic instead of managing the creation of the components, you would simply manage an array of items:

```js
	constructor() {
		super();
		this.items = [];
	}
	
	onClick() {
		this.i++;
		const item = `item${this.i}`;

		this.items.push(item);

		// re-render after 100ms timeout
		this.foo();
	}
```


This adjustment should resolve the issue you're encountering. Using tags declaratively enhances readability and maintainability of the codebase in the long run. Please give it a try and let us know if you encounter any further issues.

Kind Regards,
Dobrin
