### ISSUE TITLE
[ui5-li-notification-group]: Focus is trapped

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#8768]
### Bug Description

See the steps to reproduce

### Steps to Reproduce

1. open https://sap.github.io/ui5-webcomponents/storybook/playground/fiori/pages/NotificationListGroupItem/?sap-ui-theme=sap_fiori_3
2. find to "Payments" group
3. click the second list item
4. press "arrow up" on the keyboard
5. try to press "arrow up" or "arrow down"
6. focus is trapped (can be moved only with "tab", but not with the arrows)

### Priority

Medium

### UI5 Web Components Version

main

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dimovpetar** [comment]
Hello @ui5-webcomponents-topic-rd,

`ui5-busy-indicator` intercepts all keydown and keyup events and stops their propagation. This is the reason why the focus stays trapped at the busy notification list item.
Besides keyboard, you also can't focus the busy item with the mouse, because the busy indicator adds `pointer-events: none` style.

Best regards,
Petar
