### ISSUE TITLE
Content Security Policies (CSP) can prevent script and style tags in HTML documents

### ISSUE THREAD

**Issue by jfillmor** [SAP/ui5-webcomponents#881]
**Is your feature request related to a problem? Please describe.**
Content Security Policies (CSP) can prevent script and style tags in HTML documents.

**Describe the solution you'd like**
Allow for configuration to be applied after the document is loaded.  Currently setTheme works but there is no way to set RTL, language, compactsize, calendarType, etc...

Allow for configs to be set by the application by javascript variables or update to allow changes by set functions.

**Describe alternatives you've considered**
Any other work around where this can be set on the fly.

**Comment by pskelin** [comment]
Hi @jfillmor ,
it makes sense to set those configuration before the components are rendered and the idea so far has been that changing this configuration options are essentially a page reload (as all components need to rerender).

So rendering once with the default configuration and reacting to a method call rerendering a second time will be too inefficient for start-up. Hence the JSON configuration - applied before the components are rendered at all.

Can you provide more background on your use case? Are you using a framework to develop the application? How do you store these configuration options for the user? Do you apply them from the app code itself via javascript? Any usage information will be helpful to add a different configuration.

**Comment by pskelin** [comment]
Hi @jfillmor ,
could you also specify the exact policy you used that prevents the configuration?

I just tested with the following CSP header:
`Content-Security-Policy-Report-Only: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' https: http: data: blob:; media-src 'self' https: http: data: blob:; object-src blob:; frame-src 'self' https: gap: data: blob: mailto: tel:; worker-src 'self' blob:; child-src 'self' blob:; connect-src 'self' https: wss:; base-uri 'self'; report-uri dummy.csplog;`

And there are nor CSP errors related to the script tag. In general, it seems to apply only to inline scripts of type `application/javascript`, but our configuration script is of type `application/json` which means no code execution and this seems to be allowed by CSP.

```html
<script data-ui5-config type="application/json">
	{
		"language": "de"
	}
</script>
```

Let me know how to reproduce this, otherwise the CSP should not be a problem for the inline configuration.

**Comment by jfillmor** [comment]
Thanks for the info.  I will retest and let you know.  Closing the issue.
