### ISSUE TITLE
[Breadcrumbs]: Current Page breadcrumb is a link that reloads the frame it's in

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#8853]
### Bug Description

The "current page" breadcrumb item didn't used to be a link, but now it is. This is a little confusing, visually, but the real problem is that, when clicked, it doesn't seem to have the same handling as other breadcrumb items. Instead, it reloads the page. You can see this in the UI5 examples here: https://sap.github.io/ui5-webcomponents/components/Breadcrumbs/
Find any of the examples and click on the "Current Page" in them and the iframe showing the example reloads.

This isn't too impactful in the examples, they just flash. In my application, a content editor, the editor reloads and the user loses their work.

Luckily, there's a workaround, at least for me. Use the "NoCurrentPage" design. This wraps the link in the handling that the other breadcrumbs have, so my click handler is called instead of a link being followed. It doesn't look as nice as having the current page, but at least the editor doesn't reload unexpectedly!

### Affected Component

Breadcrumbs

### Expected Behaviour

I would prefer the "Current Page" to not be a link at all.
But I expect that, even if it is a link, it would follow the same handling as the rest of the breadcrumbs: it should call my click handler.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Breadcrumbs/

### Priority

Low

### UI5 Web Components Version

1.24, 1.22

### Browser

Chrome

### Organization

SAP

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-p, 

Please check if the last Breadcrumds element works as defined in the specifications.

Best Regards,
Nikolay Hristov
UI5 WebComponents Dispatcher

**Comment by brandon-sap** [comment]
Any word on this? Thanks!

**Comment by yanaminkova** [comment]
Hello @brandon-sap,

You're correct in noticing that the final item in the `ui5-breadcrumbs` component used to be non-clickable and is now a link. This change aligns with updated UX and design specifications. Similarly, the behavior of refreshing the current page upon clicking the last item is intentional and in line with specifications.

However, we acknowledge that your feedback isn't the only one we've received regarding the new design of the component. We're currently in the process of analyzing further feedback and discussing it with designers and concept owners to effectively address it.

Thank you for sharing your thoughts, we'll take them into consideration and will keep you updated.

Kind Regards,
Yana

**Comment by brandon-sap** [comment]
Thank you. Can you provide a link to these design specifications? This behavior is very curious, indeed. Especially since the click handler is ignored for the last breadcrumb.

**Comment by yanaminkova** [comment]
Hello @brandon-sap,

I wanted to update you on our recent decision regarding the  `ui5-breadcrumbs` behavior. 
After analyzing the received feedback and consulting with our designers and accessibility experts, we have decided to revert the recent change to the current location behavior.

We are currently reworking the logic so that the current location element will accept text by default, with the option to use a link on demand.

You will be notified once this change is merged.

Thank you and kind regards,
Yana

**Comment by yanaminkova** [comment]
Internal Reference: BGSOFUIPIRIN-6596

**Comment by brandon-sap** [comment]
Thanks for the update, I really appreciate it!

**Comment by dobrinyonkov** [comment]
Closed with https://github.com/SAP/ui5-webcomponents/pull/9421
