### ISSUE TITLE
[Slider]: Slider handle disappears when it has focus

### ISSUE THREAD

**Issue by brandon-sap** [SAP/ui5-webcomponents#8854]
### Bug Description

The visual handle used to drag the slider disappears when it has focus. It gains a border or outline that still shows where the handle is, but the icon disappears. Click back off of it and the icon comes back.
Luckily, the handle is still there. Dragging the outline around still changes the value of the slider.

### Affected Component

Slider

### Expected Behaviour

The handle should be visible all the time, even when it is being dragged.

### Isolated Example

https://sap.github.io/ui5-webcomponents/components/Slider/

### Steps to Reproduce

1. Load https://sap.github.io/ui5-webcomponents/components/Slider/
2. Find any example slider
3. Click on the handle
4. Notice that the icon disappears

### Log Output, Stack Trace or Screenshots

None

### Priority

Low

### UI5 Web Components Version

1.24, 1.22

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by NHristov-sap** [comment]
Hello @ui5-webcomponents-topic-rl,

I am forwarding this issue to you, because the issue is reproducible.

Best Regards,
Nikolay Hristov
UI5 WebComponents Dispatcher

**Comment by elenastoyanovaa** [comment]
Hello @brandon-sap ,

This is an intentional behavior and it is by design. The idea is to give the possibility for the user to precisely set a value when the step is small. Having the slider handle with solid background on top of the slider progress bar and on top of the tickmarks does not give precise information to the user what is the actual set value of the slider so this is the reason that on focus (while dragging for example) the handle has a transparent background.
I hope this makes sense to you. Additionally I have sent and email with links to the visual design specification.

Kind Regards,
Elena

**Comment by brandon-sap** [comment]
That is interesting, thank you.

In my use case, the values are widespread, either 3 or 4 possible values and that's it. This makes the design unnecessary and confusing. I certainly see the application in the design docs, and I can see that when used on a touch screen, too, it makes a lot of sense.

When I upgraded my ui5 library (and likely it's been this way for a while, I was pretty behind in a lot of packages!), however, this came back to me as a bug in my project. Since my use case doesn't fit the intended design (by that, I mean that the steps are not small, so there's no need to hide the handle), would it be possible to make this an optional thing?

Maybe I could set an attribute on the component that tells it to always show the handle?

Thanks!
Brandon
