### ISSUE TITLE
[Feature Request]:The popover is optional when focus on the informational input

### ISSUE THREAD

**Issue by bomasap** [SAP/ui5-webcomponents#8922]
### Feature Request Description

We need to implement a design requirement for the old value field. The design specifies a blue highlighted informational input box. When the input box is focused, it should not display any popover; this feature is purely visual. Please see the "Default with change" and "Focused with change" in the attachment. 

Requirement Design: 
<img width="874" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/169193249/939c5efb-b729-4970-8b73-e5c76308b9e7">

### Proposed Solution

When the input is being focused, the popover should be optional 

### Organization

SF

### Priority

Very High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by i832513** [comment]
To give a short background here - our requirements are to show Forms which always maintain the currently saved value and surface that information without requiring the user to focus the Field to see that information; however, we also want that field to be shown as though it has an "Information" value state with a Blue highlight.

Another thing to note -- an Input that has a Previous Value AND an error message could happen. So in that situation, the footer text under the input needs to be visible, and the input can be Red color with an Error value state message.

It is for this reason that we cannot pass the text "Previously: Tea" to the component as the value state message - since we may also need to pass a value state message to be displayed in the Value State popover in case of error.

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

Could you please take a look of that feature request?

Thank you in advance!

Kind Regards,
Niya

**Comment by hristop** [comment]
Hi @i832513 ,

Can you please raise a design item to the Central Design Team and leave the ID here. We believe that this case should first be discussed with them and once they provide and updated component specifications, we can proceed on our end. 

Best Regards,
Hristo
