### ISSUE TITLE
Screen Group skipping is not supported for Table 

### ISSUE THREAD

**Issue by C5362575** [SAP/ui5-webcomponents#8931]
### Bug Description

The group skipping must be possible to bypass larger elements/ skip a complex UI element/group like Table using the keyboard shortcuts
- either CTRL + TAB or SHIFT + CTRL + TAB
- or F6 or SHIFT + F6.
For more or detailed information please refer to the below link:
https://wiki.one.int.sap/wiki/pages/viewpage.action?spaceKey=Acc&title=ACC-269+Details 

### Affected Component

Table 

### Expected Behaviour

There should be a mechanism available to bypass blocks of content that are repeated on multiple Web pages. A user must be able to locate the focus of a page as quickly as possible without, for example, having to traverse identical content after changing screens.
So there should be mechanism to Group skip complement UI element like Table 
 

### Steps to Reproduce

 There is no possibility to skip a complex UI element/group using the keyboard. Currently, Table does not support bypassing of larger elements.

### Priority

None

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by niyap** [comment]
Hello @C5362575,

The ui5-table component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up]. In order to use this functionality, you need to import the following module: import "@ui5/webcomponents-base/dist/features/F6Navigation.js"

We will enhance our documentation with that information.

Kind Regards,
Niya

**Comment by niyap** [comment]
Hello @SAP/ui5-webcomponents-core,

The ui5-table web components provides a build in fast navigation, but it is not described in its documentation. Could you please enhance it?

Thank you in advance!

Kind Regards,
Niya

**Comment by petyabegovska** [comment]
Hi @C5362575,

The Fast navigation documentation is available here: (https://sap.github.io/ui5-webcomponents/nightly/docs/getting-started/using-features/#f6-navigation-fast-navigation) 

The Table component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up]. In order to use this functionality, you need to import the following module: import "@ui5/webcomponents-base/dist/features/F6Navigation.js": (https://sap.github.io/ui5-webcomponents/nightly/components/compat/Table/#keyboard-handling).

Best regards,
Petya
