### ISSUE TITLE
DatePicker: Wrong value set when formatPattern MM/YYYY used 

### ISSUE THREAD

**Issue by gitgmehja** [SAP/ui5-webcomponents#8949]
### Describe the bug

if formatPattern MM/YYYY is set and user chooses for example 01/2017 the value is somehow changed to 01/2016

### Reproduction steps

1. open https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-datepicker--default
2. change formatPattern to MM/YYYY
3. try to select 01/2017

### Expected Behaviour

selected value should be the one the user chose, but it changes to some other year 01/2016 or 01/2015
![image](https://github.com/SAP/ui5-webcomponents-react/assets/129291860/7b518ab2-0e6a-426b-a692-329bf4ef8395)

### UI5 Web Components for React Version

1.26.3

### UI5 Web Components Version

1.26.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by GerganaKremenska** [comment]
Hello @gitgmehja, 

The issue is not reproducible in storybook, or in the exmaple provided by @Lukas742.
I have attached videos testing in storybook and Blitz.


Can you please provide more information on how to reproduce this issue?

Best Regards,
Gergana

https://github.com/SAP/ui5-webcomponents/assets/22882174/aada3779-54b5-4e7e-bfca-7727d4a97fec


https://github.com/SAP/ui5-webcomponents/assets/22882174/06a76229-5fee-405d-8bee-bb387a3771b9

**Comment by gitgmehja** [comment]
thanks @Lukas742

**Comment by GerganaKremenska** [comment]
Hello Colleagues,

Can you take over the issue regarding date picker? Looks like when locale is used there is an issue.
Lukas previous comments have steps to reproduce.

Best Regards,
Gergana
