### ISSUE TITLE
ui5-shellbar: implement animation:off for co-pilot

### ISSUE THREAD

**Issue by pskelin** [SAP/ui5-webcomponents#899]
- [x] The latest visual specification provides a static svg besides the animated svg.
- [x] Make a property to control the rendering.
- [x] update the animated svg with the latest spec

**Comment by ilhan007** [comment]
- global config will be introduced rather than component level property
[feat: add animationMode configuration](https://github.com/SAP/ui5-webcomponents/pull/905)
- update the animated SVG with the latest spec is started in this change
[extract animated coPilot as add-on feat](https://github.com/SAP/ui5-webcomponents/pull/904)
- The latest visual specification provides a static SVG besides the animated SVG
[extract animated coPilot as add-on feat](https://github.com/SAP/ui5-webcomponents/pull/904)
