### ISSUE TITLE
Cannot add data automation id property to MenuItem

### ISSUE THREAD

**Issue by Ilian-Allaf** [SAP/ui5-webcomponents#9065]
### Bug Description

When adding automationId to MenuItem, the property don't appear on the DOM element.

### Affected Component

MenuItem

### Steps to Reproduce

1. Add automationId property to a MenuItem component
2. Find  your MenuItem on the DOM and look at its properties

### Priority

None

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by amaillard-sap** [comment]
The data-automation-id attribute is a mandatory attribute in order to assign hotspots in web assistant + is used for automation purpose including the parsing of translation in the Rigi tool. 
Being unable to inject this attribute on some elements put us out of SAP development standard & best practices.

This is considered High priority on SBPA product.

**Comment by plamenivanov91** [comment]
Hello @amaillard-sap ,

As `automationId` is not something we officially support, can you use the native 

You can use the native API `setAttribute('automationId', 'test id')` as shown in this [snippet](https://stackblitz.com/edit/js-e178zr?file=index.html).

Can you confirm if this is sufficient solution for you ?

Regards,
Plamen Ivanov

**Comment by amaillard-sap** [comment]
We do not need to use the native API, we can directly set the data-automation-id on the web component, the problem is that this property on the ui5-menu-item is not transfered to the created ui5-li in the static area which is actually what the users see on their screen.
We need a way to have a unique information transfered from the web component that we create (the ui5-menu-item) to the element that is dsplayed (here the ui5-li).

**Comment by nnaydenow** [comment]
Hi @Ilian-Allaf, @amaillard-sap,

Could you please check the following [comment](https://github.com/SAP/ui5-webcomponents/issues/7722#issuecomment-1923933048) of @vladitasev in https://github.com/SAP/ui5-webcomponents/issues/7722 and if it will work for you?

BR,
Nayden

**Comment by amaillard-sap** [comment]
Hi @nnaydenow,

I do not understand exactly what should be done based on the comment you linked.

I tried to use 'stable-dom-ref' on this stack blitz > https://stackblitz.com/edit/js-gq2yq1?file=index.js,index.html but I do not see any effect; can you assist us here ?

Thanks

**Comment by amaillard-sap** [comment]
Hi @nnaydenow,

I cannot say whether or not the companion / webassistant will be able to identify the select entry with this information, but this surely goes in the good direction :)
