### ISSUE TITLE
[Input] Exception thrown when pasting value from Chrome suggestions

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents#9081]
### Describe the bug

We have an `Input` component in a `Dialog`. When I enter a string into that input, close the dialog, refresh the page, reopen the dialog and click on the input, Chrome suggests the string I entered before. If I accept this suggestion, I get an error in the console.

I wasn't able to get Chrome to provide a suggestion in a StackBlitz, I can therefore only show you a video. It's a simple input component though, without any fancy logic.

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/110408767/68f91e5f-ebaf-44e1-8966-0e0239c95744

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

### Operating System

Win11

### React Version

17.0.2

**Comment by plamenivanov91** [comment]
Hello @SAP/ui5-webcomponents-topic-rl,

This issue is also easily reproducible locally on the main branch.

```
	<ui5-dialog id="dialogInput" header-text="Dialog">
		<form>
			<label for="fname">First name:</label><br>
			<ui5-input type="text" id="fname" name="fname"><br>
		</form> 
	</ui5-dialog>
```

1. Open Dialog
2. Type your name
3. Refresh Page
4. Open Dialog
5. Pick your name from the Chrome Suggestion for the input field
6. Exception in console

![Screenshot 2024-05-30 153919](https://github.com/SAP/ui5-webcomponents/assets/13866865/cfbb53ae-1018-47fb-8626-61da664f24bd)

Could you please take over?

Regards,
Plamen Ivanov
