### ISSUE TITLE
[ui5-popover]: RTL sample issue

### ISSUE THREAD

**Issue by kskondov** [SAP/ui5-webcomponents#9232]
### Bug Description

When in RTL mode the dot in the popover is displayed before the text
![PopoverRTL](https://github.com/SAP/ui5-webcomponents/assets/6640019/4bf2300b-028d-4b14-90f9-1389d92da6bb)

### Affected Component

Popover, Responsive Popover

### Expected Behaviour

Text is displayed correctly with the dot at the end 

### Isolated Example

https://sap.github.io/ui5-webcomponents/nightly/components/Popover/

### Steps to Reproduce

1. Open: https://sap.github.io/ui5-webcomponents/nightly/components/Popover/
2. Change text direction to RTL from Settings
3. Open Basic Sample popover

### Priority

Medium

### UI5 Web Components Version

2.0

### Browser

Chrome, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by LidiyaGeorgieva** [comment]
Hello @kskondov ,

This is expected behavior.
You can see this plain html sample: https://jsbin.com/berahaxiyo/edit?html,output
Also you can test sap.m.Text in this page: https://sapui5untested.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Text/sample/sap.m.sample.Text
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/0fa47e2a-82a6-4580-9d7e-aaafe2b1fec7)
If the textDirection property is set to "RTL" the result is the same.
It is different if the textDirection property is set to "LTR" (page is in RTL, but specific control is with own direction):
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/3e78abe6-138d-41b9-80de-3cc9647f0c2a)
but this is not possible for the [Label component](https://sap.github.io/ui5-webcomponents/nightly/components/Label/), which is currently used inside the Popover.
Maybe this will be future improvement?

Best Regards,
Lidiya
