### ISSUE TITLE
ShellBar : Screen title is truncated on resizing the screen to 200%.

### ISSUE THREAD

**Issue by DikshaHub** [SAP/ui5-webcomponents#9296]
### Describe the bug

When the screen zoomed in to 200%, the title gets truncated.

### Isolated Example

https://stackblitz.com/edit/github-wcwdgu-f5wwkv?file=src%2FApp.tsx 

### Reproduction steps

1. Open the isolated example.

2. On the top right click on 'Open preview in new tab'. A new tab with UI will be opened with the isolated example. (https://githubwcwdguf5wwkv-tr3y--5173--dc4d7514.local-credentialless.webcontainer.io/ )

3. Resize the screen to 200 %.

4. The screen title "SAP New Project Here," gets truncated when screen zoomed in to 200%.

### Expected Behaviour

Truncation should be avoided on resizing the screen to 200%.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/66899235/faa82083-40e1-4f43-b94e-ff66a5ac11bc)

### UI5 Web Components for React Version

~1.29.0

### UI5 Web Components Version

~1.24.0

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kineticjs** [comment]
Hello@SAP/ui5-webcomponents-topic-p,

The issue is about undesired truncation of the ui5-shellbar title in the case when the overall space is small, but there is still some empty unused space on the side of the truncated title. For example, we see 7.5rem unused space taken from the "middle" container when it is empty.
Can we check if we can improve the handling of the available space?

**Comment by DikshaHub** [comment]
Certainly! We can improve the handling of the available space. 
My requirement is to ensure that text around 30 characters long does not get truncated. Please let me know.

**Comment by DikshaHub** [comment]
Text around 30 characters gets truncated when resized to 200%. Please advise on how to address this.
