### ISSUE TITLE
DynamicPage : Wizard steps area is within the same container as the page header.

### ISSUE THREAD

**Issue by DikshaHub** [SAP/ui5-webcomponents#9312]
### Feature Request Description

We are working on a dynamic page that includes a wizard. Our requirement is to have the page header and wizard steps within the same container.
Please refer : https://stackblitz.com/edit/github-wcwdgu-svwpsw?file=src%2FApp.tsx
Here is the current layout.

![image](https://github.com/SAP/ui5-webcomponents/assets/66899235/7ab9b4e0-0172-4ed8-8cb8-19e30b34490c)

### Proposed Solution

We expect the layout to look like the example below.

![image](https://github.com/SAP/ui5-webcomponents/assets/66899235/4c7a2e18-22bc-4768-a046-3dfc97b2aed4)

Refer https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697897301 .

The wizard step icon titles should be integrated into the header, and there should be no unnecessary padding visible between the wizard content block and the page border.

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kineticjs** [comment]
Hi @DikshaHub,

Thank you for the sample of the issue.  When inspecting  the rendered HTML, however, I cannot see the `ui5-dynamic-page ` component developed in this repo, see e.g.: https://sap.github.io/ui5-webcomponents/nightly/components/fiori/DynamicPage/

Maybe you are using a different DynamicPage component currently?

In our ui5-dynamic-page I was able to nest ui5-wizard in its "headerArea" slot, so probably the issue is specific to the component in your linked sample.

Thanks
