### ISSUE TITLE
The example in the Playground can't be scrolled

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [SAP/ui5-webcomponents#9370]
### **Issue Description**
No scrolling of the sample possible (the whole page is scrolled and the third notifications group is not fully visible)

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [X] Other

Steps to reproduce:
1. Open https://sap.github.io/ui5-webcomponents/nightly/components/fiori/NotificationList/#notification-list-with-group-items
2. Click on "Open in Playground" button
3. Expand the two collapsed groups
4. Issue: no scrolling of the sample possible (the whole page is scrolled and the third notifications group is not fully visible)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/240ea40c-c1b4-44a0-a683-ca5e6d016c0c)

**Comment by nnaydenow** [comment]
Since the sample's height is dynamically we can't guarantee what to be used. You can set some harcoded height to the body element inside the sample

**Comment by dimovpetar** [comment]
Hello @SAP/ui5-webcomponents-topic-core ,

I have opened https://github.com/SAP/ui5-webcomponents/pull/9475 to set fixed height of the sample.
However, I would like to use 100% height to the `body` and the `html` elements, which currently doesn't improve anything, because the `iframe` has only 150px height.  Why 100% height is not the default for all of the samples?

Best regards,
Petar
