### ISSUE TITLE
[Card | theming]: Border Radius are different in High Contrast Theme

### ISSUE THREAD

**Issue by surjadeep** [SAP/ui5-webcomponents#9374]
### Bug Description

Border Radius are different in High Contrast theme

### Affected Component

Card

### Expected Behaviour

Border Radius should be same across all themes

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

![screenshot-1](https://github.com/SAP/ui5-webcomponents/assets/12830367/65653b73-4aa6-4cef-8ca9-551c56eb12d3)
![screenshot-2](https://github.com/SAP/ui5-webcomponents/assets/12830367/58c4be42-3c8d-4e72-9aa2-a7f9b84cdafe)

### Priority

Medium

### UI5 Web Components Version

Latest

### Browser

Chrome

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nikoletavnv** [comment]
Hello @surjadeep,

The high contrast themes differ from the normal themes not only by color but also by representation. Many components have smaller border radius in their high contrast variants than their normal light and dark theme variants. 

I have checked about the card component and it is not a bug - it is by design. 

Kind regards,
Nikoleta Terzieva
