### ISSUE TITLE
[ui5-input]: Issues found during testing

### ISSUE THREAD

**Issue by nikoletavnv** [SAP/ui5-webcomponents#9454]
### Bug Description

**1. Input of type Number does not allow "1e" as a value but the native input of type number does**
Input of type "Number" - Entering "e1" as a value is accepted, but "1e" is not accepted and the value disappears. The native input of type "number" accepts both combinations.

**2. Details popup is not closed when focusing out** 
 https://sap.github.io/ui5-webcomponents/nightly/packages/main/test/pages/Input_quickview.html - sample "Test Quick View sample" - select an item from the suggestions list - a popup with details is opened. Click somewhere inside the details popup - the suggestions list closes but the details popup remains open. 

### Affected Component

ui5-input

### Steps to Reproduce

1.
2.
3.
...

### Priority

Low

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hi,

As discussed with the team:

1.  First issue will be handled with [#4353](https://github.com/SAP/ui5-webcomponents/issues/4353).
2. Second issue happens because the sample is incomplete, which is done on purpose just to show some possibilities for the application developers and we decided not to spend time on extending the functionality.

Regards,
Ivaylo
