### ISSUE TITLE
[ui5-message-strip]: No default theming for invalid color schemes

### ISSUE THREAD

**Issue by nikoletavnv** [SAP/ui5-webcomponents#9457]
### Bug Description

When you set invalid number/value for the color-scheme property (e.g. 13), the appearance of the message strip does not default to an existing color scheme but looks strange, especially for design="ColorSet1" because there is white text on transparent background

### Steps to Reproduce

1. Open https://sap.github.io/ui5-webcomponents/components/MessageStrip/
2. Scroll to the sample "Custom visualisation"
3. Edit the sample - set the following attributes to the second message strip: 
**design="ColorSet1" color-scheme="13"**
4. No default theming for invalid color-scheme

### Priority

Low

### UI5 Web Components Version

2.0.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment]
Previously there was a built-in mechanism in the framework for fallback to the default value when invalid one is set. With 2.0 this has been removed with this [change](https://github.com/SAP/ui5-webcomponents/pull/8846)

There are no fallbacks any more. All runtime checks for properties (especially enumerations) are removed. All type checking is left to the TypeScript compiler and assigning an invalid value to an enumeration or a number/boolean field is considered a bug that should be fixed instead of the framework silently masking it by providing a fallback value.

So I don't consider this as bug, if this happens we will ask the developer/consumer to fix the usage.
On CSS level probably we can write some smarter styles to make it better but again we will mask the wrong usage.

**Comment by ivoplashkov** [comment]
Hi @ilhan007,

Thank you for your feedback regarding this issue. Since you mentioned that this isn't actually an issue, but more of an incorrect usage, I will go ahead and close it. If there are any further details or concerns related to this matter, please feel free to reopen the issue or create a new one.

Best regards,
Ivaylo
