### ISSUE TITLE
Display Start Column in FlexibleColumnLayout on Mobile

### ISSUE THREAD

**Issue by bomasap** [SAP/ui5-webcomponents#9481]
### Is your feature request related to a problem?

When using the FlexibleColumnLayout component with the layout set to TwoColumnsStartExpanded on mobile screens, only the content in the middle column is displayed. However, when a user clicks any item in the middle column, there is currently no method to display the start column accordingly.

https://stackblitz.com/edit/github-t5j5mn-nkufxa?file=src%2FApp.tsx

<img width="617" alt="Screenshot 2024-07-12 at 9 44 32 AM" src="https://github.com/user-attachments/assets/31711883-2c80-45ce-9510-a9a7463d946d">

### Describe the solution you'd like

Introduce a method that allows the display of the start column when an item in the middle column is clicked. This will improve the user experience by providing better navigation and content visibility on mobile devices.

### Additional Context

If there are any existing workarounds or if additional context or examples are needed, please let me know. This feature will greatly benefit users who interact with FlexibleColumnLayout on mobile devices by providing a more seamless and intuitive experience.

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by dobrinyonkov** [comment]
Hi @bomasap,

The behavior you have described is by design. In mobile screen sizes (Size S), the FlexibleColumnLayout only displays one column at a time (the most right one of the current layout) to ensure optimal use of the limited screen space. When the layout is set to TwoColumnsStartExpanded, the middle column takes precedence for display.
This is needed because of scenarios such, if the flexible column layout was initially loaded in size bigger then S (M,L,XL) and then, the user navigates to the second column and changes the browser window to size S, the default 2-column layout for size S (0% : 100%) should be shown, otherwise users will be shown the first column which they already navigated out of. 

You can check more about it in the Fiori guidelines: https://experience.sap.com/fiori-design-web/flexible-column-layout/


**Suggested Solution:**
To address your use case, we recommend implementing a back navigation mechanism. This can be achieved by providing a back button or similar navigation control within the middle column that, when clicked, navigates the user back to the start column.

Here is an example of how you might implement this in your application:

- Add a Back or Close Button in the Middle Column:
- Add a button in the header or toolbar of the middle column that triggers a navigation action.

**Handle the Back Navigation:**
Implement the logic to handle the navigation back to the start column when the back button is clicked. This could involve setting the layout to display a one column layout. additionally you may want to change the url to match the newly navigated page.

Here's a simple example in the context of your provided code:
https://stackblitz.com/edit/github-t5j5mn-dmenui?file=src%2FApp.tsx

Please try this approach and let us know if you encaouter any problems.

Kind Regards,
Dobrin
