### ISSUE TITLE
[Feature Request]: Support @data variables of Handlebars

### ISSUE THREAD

**Issue by koeppel** [SAP/ui5-webcomponents#9503]
### Feature Request Description

Handlebars.js offers different @data variables (https://handlebarsjs.com/api-reference/data-variables.html).
These can be used in loops to determine if a item is the first or last entry. Also @root allows to refer to the initial context of the template, this would reduce the usage of `../XYZ` which could be replaced with `@root.XYZ`.

Currently only `@index` is supported, I'm not sure if `@level` is necessary as it's only for logging. But `@root`, `@key`, `@first` and `@last` would be super handy.

### Proposed Solution

Implement support for `@root`, `@key`, `@first` and `@last`

### Organization

SAP

### Priority

Medium

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by vladitasev** [comment]
Hello,

Thanks for reaching out to us. Let me give you some context on our `.hbs` support on a general level. Based on our experience with other UI frameworks, our main observation was that people were abusing component renderers a lot - to perform complex data transformations, change state, etc. Therefore, for UI5 Web Components we wanted to have the bare minimum in terms of renderer capabilities in a declarative format, so that people would not fill renderers with code that doesn't belong there. Another key decision was to only allow for very general functionality so that we can transpile the `.hbs` templates not only to `lit-html`, but also to any other future technology. That's why we settled on the minimal HBS syntax scope.

While `@root`, `@first`, etc. totally make sense, and do not break our paradigm, we are now more focused on providing `.jsx`/`.tsx` support for renderers in the short-medium term, as an alternative to `.hbs` due to popular demand, and don't plan on investing in new features for the `.hbs` compiler right now. If this changes at some point, and we update our `hbs2lit` compiler, we'll have these features in mind.

Regards,
Vladi

**Comment by ilhan007** [comment]
Hi @koeppel we have discussed the request internally, Vladi already explained our thoughts and we have decided that improving the HBS compiler is not part of our plans. Unfortunately we will close this request. However we will work on JSX templates story to provide even more capabilities to templates.
Thanks for the understanding.

Regards,
ilhan
