### ISSUE TITLE
[Feature Request]: Enable native DOM event handlers on components like e.g. ui5-input

### ISSUE THREAD

**Issue by ehni** [SAP/ui5-webcomponents#9546]
## Feature Request
Enable consuming native DOM events on ui5 web components (if this is possible, I am not very familiar with the creation and API of web components).
With e.g. Vue.js, there are many nice features for easier event handling, see https://vuejs.org/guide/essentials/event-handling.html#event-modifiers. 
These can not be used with most ui5 web components as the native DOM events are either not thrown or a CustomEvent is thrown.

## Use cases (examples)

The following uses cases would be possible with native DOM events.

### ui5-input

- Use `CMD`/`ALT`+`Return` to e.g. submit or add an line break  
- Use `Return` to submit an input field

### ui5-navigation-item

- Handle `CMD`+`Click` on navigation items to open them in a new tab when having `href` not set 

### Proposed Solution

Support native DOM events for inputs or clickable elements.

### Organization

SAP

### Priority

None

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by pskelin** [comment]
vuejs supports custom events, it even says so in the docs
<img width="700" alt="Screenshot 2024-07-24 at 8 56 47" src="https://github.com/user-attachments/assets/603ecf33-f5b8-4628-bf3b-10f588fa3ed3">
from here:
https://vuejs.org/guide/extras/web-components

I have create a test application and the following line works
```html
    <ui5-input @selection-change.stop="selChange" show-suggestions>
```

so you can both use the custom event and apply the event modifiers like with normal events.

I suppose your issue is that you do not get autocompletion, and that is indeed the case. Until now, we have not investigated how to add autocompletion for events, but it works at least for properties.

If you are using VSCode, you we provide custom data for properties, you just have to configure it.

1. Open VSCode settings
2. search for `html.customData`
3. click `add item` and paste this path `node_modules/@ui5/webcomponents/dist/vscode.html-custom-data.json`
4. restart VS Code

Then you should get at least code completion for properties like this:
<img width="542" alt="Screenshot 2024-07-24 at 9 03 21" src="https://github.com/user-attachments/assets/33b3394e-2397-495b-9f9f-64ed95607db4">

Note that I typed `sh` and see the suggestions for `show-clear-icon` and `show-suggestion`

Unfortunately this html-custom-data format works only for html properties and vue events are discovered via a different mechanism that we have to investigate. I'll keep this issue open to investigate better code completion support and will rename the issue if you can confirm that is what you actually mean (since custom events do work).

Please let me know if that addresses your original request.

**Comment by ehni** [comment]
Sorry for the late reply. You did answer my question and the issue is fixed :-)
