### ISSUE TITLE
[ShellBar]]: missing import for icon "slim-arrow-down"

### ISSUE THREAD

**Issue by camelCaseChris** [SAP/ui5-webcomponents#9580]
### Bug Description

The ShellBar uses icon slim-arrow-down but does not import it. The result are console errors and the icon is missing in the rendered component.

You can reproduce this in the second sample of the component documention. Open https://sap.github.io/ui5-webcomponents/components/fiori/ShellBar/#profile-area and open the console. You will see errors like 'No loader registered for the SAP-icons-v5 icons collection. Probably you forgot to import the "AllIcons.js" module for the respective package.' Also, the icon is missing in the rendered menu.

Two side notes:
1. It seems strange that the error suggests using the AllIcons.js import. Is importing individual icons not the more usual use-case?
2. There is also #9534 about the same issue with another component. A general review of icon imports might be useful.

### Affected Component

ShellBar

### Expected Behaviour

A component should import all icons it uses.

### Isolated Example

See bug description.

### Steps to Reproduce

See bug description.

### Priority

Medium

### UI5 Web Components Version

2.0.1

### Browser

Chrome, Firefox

### Operating System

Win11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

The issue can be reproduced as described by the reporter. 

The problem is that the not every icon used in the template is imported as a dependency on the cmponent level. 

- For the Shellbar => `import "@ui5/webcomponents-icons/dist/slim-arrow-down.js"` 

- For the FlexibleColumnLayout is => `import "@ui5/webcomponents-icons/dist/addjs"` and `import "@ui5/webcomponents-icons/dist/full-screenjs"`

Best regards,
Ivaylo
