### ISSUE TITLE
TableRow: Possibility to disable certain Rows from being checked within MultiSelect / SingleSelect

### ISSUE THREAD

**Issue by adrianui5** [SAP/ui5-webcomponents#9627]
### Feature Request Description

Reference: https://github.com/SAP/ui5-webcomponents/issues/9605

We would like to have the possibility of enabling/disabling certain TableRows from being selectable.

### Proposed Solution

Introduction of a new prop for TableRow which determines if the row is selectable/clickable or not. Ideally, the Row and the MultiSelect checkbox should be greyed out for visual indication. Also, the "select all"-checkbox should only select the selectable Rows.

### Proposed Alternatives

-

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ivoplashkov** [comment]
Hello colleagues,

Currently there seems to be no way to achieve a disabled TableRow through the API of the component. Could you please evaluate if this is something to be implemented.

Thank you in advance!
Best regards,
Ivaylo

**Comment by adrianui5** [comment]
Hi colleagues, 

Could you please kindly update me on this ticket? Do you know if this feature request will be accepted and implemented, and if so, when will it be implemented?

Best regards,
Adrian

**Comment by nnaydenow** [comment]
Hi @adrianui5,
I understand that you want to exclude certain table rows from being selected in a multi-selection scenario. However, I have a few questions regarding this requirement:
- Should the disabled rows still be displayed in the table?
- How do you plan to inform users that these rows are not selectable, and is there a way for them to enable for selection these rows if needed?
For other UI components, such as ui5-select and ui5-combobox, we have removed the disabled property and recommend that developers filter out disabled options. This approach is taken because there is no straightforward way to inform the users why certain options are disabled.
 
Additionally, please note that your feature request is for version 1, which is currently in maintenance mode. As a result, it’s unlikely that this feature will be implemented.

In version 2 we reimplemented the table and this feature request might be implemented in the future but I can't give you timelines for that. Is this sufficient answer for you?

**Comment by adrianui5** [comment]
Hi @nnaydenow,
- In our use case we want the user to be able to see the all options, but as some of them are should not be possible to select, these particular options should then be disabled and the user should still know about the existence about the options but that they are not possible to select. So yes, the disabled rows should still be displayed
- Ideally the disabled rows should be visually indicated by being greyed out, and the checkbox is not clickable

Do I understand correctly that this feature will not be implemented any time soon?

Thanks,
Adrian

**Comment by adrianui5** [comment]
@petyabegovska SAP

**Comment by adrianui5** [comment]
Hi colleagues,

As this topic is important to us, could you please let us the progress on the ticket?

Thanks,
Adrian

**Comment by petyabegovska** [comment]
Hi @adrianui5, please contact me in Microsoft Teams.

Thanks!
