### ISSUE TITLE
[SF_ACC][ui5-list]: AXE error of grouping list

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#9684]
### Bug Description

AXE error of grouping list

### Affected Component

ui5-list

### Expected Behaviour

no AXE error

### Steps to Reproduce

1. open [demo page](XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0SXRlbVN0YW5kYXJkLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9MaXN0SXRlbUN1c3RvbS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvTGlzdEl0ZW1Hcm91cC5qc1wiO1xuXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMtaWNvbnMvZGlzdC9uYXZpZ2F0aW9uLXJpZ2h0LWFycm93LmpzXCI7In19)
2. run AXE tool scan
3. check error

### Log Output, Stack Trace or Screenshots

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/98aa6189-63a9-468f-b275-4ddb09675b8e">
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/28e174d8-96c0-4cc7-b533-9eadd7c811e4">

### Priority

Medium

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

The issue is reproducible with 1.24.8 patch in the sample page:
https://sap.github.io/ui5-webcomponents/v1/components/List/
Open the "Grouping" snippet into edit mode and run AXE tool.

According to the accessibility standard it is allowed to use a `group` element containing "option" elements into a `listbox`.
https://www.w3.org/TR/wai-aria-1.2/#listbox

For the `list` role however there is no `group` role in 

> Required Owned Elements

 section
https://www.w3.org/TR/wai-aria-1.2/#list

Best regards,
Boyan

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @GongRichard ,
the issue is raised and defined as a backlog item.
Internal reference: BGSOFUIPIRIN-6285.
Also, there is a similar one on the subject: #10297 
Best regards,
Petya Markova.
