### ISSUE TITLE
[ui5-breadcrumbs]: current location should not be a link

### ISSUE THREAD

**Issue by sturmsap** [SAP/ui5-webcomponents#9700]
### Bug Description

According to the [Fiori Horizon](https://experience.sap.com/fiori-design-web/breadcrumb/#types) and Brand Specs the last breadcrumb (denoting the current page) should not be a link. 
I have seen that you changed this behaviour with https://github.com/SAP/ui5-webcomponents/pull/8206 but can't find any specs for the current state.

### Affected Component

Breadcrumbs

### Expected Behaviour

The last breadcrumb denoting the current page should not be a link but text.

### Isolated Example

https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG48aGVhZD5cbiAgICBcbiAgICA8c3R5bGU-XG4gICAgICAqOm5vdCg6ZGVmaW5lZCkge1xuICAgICAgICBkaXNwbGF5OiBub25lO1xuICAgICAgfVxuICAgIDwvc3R5bGU-XG5cbiAgICA8bWV0YSBjaGFyc2V0PVwiVVRGLThcIj5cbiAgICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICAgIDx0aXRsZT5TYW1wbGU8L3RpdGxlPlxuPC9oZWFkPlxuXG48Ym9keSBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6IHZhcigtLXNhcEJhY2tncm91bmRDb2xvcilcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LWJyZWFkY3J1bWJzPlxuICAgICAgICA8dWk1LWJyZWFkY3J1bWJzLWl0ZW0gaHJlZj1cImh0dHBzOi8vd3d3LnNhcC5jb21cIiB0YXJnZXQ9XCJfYmxhbmtcIj5Sb290IFBhZ2UgPC91aTUtYnJlYWRjcnVtYnMtaXRlbT5cbiAgICAgICAgPHVpNS1icmVhZGNydW1icy1pdGVtIGhyZWY9XCJodHRwczovL3d3dy5zYXAuY29tXCIgdGFyZ2V0PVwiX2JsYW5rXCI-UGFyZW50IFBhZ2U8L3VpNS1icmVhZGNydW1icy1pdGVtPlxuICAgICAgICA8dWk1LWJyZWFkY3J1bWJzLWl0ZW0-Q3VycmVudCBQYWdlPC91aTUtYnJlYWRjcnVtYnMtaXRlbT5cbiAgICA8L3VpNS1icmVhZGNydW1icz5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0JyZWFkY3J1bWJzLmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9CcmVhZGNydW1ic0l0ZW0uanNcIjtcbiJ9fQ

### Priority

Medium

### UI5 Web Components Version

2.1.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by unazko** [comment]
Hello @SAP/ui5-webcomponents-topic-p,

According to the UX fiori guidelines cited by @sturmsap and the visual design specification the current page should appear as a text element instead of a link.

The same visualization and interaction is also present in the openui5 `sap.m.Breadcrumbs` control.

Could you please check out if the specs need to be updated or the control doesn't behave in this scenario accordingly.

Best regards,
Boyan

**Comment by plamenivanov91** [comment]
Hello @sturmsap ,

After consulting with @PetyaMarkovaBogdanova , it seems the fix is already implemented but not yet released.

Here you can see a demo how it works:
https://sap.github.io/ui5-webcomponents/nightly/play/

You should omit the `href ` attribute in order to get last Breadcrumb to be `ui5-label` and not a link.

Regards,
Plamen Ivanov
