### ISSUE TITLE
TextArea: Cant type spaces when used inside of UploadCollection

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents#9703]
### Describe the bug

When the TextArea Component is used inside of the UploadCollection (and UploadCollectionItem) it is not possible to type spaces.

### Isolated Example

https://stackblitz.com/edit/github-7dyw9x?file=src%2FApp.tsx

### Reproduction steps

Pass TextArea as children to UploadCollectionItem like shown in StackBlitz example.

### Expected Behaviour

Regular behaviour of the TextArea Component.

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hello @sap/ui5-webcomponents-topic-rd,

Could you please check the issue? Same applies for the ui5-input as well.

Regards,
Nayden

**Comment by GerganaKremenska** [comment]
Hello @SAP/ui5-webcomponents-topic-p, 

The issue is reproducible in this [example](https://stackblitz.com/edit/js-9pecrc?file=index.html,index.js,package.json)
UploadColectionItem extends ListItem, when an input/textarea (guessing any type of input) are placed inside a list item and some text is entered trying to use space to separate words is impossible. 

From what i can see in the ListItem space is only used for activating the list item.
Is this a use case that you have encountered?

Can you please take over?

Note: In openui5 this scenario works.

Best Regards,
Gergana
