### ISSUE TITLE
[Feature Request]: Ability to close menu with TAB key

### ISSUE THREAD

**Issue by shubhamnazare** [SAP/ui5-webcomponents#9707]
### Feature Request Description

Currently, the `Menu` and `Submenu` component could be closed with `ESC` key only. We have an urgent requirement to close both menus with `TAB` key as well. Could this be supported? Can someone also please provide a workaround if this could not be supported anytime soon.

### Proposed Solution

N/A

### Priority

High

### Privacy Policy

- [X] I’m not disclosing any internal or sensitive information.

**Comment by yanaminkova** [comment]
Hello @SAP/ui5-webcomponents-topic-b  ,

Could you please review this feature request and assess whether it's worth considering for implementation?

Thanks and Best regards,
Yana

**Comment by DMihaylova** [comment]
Hello @shubhamnazare,

Unfortunately there's no way to close menu with TAB key because TAB is already reserved for the cases where end content is available. That's the only way how a user could go though a keyboard to the content in that slot.
You could check the last sample here: https://sap.github.io/ui5-webcomponents/nightly/components/Menu/

Our recommendation is to continue using ESC key.

Thanks & Regards,
Diana
