### ISSUE TITLE
[SF_ACC][ui5-input][ui5-multi-input]: When selecting any suggestion item, screen reader announces 'no results‘

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents#9764]
### Bug Description

When selecting any suggestion item, screen reader announces 'no results‘

### Affected Component

ui5-input, ui5-multi-input

### Expected Behaviour

When selecting any suggestion item, screen reader shouldn't announce 'no results‘

### Steps to Reproduce

1. open page "https://github.wdf.sap.corp/pages/xweb/people-search/?path=/story/people-search-widget--employment-scope"
2. open jaws
3. type ad in input field
4. select any suggestion item
5. you will hear "no results"

### Log Output, Stack Trace or Screenshots

![NoResults](https://github.com/user-attachments/assets/a6f84cf4-74d1-4370-a5b6-d20b1e19d10a)
<img width="1571" alt="image" src="https://github.com/user-attachments/assets/6ff3e2c3-0d52-4310-9a52-0d8c11b3e4a9">

### Priority

Medium

### UI5 Web Components Version

1.24.x

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by elenastoyanovaa** [comment]
Hello,

The issue is not reproducible in version 1.24.8 of the ui5 web components using our playground sample with suggestions: https://sap.github.io/ui5-webcomponents/v1/components/Input/ . I have tested with JAWS 2024 and Chrome latest. As it is not reproducible in our samples I assume that part of your coding is related to the update of this hidden announcement, since it does not get updated in our samples.

Please adapt the sample in the playground showcasing your usage and the issue - [sample](https://sap.github.io/ui5-webcomponents/v1/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cbjxoZWFkPlxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIFxuICAgIDxzdHlsZT5cbiAgICAgICo6bm90KDpkZWZpbmVkKSB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICB9XG4gICAgPC9zdHlsZT5cblxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wXCI-XG4gICAgPHRpdGxlPlNhbXBsZTwvdGl0bGU-XG48L2hlYWQ-XG5cbjxib2R5IHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjogdmFyKC0tc2FwQmFja2dyb3VuZENvbG9yKTsgaGVpZ2h0OiAzMDBweDtcIj5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG5cbiAgICA8dWk1LWlucHV0IGlkPVwiaW5wdXRcIiBzaG93LXN1Z2dlc3Rpb25zIHBsYWNlaG9sZGVyPVwiVHlwZSAnYSdcIj48L3VpNS1pbnB1dD5cbiAgICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCJtYWluLmpzXCI-PC9zY3JpcHQ-XG48L2JvZHk-XG5cbjwvaHRtbD5cbjwhLS0gcGxheWdyb3VuZC1mb2xkLWVuZCAtLT5cbiJ9LCJtYWluLmpzIjp7Im5hbWUiOiJtYWluLmpzIiwiY29udGVudCI6Ii8qIHBsYXlncm91bmQtaGlkZSAqL1xuaW1wb3J0IFwiLi9wbGF5Z3JvdW5kLXN1cHBvcnQuanNcIjtcbi8qIHBsYXlncm91bmQtaGlkZS1lbmQgKi9cbmltcG9ydCBcIkB1aTUvd2ViY29tcG9uZW50cy9kaXN0L0lucHV0LmpzXCI7XG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9TdWdnZXN0aW9uSXRlbS5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvZmVhdHVyZXMvSW5wdXRTdWdnZXN0aW9ucy5qc1wiO1xuXG5jb25zdCBpbnB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwiaW5wdXRcIik7XG5pbnB1dC5hZGRFdmVudExpc3RlbmVyKFwiaW5wdXRcIiwgKCkgPT4ge1xuICAgIGNvbnN0IHZhbHVlID0gaW5wdXQudmFsdWU7XG4gICAgbGV0IHN1Z2dlc3Rpb25JdGVtcyA9IFtdO1xuICAgIGNvbnN0IHVpNV9kYXRhYmFzZV9lbnRyaWVzID0gW1wiQXJnZW50aW5hXCIsIFwiQWxiYW5pYVwiLCBcIkFsZ2VyaWFcIiwgXCJBbmdvbGFcIixcbiAgICAgICAgXCJBdXN0cmlhXCIsIFwiQXVzdHJhbGlhXCIsIFwiQnVsZ2FyaWFcIiwgXCJDYW5hZGFcIiwgXCJDb2x1bWJpYVwiLCBcIkNyb2F0aWFcIiwgXCJEZW5tYXJrXCIsXG4gICAgICAgIFwiRW5nbGFuZFwiLCBcIkZpbmxhbmRcIiwgXCJGcmFuY2VcIiwgXCJHZXJtYW55XCIsIFwiSHVuZ2FyeVwiLCBcIklyZWxhbmRcIiwgXCJJdGFseVwiLCBcIkt1d2FpdFwiLFxuICAgICAgICBcIkx1eGVtYm91cmdcIiwgXCJNZXhpY29cIiwgXCJNb3JvY2NvXCIsIFwiTm9yd2F5XCIsIFwiUGFyYWd1YXlcIiwgXCJQaGlsaXBwaW5lc1wiLCBcIlBvcnR1Z2FsXCIsXG4gICAgICAgIFwiU3BhaW5cIiwgXCJTd2VkZW5cIiwgXCJTcmkgTGFua2FcIiwgXCJTZW5lZ2FsXCIsIFwiVGhhaWxhbmRcIiwgXCJUaGUgVW5pdGVkIEtpbmdkb20gb2YgR3JlYXQgQnJpdGFpbiBhbmQgTm9ydGhlcm4gSXJlbGFuZFwiLCBcIlVTQVwiXTtcblxuICAgIGlmICh2YWx1ZSkge1xuICAgICAgICBzdWdnZXN0aW9uSXRlbXMgPSB1aTVfZGF0YWJhc2VfZW50cmllcy5maWx0ZXIoKGl0ZW0pID0-IHtcbiAgICAgICAgICAgIHJldHVybiBpdGVtLnRvVXBwZXJDYXNlKCkuaW5kZXhPZih2YWx1ZS50b1VwcGVyQ2FzZSgpKSA9PT0gMDtcbiAgICAgICAgfSk7XG4gICAgfVxuICAgIEFycmF5LmZyb20oaW5wdXQuY2hpbGRyZW4pLmZvckVhY2goKGNoaWxkKSA9PiB7XG4gICAgICAgIGlucHV0LnJlbW92ZUNoaWxkKGNoaWxkKTtcbiAgICB9KTtcbiAgICBzdWdnZXN0aW9uSXRlbXMuZm9yRWFjaCgoaXRlbSkgPT4ge1xuICAgICAgICBjb25zdCBsaSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoXCJ1aTUtc3VnZ2VzdGlvbi1pdGVtXCIpO1xuICAgICAgICBsaS50ZXh0ID0gaXRlbTtcbiAgICAgICAgaW5wdXQuYXBwZW5kQ2hpbGQobGkpO1xuICAgIH0pO1xufSk7In19)
and get back to us with more information and a link to the adjusted sample if you did not manage to find an issue in your coding in the meantime.

Kind Regards,
Elena

**Comment by GongRichard** [comment]
Hi @elenastoyanovaa ,
Let me try to reproduce this issue in a sandbox. And get back to you later.
Thanks,
Richard

**Comment by GongRichard** [comment]
Hi @elenastoyanovaa ,
Please close this issue, it's our code's problem.
Thanks,
Richard
