### ISSUE TITLE
[Switch]: [Accessibility issue - aria-required]

### ISSUE THREAD

**Issue by IlianaB** [SAP/ui5-webcomponents#9916]
### Bug Description

This issue is originally reported in [9872](https://github.com/SAP/ui5-webcomponents/issues/9872)

According to Access Assistant tool:
The aria-required attribute is not allowed on this DIV

### Affected Component

ui5-switch

### Expected Behaviour

No warnings with Access Assistant tool.

### Isolated Example

https://stackblitz.com/edit/github-qgw27d-nln9nx?file=index.html,main.js

### Steps to Reproduce

1. Open sample https://stackblitz.com/edit/github-qgw27d-nln9nx?file=index.html,main.js
2. Run Access Assistant and check the Notes

Refered to the switch:
The aria-required attribute is not allowed on this DIV

### Priority

Low

### UI5 Web Components Version

1.24.6

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by IlianaB** [comment]
Hello @ui5-webcomponents-topic-b , please check out this accessibility issue about ui5-switch.

Regards,
Iliana

**Comment by unazko** [comment]
Hello @IlianaB,

The `aria-required` attribute is allowed over an element with role `switch` since wai-aria-1.2:
https://www.w3.org/TR/wai-aria-1.2/#switch
Also the `switch` role is present in the list of role for the `aria-required` attribute:
https://www.w3.org/TR/wai-aria-1.2/#aria-required

The access assistant doesn't yet correspond to all the updates from wai-aria-1.2.

Best regards,
Boyan
